#include "types.h"
// Auto-generated inline asm decomp stubs for TGA_INFO
// Generated by gen_asm_decomp.py
// 2 functions, 332 bytes
//
// Each function has its original C++ signature with the body as inline PPC asm.
// These can be incrementally replaced with real C++ as decompilation progresses.

class TGA_INFO {
public:
    void WriteHeaderToBuffer(void *);
    void WriteFooterToBuffer(void *);
};

// 0x8030C798 (208 bytes)
// TGA_INFO::WriteHeaderToBuffer(void *)
__attribute__((noreturn))
void TGA_INFO::WriteHeaderToBuffer(void *) {
    __asm__ __volatile__(
        "stwu	1,-32(1)\n"
        "mflr	0\n"
        "stmw	28,16(1)\n"
        "stw	0,36(1)\n"
        "mr	29,3\n"
        "mr	28,4\n"
        "addi	30,1,8\n"
        "lbz	4,0(29)\n"
        "stw	28,8(1)\n"
        "mr	3,30\n"
        ".long 0x4bffff5d  /* bl Add1Byte(unsigned char *&, unsigned char) */\n"
        "lbz	4,1(29)\n"
        "mr	3,30\n"
        ".long 0x4bffff51  /* bl Add1Byte(unsigned char *&, unsigned char) */\n"
        "lbz	4,2(29)\n"
        "mr	3,30\n"
        ".long 0x4bffff45  /* bl Add1Byte(unsigned char *&, unsigned char) */\n"
        "lhz	4,4(29)\n"
        "mr	3,30\n"
        ".long 0x4bffff15  /* bl Add2Bytes(unsigned char *&, unsigned short) */\n"
        "lhz	4,6(29)\n"
        "mr	3,30\n"
        ".long 0x4bffff09  /* bl Add2Bytes(unsigned char *&, unsigned short) */\n"
        "lbz	4,8(29)\n"
        "mr	3,30\n"
        ".long 0x4bffff21  /* bl Add1Byte(unsigned char *&, unsigned char) */\n"
        "lhz	4,10(29)\n"
        "mr	3,30\n"
        ".long 0x4bfffef1  /* bl Add2Bytes(unsigned char *&, unsigned short) */\n"
        "lhz	4,12(29)\n"
        "mr	3,30\n"
        ".long 0x4bfffee5  /* bl Add2Bytes(unsigned char *&, unsigned short) */\n"
        "lhz	4,14(29)\n"
        "mr	3,30\n"
        ".long 0x4bfffed9  /* bl Add2Bytes(unsigned char *&, unsigned short) */\n"
        "lhz	4,16(29)\n"
        "mr	3,30\n"
        ".long 0x4bfffecd  /* bl Add2Bytes(unsigned char *&, unsigned short) */\n"
        "lbz	4,18(29)\n"
        "mr	3,30\n"
        ".long 0x4bfffee5  /* bl Add1Byte(unsigned char *&, unsigned char) */\n"
        "lbz	4,19(29)\n"
        "mr	3,30\n"
        ".long 0x4bfffed9  /* bl Add1Byte(unsigned char *&, unsigned char) */\n"
        "lwz	3,8(1)\n"
        "subf	3,28,3\n"
        "clrlwi	3,3,24\n"
        "lwz	0,36(1)\n"
        "mtlr	0\n"
        "lmw	28,16(1)\n"
        "addi	1,1,32\n"
        "blr\n"
    );
    __builtin_unreachable();
}

// 0x8030C868 (124 bytes)
// TGA_INFO::WriteFooterToBuffer(void *)
__attribute__((noreturn))
void TGA_INFO::WriteFooterToBuffer(void *) {
    __asm__ __volatile__(
        "stwu	1,-48(1)\n"
        "stmw	30,40(1)\n"
        "lis	9,-32702\n"
        "addi	11,1,8\n"
        "lwz	0,-757(9)\n"
        "li	3,26\n"
        "addi	9,9,-757\n"
        "lhz	10,24(9)\n"
        "lwz	8,4(9)\n"
        "lwz	7,8(9)\n"
        "lwz	6,12(9)\n"
        "lwz	5,16(9)\n"
        "lwz	30,20(9)\n"
        "stw	0,8(1)\n"
        "sth	10,24(11)\n"
        "stw	8,4(11)\n"
        "stw	7,8(11)\n"
        "stw	6,12(11)\n"
        "stw	5,16(11)\n"
        "stw	30,20(11)\n"
        "sth	10,24(4)\n"
        "lwz	0,8(1)\n"
        "stw	8,4(4)\n"
        "stw	0,0(4)\n"
        "stw	7,8(4)\n"
        "stw	6,12(4)\n"
        "stw	5,16(4)\n"
        "stw	30,20(4)\n"
        "lmw	30,40(1)\n"
        "addi	1,1,48\n"
        "blr\n"
    );
    __builtin_unreachable();
}

