#include "types.h"
// Auto-generated inline asm decomp stubs for ENgcTextureRGB5A3
// Generated by gen_asm_decomp.py
// 2 functions, 160 bytes
//
// Each function has its original C++ signature with the body as inline PPC asm.
// These can be incrementally replaced with real C++ as decompilation progresses.

class ENgcTextureRGB5A3 {
public:
    ENgcTextureRGB5A3(void);
    ~ENgcTextureRGB5A3(void);
};

// 0x8035159C (72 bytes)
// ENgcTextureRGB5A3::ENgcTextureRGB5A3(void)
__attribute__((noreturn))
ENgcTextureRGB5A3::ENgcTextureRGB5A3(void) {
    __asm__ __volatile__(
        "stwu	1,-16(1)\n"
        "mflr	0\n"
        "stmw	30,8(1)\n"
        "stw	0,20(1)\n"
        "mr	30,3\n"
        "li	4,5\n"
        "li	5,4\n"
        "li	6,4\n"
        ".long 0x4bffe685  /* bl ENgcTextureBase::ENgcTextureBase(unsigned int, int, int) */\n"
        "lis	9,-32697\n"
        "mr	3,30\n"
        "addi	9,9,-11112\n"
        "stw	9,36(30)\n"
        "lwz	0,20(1)\n"
        "mtlr	0\n"
        "lmw	30,8(1)\n"
        "addi	1,1,16\n"
        "blr\n"
    );
    __builtin_unreachable();
}

// 0x803515E4 (88 bytes)
// ENgcTextureRGB5A3::~ENgcTextureRGB5A3(void)
__attribute__((noreturn))
ENgcTextureRGB5A3::~ENgcTextureRGB5A3(void) {
    __asm__ __volatile__(
        "stwu	1,-16(1)\n"
        "mflr	0\n"
        "stmw	30,8(1)\n"
        "stw	0,20(1)\n"
        "lis	9,-32697\n"
        "mr	31,3\n"
        "mr	30,4\n"
        "addi	9,9,-11112\n"
        "stw	9,36(31)\n"
        "li	4,0\n"
        ".long 0x4bffe6b1  /* bl ENgcTextureBase::~ENgcTextureBase(void) */\n"
        "andi.	0,30,1\n"
        "beq	.L_80351628\n"
        "lis	3,-32692\n"
        "mr	4,31\n"
        "addi	3,3,-7364\n"
        ".long 0x4bfd6089  /* bl EResourceManager::Free(void *) */\n"
        ".L_80351628:\n"
        "lwz	0,20(1)\n"
        "mtlr	0\n"
        "lmw	30,8(1)\n"
        "addi	1,1,16\n"
        "blr\n"
    );
    __builtin_unreachable();
}

