#include "types.h"
#include "stub_classes.h"
// Auto-generated raw-byte matches for AptValueVector
// Generated by gen_raw_byte_matches.py
// 1 functions, 56 bytes
// These functions are matched by directly injecting DOL bytes into the skeleton.
// The C++ stubs below exist only as annotations for the matching pipeline.

// 0x802B4D04 (56 bytes)
// AptValueVector__PushValue_AptValue_ptr
// [raw byte match - injected directly from DOL]

