#include "types.h"
// Auto-generated inline asm decomp stubs for REffectsEmitter
// Generated by gen_asm_decomp.py
// 8 functions, 876 bytes
//
// Each function has its original C++ signature with the body as inline PPC asm.
// These can be incrementally replaced with real C++ as decompilation progresses.

class EFile;

class REffectsEmitter {
public:
    REffectsEmitter(void);
    ~REffectsEmitter(void);
    void Deallocate(void);
    void AddRefSubResources(void);
    void TryIncrementSubResources(void);
    void Load(EFile *);
    void Refresh(EFile *);
    void RegisterType(unsigned short);
};

// 0x8036A7B4 (80 bytes)
// REffectsEmitter::REffectsEmitter(void)
__attribute__((noreturn))
REffectsEmitter::REffectsEmitter(void) {
    __asm__ __volatile__(
        "stwu	1,-16(1)\n"
        "mflr	0\n"
        "stmw	30,8(1)\n"
        "stw	0,20(1)\n"
        "mr	30,3\n"
        ".long 0x4bfa7601  /* bl EResource::EResource(void) */\n"
        "lis	9,-32697\n"
        "li	0,0\n"
        "addi	9,9,-8152\n"
        "stw	0,32(30)\n"
        "stw	9,0(30)\n"
        "mr	3,30\n"
        "stw	0,20(30)\n"
        "stw	0,24(30)\n"
        "stw	0,28(30)\n"
        "lwz	0,20(1)\n"
        "mtlr	0\n"
        "lmw	30,8(1)\n"
        "addi	1,1,16\n"
        "blr\n"
    );
    __builtin_unreachable();
}

// 0x8036A804 (92 bytes)
// REffectsEmitter::~REffectsEmitter(void)
__attribute__((noreturn))
REffectsEmitter::~REffectsEmitter(void) {
    __asm__ __volatile__(
        "stwu	1,-16(1)\n"
        "mflr	0\n"
        "stmw	30,8(1)\n"
        "stw	0,20(1)\n"
        "lis	9,-32697\n"
        "mr	31,3\n"
        "addi	9,9,-8152\n"
        "mr	30,4\n"
        "stw	9,0(31)\n"
        ".long 0x48000039  /* bl REffectsEmitter::Deallocate(void) */\n"
        "mr	3,31\n"
        "li	4,0\n"
        ".long 0x4bfa75c5  /* bl EResource::~EResource(void) */\n"
        "andi.	0,30,1\n"
        "beq	.L_8036A84C\n"
        ".long 0x4bf656c1  /* bl MainHeap(void) */\n"
        "mr	4,31\n"
        ".long 0x4bf66531  /* bl EAHeap::Free(void *) */\n"
        ".L_8036A84C:\n"
        "lwz	0,20(1)\n"
        "mtlr	0\n"
        "lmw	30,8(1)\n"
        "addi	1,1,16\n"
        "blr\n"
    );
    __builtin_unreachable();
}

// 0x8036A860 (100 bytes)
// REffectsEmitter::Deallocate(void)
__attribute__((noreturn))
void REffectsEmitter::Deallocate(void) {
    __asm__ __volatile__(
        "stwu	1,-16(1)\n"
        "mflr	0\n"
        "stw	31,12(1)\n"
        "stw	0,20(1)\n"
        "mr	31,3\n"
        "lwz	9,0(31)\n"
        "lwz	0,108(9)\n"
        "lha	3,104(9)\n"
        "mtlr	0\n"
        "add	3,31,3\n"
        "blrl\n"
        "lwz	0,24(31)\n"
        "cmpwi	0,0\n"
        "beq	.L_8036A8B0\n"
        ".long 0x4bf65669  /* bl MainHeap(void) */\n"
        "lwz	4,24(31)\n"
        ".long 0x4bf664d9  /* bl EAHeap::Free(void *) */\n"
        "li	0,0\n"
        "stw	0,24(31)\n"
        "stw	0,20(31)\n"
        ".L_8036A8B0:\n"
        "lwz	0,20(1)\n"
        "mtlr	0\n"
        "lwz	31,12(1)\n"
        "addi	1,1,16\n"
        "blr\n"
    );
    __builtin_unreachable();
}

// 0x8036A904 (96 bytes)
// REffectsEmitter::AddRefSubResources(void)
__attribute__((noreturn))
void REffectsEmitter::AddRefSubResources(void) {
    __asm__ __volatile__(
        "stwu	1,-16(1)\n"
        "mflr	0\n"
        "stw	31,12(1)\n"
        "stw	0,20(1)\n"
        "mr	31,3\n"
        "li	0,0\n"
        "lwz	4,20(31)\n"
        "stw	0,28(31)\n"
        "cmpwi	4,0\n"
        "beq	.L_8036A950\n"
        "lwz	4,192(4)\n"
        "cmpwi	4,0\n"
        "beq	.L_8036A950\n"
        "lis	3,-32692\n"
        "li	5,0\n"
        "addi	3,3,-7364\n"
        "li	6,0\n"
        ".long 0x4bfbc3b1  /* bl EResourceManager::AddRef(unsigned int, EFile *, int) */\n"
        "stw	3,28(31)\n"
        ".L_8036A950:\n"
        "lwz	0,20(1)\n"
        "mtlr	0\n"
        "lwz	31,12(1)\n"
        "addi	1,1,16\n"
        "blr\n"
    );
    __builtin_unreachable();
}

// 0x8036A964 (108 bytes)
// REffectsEmitter::TryIncrementSubResources(void)
__attribute__((noreturn))
void REffectsEmitter::TryIncrementSubResources(void) {
    __asm__ __volatile__(
        "stwu	1,-24(1)\n"
        "mflr	0\n"
        "stw	31,20(1)\n"
        "stw	0,28(1)\n"
        "mr	31,3\n"
        "lwz	4,20(31)\n"
        "cmpwi	4,0\n"
        "beq	.L_8036A9B8\n"
        "lwz	4,192(4)\n"
        "cmpwi	4,0\n"
        "beq	.L_8036A9B8\n"
        "lis	3,-32692\n"
        "addi	5,1,8\n"
        "addi	3,3,-7364\n"
        ".long 0x4bfbc0c5  /* bl EResourceManager::TryIncrementResource(unsigned int, EResource **) */\n"
        "cmpwi	3,0\n"
        "bne	.L_8036A9B0\n"
        "li	3,0\n"
        "b	.L_8036A9BC\n"
        ".L_8036A9B0:\n"
        "lwz	0,8(1)\n"
        "stw	0,28(31)\n"
        ".L_8036A9B8:\n"
        "li	3,1\n"
        ".L_8036A9BC:\n"
        "lwz	0,28(1)\n"
        "mtlr	0\n"
        "lwz	31,20(1)\n"
        "addi	1,1,24\n"
        "blr\n"
    );
    __builtin_unreachable();
}

// 0x8036A9D0 (244 bytes)
// REffectsEmitter::Load(EFile *)
__attribute__((noreturn))
void REffectsEmitter::Load(EFile *) {
    __asm__ __volatile__(
        "stwu	1,-40(1)\n"
        "mflr	0\n"
        "stmw	30,32(1)\n"
        "stw	0,44(1)\n"
        "mr	31,3\n"
        "mr	30,4\n"
        ".long 0x4bfffe79  /* bl REffectsEmitter::Deallocate(void) */\n"
        "cmpwi	30,0\n"
        "beq	.L_8036AAB0\n"
        "addi	3,1,8\n"
        ".long 0x4bff0479  /* bl EDataHeader::EDataHeader(void) */\n"
        "lis	5,17733\n"
        "addi	3,1,8\n"
        "mr	4,30\n"
        "ori	5,5,19796\n"
        "li	6,1\n"
        "li	7,1\n"
        ".long 0x4bff0689  /* bl EDataHeader::Read(EFile &, unsigned int, unsigned int, unsigned int) */\n"
        "cmpwi	3,0\n"
        "bne	.L_8036AA30\n"
        "addi	3,1,8\n"
        "li	4,2\n"
        ".long 0x4bff0481  /* bl EDataHeader::~EDataHeader(void) */\n"
        "b	.L_8036AAB0\n"
        ".L_8036AA30:\n"
        "addi	3,1,8\n"
        ".long 0x4bff08ed  /* bl EDataHeader::GetName(void) */\n"
        "lwz	9,24(1)\n"
        "lwz	0,16(31)\n"
        "rlwimi	0,9,8,0,23\n"
        "stw	0,16(31)\n"
        ".long 0x4bf654b9  /* bl MainHeap(void) */\n"
        "lwz	4,24(1)\n"
        "li	6,0\n"
        "li	7,0\n"
        "li	5,64\n"
        ".long 0x4bf66115  /* bl EAHeap::MallocAligned(unsigned int, unsigned int, unsigned int, int) */\n"
        "mr	4,3\n"
        "lwz	5,24(1)\n"
        "addi	0,4,144\n"
        "stw	4,24(31)\n"
        "stw	0,20(31)\n"
        "lwz	9,40(30)\n"
        "lwz	0,28(9)\n"
        "lha	3,24(9)\n"
        "mtlr	0\n"
        "add	3,30,3\n"
        "blrl\n"
        "lwz	9,0(31)\n"
        "lha	3,112(9)\n"
        "lwz	0,116(9)\n"
        "add	3,31,3\n"
        "mtlr	0\n"
        "blrl\n"
        "addi	3,1,8\n"
        "li	4,2\n"
        ".long 0x4bff03fd  /* bl EDataHeader::~EDataHeader(void) */\n"
        ".L_8036AAB0:\n"
        "lwz	0,44(1)\n"
        "mtlr	0\n"
        "lmw	30,32(1)\n"
        "addi	1,1,40\n"
        "blr\n"
    );
    __builtin_unreachable();
}

// 0x8036AAC4 (72 bytes)
// REffectsEmitter::Refresh(EFile *)
__attribute__((noreturn))
void REffectsEmitter::Refresh(EFile *) {
    __asm__ __volatile__(
        "stwu	1,-16(1)\n"
        "mflr	0\n"
        "stmw	30,8(1)\n"
        "stw	0,20(1)\n"
        "mr	31,3\n"
        "mr.	30,4\n"
        "beq	.L_8036AAF8\n"
        ".long 0x4bfffd81  /* bl REffectsEmitter::Deallocate(void) */\n"
        "mr	4,30\n"
        "mr	3,31\n"
        ".long 0x4bfffee5  /* bl REffectsEmitter::Load(EFile *) */\n"
        "li	0,1\n"
        "stw	0,32(31)\n"
        ".L_8036AAF8:\n"
        "lwz	0,20(1)\n"
        "mtlr	0\n"
        "lmw	30,8(1)\n"
        "addi	1,1,16\n"
        "blr\n"
    );
    __builtin_unreachable();
}

// 0x8036AC78 (84 bytes)
// REffectsEmitter::RegisterType(unsigned short)
__attribute__((noreturn))
void REffectsEmitter::RegisterType(unsigned short) {
    __asm__ __volatile__(
        "stwu	1,-8(1)\n"
        "mflr	0\n"
        "stw	0,12(1)\n"
        "mr	7,3\n"
        "lis	4,-32713\n"
        "lis	3,-32688\n"
        "lis	5,-32713\n"
        "lis	6,-32713\n"
        "lis	8,-32702\n"
        "lis	9,-32688\n"
        "addi	3,3,-10084\n"
        "addi	4,4,-21636\n"
        "addi	5,5,-21588\n"
        "addi	6,6,-21556\n"
        "addi	8,8,13256\n"
        "addi	9,9,-13000\n"
        ".long 0x4bf6ac15  /* bl ETypeInfo::Register(EStorable *(*)(void), void (*)(void *), void (*)(void *), unsigned short, char *, ETypeInfo *) */\n"
        "lwz	0,12(1)\n"
        "mtlr	0\n"
        "addi	1,1,8\n"
        "blr\n"
    );
    __builtin_unreachable();
}

