#include "types.h"
#include "stub_classes.h"
// Auto-generated raw-byte matches for UIUserDrawCBTable
// Generated by gen_raw_byte_matches.py
// 2 functions, 112 bytes
// These functions are matched by directly injecting DOL bytes into the skeleton.
// The C++ stubs below exist only as annotations for the matching pipeline.

// 0x80182284 (60 bytes)
// UIUserDrawCBTable__Instance_void
// [raw byte match - injected directly from DOL]

// 0x803B214C (52 bytes)
// UIUserDrawCBTable__UserDrawCBTableRecord__dtor_UserDrawCBTableRecord_void
// [raw byte match - injected directly from DOL]

