#include "types.h"
// Auto-generated inline asm decomp stubs for DigestGeomShaderPtr
// Generated by gen_asm_decomp.py
// 1 functions, 164 bytes
//
// Each function has its original C++ signature with the body as inline PPC asm.
// These can be incrementally replaced with real C++ as decompilation progresses.

class DigestGeomShaderPtr {
public:
    void UpdateShaderFlags(bool &);
};

// 0x80227530 (164 bytes)
// DigestGeomShaderPtr::UpdateShaderFlags(bool &)
__attribute__((noreturn))
void DigestGeomShaderPtr::UpdateShaderFlags(bool &) {
    __asm__ __volatile__(
        "lwz	9,4(3)\n"
        "lwz	0,20(9)\n"
        "cmpwi	0,0\n"
        "beq	.L_80227548\n"
        "mr	11,0\n"
        "b	.L_8022755C\n"
        ".L_80227548:\n"
        "lwz	9,24(9)\n"
        "li	11,0\n"
        "cmpwi	9,0\n"
        "beq	.L_8022755C\n"
        "lwz	11,20(9)\n"
        ".L_8022755C:\n"
        "lwz	9,4(11)\n"
        "li	10,0\n"
        "addi	11,11,100\n"
        "stw	9,8(3)\n"
        "lwz	0,12(11)\n"
        "andi.	9,0,64\n"
        "beq	.L_802275A0\n"
        "lbz	0,28(11)\n"
        "cmpwi	0,1\n"
        "beq	.L_8022759C\n"
        "lbz	0,29(11)\n"
        "cmpwi	0,1\n"
        "beq	.L_8022759C\n"
        "lbz	0,31(11)\n"
        "cmpwi	0,1\n"
        "bne	.L_802275A0\n"
        ".L_8022759C:\n"
        "li	10,1\n"
        ".L_802275A0:\n"
        "cmpwi	10,0\n"
        "beq	.L_802275BC\n"
        "lwz	0,8(3)\n"
        "andi.	9,0,2048\n"
        "bne	.L_802275BC\n"
        "ori	0,0,32768\n"
        "stw	0,8(3)\n"
        ".L_802275BC:\n"
        "lwz	0,8(3)\n"
        "andi.	9,0,32\n"
        "beqlr\n"
        "li	0,1\n"
        "stw	0,0(4)\n"
        "blr\n"
    );
    __builtin_unreachable();
}

