#include "types.h"
#include "stub_classes.h"
// Auto-converted call wrapper stubs for AptFloat
// Generated by convert_call_wrappers.py

// 0x802BBB90 (84 bytes)
// Call wrapper [2bl_with_branch]: AptValue::~AptValue(void), AptFloat::operator delete(void *, unsigned int)
__attribute__((noreturn))
AptFloat::~AptFloat(void) {
    __asm__ __volatile__(
        "stwu	1,-16(1)\n"
        "mflr	0\n"
        "stmw	30,8(1)\n"
        "stw	0,20(1)\n"
        "lis	9,-32702\n"
        "mr	31,3\n"
        "mr	30,4\n"
        "addi	9,9,-26784\n"
        "stw	9,8(31)\n"
        "li	4,0\n"
        ".long 0x4bff8bb9  /* bl AptValue::~AptValue(void) */\n"
        "andi.	0,30,1\n"
        "beq	.L_802BBBD0\n"
        "mr	3,31\n"
        "li	4,16\n"
        ".long 0x48000041  /* bl AptFloat::operator delete(void *, unsigned int) */\n"
        ".L_802BBBD0:\n"
        "lwz	0,20(1)\n"
        "mtlr	0\n"
        "lmw	30,8(1)\n"
        "addi	1,1,16\n"
        "blr\n"
    );
    __builtin_unreachable();
}
