#include "types.h"
#include "stub_classes.h"
// Auto-generated raw-byte matches for LoadingScreenWaitingForLoadState
// Generated by gen_raw_byte_matches.py
// 2 functions, 112 bytes
// These functions are matched by directly injecting DOL bytes into the skeleton.
// The C++ stubs below exist only as annotations for the matching pipeline.

// 0x80091018 (60 bytes)
// LoadingScreenWaitingForLoadState__FaderStart_float
// [raw byte match - injected directly from DOL]

// 0x803A0C3C (52 bytes)
// LoadingScreenWaitingForLoadState__dtor_LoadingScreenWaitingForLoadState_void
// [raw byte match - injected directly from DOL]

