// FLAGS: -fno-schedule-insns
// CBMemberTranslator1<ERC *, R2LTarget, void (UIObjectBase::*)(UIObjectBase *, ERC *)>::thunk(CBFunctorBase &, ERC *) at 0x803B9DB8 (120 bytes)
// PMF ABI crack — generated by blast_cbmember.py
class ERC;
class R2LTarget;
class UIObjectBase;

class CBFunctorBase {
public:
    void (UIObjectBase::*m_pmf)();
    UIObjectBase* m_obj;
};

void cbmt_thunk_803B9DB8(CBFunctorBase& f) {
    UIObjectBase* obj = f.m_obj;
    (obj->*f.m_pmf)();
}
