// FLAGS: -fno-schedule-insns
// CBMemberTranslator1<int, INGTarget, void (INGTarget::*)(INGTarget *, int)>::thunk(CBFunctorBase &, int) at 0x803B7AF4 (120 bytes)
// PMF ABI crack — generated by blast_cbmember.py
class INGTarget;

class CBFunctorBase {
public:
    void (INGTarget::*m_pmf)();
    INGTarget* m_obj;
};

void cbmt_thunk_803B7AF4(CBFunctorBase& f) {
    INGTarget* obj = f.m_obj;
    (obj->*f.m_pmf)();
}
