// FLAGS: -fno-schedule-insns
// CBMemberTranslator1<int, HelpDialog, void (HelpDialog::*)(HelpDialog *, int)>::thunk(CBFunctorBase &, int) at 0x803B0F2C (120 bytes)
// PMF ABI crack — generated by blast_cbmember.py
class HelpDialog;

class CBFunctorBase {
public:
    void (HelpDialog::*m_pmf)();
    HelpDialog* m_obj;
};

void cbmt_thunk_803B0F2C(CBFunctorBase& f) {
    HelpDialog* obj = f.m_obj;
    (obj->*f.m_pmf)();
}
