// FLAGS: -fno-schedule-insns
// CBMemberTranslator1wRet<char *, char *, FAMTarget, char *(FAMTarget::*)(FAMTarget *, char *)>::thunk(CBFunctorBase &, char *) at 0x803B6E78 (120 bytes)
// PMF ABI crack — generated by blast_cbmember.py
class FAMTarget;

class CBFunctorBase {
public:
    void (FAMTarget::*m_pmf)();
    FAMTarget* m_obj;
};

void cbmt_thunk_803B6E78(CBFunctorBase& f) {
    FAMTarget* obj = f.m_obj;
    (obj->*f.m_pmf)();
}
