// FLAGS: -fno-schedule-insns
// CBMemberTranslator2<char *, char *, CASTattooTarget, void (CASTattooTarget::*)(CASTattooTarget *, char *, char *)>::thunk(CBFunctorBase &, char *, char *) at 0x803B4A30 (120 bytes)
// PMF ABI crack — generated by blast_cbmember.py
class CASTattooTarget;

class CBFunctorBase {
public:
    void (CASTattooTarget::*m_pmf)();
    CASTattooTarget* m_obj;
};

void cbmt_thunk_803B4A30(CBFunctorBase& f) {
    CASTattooTarget* obj = f.m_obj;
    (obj->*f.m_pmf)();
}
