// FLAGS: -fno-schedule-insns
// CBMemberTranslator1wRet<char *, char *, INGTarget, char *(INGTarget::*)(INGTarget *, char *)>::thunk(CBFunctorBase &, char *) at 0x803B789C (120 bytes)
// PMF ABI crack — generated by blast_cbmember.py
class INGTarget;

class CBFunctorBase {
public:
    void (INGTarget::*m_pmf)();
    INGTarget* m_obj;
};

void cbmt_thunk_803B789C(CBFunctorBase& f) {
    INGTarget* obj = f.m_obj;
    (obj->*f.m_pmf)();
}
