// FLAGS: -fno-schedule-insns
// CBMemberTranslator1wRet<char *, char *, ITBTarget, char *(ITBTarget::*)(ITBTarget *, char *)>::thunk(CBFunctorBase &, char *) at 0x803B7B6C (120 bytes)
// PMF ABI crack — generated by blast_cbmember.py
class ITBTarget;

class CBFunctorBase {
public:
    void (ITBTarget::*m_pmf)();
    ITBTarget* m_obj;
};

void cbmt_thunk_803B7B6C(CBFunctorBase& f) {
    ITBTarget* obj = f.m_obj;
    (obj->*f.m_pmf)();
}
