// FLAGS: -fno-schedule-insns
// CBMemberTranslator1wRet<char *, unsigned wchar_t *, CASMorphTarget, unsigned wchar_t *(UIObjectBase::*)(UIObjectBase *, char *)>::thunk(CBFunctorBase &, char *) at 0x803B45F8 (120 bytes)
// PMF ABI crack — generated by blast_cbmember.py
class CASMorphTarget;
class UIObjectBase;

class CBFunctorBase {
public:
    void (UIObjectBase::*m_pmf)();
    UIObjectBase* m_obj;
};

void cbmt_thunk_803B45F8(CBFunctorBase& f) {
    UIObjectBase* obj = f.m_obj;
    (obj->*f.m_pmf)();
}
