// FLAGS: -fno-schedule-insns
// CBMemberTranslator0<PRGTarget, void (UIObjectBase::*)(UIObjectBase *)>::thunk(CBFunctorBase &) at 0x803B9AE8 (120 bytes)
// PMF ABI crack — generated by blast_cbmember.py
class PRGTarget;
class UIObjectBase;

class CBFunctorBase {
public:
    void (UIObjectBase::*m_pmf)();
    UIObjectBase* m_obj;
};

void cbmt_thunk_803B9AE8(CBFunctorBase& f) {
    UIObjectBase* obj = f.m_obj;
    (obj->*f.m_pmf)();
}
