// FLAGS: -fno-schedule-insns
// CBMemberTranslator1<ERC *, RCPTarget, void (RCPTarget::*)(RCPTarget *, ERC *)>::thunk(CBFunctorBase &, ERC *) at 0x803BA088 (120 bytes)
// PMF ABI crack — generated by blast_cbmember.py
class ERC;
class RCPTarget;

class CBFunctorBase {
public:
    void (RCPTarget::*m_pmf)();
    RCPTarget* m_obj;
};

void cbmt_thunk_803BA088(CBFunctorBase& f) {
    RCPTarget* obj = f.m_obj;
    (obj->*f.m_pmf)();
}
