// FLAGS: -fno-schedule-insns
// CBMemberTranslator0<WXFTarget, void (WXFTarget::*)(WXFTarget *)>::thunk(CBFunctorBase &) at 0x803BA970 (120 bytes)
// PMF ABI crack — generated by blast_cbmember.py
class WXFTarget;

class CBFunctorBase {
public:
    void (WXFTarget::*m_pmf)();
    WXFTarget* m_obj;
};

void cbmt_thunk_803BA970(CBFunctorBase& f) {
    WXFTarget* obj = f.m_obj;
    (obj->*f.m_pmf)();
}
