// FLAGS: -fno-schedule-insns
// CBMemberTranslator1wRet<char *, char *, INTTarget, char *(INTTarget::*)(INTTarget *, char *)>::thunk(CBFunctorBase &, char *) at 0x803BB938 (120 bytes)
// PMF ABI crack — generated by blast_cbmember.py
class INTTarget;

class CBFunctorBase {
public:
    void (INTTarget::*m_pmf)();
    INTTarget* m_obj;
};

void cbmt_thunk_803BB938(CBFunctorBase& f) {
    INTTarget* obj = f.m_obj;
    (obj->*f.m_pmf)();
}
