// FLAGS: -fno-schedule-insns
// CBMemberTranslator1<ERC *, CASRoommateTarget, void (CASRoommateTarget::*)(CASRoommateTarget *, ERC *)>::thunk(CBFunctorBase &, ERC *) at 0x803B4DF0 (120 bytes)
// PMF ABI crack — generated by blast_cbmember.py
class CASRoommateTarget;
class ERC;

class CBFunctorBase {
public:
    void (CASRoommateTarget::*m_pmf)();
    CASRoommateTarget* m_obj;
};

void cbmt_thunk_803B4DF0(CBFunctorBase& f) {
    CASRoommateTarget* obj = f.m_obj;
    (obj->*f.m_pmf)();
}
