// FLAGS: -fno-schedule-insns
// CBMemberTranslator1<ERC *, UIDBTarget, void (UIObjectBase::*)(UIObjectBase *, ERC *)>::thunk(CBFunctorBase &, ERC *) at 0x803B13AC (120 bytes)
// PMF ABI crack — generated by blast_cbmember.py
class ERC;
class UIDBTarget;
class UIObjectBase;

class CBFunctorBase {
public:
    void (UIObjectBase::*m_pmf)();
    UIObjectBase* m_obj;
};

void cbmt_thunk_803B13AC(CBFunctorBase& f) {
    UIObjectBase* obj = f.m_obj;
    (obj->*f.m_pmf)();
}
