// FLAGS: -fno-schedule-insns
// CBMemberTranslator1wRet<char *, unsigned wchar_t *, CRDTarget, unsigned wchar_t *(CRDTarget::*)(CRDTarget *, char *)>::thunk(CBFunctorBase &, char *) at 0x803B637C (120 bytes)
// PMF ABI crack — generated by blast_cbmember.py
class CRDTarget;

class CBFunctorBase {
public:
    void (CRDTarget::*m_pmf)();
    CRDTarget* m_obj;
};

void cbmt_thunk_803B637C(CBFunctorBase& f) {
    CRDTarget* obj = f.m_obj;
    (obj->*f.m_pmf)();
}
