// FLAGS: -fno-schedule-insns
// CBMemberTranslator0<ACTTarget, void (ACTTarget::*)(ACTTarget *)>::thunk(CBFunctorBase &) at 0x803B5E20 (120 bytes)
// PMF ABI crack — generated by blast_cbmember.py
class ACTTarget;

class CBFunctorBase {
public:
    void (ACTTarget::*m_pmf)();
    ACTTarget* m_obj;
};

void cbmt_thunk_803B5E20(CBFunctorBase& f) {
    ACTTarget* obj = f.m_obj;
    (obj->*f.m_pmf)();
}
