// FLAGS: -fno-schedule-insns
// CBMemberTranslator1wRet<char *, unsigned wchar_t *, BBHTarget, unsigned wchar_t *(BBHTarget::*)(BBHTarget *, char *)>::thunk(CBFunctorBase &, char *) at 0x803B6000 (120 bytes)
// PMF ABI crack — generated by blast_cbmember.py
class BBHTarget;

class CBFunctorBase {
public:
    void (BBHTarget::*m_pmf)();
    BBHTarget* m_obj;
};

void cbmt_thunk_803B6000(CBFunctorBase& f) {
    BBHTarget* obj = f.m_obj;
    (obj->*f.m_pmf)();
}
