// FLAGS: -fno-schedule-insns
// CBMemberTranslator1wRet<char *, char *, CASMorphTarget, char *(CASMorphTarget::*)(CASMorphTarget *, char *)>::thunk(CBFunctorBase &, char *) at 0x803B4508 (120 bytes)
// PMF ABI crack — generated by blast_cbmember.py
class CASMorphTarget;

class CBFunctorBase {
public:
    void (CASMorphTarget::*m_pmf)();
    CASMorphTarget* m_obj;
};

void cbmt_thunk_803B4508(CBFunctorBase& f) {
    CASMorphTarget* obj = f.m_obj;
    (obj->*f.m_pmf)();
}
