// FLAGS: -fno-schedule-insns
// CBMemberTranslator2<char *, char *, MOTTarget, void (MOTTarget::*)(MOTTarget *, char *, char *)>::thunk(CBFunctorBase &, char *, char *) at 0x803B8B5C (120 bytes)
// PMF ABI crack — generated by blast_cbmember.py
class MOTTarget;

class CBFunctorBase {
public:
    void (MOTTarget::*m_pmf)();
    MOTTarget* m_obj;
};

void cbmt_thunk_803B8B5C(CBFunctorBase& f) {
    MOTTarget* obj = f.m_obj;
    (obj->*f.m_pmf)();
}
