// FLAGS: -fno-schedule-insns
// CBMemberTranslator1<ERC *, UIScreenManager, void (UIObjectBase::*)(UIObjectBase *, ERC *)>::thunk(CBFunctorBase &, ERC *) at 0x803B1BF0 (120 bytes)
// PMF ABI crack — generated by blast_cbmember.py
class ERC;
class UIObjectBase;
class UIScreenManager;

class CBFunctorBase {
public:
    void (UIObjectBase::*m_pmf)();
    UIObjectBase* m_obj;
};

void cbmt_thunk_803B1BF0(CBFunctorBase& f) {
    UIObjectBase* obj = f.m_obj;
    (obj->*f.m_pmf)();
}
