// FLAGS: -fno-schedule-insns
// CBMemberTranslator1wRet<char *, char *, MODTarget, char *(MODTarget::*)(MODTarget *, char *)>::thunk(CBFunctorBase &, char *) at 0x803B8814 (120 bytes)
// PMF ABI crack — generated by blast_cbmember.py
class MODTarget;

class CBFunctorBase {
public:
    void (MODTarget::*m_pmf)();
    MODTarget* m_obj;
};

void cbmt_thunk_803B8814(CBFunctorBase& f) {
    MODTarget* obj = f.m_obj;
    (obj->*f.m_pmf)();
}
