// FLAGS: -fno-schedule-insns
// CBMemberTranslator1wRet<char *, char *, G2DTarget, char *(G2DTarget::*)(G2DTarget *, char *)>::thunk(CBFunctorBase &, char *) at 0x803B73EC (120 bytes)
// PMF ABI crack — generated by blast_cbmember.py
class G2DTarget;

class CBFunctorBase {
public:
    void (G2DTarget::*m_pmf)();
    G2DTarget* m_obj;
};

void cbmt_thunk_803B73EC(CBFunctorBase& f) {
    G2DTarget* obj = f.m_obj;
    (obj->*f.m_pmf)();
}
