#include "types.h"
// Auto-generated inline asm decomp stubs for basic_string_L_wchar_t_char_traits_L_wchar_t_R_allocator_L_wchar_t_R_R
// Generated by gen_asm_decomp.py
// 2 functions, 304 bytes
//
// Each function has its original C++ signature with the body as inline PPC asm.
// These can be incrementally replaced with real C++ as decompilation progresses.

template <typename T0> class allocator;
template <typename T0, typename T1, typename T2> class basic_string;
template <typename T0> class char_traits;

template <typename T0, typename T1, typename T2> class basic_string;
template <> class basic_string<wchar_t, char_traits<wchar_t>, allocator<wchar_t> > {
public:
    basic_string(unsigned short *, allocator<wchar_t> &);
    basic_string(basic_string<wchar_t, char_traits<wchar_t>, allocator<wchar_t> > &);
};

// 0x803B518C (176 bytes)
// basic_string<wchar_t, char_traits<wchar_t>, allocator<wchar_t> >::basic_string(unsigned wchar_t *, allocator<wchar_t> &)
__attribute__((noreturn))
basic_string<wchar_t, char_traits<wchar_t>, allocator<wchar_t> >::basic_string(unsigned short *, allocator<wchar_t> &) {
    __asm__ __volatile__(
        "stwu	1,-24(1)\n"
        "mflr	0\n"
        "stmw	28,8(1)\n"
        "stw	0,28(1)\n"
        "li	0,0\n"
        "mr	29,3\n"
        "stw	0,0(29)\n"
        "addi	9,29,8\n"
        "stw	0,4(29)\n"
        "mr	28,4\n"
        "stw	0,4(9)\n"
        "li	30,0\n"
        "lhz	0,0(28)\n"
        "cmpwi	0,0\n"
        "beq	.L_803B51E0\n"
        "li	11,0\n"
        "mr	9,28\n"
        ".L_803B51D0:\n"
        "lhzu	0,2(9)\n"
        "addi	30,30,1\n"
        "cmpw	0,11\n"
        "bne	.L_803B51D0\n"
        ".L_803B51E0:\n"
        "add	30,30,30\n"
        "mr	3,29\n"
        "add	30,30,28\n"
        "subf	31,28,30\n"
        "srawi	4,31,1\n"
        "addi	4,4,1\n"
        ".long 0x4bffff1d  /* bl _String_base<wchar_t, allocator<wchar_t> >::_M_allocate_block(unsigned int) */\n"
        "lwz	3,0(29)\n"
        "cmpw	30,28\n"
        "beq	.L_803B5218\n"
        "mr	4,28\n"
        "mr	5,31\n"
        ".long 0x4be8e2e9  /* bl memmove */\n"
        "add	3,3,31\n"
        ".L_803B5218:\n"
        "stw	3,4(29)\n"
        "li	0,0\n"
        "sth	0,0(3)\n"
        "mr	3,29\n"
        "lwz	0,28(1)\n"
        "mtlr	0\n"
        "lmw	28,8(1)\n"
        "addi	1,1,24\n"
        "blr\n"
    );
    __builtin_unreachable();
}

// 0x803B523C (128 bytes)
// basic_string<wchar_t, char_traits<wchar_t>, allocator<wchar_t> >::basic_string(basic_string<wchar_t, char_traits<wchar_t>, allocator<wchar_t> > &)
__attribute__((noreturn))
basic_string<wchar_t, char_traits<wchar_t>, allocator<wchar_t> >::basic_string(basic_string<wchar_t, char_traits<wchar_t>, allocator<wchar_t> > &) {
    __asm__ __volatile__(
        "stwu	1,-32(1)\n"
        "mflr	0\n"
        "stmw	28,16(1)\n"
        "stw	0,36(1)\n"
        "mr	31,3\n"
        "li	0,0\n"
        "stw	0,0(31)\n"
        "addi	9,31,8\n"
        "stw	0,4(31)\n"
        "stw	0,4(9)\n"
        "lwz	29,0(4)\n"
        "lwz	30,4(4)\n"
        "subf	28,29,30\n"
        "srawi	4,28,1\n"
        "addi	4,4,1\n"
        ".long 0x4bfffe9d  /* bl _String_base<wchar_t, allocator<wchar_t> >::_M_allocate_block(unsigned int) */\n"
        "lwz	3,0(31)\n"
        "cmpw	30,29\n"
        "beq	.L_803B5298\n"
        "mr	4,29\n"
        "mr	5,28\n"
        ".long 0x4be8e269  /* bl memmove */\n"
        "add	3,3,28\n"
        ".L_803B5298:\n"
        "stw	3,4(31)\n"
        "li	0,0\n"
        "sth	0,0(3)\n"
        "mr	3,31\n"
        "lwz	0,36(1)\n"
        "mtlr	0\n"
        "lmw	28,16(1)\n"
        "addi	1,1,32\n"
        "blr\n"
    );
    __builtin_unreachable();
}

