#include "types.h"
// Auto-generated inline asm decomp stubs for ERQuickdata
// Generated by gen_asm_decomp.py
// 13 functions, 1696 bytes
//
// Each function has its original C++ signature with the body as inline PPC asm.
// These can be incrementally replaced with real C++ as decompilation progresses.

class EFile;

class ERQuickdata {
public:
    ERQuickdata(void);
    ~ERQuickdata(void);
    void reset(void);
    void Reload(EFile *);
    void Load(EFile *, int);
    void getTableIndex(int, int, char *);
    void getTable(char *);
    void getRowIndex(int, int, char *, char **);
    void getRow(void *, char *);
    void getStartAddr(int);
    void findTableIndex(int, int, void *);
    void findRow(void *, unsigned int *);
    void FindTableName(void *, char **);
};

// 0x8031B7F4 (72 bytes)
// ERQuickdata::ERQuickdata(void)
__attribute__((noreturn))
ERQuickdata::ERQuickdata(void) {
    __asm__ __volatile__(
        "stwu	1,-16(1)\n"
        "mflr	0\n"
        "stmw	30,8(1)\n"
        "stw	0,20(1)\n"
        "mr	30,3\n"
        ".long 0x4bff65c1  /* bl EResource::EResource(void) */\n"
        "lis	9,-32697\n"
        "li	0,0\n"
        "addi	9,9,-18968\n"
        "stw	0,24(30)\n"
        "stw	9,0(30)\n"
        "mr	3,30\n"
        "stw	0,20(30)\n"
        "lwz	0,20(1)\n"
        "mtlr	0\n"
        "lmw	30,8(1)\n"
        "addi	1,1,16\n"
        "blr\n"
    );
    __builtin_unreachable();
}

// 0x8031B83C (96 bytes)
// ERQuickdata::~ERQuickdata(void)
__attribute__((noreturn))
ERQuickdata::~ERQuickdata(void) {
    __asm__ __volatile__(
        "stwu	1,-16(1)\n"
        "mflr	0\n"
        "stmw	30,8(1)\n"
        "stw	0,20(1)\n"
        "lis	9,-32697\n"
        "mr	31,3\n"
        "addi	9,9,-18968\n"
        "mr	30,4\n"
        "stw	9,0(31)\n"
        ".long 0x4800003d  /* bl ERQuickdata::reset(void) */\n"
        "mr	3,31\n"
        "li	4,0\n"
        ".long 0x4bff658d  /* bl EResource::~EResource(void) */\n"
        "andi.	0,30,1\n"
        "beq	.L_8031B888\n"
        "lis	3,-32692\n"
        "mr	4,31\n"
        "addi	3,3,-20832\n"
        ".long 0x4800be29  /* bl EResourceManager::Free(void *) */\n"
        ".L_8031B888:\n"
        "lwz	0,20(1)\n"
        "mtlr	0\n"
        "lmw	30,8(1)\n"
        "addi	1,1,16\n"
        "blr\n"
    );
    __builtin_unreachable();
}

// 0x8031B89C (84 bytes)
// ERQuickdata::reset(void)
__attribute__((noreturn))
void ERQuickdata::reset(void) {
    __asm__ __volatile__(
        "stwu	1,-16(1)\n"
        "mflr	0\n"
        "stw	31,12(1)\n"
        "stw	0,20(1)\n"
        "mr	31,3\n"
        "lwz	0,20(31)\n"
        "cmpwi	0,0\n"
        "beq	.L_8031B8C0\n"
        ".long 0x48000035  /* bl ERQuickdata::UnlockImage(void) */\n"
        ".L_8031B8C0:\n"
        "lis	3,-32692\n"
        "lwz	4,20(31)\n"
        "addi	3,3,-20832\n"
        ".long 0x4800bde1  /* bl EResourceManager::Free(void *) */\n"
        "li	0,0\n"
        "stw	0,24(31)\n"
        "stw	0,20(31)\n"
        "lwz	0,20(1)\n"
        "mtlr	0\n"
        "lwz	31,12(1)\n"
        "addi	1,1,16\n"
        "blr\n"
    );
    __builtin_unreachable();
}

// 0x8031B8F8 (80 bytes)
// ERQuickdata::Reload(EFile *)
__attribute__((noreturn))
void ERQuickdata::Reload(EFile *) {
    __asm__ __volatile__(
        "stwu	1,-24(1)\n"
        "mflr	0\n"
        "stmw	29,12(1)\n"
        "stw	0,28(1)\n"
        "mr	30,3\n"
        "mr	29,4\n"
        ".long 0x4bffffe1  /* bl ERQuickdata::UnlockImage(void) */\n"
        "lis	9,-32692\n"
        "lwz	4,20(30)\n"
        "lwz	6,-17472(9)\n"
        "addi	5,30,24\n"
        "mr	3,29\n"
        ".long 0x4800098d  /* bl ReloadXImage(EFile *, void *, unsigned int &, int) */\n"
        "mr	3,30\n"
        ".long 0x4bffffc5  /* bl ERQuickdata::LockImage(void) */\n"
        "lwz	0,28(1)\n"
        "mtlr	0\n"
        "lmw	29,12(1)\n"
        "addi	1,1,24\n"
        "blr\n"
    );
    __builtin_unreachable();
}

// 0x8031B948 (108 bytes)
// ERQuickdata::Load(EFile *, int)
__attribute__((noreturn))
void ERQuickdata::Load(EFile *, int) {
    __asm__ __volatile__(
        "stwu	1,-24(1)\n"
        "mflr	0\n"
        "stmw	29,12(1)\n"
        "stw	0,28(1)\n"
        "mr	31,3\n"
        "mr	30,4\n"
        "mr	29,5\n"
        ".long 0x4bffff39  /* bl ERQuickdata::reset(void) */\n"
        "lwz	4,20(31)\n"
        "mr	3,30\n"
        "mr	6,29\n"
        "addi	5,31,24\n"
        ".long 0x4800093d  /* bl ReloadXImage(EFile *, void *, unsigned int &, int) */\n"
        "cmpwi	3,0\n"
        "stw	3,20(31)\n"
        "beq	.L_8031B998\n"
        "lwz	0,16(31)\n"
        "lwz	9,24(31)\n"
        "rlwimi	0,9,8,0,23\n"
        "stw	0,16(31)\n"
        ".L_8031B998:\n"
        "mr	3,31\n"
        ".long 0x4bffff59  /* bl ERQuickdata::LockImage(void) */\n"
        "lwz	0,28(1)\n"
        "mtlr	0\n"
        "lmw	29,12(1)\n"
        "addi	1,1,24\n"
        "blr\n"
    );
    __builtin_unreachable();
}

// 0x8031B9B4 (192 bytes)
// ERQuickdata::getTableIndex(int, int, char *)
__attribute__((noreturn))
void ERQuickdata::getTableIndex(int, int, char *) {
    __asm__ __volatile__(
        "stwu	1,-32(1)\n"
        "mflr	0\n"
        "stmw	27,12(1)\n"
        "stw	0,36(1)\n"
        "mr	27,3\n"
        "mr	30,4\n"
        "mr	29,5\n"
        "mr	28,6\n"
        ".L_8031B9D4:\n"
        "cmpwi	28,0\n"
        "beq	.L_8031BA5C\n"
        "subf.	9,30,29\n"
        "blt	.L_8031BA5C\n"
        "bne	.L_8031BA10\n"
        "mulli	0,30,20\n"
        "lwz	9,20(27)\n"
        "mr	3,28\n"
        "addi	9,9,24\n"
        "lwzx	4,9,0\n"
        ".long 0x4bf27e3d  /* bl strcmp */\n"
        "cmpwi	3,0\n"
        "mr	3,30\n"
        "beq	.L_8031BA60\n"
        "b	.L_8031BA5C\n"
        ".L_8031BA10:\n"
        "srwi	0,9,31\n"
        "lwz	11,20(27)\n"
        "add	0,9,0\n"
        "mr	3,28\n"
        "srawi	0,0,1\n"
        "addi	11,11,24\n"
        "add	31,30,0\n"
        "mulli	9,31,20\n"
        "lwzx	4,11,9\n"
        ".long 0x4bf27e05  /* bl strcmp */\n"
        "cmpwi	3,0\n"
        "bne	.L_8031BA48\n"
        "mr	3,31\n"
        "b	.L_8031BA60\n"
        ".L_8031BA48:\n"
        "ble	.L_8031BA54\n"
        "addi	30,31,1\n"
        "b	.L_8031B9D4\n"
        ".L_8031BA54:\n"
        "addi	29,31,-1\n"
        "b	.L_8031B9D4\n"
        ".L_8031BA5C:\n"
        "li	3,-1\n"
        ".L_8031BA60:\n"
        "lwz	0,36(1)\n"
        "mtlr	0\n"
        "lmw	27,12(1)\n"
        "addi	1,1,32\n"
        "blr\n"
    );
    __builtin_unreachable();
}

// 0x8031BA74 (104 bytes)
// ERQuickdata::getTable(char *)
__attribute__((noreturn))
void ERQuickdata::getTable(char *) {
    __asm__ __volatile__(
        "stwu	1,-16(1)\n"
        "mflr	0\n"
        "stmw	30,8(1)\n"
        "stw	0,20(1)\n"
        "mr	31,3\n"
        "li	30,0\n"
        "mr.	4,4\n"
        "beq	.L_8031BAC4\n"
        "lwz	9,20(31)\n"
        "mr	6,4\n"
        "li	4,0\n"
        "lwz	5,8(9)\n"
        "addi	5,5,-1\n"
        ".long 0x4bffff0d  /* bl ERQuickdata::getTableIndex(int, int, char *) */\n"
        "mr.	3,3\n"
        "blt	.L_8031BAC4\n"
        "mulli	9,3,20\n"
        "lwz	0,20(31)\n"
        "addi	9,9,24\n"
        "add	30,0,9\n"
        ".L_8031BAC4:\n"
        "mr	3,30\n"
        "lwz	0,20(1)\n"
        "mtlr	0\n"
        "lmw	30,8(1)\n"
        "addi	1,1,16\n"
        "blr\n"
    );
    __builtin_unreachable();
}

// 0x8031BADC (184 bytes)
// ERQuickdata::getRowIndex(int, int, char *, char **)
__attribute__((noreturn))
void ERQuickdata::getRowIndex(int, int, char *, char **) {
    __asm__ __volatile__(
        "stwu	1,-32(1)\n"
        "mflr	0\n"
        "stmw	27,12(1)\n"
        "stw	0,36(1)\n"
        "mr	30,3\n"
        "mr	29,4\n"
        "mr	28,5\n"
        "mr	27,6\n"
        ".L_8031BAFC:\n"
        "cmpwi	28,0\n"
        "beq	.L_8031BB7C\n"
        "cmpwi	27,0\n"
        "beq	.L_8031BB7C\n"
        "subf.	9,30,29\n"
        "blt	.L_8031BB7C\n"
        "bne	.L_8031BB38\n"
        "slwi	0,30,2\n"
        "mr	3,28\n"
        "lwzx	4,27,0\n"
        ".long 0x4bf27d15  /* bl strcmp */\n"
        "cmpwi	3,0\n"
        "mr	3,30\n"
        "beq	.L_8031BB80\n"
        "b	.L_8031BB7C\n"
        ".L_8031BB38:\n"
        "srwi	0,9,31\n"
        "mr	3,28\n"
        "add	0,9,0\n"
        "srawi	0,0,1\n"
        "add	31,30,0\n"
        "slwi	9,31,2\n"
        "lwzx	4,9,27\n"
        ".long 0x4bf27ce5  /* bl strcmp */\n"
        "cmpwi	3,0\n"
        "bne	.L_8031BB68\n"
        "mr	3,31\n"
        "b	.L_8031BB80\n"
        ".L_8031BB68:\n"
        "ble	.L_8031BB74\n"
        "addi	30,31,1\n"
        "b	.L_8031BAFC\n"
        ".L_8031BB74:\n"
        "addi	29,31,-1\n"
        "b	.L_8031BAFC\n"
        ".L_8031BB7C:\n"
        "li	3,-1\n"
        ".L_8031BB80:\n"
        "lwz	0,36(1)\n"
        "mtlr	0\n"
        "lmw	27,12(1)\n"
        "addi	1,1,32\n"
        "blr\n"
    );
    __builtin_unreachable();
}

// 0x8031BB94 (124 bytes)
// ERQuickdata::getRow(void *, char *)
__attribute__((noreturn))
void ERQuickdata::getRow(void *, char *) {
    __asm__ __volatile__(
        "stwu	1,-24(1)\n"
        "mflr	0\n"
        "stmw	29,12(1)\n"
        "stw	0,28(1)\n"
        "li	29,0\n"
        "mr.	30,4\n"
        "beq	.L_8031BBF8\n"
        "cmpwi	5,0\n"
        "beq	.L_8031BBF8\n"
        "lwz	6,8(30)\n"
        "cmpwi	6,0\n"
        "beq	.L_8031BBF8\n"
        "lwz	31,16(30)\n"
        "cmpwi	31,0\n"
        "bne	.L_8031BBD4\n"
        "li	31,1\n"
        ".L_8031BBD4:\n"
        "lwz	4,12(30)\n"
        "li	3,0\n"
        "addi	4,4,-1\n"
        ".long 0x4bfffefd  /* bl ERQuickdata::getRowIndex(int, int, char *, char **) */\n"
        "mr.	3,3\n"
        "blt	.L_8031BBF8\n"
        "mullw	9,3,31\n"
        "lwz	0,4(30)\n"
        "add	29,0,9\n"
        ".L_8031BBF8:\n"
        "mr	3,29\n"
        "lwz	0,28(1)\n"
        "mtlr	0\n"
        "lmw	29,12(1)\n"
        "addi	1,1,24\n"
        "blr\n"
    );
    __builtin_unreachable();
}

// 0x8031BC10 (120 bytes)
// ERQuickdata::getStartAddr(int)
__attribute__((noreturn))
void ERQuickdata::getStartAddr(int) {
    __asm__ __volatile__(
        "mulli	0,4,20\n"
        "lwz	11,20(3)\n"
        "addi	9,11,28\n"
        "lwzx	3,9,0\n"
        "cmpwi	3,0\n"
        "bnelr\n"
        "mr	0,4\n"
        "cmpwi	0,0\n"
        "addi	4,4,-1\n"
        "blelr\n"
        "mulli	9,4,20\n"
        "addi	9,9,36\n"
        "add	9,9,11\n"
        ".L_8031BC44:\n"
        "lwz	3,-8(9)\n"
        "cmpwi	3,0\n"
        "beq	.L_8031BC70\n"
        "lwz	11,4(9)\n"
        "cmpwi	11,0\n"
        "bne	.L_8031BC60\n"
        "li	11,1\n"
        ".L_8031BC60:\n"
        "lwz	0,0(9)\n"
        "mullw	0,11,0\n"
        "add	3,3,0\n"
        "blr\n"
        ".L_8031BC70:\n"
        "mr	0,4\n"
        "addi	9,9,-20\n"
        "cmpwi	0,0\n"
        "addi	4,4,-1\n"
        "bgt	.L_8031BC44\n"
        "blr\n"
    );
    __builtin_unreachable();
}

// 0x8031BC88 (260 bytes)
// ERQuickdata::findTableIndex(int, int, void *)
__attribute__((noreturn))
void ERQuickdata::findTableIndex(int, int, void *) {
    __asm__ __volatile__(
        "stwu	1,-32(1)\n"
        "mflr	0\n"
        "stmw	27,12(1)\n"
        "stw	0,36(1)\n"
        "mr	28,3\n"
        "mr	30,4\n"
        "mr	29,5\n"
        "mr	27,6\n"
        ".L_8031BCA8:\n"
        "subf.	9,30,29\n"
        "blt	.L_8031BD04\n"
        "bne	.L_8031BD0C\n"
        "mulli	0,30,20\n"
        "lwz	3,20(28)\n"
        "addi	9,3,28\n"
        "lwzx	10,9,0\n"
        "cmpwi	10,0\n"
        "beq	.L_8031BD04\n"
        "cmplw	27,10\n"
        "blt	.L_8031BD04\n"
        "addi	9,3,40\n"
        "lwzx	11,9,0\n"
        "cmpwi	11,0\n"
        "bne	.L_8031BCE8\n"
        "li	11,1\n"
        ".L_8031BCE8:\n"
        "addi	9,3,36\n"
        "lwzx	0,9,0\n"
        "mr	3,30\n"
        "mullw	0,11,0\n"
        "add	0,10,0\n"
        "cmplw	27,0\n"
        "blt	.L_8031BD78\n"
        ".L_8031BD04:\n"
        "li	3,-1\n"
        "b	.L_8031BD78\n"
        ".L_8031BD0C:\n"
        "srwi	0,9,31\n"
        "mr	3,28\n"
        "add	0,9,0\n"
        "srawi	0,0,1\n"
        "add	31,30,0\n"
        "mr	4,31\n"
        ".long 0x4bfffeed  /* bl ERQuickdata::getStartAddr(int) */\n"
        "cmplw	27,3\n"
        "bge	.L_8031BD38\n"
        "addi	29,31,-1\n"
        "b	.L_8031BCA8\n"
        ".L_8031BD38:\n"
        "mulli	0,31,20\n"
        "lwz	10,20(28)\n"
        "addi	9,10,40\n"
        "lwzx	11,9,0\n"
        "cmpwi	11,0\n"
        "bne	.L_8031BD54\n"
        "li	11,1\n"
        ".L_8031BD54:\n"
        "addi	9,10,36\n"
        "lwzx	0,9,0\n"
        "mullw	0,11,0\n"
        "add	0,3,0\n"
        "cmplw	27,0\n"
        "blt	.L_8031BD74\n"
        "addi	30,31,1\n"
        "b	.L_8031BCA8\n"
        ".L_8031BD74:\n"
        "mr	3,31\n"
        ".L_8031BD78:\n"
        "lwz	0,36(1)\n"
        "mtlr	0\n"
        "lmw	27,12(1)\n"
        "addi	1,1,32\n"
        "blr\n"
    );
    __builtin_unreachable();
}

// 0x8031BD8C (156 bytes)
// ERQuickdata::findRow(void *, unsigned int *)
__attribute__((noreturn))
void ERQuickdata::findRow(void *, unsigned int *) {
    __asm__ __volatile__(
        "stwu	1,-24(1)\n"
        "mflr	0\n"
        "stmw	29,12(1)\n"
        "stw	0,28(1)\n"
        "mr	31,3\n"
        "mr	29,5\n"
        "lwz	9,20(31)\n"
        "mr	30,4\n"
        "li	4,0\n"
        "lwz	5,8(9)\n"
        "mr	6,30\n"
        "addi	5,5,-1\n"
        ".long 0x4bfffecd  /* bl ERQuickdata::findTableIndex(int, int, void *) */\n"
        "mr.	3,3\n"
        "li	7,0\n"
        "blt	.L_8031BE10\n"
        "mulli	8,3,20\n"
        "lwz	3,20(31)\n"
        "addi	9,3,40\n"
        "lwzx	11,9,8\n"
        "cmpwi	11,0\n"
        "bne	.L_8031BDE8\n"
        "li	11,1\n"
        ".L_8031BDE8:\n"
        "addi	9,3,28\n"
        "lwzx	0,9,8\n"
        "subf	0,0,30\n"
        "divwu	10,0,11\n"
        "mullw	9,10,11\n"
        "cmpw	0,9\n"
        "bne	.L_8031BE10\n"
        "addi	0,8,24\n"
        "stw	10,0(29)\n"
        "add	7,3,0\n"
        ".L_8031BE10:\n"
        "mr	3,7\n"
        "lwz	0,28(1)\n"
        "mtlr	0\n"
        "lmw	29,12(1)\n"
        "addi	1,1,24\n"
        "blr\n"
    );
    __builtin_unreachable();
}

// 0x8031BE28 (116 bytes)
// ERQuickdata::FindTableName(void *, char **)
__attribute__((noreturn))
void ERQuickdata::FindTableName(void *, char **) {
    __asm__ __volatile__(
        "stwu	1,-16(1)\n"
        "mflr	0\n"
        "stmw	30,8(1)\n"
        "stw	0,20(1)\n"
        "mr	31,3\n"
        "mr	30,5\n"
        "lwz	9,20(31)\n"
        "mr	6,4\n"
        "li	4,0\n"
        "lwz	5,8(9)\n"
        "addi	5,5,-1\n"
        ".long 0x4bfffe35  /* bl ERQuickdata::findTableIndex(int, int, void *) */\n"
        "mr.	3,3\n"
        "bge	.L_8031BE70\n"
        "li	0,0\n"
        "li	3,0\n"
        "stw	0,0(30)\n"
        "b	.L_8031BE88\n"
        ".L_8031BE70:\n"
        "mulli	0,3,20\n"
        "lwz	9,20(31)\n"
        "li	3,1\n"
        "addi	9,9,24\n"
        "lwzx	11,9,0\n"
        "stw	11,0(30)\n"
        ".L_8031BE88:\n"
        "lwz	0,20(1)\n"
        "mtlr	0\n"
        "lmw	30,8(1)\n"
        "addi	1,1,16\n"
        "blr\n"
    );
    __builtin_unreachable();
}

