#include "types.h"
// Inline asm leaf matches for ENgcMovie
// 1 functions, 92 bytes

#include "types.h"
// Auto-generated inline asm decomp stubs for ENgcMovie
// Generated by gen_asm_decomp.py
// 18 functions, 4552 bytes
//
// Each function has its original C++ signature with the body as inline PPC asm.
// These can be incrementally replaced with real C++ as decompilation progresses.

class EAllocGroup;
class EFile;
class THPAudioInfo;
class _GXRenderModeObj;

class ENgcMovie {
public:
    ENgcMovie(void);
    ~ENgcMovie(void);
    void Load(EFile *, unsigned int, unsigned int, unsigned int);
    void Start(int, int);
    void IsFinished(void);
    void GetNextFrame(void);
    void PlayerInit(int);
    void PlayerQuit(void);
    void PlayerOpen(unsigned int, bool);
    void PlayerClose(void);
    void PlayerCreateBuffers(EAllocGroup &);
    void PlayerPrepare(int, int, int);
    void PlayerPlay(void);
    void PlayerStop(void);
    void PlayerSkip(void);
    void PlayerDrawCurrentFrame(_GXRenderModeObj *, unsigned int, unsigned int, unsigned int, unsigned int);
    void PlayerGetAudioInfo(THPAudioInfo *);
    void PlayerDrawDone(void);
};


// 0x80335F10 (92 bytes)
// ENgcMovie::PlayerPlay(void)
__attribute__((noreturn))
void ENgcMovie::PlayerPlay(void) {
    __asm__ __volatile__(
        "lis	9,-32691\n"
        "addi	8,9,14656\n"
        "lwz	0,160(8)\n"
        "cmpwi	0,0\n"
        "beq	.L_80335F64\n"
        "lbz	0,164(8)\n"
        "cmpwi	0,1\n"
        "beq	.L_80335F38\n"
        "cmpwi	0,4\n"
        "bne	.L_80335F64\n"
        ".L_80335F38:\n"
        "li	9,-1\n"
        "li	11,0\n"
        "li	0,2\n"
        "li	10,-1\n"
        "stb	0,164(8)\n"
        "li	3,1\n"
        "stw	9,200(8)\n"
        "stw	10,204(8)\n"
        "stw	11,212(8)\n"
        "stw	11,208(8)\n"
        "blr\n"
        ".L_80335F64:\n"
        "li	3,0\n"
        "blr\n"
    );
}

