#include "types.h"
#include "stub_classes.h"
// Auto-generated matching stubs for Bookmark (medium functions)
// Generated by auto_match_medium.py
// 1 functions, 28 bytes

// 0x8014ABC8 (28 bytes)
void WantFear::Bookmark::Clear() { *(short*)((char*)this + 0x8) = 0; *(int*)((char*)this + 0x4) = 0; *(short*)((char*)this + 0x0) = 0; *(short*)((char*)this + 0x2) = 0; }

