#include "types.h"
#include "stub_classes.h"
// Auto-generated raw-byte matches for void_partial_sort_L_Neighbor_ptrp
// Generated by gen_raw_byte_matches.py
// 1 functions, 48 bytes
// These functions are matched by directly injecting DOL bytes into the skeleton.
// The C++ stubs below exist only as annotations for the matching pipeline.

// 0x8039EAB0 (48 bytes)
// void_partial_sort_L_Neighbor_ptrp__RelationsCmp_R__Neighbor_ptrp__Neighbor_ptrp__Neighbor_ptrp__RelationsCmp
// [raw byte match - injected directly from DOL]

