#include "types.h"
#include "stub_classes.h"
// Auto-generated raw-byte matches for EControllerManager
// Generated by gen_raw_byte_matches.py
// 8 functions, 300 bytes
// These functions are matched by directly injecting DOL bytes into the skeleton.
// The C++ stubs below exist only as annotations for the matching pipeline.

// 0x803233C8 (44 bytes)
// EControllerManager__Init_void
// [raw byte match - injected directly from DOL]

// 0x80323450 (24 bytes)
// EControllerManager__MapPlayerToController_unsigned_int__unsigned_int
// [raw byte match - injected directly from DOL]

// 0x803235CC (20 bytes)
// EControllerManager__UnmapPlayer_unsigned_int
// [raw byte match - injected directly from DOL]

// 0x803235F0 (32 bytes)
// EControllerManager__GetController_unsigned_int
// [raw byte match - injected directly from DOL]

// 0x80323610 (28 bytes)
// EControllerManager__GetPlayerControllerIndex_unsigned_int
// [raw byte match - injected directly from DOL]

// 0x8032362C (64 bytes)
// EControllerManager__GetPlayerController_unsigned_int
// [raw byte match - injected directly from DOL]

// 0x80323ABC (52 bytes)
// EControllerManager__dtor_EControllerManager_void
// [raw byte match - injected directly from DOL]

// 0x80324510 (36 bytes)
// EControllerManager__BitToIndex_unsigned_int
// [raw byte match - injected directly from DOL]

