#include "types.h"
#include "stub_classes.h"
// Auto-generated raw-byte matches for REffectsSequencer
// Generated by gen_raw_byte_matches.py
// 8 functions, 388 bytes
// These functions are matched by directly injecting DOL bytes into the skeleton.
// The C++ stubs below exist only as annotations for the matching pipeline.

// 0x8036AE70 (60 bytes)
// REffectsSequencer__REffectsSequencer_void
// [raw byte match - injected directly from DOL]

// 0x8036AF08 (52 bytes)
// REffectsSequencer__Deallocate_void
// [raw byte match - injected directly from DOL]

// 0x8036AFFC (64 bytes)
// REffectsSequencer__Refresh_EFile_ptr
// [raw byte match - injected directly from DOL]

// 0x8036B0AC (48 bytes)
// REffectsSequencer__New_void
// [raw byte match - injected directly from DOL]

// 0x8036B0DC (32 bytes)
// REffectsSequencer__Construct_REffectsSequencer_ptr
// [raw byte match - injected directly from DOL]

// 0x8036B0FC (36 bytes)
// REffectsSequencer__Destruct_REffectsSequencer_ptr
// [raw byte match - injected directly from DOL]

// 0x8036B120 (64 bytes)
// REffectsSequencer__SafeDelete_void
// [raw byte match - injected directly from DOL]

// 0x8036B1FC (32 bytes)
// REffectsSequencer__CreateCopy_void__const
// [raw byte match - injected directly from DOL]

