#include "types.h"
#include "stub_classes.h"
// Auto-generated matching stubs for CasListener (medium functions)
// Generated by auto_match_medium.py
// 1 functions, 28 bytes

// 0x80161B50 (28 bytes)
CasListener::CasListener() { *(void**)((char*)this + 0x4) = (void*)0x80465F68; *(int*)((char*)this + 0x0) = 0; }

