#include "types.h"
// Auto-generated inline asm decomp stubs for EResourceMap
// Generated by gen_asm_decomp.py
// 6 functions, 1004 bytes
//
// Each function has its original C++ signature with the body as inline PPC asm.
// These can be incrementally replaced with real C++ as decompilation progresses.

class EResource;
class EResourceManager;

class EResourceMap {
public:
    void Search(unsigned int);
    void Find(unsigned int, EResource **);
    void SetCapacity(int, char *);
    void Insert(EResourceManager *, unsigned int, EResource *, char *);
    void Remove(unsigned int);
    void RemoveAll(void);
};

// 0x80327A9C (76 bytes)
// EResourceMap::Search(unsigned int)
__attribute__((noreturn))
void EResourceMap::Search(unsigned int) {
    __asm__ __volatile__(
        "lwz	11,4(3)\n"
        "li	10,0\n"
        "cmpw	10,11\n"
        "bge	.L_80327AE0\n"
        "lwz	8,0(3)\n"
        ".L_80327AB0:\n"
        "add	0,10,11\n"
        "srawi	3,0,1\n"
        "slwi	9,3,3\n"
        "lwzx	0,9,8\n"
        "cmplw	4,0\n"
        "ble	.L_80327AD0\n"
        "addi	10,3,1\n"
        "b	.L_80327AD8\n"
        ".L_80327AD0:\n"
        "bgelr\n"
        "mr	11,3\n"
        ".L_80327AD8:\n"
        "cmpw	10,11\n"
        "blt	.L_80327AB0\n"
        ".L_80327AE0:\n"
        "mr	3,10\n"
        "blr\n"
    );
    __builtin_unreachable();
}

// 0x80327AE8 (116 bytes)
// EResourceMap::Find(unsigned int, EResource **)
__attribute__((noreturn))
void EResourceMap::Find(unsigned int, EResource **) {
    __asm__ __volatile__(
        "stwu	1,-24(1)\n"
        "mflr	0\n"
        "stmw	29,12(1)\n"
        "stw	0,28(1)\n"
        "mr	31,3\n"
        "mr	30,4\n"
        "mr	29,5\n"
        ".long 0x4bffff99  /* bl EResourceMap::Search(unsigned int) */\n"
        "lwz	0,4(31)\n"
        "cmpw	3,0\n"
        "bge	.L_80327B44\n"
        "lwz	11,0(31)\n"
        "slwi	9,3,3\n"
        "lwzx	0,9,11\n"
        "add	10,9,11\n"
        "cmpw	0,30\n"
        "bne	.L_80327B44\n"
        "cmpwi	29,0\n"
        "beq	.L_80327B3C\n"
        "lwz	0,4(10)\n"
        "stw	0,0(29)\n"
        ".L_80327B3C:\n"
        "li	3,1\n"
        "b	.L_80327B48\n"
        ".L_80327B44:\n"
        "li	3,0\n"
        ".L_80327B48:\n"
        "lwz	0,28(1)\n"
        "mtlr	0\n"
        "lmw	29,12(1)\n"
        "addi	1,1,24\n"
        "blr\n"
    );
    __builtin_unreachable();
}

// 0x80327B5C (124 bytes)
// EResourceMap::SetCapacity(int, char *)
__attribute__((noreturn))
void EResourceMap::SetCapacity(int, char *) {
    __asm__ __volatile__(
        "stwu	1,-24(1)\n"
        "mflr	0\n"
        "stmw	29,12(1)\n"
        "stw	0,28(1)\n"
        "mr	31,3\n"
        "mr	30,4\n"
        "lwz	0,8(31)\n"
        "cmpw	30,0\n"
        "ble	.L_80327BC4\n"
        ".long 0x4bfa8381  /* bl MainHeap(void) */\n"
        "slwi	4,30,3\n"
        "li	5,0\n"
        ".long 0x4bfa8f19  /* bl EAHeap::Malloc(unsigned int, int) */\n"
        "mr.	29,3\n"
        "beq	.L_80327BC4\n"
        "lwz	5,8(31)\n"
        "mr	3,29\n"
        "lwz	4,0(31)\n"
        "slwi	5,5,3\n"
        "crclr	4*cr1+eq\n"
        ".long 0x4bf1b8a9  /* bl memcpy */\n"
        ".long 0x4bfa8351  /* bl MainHeap(void) */\n"
        "lwz	4,0(31)\n"
        ".long 0x4bfa91c1  /* bl EAHeap::Free(void *) */\n"
        "stw	30,8(31)\n"
        "stw	29,0(31)\n"
        ".L_80327BC4:\n"
        "lwz	0,28(1)\n"
        "mtlr	0\n"
        "lmw	29,12(1)\n"
        "addi	1,1,24\n"
        "blr\n"
    );
    __builtin_unreachable();
}

// 0x80327BD8 (388 bytes)
// EResourceMap::Insert(EResourceManager *, unsigned int, EResource *, char *)
__attribute__((noreturn))
void EResourceMap::Insert(EResourceManager *, unsigned int, EResource *, char *) {
    __asm__ __volatile__(
        "stwu	1,-24(1)\n"
        "mflr	0\n"
        "stmw	28,8(1)\n"
        "stw	0,28(1)\n"
        "mr	31,3\n"
        "mr	30,5\n"
        "lwz	9,4(31)\n"
        "mr	29,4\n"
        "lwz	0,8(31)\n"
        "mr	28,6\n"
        "mr	5,7\n"
        "cmpw	9,0\n"
        "bne	.L_80327C4C\n"
        "srwi	4,9,31\n"
        "add	4,9,4\n"
        "srawi	4,4,1\n"
        "add	4,9,4\n"
        ".long 0x4bffff41  /* bl EResourceMap::SetCapacity(int, char *) */\n"
        "lwz	9,4(31)\n"
        "lwz	0,8(31)\n"
        "cmpw	9,0\n"
        "bne	.L_80327C4C\n"
        "mr	3,29\n"
        ".long 0x4bfff9fd  /* bl EResourceManager::GetUnreferencedResourceCount(void) */\n"
        "cmpwi	3,0\n"
        "li	3,0\n"
        "beq	.L_80327D48\n"
        "mr	3,29\n"
        ".long 0x4bfff965  /* bl EResourceManager::MakeSpace(void) */\n"
        ".L_80327C4C:\n"
        "lwz	10,4(31)\n"
        "li	3,0\n"
        "cmpwi	10,0\n"
        "beq	.L_80327CE0\n"
        "lwz	0,0(31)\n"
        "slwi	9,10,3\n"
        "add	9,9,0\n"
        "lwz	11,-8(9)\n"
        "cmplw	30,11\n"
        "ble	.L_80327C7C\n"
        "mr	3,10\n"
        "b	.L_80327CE0\n"
        ".L_80327C7C:\n"
        "mr	3,31\n"
        "mr	4,30\n"
        ".long 0x4bfffe19  /* bl EResourceMap::Search(unsigned int) */\n"
        "lwz	9,0(31)\n"
        "slwi	11,3,3\n"
        "lwzx	0,11,9\n"
        "cmpw	0,30\n"
        "bne	.L_80327CA4\n"
        "li	3,0\n"
        "b	.L_80327D48\n"
        ".L_80327CA4:\n"
        "lwz	9,4(31)\n"
        "addi	8,9,-1\n"
        "cmpw	8,3\n"
        "blt	.L_80327CE0\n"
        "slwi	7,8,3\n"
        ".L_80327CB8:\n"
        "lwz	11,0(31)\n"
        "addi	8,8,-1\n"
        "cmpw	8,3\n"
        "add	11,7,11\n"
        "lwz	9,0(11)\n"
        "lwz	10,4(11)\n"
        "addi	7,7,-8\n"
        "stw	9,8(11)\n"
        "stw	10,12(11)\n"
        "bge	.L_80327CB8\n"
        ".L_80327CE0:\n"
        "lwz	11,0(31)\n"
        "slwi	9,3,3\n"
        "stwx	30,9,11\n"
        "lwz	0,0(31)\n"
        "add	9,9,0\n"
        "stw	28,4(9)\n"
        "lwz	11,4(31)\n"
        "lwz	0,12(31)\n"
        "addi	11,11,1\n"
        "cmpw	11,0\n"
        "stw	11,4(31)\n"
        "ble	.L_80327D14\n"
        "stw	11,12(31)\n"
        ".L_80327D14:\n"
        "mr	3,29\n"
        ".long 0x4bfff919  /* bl EResourceManager::GetUnreferencedResourceCount(void) */\n"
        "lwz	0,4(31)\n"
        "lwz	9,16(31)\n"
        "subf	0,3,0\n"
        "cmpw	0,9\n"
        "ble	.L_80327D44\n"
        "mr	3,29\n"
        ".long 0x4bfff8fd  /* bl EResourceManager::GetUnreferencedResourceCount(void) */\n"
        "lwz	0,4(31)\n"
        "subf	0,3,0\n"
        "stw	0,16(31)\n"
        ".L_80327D44:\n"
        "li	3,1\n"
        ".L_80327D48:\n"
        "lwz	0,28(1)\n"
        "mtlr	0\n"
        "lmw	28,8(1)\n"
        "addi	1,1,24\n"
        "blr\n"
    );
    __builtin_unreachable();
}

// 0x80327D5C (212 bytes)
// EResourceMap::Remove(unsigned int)
__attribute__((noreturn))
void EResourceMap::Remove(unsigned int) {
    __asm__ __volatile__(
        "stwu	1,-16(1)\n"
        "mflr	0\n"
        "stmw	30,8(1)\n"
        "stw	0,20(1)\n"
        "mr	31,3\n"
        "mr	30,4\n"
        ".long 0x4bfffd29  /* bl EResourceMap::Search(unsigned int) */\n"
        "lwz	9,0(31)\n"
        "slwi	10,3,3\n"
        "lwzx	0,10,9\n"
        "add	11,10,9\n"
        "cmpw	0,30\n"
        "beq	.L_80327D98\n"
        "li	3,0\n"
        "b	.L_80327E1C\n"
        ".L_80327D98:\n"
        "lwz	11,4(11)\n"
        "li	0,0\n"
        "stw	0,4(11)\n"
        "lwz	9,4(31)\n"
        "addi	9,9,-1\n"
        "cmpw	3,9\n"
        "bge	.L_80327DE8\n"
        "mr	8,10\n"
        ".L_80327DB8:\n"
        "lwz	10,0(31)\n"
        "addi	3,3,1\n"
        "add	10,8,10\n"
        "lwz	11,8(10)\n"
        "lwz	12,12(10)\n"
        "addi	8,8,8\n"
        "stw	11,0(10)\n"
        "stw	12,4(10)\n"
        "lwz	9,4(31)\n"
        "addi	9,9,-1\n"
        "cmpw	3,9\n"
        "blt	.L_80327DB8\n"
        ".L_80327DE8:\n"
        "lwz	9,4(31)\n"
        "li	8,0\n"
        "lwz	10,0(31)\n"
        "li	3,1\n"
        "addi	9,9,-1\n"
        "stw	9,4(31)\n"
        "slwi	11,9,3\n"
        "stwx	8,11,10\n"
        "lwz	9,4(31)\n"
        "lwz	0,0(31)\n"
        "slwi	9,9,3\n"
        "add	9,9,0\n"
        "stw	8,4(9)\n"
        ".L_80327E1C:\n"
        "lwz	0,20(1)\n"
        "mtlr	0\n"
        "lmw	30,8(1)\n"
        "addi	1,1,16\n"
        "blr\n"
    );
    __builtin_unreachable();
}

// 0x80327E48 (88 bytes)
// EResourceMap::RemoveAll(void)
__attribute__((noreturn))
void EResourceMap::RemoveAll(void) {
    __asm__ __volatile__(
        "stwu	1,-16(1)\n"
        "mflr	0\n"
        "stw	31,12(1)\n"
        "stw	0,20(1)\n"
        "mr	31,3\n"
        "lwz	0,0(31)\n"
        "cmpwi	0,0\n"
        "beq	.L_80327E74\n"
        ".long 0x4bfa8099  /* bl MainHeap(void) */\n"
        "lwz	4,0(31)\n"
        ".long 0x4bfa8f09  /* bl EAHeap::Free(void *) */\n"
        ".L_80327E74:\n"
        "li	0,0\n"
        "stw	0,16(31)\n"
        "stw	0,0(31)\n"
        "stw	0,4(31)\n"
        "stw	0,8(31)\n"
        "stw	0,12(31)\n"
        "lwz	0,20(1)\n"
        "mtlr	0\n"
        "lwz	31,12(1)\n"
        "addi	1,1,16\n"
        "blr\n"
    );
    __builtin_unreachable();
}

