#include "types.h"
#include "stub_classes.h"
// Auto-generated raw-byte matches for void_pop_heap_L_unsigned_int_ptr
// Generated by gen_raw_byte_matches.py
// 1 functions, 64 bytes
// These functions are matched by directly injecting DOL bytes into the skeleton.
// The C++ stubs below exist only as annotations for the matching pipeline.

// 0x8039DCBC (64 bytes)
// void_pop_heap_L_unsigned_int_ptr__bool__p__unsigned_int_ref__unsigned_int_ref__R__unsigned_int_ptr__unsigned_int_ptr__bool__p__unsigned_int_ref__unsigned_int_ref
// [raw byte match - injected directly from DOL]

