#include "types.h"
// Auto-generated inline asm decomp stubs for CDirtyXmlNode
// Generated by gen_asm_decomp.py
// 7 functions, 780 bytes
//
// Each function has its original C++ signature with the body as inline PPC asm.
// These can be incrementally replaced with real C++ as decompilation progresses.

class CDirtyXmlNode {
public:
    ~CDirtyXmlNode(void);
    void getFirstAttribute(void);
    void getNextAttribute(void);
    void nextSibling(void);
    void nodeName(void);
    void nodeValue(void);
    void previousSibling(void);
};

// 0x8023A838 (192 bytes)
// CDirtyXmlNode::~CDirtyXmlNode(void)
__attribute__((noreturn))
CDirtyXmlNode::~CDirtyXmlNode(void) {
    __asm__ __volatile__(
        "stwu	1,-24(1)\n"
        "mflr	0\n"
        "stmw	28,8(1)\n"
        "stw	0,28(1)\n"
        "mr	31,3\n"
        "lis	9,-32697\n"
        "lwz	0,16(31)\n"
        "addi	9,9,-24968\n"
        "mr	28,4\n"
        "stw	9,0(31)\n"
        "cmpwi	0,0\n"
        "ble	.L_8023A8C8\n"
        "li	30,0\n"
        "cmpw	30,0\n"
        "bge	.L_8023A8B8\n"
        "li	29,0\n"
        ".L_8023A878:\n"
        "lwz	9,28(31)\n"
        "lwzx	11,29,9\n"
        "cmpwi	11,0\n"
        "beq	.L_8023A8A4\n"
        "lwz	9,0(11)\n"
        "li	4,3\n"
        "lha	3,8(9)\n"
        "lwz	0,12(9)\n"
        "add	3,11,3\n"
        "mtlr	0\n"
        "blrl\n"
        ".L_8023A8A4:\n"
        "lwz	0,16(31)\n"
        "addi	30,30,1\n"
        "addi	29,29,4\n"
        "cmpw	30,0\n"
        "blt	.L_8023A878\n"
        ".L_8023A8B8:\n"
        "lwz	3,28(31)\n"
        "cmpwi	3,0\n"
        "beq	.L_8023A8C8\n"
        ".long 0x48096991  /* bl __builtin_vec_delete */\n"
        ".L_8023A8C8:\n"
        "lis	9,-32697\n"
        "andi.	0,28,1\n"
        "addi	9,9,-24752\n"
        "stw	9,0(31)\n"
        "beq	.L_8023A8E4\n"
        "mr	3,31\n"
        ".long 0x48096941  /* bl __builtin_delete */\n"
        ".L_8023A8E4:\n"
        "lwz	0,28(1)\n"
        "mtlr	0\n"
        "lmw	28,8(1)\n"
        "addi	1,1,24\n"
        "blr\n"
    );
    __builtin_unreachable();
}

// 0x8023A8FC (80 bytes)
// CDirtyXmlNode::getFirstAttribute(void)
__attribute__((noreturn))
void CDirtyXmlNode::getFirstAttribute(void) {
    __asm__ __volatile__(
        "stwu	1,-16(1)\n"
        "mflr	0\n"
        "stmw	30,8(1)\n"
        "stw	0,20(1)\n"
        "li	0,0\n"
        "lwz	9,0(4)\n"
        "stw	0,24(4)\n"
        "mr	30,3\n"
        "lha	0,32(9)\n"
        "lwz	9,36(9)\n"
        "add	4,4,0\n"
        "mtlr	9\n"
        "crclr	4*cr1+eq\n"
        "blrl\n"
        "mr	3,30\n"
        "lwz	0,20(1)\n"
        "mtlr	0\n"
        "lmw	30,8(1)\n"
        "addi	1,1,16\n"
        "blr\n"
    );
    __builtin_unreachable();
}

// 0x8023A94C (180 bytes)
// CDirtyXmlNode::getNextAttribute(void)
__attribute__((noreturn))
void CDirtyXmlNode::getNextAttribute(void) {
    __asm__ __volatile__(
        "stwu	1,-40(1)\n"
        "mflr	0\n"
        "stmw	27,20(1)\n"
        "stw	0,44(1)\n"
        "li	0,0\n"
        "addi	30,1,8\n"
        "stw	0,8(1)\n"
        "mr	31,4\n"
        "stw	0,4(30)\n"
        "mr	28,3\n"
        "stw	0,8(1)\n"
        "lis	27,-32695\n"
        "addi	5,27,-784\n"
        "li	6,128\n"
        "lwz	3,4(31)\n"
        "lwz	4,24(31)\n"
        "stw	0,4(30)\n"
        ".long 0x480013c1  /* bl XmlGetAttribName */\n"
        "cmpwi	3,0\n"
        "ble	.L_8023A9D8\n"
        "lwz	3,4(31)\n"
        "lis	29,-32695\n"
        "lwz	4,24(31)\n"
        "addi	5,29,-656\n"
        "li	6,128\n"
        ".long 0x48001421  /* bl XmlGetAttribValue */\n"
        "cmpwi	3,0\n"
        "ble	.L_8023A9D8\n"
        "lwz	9,24(31)\n"
        "addi	0,27,-784\n"
        "stw	0,8(1)\n"
        "addi	11,29,-656\n"
        "addi	9,9,1\n"
        "stw	11,4(30)\n"
        "stw	9,24(31)\n"
        ".L_8023A9D8:\n"
        "lwz	9,8(1)\n"
        "lwz	10,12(1)\n"
        "mr	3,28\n"
        "stw	9,0(28)\n"
        "stw	10,4(28)\n"
        "lwz	0,44(1)\n"
        "mtlr	0\n"
        "lmw	27,20(1)\n"
        "addi	1,1,40\n"
        "blr\n"
    );
    __builtin_unreachable();
}

// 0x8023AAD8 (76 bytes)
// CDirtyXmlNode::nextSibling(void)
__attribute__((noreturn))
void CDirtyXmlNode::nextSibling(void) {
    __asm__ __volatile__(
        "lwz	9,12(3)\n"
        "li	10,0\n"
        "cmpwi	9,0\n"
        "beq	.L_8023AB1C\n"
        "lwz	11,16(9)\n"
        "addi	0,11,-1\n"
        "cmpw	10,0\n"
        "bge	.L_8023AB1C\n"
        "mr	11,0\n"
        "lwz	9,28(9)\n"
        "mtctr	11\n"
        ".L_8023AB04:\n"
        "lwz	0,0(9)\n"
        "cmpw	0,3\n"
        "bne	.L_8023AB14\n"
        "lwz	10,4(9)\n"
        ".L_8023AB14:\n"
        "addi	9,9,4\n"
        "bdnz	.L_8023AB04\n"
        ".L_8023AB1C:\n"
        "mr	3,10\n"
        "blr\n"
    );
    __builtin_unreachable();
}

// 0x8023AB24 (88 bytes)
// CDirtyXmlNode::nodeName(void)
__attribute__((noreturn))
void CDirtyXmlNode::nodeName(void) {
    __asm__ __volatile__(
        "stwu	1,-16(1)\n"
        "mflr	0\n"
        "stmw	30,8(1)\n"
        "stw	0,20(1)\n"
        "lwz	0,8(3)\n"
        "li	30,0\n"
        "cmpwi	0,1\n"
        "bne	.L_8023AB64\n"
        "lwz	3,4(3)\n"
        "lis	31,-32695\n"
        "addi	4,31,-784\n"
        "li	5,128\n"
        ".long 0x48001149  /* bl XmlGetNodeName */\n"
        "cmpwi	3,0\n"
        "ble	.L_8023AB64\n"
        "addi	30,31,-784\n"
        ".L_8023AB64:\n"
        "mr	3,30\n"
        "lwz	0,20(1)\n"
        "mtlr	0\n"
        "lmw	30,8(1)\n"
        "addi	1,1,16\n"
        "blr\n"
    );
    __builtin_unreachable();
}

// 0x8023AB88 (88 bytes)
// CDirtyXmlNode::nodeValue(void)
__attribute__((noreturn))
void CDirtyXmlNode::nodeValue(void) {
    __asm__ __volatile__(
        "stwu	1,-16(1)\n"
        "mflr	0\n"
        "stmw	30,8(1)\n"
        "stw	0,20(1)\n"
        "lwz	0,8(3)\n"
        "li	30,0\n"
        "cmpwi	0,3\n"
        "bne	.L_8023ABC8\n"
        "lwz	3,4(3)\n"
        "lis	31,-32695\n"
        "addi	4,31,-784\n"
        "li	5,128\n"
        ".long 0x48001155  /* bl XmlGetNodeValue */\n"
        "cmpwi	3,0\n"
        "ble	.L_8023ABC8\n"
        "addi	30,31,-784\n"
        ".L_8023ABC8:\n"
        "mr	3,30\n"
        "lwz	0,20(1)\n"
        "mtlr	0\n"
        "lmw	30,8(1)\n"
        "addi	1,1,16\n"
        "blr\n"
    );
    __builtin_unreachable();
}

// 0x8023ABEC (76 bytes)
// CDirtyXmlNode::previousSibling(void)
__attribute__((noreturn))
void CDirtyXmlNode::previousSibling(void) {
    __asm__ __volatile__(
        "lwz	9,12(3)\n"
        "li	10,0\n"
        "cmpwi	9,0\n"
        "beq	.L_8023AC30\n"
        "lwz	11,16(9)\n"
        "cmpwi	11,1\n"
        "ble	.L_8023AC30\n"
        "addi	11,11,-1\n"
        "lwz	9,28(9)\n"
        "mtctr	11\n"
        "addi	9,9,4\n"
        ".L_8023AC18:\n"
        "lwz	0,0(9)\n"
        "cmpw	0,3\n"
        "bne	.L_8023AC28\n"
        "lwz	10,-4(9)\n"
        ".L_8023AC28:\n"
        "addi	9,9,4\n"
        "bdnz	.L_8023AC18\n"
        ".L_8023AC30:\n"
        "mr	3,10\n"
        "blr\n"
    );
    __builtin_unreachable();
}

