#include "types.h"
// Auto-generated inline asm decomp stubs for FPHeap
// Generated by gen_asm_decomp.py
// 3 functions, 388 bytes
//
// Each function has its original C++ signature with the body as inline PPC asm.
// These can be incrementally replaced with real C++ as decompilation progresses.

class FPHeap {
public:
    void InitializeHeapStatics(void);
    void Malloc(unsigned int, int);
    void Free(void *);
};

// 0x802D08F8 (180 bytes)
// FPHeap::InitializeHeapStatics(void)
__attribute__((noreturn))
void FPHeap::InitializeHeapStatics(void) {
    __asm__ __volatile__(
        "stwu	1,-16(1)\n"
        "mflr	0\n"
        "stmw	30,8(1)\n"
        "stw	0,20(1)\n"
        "lwz	0,-22836(13)\n"
        "lis	11,-32694\n"
        "cmpwi	0,0\n"
        "bne	.L_802D0968\n"
        "addi	9,11,7208\n"
        "stw	0,7208(11)\n"
        "stw	0,4(9)\n"
        "addi	30,9,8\n"
        "li	31,7\n"
        ".L_802D092C:\n"
        "mr	3,30\n"
        "li	4,0\n"
        "li	5,0\n"
        "li	6,0\n"
        "li	7,0\n"
        "addi	30,30,24\n"
        ".long 0x48006639  /* bl FastAllocPool::FastAllocPool(char *, void *, int, int) */\n"
        "cmpwi	31,0\n"
        "addi	31,31,-1\n"
        "bne	.L_802D092C\n"
        "li	0,1\n"
        "lis	3,-32723\n"
        "stw	0,-22836(13)\n"
        "addi	3,3,2188\n"
        ".long 0x4bf71e9d  /* bl atexit */\n"
        ".L_802D0968:\n"
        "lis	9,-32694\n"
        "lis	4,-32702\n"
        "addi	9,9,7208\n"
        "addi	4,4,-6984\n"
        "mr	3,9\n"
        "stw	9,-21320(13)\n"
        ".long 0x480f1699  /* bl AllocPoolManager<FastAllocPool>::InitAllocPools(unsigned int *) */\n"
        ".long 0x4bfffca9  /* bl AptHeap(void) */\n"
        "lis	4,-32718\n"
        "li	5,0\n"
        "addi	4,4,31252\n"
        ".long 0x480085e5  /* bl EA::Allocator::GeneralAllocator::SetMallocFailureFunction(bool (*)(EA::Allocator::GeneralAllocator *, unsigned int, unsigned int, void *), void *) */\n"
        "lwz	0,20(1)\n"
        "mtlr	0\n"
        "lmw	30,8(1)\n"
        "addi	1,1,16\n"
        "blr\n"
    );
    __builtin_unreachable();
}

// 0x802D0FF4 (100 bytes)
// FPHeap::Malloc(unsigned int, int)
__attribute__((noreturn))
void FPHeap::Malloc(unsigned int, int) {
    __asm__ __volatile__(
        "stwu	1,-24(1)\n"
        "mflr	0\n"
        "stmw	29,12(1)\n"
        "stw	0,28(1)\n"
        "mr	30,3\n"
        "mr	29,5\n"
        "mr.	31,4\n"
        "beq	.L_802D1040\n"
        "lwz	3,-21320(13)\n"
        "mr	4,31\n"
        "li	5,8\n"
        ".long 0x480f12d5  /* bl AllocPoolManager<FastAllocPool>::AttemptPoolAlloc(unsigned int, unsigned int) */\n"
        "mr.	3,3\n"
        "bne	.L_802D1044\n"
        "mr	3,30\n"
        "mr	4,31\n"
        "mr	5,29\n"
        ".long 0x4bfffa6d  /* bl EAHeap::Malloc(unsigned int, int) */\n"
        "b	.L_802D1044\n"
        ".L_802D1040:\n"
        "li	3,0\n"
        ".L_802D1044:\n"
        "lwz	0,28(1)\n"
        "mtlr	0\n"
        "lmw	29,12(1)\n"
        "addi	1,1,24\n"
        "blr\n"
    );
    __builtin_unreachable();
}

// 0x802D1058 (108 bytes)
// FPHeap::Free(void *)
__attribute__((noreturn))
void FPHeap::Free(void *) {
    __asm__ __volatile__(
        "stwu	1,-16(1)\n"
        "mflr	0\n"
        "stmw	30,8(1)\n"
        "stw	0,20(1)\n"
        "mr	30,3\n"
        "mr.	31,4\n"
        "beq	.L_802D10B0\n"
        "lwz	3,-21320(13)\n"
        "mr	4,31\n"
        ".long 0x480f12ed  /* bl AllocPoolManager<FastAllocPool>::FindPoolForBlock(void *) */\n"
        "mr.	3,3\n"
        "beq	.L_802D10A4\n"
        "lis	0,17733\n"
        "ori	0,0,21062\n"
        "stw	0,0(31)\n"
        "lwz	9,4(3)\n"
        "stw	9,4(31)\n"
        "stw	31,4(3)\n"
        "b	.L_802D10B0\n"
        ".L_802D10A4:\n"
        "mr	3,30\n"
        "mr	4,31\n"
        ".long 0x4bfffccd  /* bl EAHeap::Free(void *) */\n"
        ".L_802D10B0:\n"
        "lwz	0,20(1)\n"
        "mtlr	0\n"
        "lmw	30,8(1)\n"
        "addi	1,1,16\n"
        "blr\n"
    );
    __builtin_unreachable();
}

