#include "types.h"
// Auto-generated inline asm decomp stubs for List_base_L_pair_L_cXObject_ptr_int_R_allocator_L_pair_L_cXObject_ptr_int_R_R_R
// Generated by gen_asm_decomp.py
// 1 functions, 108 bytes
//
// Each function has its original C++ signature with the body as inline PPC asm.
// These can be incrementally replaced with real C++ as decompilation progresses.

template <typename T0, typename T1> class _List_base;
template <> class _List_base<pair<cXObject *, int>, allocator<pair<cXObject *, int> > > {
public:
    void clear(void);
};

// 0x8039D55C (108 bytes)
// _List_base<pair<cXObject *, int>, allocator<pair<cXObject *, int> > >::clear(void)
__attribute__((noreturn))
void _List_base<pair<cXObject *, int>, allocator<pair<cXObject *, int> > >::clear(void) {
    __asm__ __volatile__(
        "stwu	1,-16(1)\n"
        "mflr	0\n"
        "stmw	30,8(1)\n"
        "stw	0,20(1)\n"
        "mr	30,3\n"
        "lwz	9,4(30)\n"
        "lwz	31,0(9)\n"
        "cmpw	31,9\n"
        "beq	.L_8039D5A4\n"
        ".L_8039D580:\n"
        "mr	3,31\n"
        "lwz	31,0(31)\n"
        "cmpwi	3,0\n"
        "beq	.L_8039D598\n"
        "li	4,16\n"
        ".long 0x4bffe8cd  /* bl __node_alloc<false, 0>::_M_deallocate(void *, unsigned int) */\n"
        ".L_8039D598:\n"
        "lwz	0,4(30)\n"
        "cmpw	31,0\n"
        "bne	.L_8039D580\n"
        ".L_8039D5A4:\n"
        "lwz	9,4(30)\n"
        "stw	9,0(9)\n"
        "lwz	11,4(30)\n"
        "stw	11,4(11)\n"
        "lwz	0,20(1)\n"
        "mtlr	0\n"
        "lmw	30,8(1)\n"
        "addi	1,1,16\n"
        "blr\n"
    );
    __builtin_unreachable();
}

