#include "types.h"
#include "stub_classes.h"
// Auto-generated matching stubs for ESemaphore
// Generated by auto_match.py
// 4 functions, 36 bytes

// 0x802D7854 (8 bytes)
int ESemaphore::GetObject(int) { return 0; }

// 0x802D78C8 (12 bytes)
void ESemaphore::Destroy() { register int __r0 __asm__("r0") = 0; __asm__ __volatile__("" : "+r"(__r0)); *(int*)((char*)this + 0x4) = __r0; }

// 0x802D79F8 (8 bytes)
int ESemaphore::GetCurrentCount() { return *(int*)((char*)this + 0xC); }  // offset 0xC

// 0x802D7A00 (8 bytes)
int ESemaphore::GetMaxCount() { return *(int*)((char*)this + 0x8); }  // offset 0x8

