#include "types.h"
// Auto-generated inline asm decomp stubs for CBMemberTranslator0_L_SaveGameTarget_void_UIDialog_ptr_UIDialog_ptr_R
// Generated by gen_asm_decomp.py
// 1 functions, 144 bytes
//
// Each function has its original C++ signature with the body as inline PPC asm.
// These can be incrementally replaced with real C++ as decompilation progresses.

class CBFunctorBase;

template <typename T0, typename T1> class CBMemberTranslator0;
template <> class CBMemberTranslator0<SaveGameTarget, void (UIDialog::*)(UIDialog *)> {
public:
    void thunk(CBFunctorBase &);
};

// 0x803B2E54 (144 bytes)
// CBMemberTranslator0<SaveGameTarget, void (UIDialog::*)(UIDialog *)>::thunk(CBFunctorBase &)
__attribute__((noreturn))
void CBMemberTranslator0<SaveGameTarget, void (UIDialog::*)(UIDialog *)>::thunk(CBFunctorBase &) {
    __asm__ __volatile__(
        "stwu	1,-8(1)\n"
        "mflr	0\n"
        "stw	0,12(1)\n"
        "lha	10,2(3)\n"
        "lwz	8,8(3)\n"
        "cmpwi	10,0\n"
        "blt	.L_803B2E94\n"
        "lha	9,4(3)\n"
        "slwi	11,10,3\n"
        "add	9,8,9\n"
        "lwz	0,132(9)\n"
        "add	11,11,0\n"
        "lwz	12,-4(11)\n"
        "lwz	11,-8(11)\n"
        "mr	9,12\n"
        "b	.L_803B2E98\n"
        ".L_803B2E94:\n"
        "lwz	9,4(3)\n"
        ".L_803B2E98:\n"
        "lha	3,0(3)\n"
        "cmpwi	10,0\n"
        "blt	.L_803B2EB4\n"
        "srawi	0,11,16\n"
        "add	0,0,3\n"
        "add	3,8,0\n"
        "b	.L_803B2EB8\n"
        ".L_803B2EB4:\n"
        "add	3,8,3\n"
        ".L_803B2EB8:\n"
        "cmpwi	3,0\n"
        "li	0,0\n"
        "beq	.L_803B2EC8\n"
        "addi	0,3,132\n"
        ".L_803B2EC8:\n"
        "mr	3,0\n"
        "mtlr	9\n"
        "blrl\n"
        "lwz	0,12(1)\n"
        "mtlr	0\n"
        "addi	1,1,8\n"
        "blr\n"
    );
    __builtin_unreachable();
}

