#include "types.h"
// Auto-generated inline asm decomp stubs for TArray_L_ENDummyPoint_TArrayDefaultAllocator_R
// Generated by gen_asm_decomp.py
// 4 functions, 656 bytes
//
// Each function has its original C++ signature with the body as inline PPC asm.
// These can be incrementally replaced with real C++ as decompilation progresses.

template <typename T0, typename T1> class TArray;

class ENDummyPoint;
class TArrayDefaultAllocator;

template <typename T0, typename T1> class TArray;
template <> class TArray<ENDummyPoint, TArrayDefaultAllocator> {
public:
    void Copy(ENDummyPoint *, ENDummyPoint *, int);
    void SetSize(int, int);
    void Deallocate(void);
    void operator=(TArray<ENDummyPoint, TArrayDefaultAllocator> &);
};

// 0x8039CBA0 (204 bytes)
// TArray<ENDummyPoint, TArrayDefaultAllocator>::Copy(ENDummyPoint *, ENDummyPoint *, int)
__attribute__((noreturn))
void TArray<ENDummyPoint, TArrayDefaultAllocator>::Copy(ENDummyPoint *, ENDummyPoint *, int) {
    __asm__ __volatile__(
        "addi	8,5,-1\n"
        "cmpwi	5,0\n"
        "beqlr\n"
        "addi	3,3,-64\n"
        "addi	4,4,-64\n"
        ".L_8039CBB4:\n"
        "addi	4,4,80\n"
        "addi	3,3,80\n"
        "lwz	0,-16(4)\n"
        "cmpwi	8,0\n"
        "addi	8,8,-1\n"
        "stw	0,-16(3)\n"
        "lwz	9,-12(4)\n"
        "lwz	11,-4(4)\n"
        "lwz	0,-8(4)\n"
        "stw	9,-12(3)\n"
        "stw	0,-8(3)\n"
        "stw	11,-4(3)\n"
        "lwz	9,0(4)\n"
        "lwz	10,4(4)\n"
        "stw	9,0(3)\n"
        "stw	10,4(3)\n"
        "lwz	11,8(4)\n"
        "lwz	12,12(4)\n"
        "stw	11,8(3)\n"
        "stw	12,12(3)\n"
        "lwz	9,16(4)\n"
        "lwz	10,20(4)\n"
        "stw	9,16(3)\n"
        "stw	10,20(3)\n"
        "lwz	11,24(4)\n"
        "lwz	12,28(4)\n"
        "stw	11,24(3)\n"
        "stw	12,28(3)\n"
        "lwz	9,32(4)\n"
        "lwz	10,36(4)\n"
        "stw	9,32(3)\n"
        "stw	10,36(3)\n"
        "lwz	11,40(4)\n"
        "lwz	12,44(4)\n"
        "stw	11,40(3)\n"
        "stw	12,44(3)\n"
        "lwz	9,48(4)\n"
        "lwz	10,52(4)\n"
        "stw	9,48(3)\n"
        "stw	10,52(3)\n"
        "lwz	11,56(4)\n"
        "lwz	12,60(4)\n"
        "stw	11,56(3)\n"
        "stw	12,60(3)\n"
        "bne	.L_8039CBB4\n"
        "blr\n"
    );
    __builtin_unreachable();
}

// 0x8039CC6C (300 bytes)
// TArray<ENDummyPoint, TArrayDefaultAllocator>::SetSize(int, int)
__attribute__((noreturn))
void TArray<ENDummyPoint, TArrayDefaultAllocator>::SetSize(int, int) {
    __asm__ __volatile__(
        "stwu	1,-32(1)\n"
        "mflr	0\n"
        "stmw	26,8(1)\n"
        "stw	0,36(1)\n"
        "mr	31,3\n"
        "mr	29,4\n"
        "mr.	27,5\n"
        "bne	.L_8039CC90\n"
        "mr	27,29\n"
        ".L_8039CC90:\n"
        "lwz	26,4(31)\n"
        "cmpw	29,26\n"
        "bge	.L_8039CCB0\n"
        "mulli	0,29,80\n"
        "lwz	3,0(31)\n"
        "subf	4,29,26\n"
        "add	3,3,0\n"
        ".long 0x4bfffea9  /* bl TArray<ENDummyPoint, TArrayDefaultAllocator>::Destruct(ENDummyPoint *, int) */\n"
        ".L_8039CCB0:\n"
        "cmpwi	27,0\n"
        "bne	.L_8039CCD4\n"
        "lwz	30,0(31)\n"
        ".long 0x4bf33245  /* bl MainHeap(void) */\n"
        "mr	4,30\n"
        ".long 0x4bf340b5  /* bl EAHeap::Free(void *) */\n"
        "mr	3,31\n"
        ".long 0x4bfffea5  /* bl TArray<ENDummyPoint, TArrayDefaultAllocator>::Init(void) */\n"
        "b	.L_8039CD68\n"
        ".L_8039CCD4:\n"
        "lwz	0,8(31)\n"
        "cmpw	0,27\n"
        "beq	.L_8039CD64\n"
        "mulli	30,27,80\n"
        ".long 0x4bf3321d  /* bl MainHeap(void) */\n"
        "li	5,16\n"
        "li	6,0\n"
        "li	7,0\n"
        "mr	4,30\n"
        ".long 0x4bf33e79  /* bl EAHeap::MallocAligned(unsigned int, unsigned int, unsigned int, int) */\n"
        "mr.	28,3\n"
        "beq	.L_8039CD68\n"
        "lwz	0,0(31)\n"
        "cmpwi	0,0\n"
        "beq	.L_8039CD5C\n"
        "lwz	0,4(31)\n"
        "mr	30,29\n"
        "cmpw	29,0\n"
        "ble	.L_8039CD24\n"
        "mr	30,0\n"
        ".L_8039CD24:\n"
        "mr	4,30\n"
        "mr	3,28\n"
        ".long 0x4bfffe59  /* bl TArray<ENDummyPoint, TArrayDefaultAllocator>::Construct(ENDummyPoint *, int) */\n"
        "lwz	4,0(31)\n"
        "mr	5,30\n"
        "mr	3,28\n"
        ".long 0x4bfffe65  /* bl TArray<ENDummyPoint, TArrayDefaultAllocator>::Copy(ENDummyPoint *, ENDummyPoint *, int) */\n"
        "lwz	4,4(31)\n"
        "lwz	3,0(31)\n"
        ".long 0x4bfffe0d  /* bl TArray<ENDummyPoint, TArrayDefaultAllocator>::Destruct(ENDummyPoint *, int) */\n"
        "lwz	30,0(31)\n"
        ".long 0x4bf331b1  /* bl MainHeap(void) */\n"
        "mr	4,30\n"
        ".long 0x4bf34021  /* bl EAHeap::Free(void *) */\n"
        ".L_8039CD5C:\n"
        "stw	28,0(31)\n"
        "stw	27,8(31)\n"
        ".L_8039CD64:\n"
        "stw	29,4(31)\n"
        ".L_8039CD68:\n"
        "cmpw	29,26\n"
        "ble	.L_8039CD84\n"
        "mulli	0,26,80\n"
        "lwz	3,0(31)\n"
        "subf	4,26,29\n"
        "add	3,3,0\n"
        ".long 0x4bfffe05  /* bl TArray<ENDummyPoint, TArrayDefaultAllocator>::Construct(ENDummyPoint *, int) */\n"
        ".L_8039CD84:\n"
        "lwz	0,36(1)\n"
        "mtlr	0\n"
        "lmw	26,8(1)\n"
        "addi	1,1,32\n"
        "blr\n"
    );
    __builtin_unreachable();
}

// 0x803C1D2C (76 bytes)
// TArray<ENDummyPoint, TArrayDefaultAllocator>::Deallocate(void)
__attribute__((noreturn))
void TArray<ENDummyPoint, TArrayDefaultAllocator>::Deallocate(void) {
    __asm__ __volatile__(
        "stwu	1,-24(1)\n"
        "mflr	0\n"
        "stmw	29,12(1)\n"
        "stw	0,28(1)\n"
        "mr	30,3\n"
        "lwz	4,4(30)\n"
        "lwz	3,0(30)\n"
        ".long 0x4bfdae0d  /* bl TArray<ENDummyPoint, TArrayDefaultAllocator>::Destruct(ENDummyPoint *, int) */\n"
        "lwz	29,0(30)\n"
        ".long 0x4bf0e1b1  /* bl MainHeap(void) */\n"
        "mr	4,29\n"
        ".long 0x4bf0f021  /* bl EAHeap::Free(void *) */\n"
        "mr	3,30\n"
        ".long 0x4bfdae11  /* bl TArray<ENDummyPoint, TArrayDefaultAllocator>::Init(void) */\n"
        "lwz	0,28(1)\n"
        "mtlr	0\n"
        "lmw	29,12(1)\n"
        "addi	1,1,24\n"
        "blr\n"
    );
    __builtin_unreachable();
}

// 0x803C4BC0 (76 bytes)
// TArray<ENDummyPoint, TArrayDefaultAllocator>::operator=(TArray<ENDummyPoint, TArrayDefaultAllocator> &)
__attribute__((noreturn))
void TArray<ENDummyPoint, TArrayDefaultAllocator>::operator=(TArray<ENDummyPoint, TArrayDefaultAllocator> &) {
    __asm__ __volatile__(
        "stwu	1,-24(1)\n"
        "mflr	0\n"
        "stmw	29,12(1)\n"
        "stw	0,28(1)\n"
        "mr	30,4\n"
        "mr	29,3\n"
        "lwz	4,4(30)\n"
        "li	5,0\n"
        ".long 0x4bfd808d  /* bl TArray<ENDummyPoint, TArrayDefaultAllocator>::SetSize(int, int) */\n"
        "lwz	3,0(29)\n"
        "lwz	5,4(30)\n"
        "lwz	4,0(30)\n"
        ".long 0x4bfd7fb1  /* bl TArray<ENDummyPoint, TArrayDefaultAllocator>::Copy(ENDummyPoint *, ENDummyPoint *, int) */\n"
        "mr	3,29\n"
        "lwz	0,28(1)\n"
        "mtlr	0\n"
        "lmw	29,12(1)\n"
        "addi	1,1,24\n"
        "blr\n"
    );
    __builtin_unreachable();
}

