#include "types.h"
// Inline asm leaf matches (XL 256-1023B) for EMat4
// 1 functions, 752 bytes

#include "types.h"
// Auto-generated inline asm decomp stubs for EMat4
// Generated by gen_asm_decomp.py
// 38 functions, 8324 bytes
//
// Each function has its original C++ signature with the body as inline PPC asm.
// These can be incrementally replaced with real C++ as decompilation progresses.

class EVec3;

class EMat4 {
public:
    void PreScale(EVec3 &);
    void PreTranslate(EVec3 &);
    void Normalize(void);
    void Transpose(EMat4 &);
    void Transpose(void);
    void Id(void);
    void Translate(EVec3 &);
    void Scale(EVec3 &);
    void RotateX(float);
    void RotateY(float);
    void RotateZ(float);
    void Invert(EMat4 &);
    void InvertSimple(EMat4 &);
    void Rotate(EVec3 &, float);
    void PreRotateX(float);
    void PostRotateX(float);
    void PreRotateY(float);
    void PostRotateY(float);
    void PreRotateZ(float);
    void PostRotateZ(float);
    void PostScale(EVec3 &);
    void Conform(EVec3 &);
    void OrientPosNormal(EVec3 &, EVec3 &, EVec3 &);
    void Clamp(void);
    void GetMaxScale(void) const;
    void GetHPR(float &, float &, float &);
    void GetLookAtPos(EVec3 &, EVec3 &, EVec3 &);
    void LookAtPos(EVec3 &, EVec3 &, EVec3 &);
    void LookAt(EVec3 &, EVec3 &, EVec3 &);
    void LookAtDirect(EVec3 &, EVec3 &, float);
    void LookTo(EVec3 &, EVec3 &, EVec3 &);
    void Projection(float, float, float, float);
    void Ortho(float, float, float, float, float, float);
    void BlendEuler(float, EMat4 &, EMat4 &);
    void BlendQuat(float, EMat4 &, EMat4 &);
    void TexturePerspectiveProjection(EVec3 &, EVec3 &, EVec3 &, float, float, float, float);
    void TexturePlanarProjection(EVec3 &, EVec3 &, EVec3 &, float, float, float, float);
    void operator=(EMat4 &);
};


// 0x802C99A0 (752 bytes)
// EMat4::Invert(EMat4 &)
__attribute__((noreturn))
void EMat4::Invert(EMat4 &) {
    __asm__ __volatile__(
        "lfs	6,36(4)\n"
        "lis	9,-32702\n"
        "lfs	13,0(4)\n"
        "mr	11,3\n"
        "lfs	4,20(4)\n"
        "lfs	7,24(4)\n"
        "fmuls	11,13,6\n"
        "lfs	10,16(4)\n"
        "fmuls	13,13,4\n"
        "lfs	9,4(4)\n"
        "fmuls	11,11,7\n"
        "lfs	5,40(4)\n"
        "fmuls	0,10,9\n"
        "lfs	12,32(4)\n"
        "lfs	8,8(4)\n"
        "fmsubs	13,13,5,11\n"
        "fmuls	0,0,5\n"
        "lfs	3,-7496(9)\n"
        "fmuls	9,12,9\n"
        "fsubs	13,13,0\n"
        "fmuls	10,10,6\n"
        "fmadds	10,10,8,13\n"
        "fmuls	12,12,4\n"
        "fmadds	9,9,7,10\n"
        "fmuls	12,12,8\n"
        "fsubs	9,9,12\n"
        "fcmpu	cr0,9,3\n"
        "beq	.L_802C9C88\n"
        "lis	9,-32702\n"
        "fmuls	0,6,7\n"
        "lfs	2,-7492(9)\n"
        "fmsubs	0,4,5,0\n"
        "li	3,1\n"
        "fdivs	6,2,9\n"
        "fmuls	0,0,6\n"
        "stfs	0,0(11)\n"
        "lfs	11,8(4)\n"
        "lfs	13,36(4)\n"
        "lfs	12,40(4)\n"
        "lfs	0,4(4)\n"
        "fmuls	13,13,11\n"
        "fnmsubs	0,0,12,13\n"
        "fmuls	0,0,6\n"
        "stfs	0,4(11)\n"
        "lfs	0,8(4)\n"
        "lfs	12,20(4)\n"
        "lfs	11,24(4)\n"
        "lfs	13,4(4)\n"
        "fmuls	12,12,0\n"
        "stfs	3,12(11)\n"
        "fmsubs	13,13,11,12\n"
        "fmuls	13,13,6\n"
        "stfs	13,8(11)\n"
        "lfs	11,24(4)\n"
        "lfs	0,16(4)\n"
        "lfs	13,32(4)\n"
        "lfs	12,40(4)\n"
        "fneg	0,0\n"
        "fmuls	13,13,11\n"
        "fmadds	0,0,12,13\n"
        "fmuls	0,0,6\n"
        "stfs	0,16(11)\n"
        "lfs	11,8(4)\n"
        "lfs	13,32(4)\n"
        "lfs	12,40(4)\n"
        "lfs	0,0(4)\n"
        "fmuls	13,13,11\n"
        "fmsubs	0,0,12,13\n"
        "fmuls	0,0,6\n"
        "stfs	0,20(11)\n"
        "lfs	0,8(4)\n"
        "lfs	12,16(4)\n"
        "lfs	11,24(4)\n"
        "lfs	13,0(4)\n"
        "fmuls	12,12,0\n"
        "stfs	3,28(11)\n"
        "fnmsubs	13,13,11,12\n"
        "fmuls	13,13,6\n"
        "stfs	13,24(11)\n"
        "lfs	11,20(4)\n"
        "lfs	0,16(4)\n"
        "lfs	13,32(4)\n"
        "lfs	12,36(4)\n"
        "fneg	0,0\n"
        "fmuls	13,13,11\n"
        "fnmadds	0,0,12,13\n"
        "fmuls	0,0,6\n"
        "stfs	0,32(11)\n"
        "lfs	11,4(4)\n"
        "lfs	13,0(4)\n"
        "lfs	0,32(4)\n"
        "lfs	12,36(4)\n"
        "fneg	13,13\n"
        "fmuls	0,0,11\n"
        "fmadds	13,13,12,0\n"
        "fmuls	13,13,6\n"
        "stfs	13,36(11)\n"
        "lfs	12,4(4)\n"
        "lfs	0,0(4)\n"
        "lfs	13,16(4)\n"
        "lfs	11,20(4)\n"
        "fneg	0,0\n"
        "fmuls	13,13,12\n"
        "stfs	3,44(11)\n"
        "fnmadds	0,0,11,13\n"
        "fmuls	0,0,6\n"
        "stfs	0,40(11)\n"
        "lfs	13,16(4)\n"
        "lfs	5,40(4)\n"
        "lfs	4,36(4)\n"
        "fneg	10,13\n"
        "lfs	7,52(4)\n"
        "fmuls	13,13,5\n"
        "lfs	9,56(4)\n"
        "fmuls	10,10,4\n"
        "lfs	12,32(4)\n"
        "fmuls	13,13,7\n"
        "lfs	11,20(4)\n"
        "fmadds	10,10,9,13\n"
        "lfs	8,24(4)\n"
        "lfs	13,48(4)\n"
        "fmuls	0,12,11\n"
        "fmuls	12,12,8\n"
        "fmadds	0,0,9,10\n"
        "fmuls	12,12,7\n"
        "fmuls	11,13,11\n"
        "fmuls	11,11,5\n"
        "fsubs	0,0,12\n"
        "fsubs	0,0,11\n"
        "fmuls	13,13,4\n"
        "fmadds	13,13,8,0\n"
        "fmuls	13,13,6\n"
        "stfs	13,48(11)\n"
        "lfs	3,40(4)\n"
        "lfs	12,0(4)\n"
        "lfs	4,52(4)\n"
        "lfs	5,4(4)\n"
        "fmuls	11,12,3\n"
        "lfs	9,36(4)\n"
        "fmuls	11,11,4\n"
        "lfs	10,32(4)\n"
        "lfs	8,56(4)\n"
        "fmuls	12,12,9\n"
        "lfs	7,8(4)\n"
        "fmuls	13,10,5\n"
        "lfs	0,48(4)\n"
        "fmsubs	12,12,8,11\n"
        "fmuls	13,13,8\n"
        "fsubs	12,12,13\n"
        "fmuls	10,10,7\n"
        "fmuls	9,0,9\n"
        "fmadds	10,10,4,12\n"
        "fmuls	0,0,5\n"
        "fmadds	0,0,3,10\n"
        "fmuls	9,9,7\n"
        "fsubs	0,0,9\n"
        "fmuls	0,0,6\n"
        "stfs	0,52(11)\n"
        "lfs	12,0(4)\n"
        "lfs	3,24(4)\n"
        "lfs	9,20(4)\n"
        "lfs	4,52(4)\n"
        "fmuls	11,12,3\n"
        "lfs	10,16(4)\n"
        "fmuls	12,12,9\n"
        "lfs	5,4(4)\n"
        "fmuls	11,11,4\n"
        "lfs	8,56(4)\n"
        "lfs	7,8(4)\n"
        "fmuls	13,10,5\n"
        "lfs	0,48(4)\n"
        "fmsubs	12,12,8,11\n"
        "fmuls	13,13,8\n"
        "fmuls	9,0,9\n"
        "fsubs	12,12,13\n"
        "fmuls	10,10,7\n"
        "fmadds	10,10,4,12\n"
        "fmuls	0,0,5\n"
        "fmadds	0,0,3,10\n"
        "fmuls	9,9,7\n"
        "fsubs	0,0,9\n"
        "fneg	0,0\n"
        "fmuls	0,0,6\n"
        "stfs	0,56(11)\n"
        "stfs	2,60(11)\n"
        "blr\n"
        ".L_802C9C88:\n"
        "li	3,0\n"
        "blr\n"
    );
}

