#include "types.h"
#include "stub_classes.h"
// Auto-generated raw-byte matches for SimpleReconObject_L_CasGenetics_R
// Generated by gen_raw_byte_matches.py
// 3 functions, 76 bytes
// These functions are matched by directly injecting DOL bytes into the skeleton.
// The C++ stubs below exist only as annotations for the matching pipeline.

// 0x803B0A74 (32 bytes)
// SimpleReconObject_L_CasGenetics_R__dtor_SimpleReconObject_void
// [raw byte match - injected directly from DOL]

// 0x803B0A94 (36 bytes)
// SimpleReconObject_L_CasGenetics_R__DoStream_ReconBuffer_ptr__int
// [raw byte match - injected directly from DOL]

// 0x803B0AB8 (8 bytes)
// SimpleReconObject_L_CasGenetics_R__GetType_void
// [raw byte match - injected directly from DOL]

