#include "types.h"
#include "stub_classes.h"
// Auto-generated matching constructors for CareersImpl
// Generated by gen_ctor_matches.py (inline asm)
// 1 functions, 20 bytes

// 0x800B1B68 (20 bytes)
__attribute__((noreturn))
CareersImpl::CareersImpl() {
    __asm__ __volatile__(
        "lis	9,-32698\n""mr	11,3\n""addi	9,9,-5832\n""stw	9,0(11)\n""blr\n"
    );
    __builtin_unreachable();
}
