#include "types.h"
// Auto-generated inline asm decomp stubs for AptSavedInputCheckpoints
// Generated by gen_asm_decomp.py
// 1 functions, 212 bytes
//
// Each function has its original C++ signature with the body as inline PPC asm.
// These can be incrementally replaced with real C++ as decompilation progresses.

class AptSavedInputCheckpoints {
public:
    ~AptSavedInputCheckpoints(void);
};

// 0x8026C094 (212 bytes)
// AptSavedInputCheckpoints::~AptSavedInputCheckpoints(void)
__attribute__((noreturn))
AptSavedInputCheckpoints::~AptSavedInputCheckpoints(void) {
    __asm__ __volatile__(
        "stwu	1,-32(1)\n"
        "mflr	0\n"
        "stmw	27,12(1)\n"
        "stw	0,36(1)\n"
        "mr	29,3\n"
        "mr	27,4\n"
        "lwz	30,8(29)\n"
        "addi	0,29,12\n"
        "cmpw	30,0\n"
        "beq	.L_8026C10C\n"
        "cmpwi	30,0\n"
        "bne	.L_8026C0D4\n"
        "li	3,8\n"
        ".long 0x48065121  /* bl __builtin_vec_new */\n"
        "stw	30,0(3)\n"
        "b	.L_8026C10C\n"
        ".L_8026C0D4:\n"
        "lwz	0,-8(30)\n"
        "addi	28,30,-8\n"
        "slwi	0,0,3\n"
        "add	31,30,0\n"
        "cmpw	30,31\n"
        "beq	.L_8026C104\n"
        ".L_8026C0EC:\n"
        "addi	31,31,-8\n"
        "li	4,2\n"
        "mr	3,31\n"
        ".long 0x48000631  /* bl EAStringC::~EAStringC(void) */\n"
        "cmpw	30,31\n"
        "bne	.L_8026C0EC\n"
        ".L_8026C104:\n"
        "mr	3,28\n"
        ".long 0x4806514d  /* bl __builtin_vec_delete */\n"
        ".L_8026C10C:\n"
        "addic.	0,29,12\n"
        "mr	30,0\n"
        "beq	.L_8026C13C\n"
        "addi	31,29,28\n"
        "cmpw	30,31\n"
        "beq	.L_8026C13C\n"
        ".L_8026C124:\n"
        "addi	31,31,-8\n"
        "li	4,2\n"
        "mr	3,31\n"
        ".long 0x480005f9  /* bl EAStringC::~EAStringC(void) */\n"
        "cmpw	30,31\n"
        "bne	.L_8026C124\n"
        ".L_8026C13C:\n"
        "andi.	0,27,1\n"
        "beq	.L_8026C154\n"
        "lwz	3,-23020(13)\n"
        "mr	4,29\n"
        "li	5,28\n"
        ".long 0x4804983d  /* bl DOGMA_PoolManager::Deallocate(void *, unsigned int) */\n"
        ".L_8026C154:\n"
        "lwz	0,36(1)\n"
        "mtlr	0\n"
        "lmw	27,12(1)\n"
        "addi	1,1,32\n"
        "blr\n"
    );
    __builtin_unreachable();
}

