#include "types.h"
// Auto-generated inline asm decomp stubs for ObjResFile
// Generated by gen_asm_decomp.py
// 3 functions, 276 bytes
//
// Each function has its original C++ signature with the body as inline PPC asm.
// These can be incrementally replaced with real C++ as decompilation progresses.

class StringBuffer;

class ObjResFile {
public:
    ObjResFile(void);
    ~ObjResFile(void);
    void Open(StringBuffer &);
};

// 0x80110368 (88 bytes)
// ObjResFile::ObjResFile(void)
__attribute__((noreturn))
ObjResFile::ObjResFile(void) {
    __asm__ __volatile__(
        "stwu	1,-16(1)\n"
        "mflr	0\n"
        "stmw	30,8(1)\n"
        "stw	0,20(1)\n"
        "mr	30,3\n"
        ".long 0x480355d9  /* bl StdResFile::StdResFile(void) */\n"
        "lis	9,-32698\n"
        "mr	3,30\n"
        "addi	9,9,8536\n"
        "stw	9,12(30)\n"
        ".long 0x4802d679  /* bl SeqResFile::ClearOpenSpecs(void) */\n"
        "lis	5,-32706\n"
        "mr	3,30\n"
        "addi	5,5,-15692\n"
        "li	4,2\n"
        ".long 0x4802d671  /* bl SeqResFile::AddOpenSpec(int, char *) */\n"
        "mr	3,30\n"
        "lwz	0,20(1)\n"
        "mtlr	0\n"
        "lmw	30,8(1)\n"
        "addi	1,1,16\n"
        "blr\n"
    );
    __builtin_unreachable();
}

// 0x801103C0 (100 bytes)
// ObjResFile::~ObjResFile(void)
__attribute__((noreturn))
ObjResFile::~ObjResFile(void) {
    __asm__ __volatile__(
        "stwu	1,-24(1)\n"
        "mflr	0\n"
        "stmw	29,12(1)\n"
        "stw	0,28(1)\n"
        "lis	9,-32698\n"
        "mr	30,3\n"
        "lwz	11,-21508(13)\n"
        "addi	9,9,8536\n"
        "stw	9,12(30)\n"
        "mr	29,4\n"
        "mr	4,30\n"
        "lwz	9,0(11)\n"
        "lha	3,272(9)\n"
        "lwz	0,276(9)\n"
        "add	3,11,3\n"
        "mtlr	0\n"
        "blrl\n"
        "mr	3,30\n"
        "mr	4,29\n"
        ".long 0x4802d6c5  /* bl SeqResFile::~SeqResFile(void) */\n"
        "lwz	0,28(1)\n"
        "mtlr	0\n"
        "lmw	29,12(1)\n"
        "addi	1,1,24\n"
        "blr\n"
    );
    __builtin_unreachable();
}

// 0x80110424 (88 bytes)
// ObjResFile::Open(StringBuffer &)
__attribute__((noreturn))
void ObjResFile::Open(StringBuffer &) {
    __asm__ __volatile__(
        "stwu	1,-16(1)\n"
        "mflr	0\n"
        "stmw	30,8(1)\n"
        "stw	0,20(1)\n"
        "mr	31,3\n"
        ".long 0x480355e1  /* bl StdResFile::Open(StringBuffer &) */\n"
        "mr.	30,3\n"
        "bne	.L_80110464\n"
        "lwz	3,-21508(13)\n"
        "mr	4,31\n"
        "lwz	9,0(3)\n"
        "lha	0,264(9)\n"
        "lwz	9,268(9)\n"
        "add	3,3,0\n"
        "mtlr	9\n"
        "blrl\n"
        ".L_80110464:\n"
        "mr	3,30\n"
        "lwz	0,20(1)\n"
        "mtlr	0\n"
        "lmw	30,8(1)\n"
        "addi	1,1,16\n"
        "blr\n"
    );
    __builtin_unreachable();
}

