#include "types.h"
// Auto-generated inline asm decomp stubs for cSoundPlayer
// Generated by gen_asm_decomp.py
// 27 functions, 3728 bytes
//
// Each function has its original C++ signature with the body as inline PPC asm.
// These can be incrementally replaced with real C++ as decompilation progresses.

class ERSoundEvent;

class cSoundPlayer {
public:
    cSoundPlayer(void);
    ~cSoundPlayer(void);
    void Initialize(void);
    void Shutdown(void);
    void KillSourceEvent(int);
    void KillAllEvent(void);
    void Update(void);
    void SetGameMode(int);
    void EnableSound(bool);
    void QuietAll(void);
    void PlayBySource(unsigned int, short);
    void PlayBySource(char *, short);
    void PlayBySource(ERSoundEvent *, short);
    void QuietBySourceID(int);
    void PauseSFX(void);
    void ResumeSFX(void);
    void PauseMusic(void);
    void ResumeMusic(void);
    void PauseSounds(void);
    void ResumeSounds(void);
    void NotifyViewChange(void);
    void NotifyHourChange(void);
    void SetOldFXVolume(int);
    void SetMusicVolume(int);
    void SetSFXVolume(int);
    void SetVOXVolume(int);
    void SetAmbientVolume(int);
};

// 0x800B7264 (104 bytes)
// cSoundPlayer::cSoundPlayer(void)
__attribute__((noreturn))
cSoundPlayer::cSoundPlayer(void) {
    __asm__ __volatile__(
        "stwu	1,-48(1)\n"
        "mflr	0\n"
        "stmw	28,32(1)\n"
        "stw	0,52(1)\n"
        "mr	30,3\n"
        "li	29,0\n"
        "addi	28,30,24\n"
        "li	3,20\n"
        "stw	29,4(28)\n"
        ".long 0x482e507d  /* bl __node_alloc<false, 0>::_M_allocate(unsigned int) */\n"
        "mr	9,3\n"
        "stw	9,0(9)\n"
        "mr	3,30\n"
        "stw	9,4(9)\n"
        "stw	9,4(28)\n"
        "stw	29,16(30)\n"
        "stw	29,0(30)\n"
        "stw	29,4(30)\n"
        "stw	29,8(30)\n"
        "stw	29,12(30)\n"
        "stw	29,24(1)\n"
        "lwz	0,52(1)\n"
        "mtlr	0\n"
        "lmw	28,32(1)\n"
        "addi	1,1,48\n"
        "blr\n"
    );
    __builtin_unreachable();
}

// 0x800B72CC (156 bytes)
// cSoundPlayer::~cSoundPlayer(void)
__attribute__((noreturn))
cSoundPlayer::~cSoundPlayer(void) {
    __asm__ __volatile__(
        "stwu	1,-24(1)\n"
        "mflr	0\n"
        "stmw	29,12(1)\n"
        "stw	0,28(1)\n"
        "mr	31,3\n"
        "mr	29,4\n"
        "lwz	0,8(31)\n"
        "cmpwi	0,0\n"
        "beq	.L_800B7324\n"
        "lwz	11,4(31)\n"
        "cmpwi	11,0\n"
        "beq	.L_800B7318\n"
        "lwz	9,0(11)\n"
        "li	4,3\n"
        "lha	3,8(9)\n"
        "lwz	0,12(9)\n"
        "add	3,11,3\n"
        "mtlr	0\n"
        "blrl\n"
        ".L_800B7318:\n"
        "li	0,0\n"
        "stw	0,-24464(13)\n"
        "stw	0,4(31)\n"
        ".L_800B7324:\n"
        "addi	30,31,24\n"
        "mr	3,30\n"
        ".long 0x482ec379  /* bl _List_base<SoundEventInfo, allocator<SoundEventInfo> >::clear(void) */\n"
        "lwz	3,4(30)\n"
        "cmpwi	3,0\n"
        "beq	.L_800B7344\n"
        "li	4,20\n"
        ".long 0x482e4b21  /* bl __node_alloc<false, 0>::_M_deallocate(void *, unsigned int) */\n"
        ".L_800B7344:\n"
        "andi.	0,29,1\n"
        "beq	.L_800B7354\n"
        "mr	3,31\n"
        ".long 0x48219ed1  /* bl __builtin_delete */\n"
        ".L_800B7354:\n"
        "lwz	0,28(1)\n"
        "mtlr	0\n"
        "lmw	29,12(1)\n"
        "addi	1,1,24\n"
        "blr\n"
    );
    __builtin_unreachable();
}

// 0x800B7368 (216 bytes)
// cSoundPlayer::Initialize(void)
__attribute__((noreturn))
void cSoundPlayer::Initialize(void) {
    __asm__ __volatile__(
        "stwu	1,-16(1)\n"
        "mflr	0\n"
        "stmw	30,8(1)\n"
        "stw	0,20(1)\n"
        "mr	31,3\n"
        "lwz	0,0(31)\n"
        "cmpwi	0,0\n"
        "bne	.L_800B742C\n"
        "lwz	9,-21436(13)\n"
        "lwz	0,716(9)\n"
        "cmpwi	0,0\n"
        "bne	.L_800B73B8\n"
        "lwz	3,-26564(13)\n"
        "lwz	9,0(3)\n"
        "lha	0,72(9)\n"
        "lwz	9,76(9)\n"
        "add	3,3,0\n"
        "mtlr	9\n"
        "blrl\n"
        "b	.L_800B7418\n"
        ".L_800B73B8:\n"
        ".long 0x480018d1  /* bl cIGZSndSys::CreateInstance(void) */\n"
        "stw	3,-24464(13)\n"
        "stw	3,4(31)\n"
        "lwz	9,0(3)\n"
        "lha	0,16(9)\n"
        "lwz	9,20(9)\n"
        "add	3,3,0\n"
        "mtlr	9\n"
        "blrl\n"
        "lwz	0,0(31)\n"
        "cmpwi	0,0\n"
        "bne	.L_800B7418\n"
        "lwz	0,4(31)\n"
        "cmpwi	0,0\n"
        "beq	.L_800B7418\n"
        "li	30,1\n"
        "li	3,124\n"
        "stw	30,8(31)\n"
        ".long 0x48219db1  /* bl __builtin_new */\n"
        ".long 0x4bff626d  /* bl cBoxX::cBoxX(void) */\n"
        "mr	0,3\n"
        "stw	0,-24508(13)\n"
        ".long 0x4bff63c9  /* bl cBoxX::Init(void) */\n"
        "stw	30,0(31)\n"
        ".L_800B7418:\n"
        "lis	3,-32692\n"
        "lis	4,-32757\n"
        "addi	3,3,9472\n"
        "addi	4,4,29196\n"
        ".long 0x482756ed  /* bl ENgcAudio::SetDiscErrorCallback(void (*)(bool)) */\n"
        ".L_800B742C:\n"
        "lwz	0,20(1)\n"
        "mtlr	0\n"
        "lmw	30,8(1)\n"
        "addi	1,1,16\n"
        "blr\n"
    );
    __builtin_unreachable();
}

// 0x800B7440 (132 bytes)
// cSoundPlayer::Shutdown(void)
__attribute__((noreturn))
void cSoundPlayer::Shutdown(void) {
    __asm__ __volatile__(
        "stwu	1,-16(1)\n"
        "mflr	0\n"
        "stw	31,12(1)\n"
        "stw	0,20(1)\n"
        "lwz	0,8(3)\n"
        "cmpwi	0,0\n"
        "beq	.L_800B74B0\n"
        "lwz	0,0(3)\n"
        "cmpwi	0,0\n"
        "beq	.L_800B74B0\n"
        "lwz	0,-24508(13)\n"
        "li	31,0\n"
        "stw	31,0(3)\n"
        "cmpwi	0,0\n"
        "beq	.L_800B74B0\n"
        "mr	3,0\n"
        ".long 0x4bff641d  /* bl cBoxX::Shutdown(void) */\n"
        "lwz	11,-24508(13)\n"
        "cmpwi	11,0\n"
        "beq	.L_800B74AC\n"
        "lwz	9,120(11)\n"
        "li	4,3\n"
        "lha	3,8(9)\n"
        "lwz	0,12(9)\n"
        "add	3,11,3\n"
        "mtlr	0\n"
        "blrl\n"
        ".L_800B74AC:\n"
        "stw	31,-24508(13)\n"
        ".L_800B74B0:\n"
        "lwz	0,20(1)\n"
        "mtlr	0\n"
        "lwz	31,12(1)\n"
        "addi	1,1,16\n"
        "blr\n"
    );
    __builtin_unreachable();
}

// 0x800B74C4 (248 bytes)
// cSoundPlayer::KillSourceEvent(int)
__attribute__((noreturn))
void cSoundPlayer::KillSourceEvent(int) {
    __asm__ __volatile__(
        "stwu	1,-64(1)\n"
        "mflr	0\n"
        "stmw	27,44(1)\n"
        "stw	0,68(1)\n"
        "mr	30,3\n"
        "mr	28,4\n"
        "addi	9,30,24\n"
        "lis	27,-32692\n"
        "lwz	11,4(9)\n"
        "mr	29,9\n"
        "lwz	0,0(11)\n"
        "stw	0,8(1)\n"
        "stw	0,16(1)\n"
        "b	.L_800B7578\n"
        ".L_800B74FC:\n"
        "lwz	0,4(29)\n"
        "li	9,1\n"
        "cmpw	11,0\n"
        "stw	0,24(1)\n"
        "bne	.L_800B7514\n"
        "li	9,0\n"
        ".L_800B7514:\n"
        "cmpwi	9,0\n"
        "beq	.L_800B759C\n"
        "lwz	9,16(1)\n"
        "addi	10,11,8\n"
        "lwz	0,0(9)\n"
        "stw	0,16(1)\n"
        "lwz	9,8(11)\n"
        "cmpw	9,28\n"
        "bne	.L_800B7570\n"
        "lwz	4,4(10)\n"
        "addi	3,27,-14084\n"
        ".long 0x4826fbcd  /* bl EResourceManager::DelRefAsync(unsigned int) */\n"
        "lwz	3,8(1)\n"
        "stw	3,32(1)\n"
        "cmpwi	3,0\n"
        "lwz	31,0(3)\n"
        "lwz	9,4(3)\n"
        "stw	31,0(9)\n"
        "stw	9,4(31)\n"
        "beq	.L_800B756C\n"
        "li	4,20\n"
        ".long 0x482e48f9  /* bl __node_alloc<false, 0>::_M_deallocate(void *, unsigned int) */\n"
        ".L_800B756C:\n"
        "stw	31,24(1)\n"
        ".L_800B7570:\n"
        "lwz	0,16(1)\n"
        "stw	0,8(1)\n"
        ".L_800B7578:\n"
        "lwz	11,8(1)\n"
        "li	9,1\n"
        "lwz	0,16(30)\n"
        "cmpw	11,0\n"
        "bne	.L_800B7590\n"
        "li	9,0\n"
        ".L_800B7590:\n"
        "cmpwi	9,0\n"
        "addi	10,30,24\n"
        "bne	.L_800B74FC\n"
        ".L_800B759C:\n"
        "lwz	0,4(10)\n"
        "stw	0,16(30)\n"
        "stw	0,24(1)\n"
        "lwz	0,68(1)\n"
        "mtlr	0\n"
        "lmw	27,44(1)\n"
        "addi	1,1,64\n"
        "blr\n"
    );
    __builtin_unreachable();
}

// 0x800B75BC (236 bytes)
// cSoundPlayer::KillAllEvent(void)
__attribute__((noreturn))
void cSoundPlayer::KillAllEvent(void) {
    __asm__ __volatile__(
        "stwu	1,-56(1)\n"
        "mflr	0\n"
        "stmw	28,40(1)\n"
        "stw	0,60(1)\n"
        "mr	30,3\n"
        "li	0,1\n"
        "stw	0,20(30)\n"
        "addi	11,30,24\n"
        "mr	29,11\n"
        "lis	28,-32692\n"
        "lwz	9,4(11)\n"
        "lwz	0,0(9)\n"
        "stw	0,8(1)\n"
        "stw	0,16(1)\n"
        "b	.L_800B7664\n"
        ".L_800B75F8:\n"
        "lwz	0,4(29)\n"
        "li	9,1\n"
        "cmpw	11,0\n"
        "stw	0,24(1)\n"
        "bne	.L_800B7610\n"
        "li	9,0\n"
        ".L_800B7610:\n"
        "cmpwi	9,0\n"
        "beq	.L_800B7688\n"
        "lwz	9,16(1)\n"
        "addi	3,28,-14084\n"
        "lwz	0,0(9)\n"
        "stw	0,16(1)\n"
        "lwz	4,12(11)\n"
        ".long 0x4826fae1  /* bl EResourceManager::DelRefAsync(unsigned int) */\n"
        "lwz	3,8(1)\n"
        "stw	3,32(1)\n"
        "cmpwi	3,0\n"
        "lwz	31,0(3)\n"
        "lwz	9,4(3)\n"
        "stw	31,0(9)\n"
        "stw	9,4(31)\n"
        "beq	.L_800B7658\n"
        "li	4,20\n"
        ".long 0x482e480d  /* bl __node_alloc<false, 0>::_M_deallocate(void *, unsigned int) */\n"
        ".L_800B7658:\n"
        "lwz	0,16(1)\n"
        "stw	31,24(1)\n"
        "stw	0,8(1)\n"
        ".L_800B7664:\n"
        "lwz	11,8(1)\n"
        "li	9,1\n"
        "lwz	0,16(30)\n"
        "cmpw	11,0\n"
        "bne	.L_800B767C\n"
        "li	9,0\n"
        ".L_800B767C:\n"
        "cmpwi	9,0\n"
        "addi	10,30,24\n"
        "bne	.L_800B75F8\n"
        ".L_800B7688:\n"
        "lwz	0,4(10)\n"
        "stw	0,16(30)\n"
        "stw	0,24(1)\n"
        "lwz	0,60(1)\n"
        "mtlr	0\n"
        "lmw	28,40(1)\n"
        "addi	1,1,56\n"
        "blr\n"
    );
    __builtin_unreachable();
}

// 0x800B76A8 (364 bytes)
// cSoundPlayer::Update(void)
__attribute__((noreturn))
void cSoundPlayer::Update(void) {
    __asm__ __volatile__(
        "stwu	1,-80(1)\n"
        "mflr	0\n"
        "stfd	30,64(1)\n"
        "stfd	31,72(1)\n"
        "stmw	26,40(1)\n"
        "stw	0,84(1)\n"
        "lis	9,-32706\n"
        "mr	28,3\n"
        "addi	11,28,24\n"
        "lfs	30,-25904(9)\n"
        "lwz	9,4(11)\n"
        "mr	27,11\n"
        "lis	26,-32692\n"
        "lwz	0,0(9)\n"
        "stw	0,8(1)\n"
        "stw	0,16(1)\n"
        "b	.L_800B776C\n"
        ".L_800B76EC:\n"
        "lwz	9,16(1)\n"
        "addi	3,26,-14084\n"
        "lwz	0,0(9)\n"
        "stw	0,16(1)\n"
        "lwz	4,12(11)\n"
        ".long 0x4826f01d  /* bl EResourceManager::GetRef(unsigned int) */\n"
        "mr.	29,3\n"
        "beq	.L_800B7764\n"
        "lwz	0,16(1)\n"
        "lwz	3,8(1)\n"
        "stw	0,16(28)\n"
        "cmpwi	3,0\n"
        "lfs	31,16(3)\n"
        "lwz	30,8(3)\n"
        "stw	3,32(1)\n"
        "lwz	31,0(3)\n"
        "lwz	9,4(3)\n"
        "stw	31,0(9)\n"
        "stw	9,4(31)\n"
        "beq	.L_800B7744\n"
        "li	4,20\n"
        ".long 0x482e4721  /* bl __node_alloc<false, 0>::_M_deallocate(void *, unsigned int) */\n"
        ".L_800B7744:\n"
        "lwz	3,-24508(13)\n"
        "mr	5,30\n"
        "stw	31,24(1)\n"
        "fadds	1,31,30\n"
        "mr	4,29\n"
        ".long 0x4bff7385  /* bl cBoxX::MappedEvent(ERSoundEvent *, int, float) */\n"
        "mr	3,29\n"
        ".long 0x4825a811  /* bl EResource::DelRef(void) */\n"
        ".L_800B7764:\n"
        "lwz	0,16(1)\n"
        "stw	0,8(1)\n"
        ".L_800B776C:\n"
        "lwz	0,4(27)\n"
        "li	9,1\n"
        "lwz	11,8(1)\n"
        "stw	0,24(1)\n"
        "cmpw	11,0\n"
        "bne	.L_800B7788\n"
        "li	9,0\n"
        ".L_800B7788:\n"
        "cmpwi	9,0\n"
        "bne	.L_800B76EC\n"
        "lwz	0,0(28)\n"
        "cmpwi	0,0\n"
        "beq	.L_800B77F8\n"
        "lwz	0,8(28)\n"
        "cmpwi	0,0\n"
        "beq	.L_800B77F8\n"
        "lwz	3,-24508(13)\n"
        ".long 0x4bff636d  /* bl cBoxX::UpdateGameMode(void) */\n"
        "lwz	0,12(28)\n"
        "cmpwi	0,0\n"
        "bne	.L_800B77F8\n"
        "lwz	11,-24508(13)\n"
        "li	4,0\n"
        "lwz	9,120(11)\n"
        "lwz	0,20(9)\n"
        "lha	3,16(9)\n"
        "mtlr	0\n"
        "add	3,11,3\n"
        "blrl\n"
        "lwz	11,4(28)\n"
        "lwz	9,0(11)\n"
        "lha	3,24(9)\n"
        "lwz	0,28(9)\n"
        "add	3,11,3\n"
        "mtlr	0\n"
        "blrl\n"
        ".L_800B77F8:\n"
        "lwz	0,84(1)\n"
        "mtlr	0\n"
        "lmw	26,40(1)\n"
        "lfd	30,64(1)\n"
        "lfd	31,72(1)\n"
        "addi	1,1,80\n"
        "blr\n"
    );
    __builtin_unreachable();
}

// 0x800B7814 (132 bytes)
// cSoundPlayer::SetGameMode(snd::eMode)
__attribute__((noreturn))
void cSoundPlayer::SetGameMode(int) {
    __asm__ __volatile__(
        "stwu	1,-8(1)\n"
        "mflr	0\n"
        "stw	0,12(1)\n"
        "lwz	0,8(3)\n"
        "cmpwi	0,0\n"
        "beq	.L_800B7888\n"
        "lwz	0,0(3)\n"
        "cmpwi	0,0\n"
        "beq	.L_800B7888\n"
        "lwz	3,-24508(13)\n"
        "cmpwi	3,0\n"
        "beq	.L_800B7888\n"
        "lwz	9,-26824(13)\n"
        "lwz	0,1104(9)\n"
        "cmpwi	0,0\n"
        "bne	.L_800B7888\n"
        "cmpwi	4,5\n"
        "bne	.L_800B786C\n"
        "addi	3,3,48\n"
        "li	4,5\n"
        ".long 0x4bff8c35  /* bl cSoundModeManager::SetMode(int) */\n"
        "b	.L_800B7888\n"
        ".L_800B786C:\n"
        "lis	9,-32706\n"
        "mr	5,4\n"
        "lfs	1,-25900(9)\n"
        "li	4,36\n"
        "li	6,0\n"
        "li	7,0\n"
        ".long 0x4bff7289  /* bl cBoxX::Event(int, int, int, ERSoundEvent *, float) */\n"
        ".L_800B7888:\n"
        "lwz	0,12(1)\n"
        "mtlr	0\n"
        "addi	1,1,8\n"
        "blr\n"
    );
    __builtin_unreachable();
}

// 0x800B78B0 (84 bytes)
// cSoundPlayer::EnableSound(bool)
__attribute__((noreturn))
void cSoundPlayer::EnableSound(bool) {
    __asm__ __volatile__(
        "stwu	1,-8(1)\n"
        "mflr	0\n"
        "stw	0,12(1)\n"
        "lwz	0,0(3)\n"
        "cmpwi	0,0\n"
        "beq	.L_800B78F4\n"
        "lwz	0,8(3)\n"
        "cmpwi	0,0\n"
        "beq	.L_800B78F4\n"
        "lis	9,-32706\n"
        "mr	5,4\n"
        "lwz	3,-24508(13)\n"
        "li	4,34\n"
        "lfs	1,-25896(9)\n"
        "li	6,0\n"
        "li	7,0\n"
        ".long 0x4bff721d  /* bl cBoxX::Event(int, int, int, ERSoundEvent *, float) */\n"
        ".L_800B78F4:\n"
        "lwz	0,12(1)\n"
        "mtlr	0\n"
        "addi	1,1,8\n"
        "blr\n"
    );
    __builtin_unreachable();
}

// 0x800B7904 (100 bytes)
// cSoundPlayer::QuietAll(void)
__attribute__((noreturn))
void cSoundPlayer::QuietAll(void) {
    __asm__ __volatile__(
        "stwu	1,-16(1)\n"
        "mflr	0\n"
        "stw	0,20(1)\n"
        "mr	11,3\n"
        "lwz	0,0(11)\n"
        "cmpwi	0,0\n"
        "beq	.L_800B7958\n"
        "lwz	0,8(11)\n"
        "cmpwi	0,0\n"
        "beq	.L_800B7958\n"
        "lwz	0,28(11)\n"
        "lis	9,-32706\n"
        "lwz	3,-24508(13)\n"
        "li	4,20\n"
        "stw	0,16(11)\n"
        "li	5,0\n"
        "lfs	1,-25892(9)\n"
        "li	6,0\n"
        "stw	0,8(1)\n"
        "li	7,0\n"
        ".long 0x4bff71b9  /* bl cBoxX::Event(int, int, int, ERSoundEvent *, float) */\n"
        ".L_800B7958:\n"
        "lwz	0,20(1)\n"
        "mtlr	0\n"
        "addi	1,1,16\n"
        "blr\n"
    );
    __builtin_unreachable();
}

// 0x800B7968 (248 bytes)
// cSoundPlayer::PlayBySource(unsigned int, short)
__attribute__((noreturn))
void cSoundPlayer::PlayBySource(unsigned int, short) {
    __asm__ __volatile__(
        "stwu	1,-56(1)\n"
        "mflr	0\n"
        "stmw	28,40(1)\n"
        "stw	0,60(1)\n"
        "mr	29,3\n"
        "mr	31,4\n"
        "lwz	0,0(29)\n"
        "mr	28,5\n"
        "cmpwi	0,0\n"
        "beq	.L_800B7A4C\n"
        "lwz	0,8(29)\n"
        "cmpwi	0,0\n"
        "beq	.L_800B7A4C\n"
        "cmpwi	31,0\n"
        "beq	.L_800B7A4C\n"
        "cmpwi	28,-2\n"
        "beq	.L_800B7A4C\n"
        "lis	3,-32692\n"
        "addi	30,1,8\n"
        "addi	3,3,-14084\n"
        ".long 0x4826f3fd  /* bl EResourceManager::AddRefAsync(unsigned int) */\n"
        "lis	9,-32706\n"
        "li	0,0\n"
        "lfs	0,-25888(9)\n"
        "lis	4,-32693\n"
        "stw	0,8(1)\n"
        "addi	4,4,-11760\n"
        "stfs	0,8(30)\n"
        "stw	0,4(30)\n"
        "stw	31,12(1)\n"
        "stw	28,8(1)\n"
        "lwz	11,-26532(13)\n"
        "lwz	9,0(11)\n"
        "lwz	0,44(9)\n"
        "lha	3,40(9)\n"
        "mtlr	0\n"
        "add	3,11,3\n"
        "blrl\n"
        "lwz	0,28(29)\n"
        "li	3,20\n"
        "stfs	1,16(1)\n"
        "stw	0,32(1)\n"
        ".long 0x482e48f5  /* bl __node_alloc<false, 0>::_M_allocate(unsigned int) */\n"
        "lwz	10,8(1)\n"
        "addi	11,3,8\n"
        "lwz	9,8(30)\n"
        "lwz	0,4(30)\n"
        "stw	10,8(3)\n"
        "stw	9,8(11)\n"
        "stw	0,4(11)\n"
        "lwz	9,32(1)\n"
        "lwz	11,4(9)\n"
        "stw	9,0(3)\n"
        "stw	11,4(3)\n"
        "stw	3,0(11)\n"
        "stw	3,4(9)\n"
        "stw	3,24(1)\n"
        ".L_800B7A4C:\n"
        "lwz	0,60(1)\n"
        "mtlr	0\n"
        "lmw	28,40(1)\n"
        "addi	1,1,56\n"
        "blr\n"
    );
    __builtin_unreachable();
}

// 0x800B7A60 (108 bytes)
// cSoundPlayer::PlayBySource(char *, short)
__attribute__((noreturn))
void cSoundPlayer::PlayBySource(char *, short) {
    __asm__ __volatile__(
        "stwu	1,-16(1)\n"
        "mflr	0\n"
        "stmw	30,8(1)\n"
        "stw	0,20(1)\n"
        "mr	31,3\n"
        "mr	30,5\n"
        "lwz	0,0(31)\n"
        "mr	3,4\n"
        "cmpwi	0,0\n"
        "beq	.L_800B7AB8\n"
        "lwz	0,8(31)\n"
        "cmpwi	0,0\n"
        "beq	.L_800B7AB8\n"
        "cmpwi	3,0\n"
        "beq	.L_800B7AB8\n"
        "cmpwi	30,-2\n"
        "beq	.L_800B7AB8\n"
        ".long 0x4826fa91  /* bl EResourceManager::CalcId(char *) */\n"
        "mr	4,3\n"
        "mr	5,30\n"
        "mr	3,31\n"
        ".long 0x4bfffeb5  /* bl cSoundPlayer::PlayBySource(unsigned int, short) */\n"
        ".L_800B7AB8:\n"
        "lwz	0,20(1)\n"
        "mtlr	0\n"
        "lmw	30,8(1)\n"
        "addi	1,1,16\n"
        "blr\n"
    );
    __builtin_unreachable();
}

// 0x800B7ACC (84 bytes)
// cSoundPlayer::PlayBySource(ERSoundEvent *, short)
__attribute__((noreturn))
void cSoundPlayer::PlayBySource(ERSoundEvent *, short) {
    __asm__ __volatile__(
        "stwu	1,-8(1)\n"
        "mflr	0\n"
        "stw	0,12(1)\n"
        "lwz	0,0(3)\n"
        "cmpwi	0,0\n"
        "beq	.L_800B7B10\n"
        "lwz	0,8(3)\n"
        "cmpwi	0,0\n"
        "beq	.L_800B7B10\n"
        "cmpwi	4,0\n"
        "beq	.L_800B7B10\n"
        "cmpwi	5,-2\n"
        "beq	.L_800B7B10\n"
        "lis	9,-32706\n"
        "lwz	3,-24508(13)\n"
        "lfs	1,-25884(9)\n"
        ".long 0x4bff6fd1  /* bl cBoxX::MappedEvent(ERSoundEvent *, int, float) */\n"
        ".L_800B7B10:\n"
        "lwz	0,12(1)\n"
        "mtlr	0\n"
        "addi	1,1,8\n"
        "blr\n"
    );
    __builtin_unreachable();
}

// 0x800B7B20 (84 bytes)
// cSoundPlayer::QuietBySourceID(int)
__attribute__((noreturn))
void cSoundPlayer::QuietBySourceID(int) {
    __asm__ __volatile__(
        "stwu	1,-8(1)\n"
        "mflr	0\n"
        "stw	0,12(1)\n"
        "lwz	0,0(3)\n"
        "cmpwi	0,0\n"
        "beq	.L_800B7B64\n"
        "lwz	0,8(3)\n"
        "cmpwi	0,0\n"
        "beq	.L_800B7B64\n"
        "lis	9,-32706\n"
        "mr	6,4\n"
        "lwz	3,-24508(13)\n"
        "li	4,23\n"
        "lfs	1,-25880(9)\n"
        "li	5,0\n"
        "li	7,0\n"
        ".long 0x4bff6fad  /* bl cBoxX::Event(int, int, int, ERSoundEvent *, float) */\n"
        ".L_800B7B64:\n"
        "lwz	0,12(1)\n"
        "mtlr	0\n"
        "addi	1,1,8\n"
        "blr\n"
    );
    __builtin_unreachable();
}

// 0x800B7B74 (112 bytes)
// cSoundPlayer::PauseSFX(void)
__attribute__((noreturn))
void cSoundPlayer::PauseSFX(void) {
    __asm__ __volatile__(
        "stwu	1,-16(1)\n"
        "mflr	0\n"
        "stw	31,12(1)\n"
        "stw	0,20(1)\n"
        "mr	31,3\n"
        "lwz	0,0(31)\n"
        "cmpwi	0,0\n"
        "beq	.L_800B7BD0\n"
        "lwz	0,8(31)\n"
        "cmpwi	0,0\n"
        "beq	.L_800B7BD0\n"
        "lwz	3,-24508(13)\n"
        "cmpwi	3,0\n"
        "beq	.L_800B7BC8\n"
        "lis	9,-32706\n"
        "li	4,49\n"
        "lfs	1,-25876(9)\n"
        "li	5,0\n"
        "li	6,0\n"
        "li	7,0\n"
        ".long 0x4bff6f49  /* bl cBoxX::Event(int, int, int, ERSoundEvent *, float) */\n"
        ".L_800B7BC8:\n"
        "mr	3,31\n"
        ".long 0x48000291  /* bl cSoundPlayer::NotifyViewChange(void) */\n"
        ".L_800B7BD0:\n"
        "lwz	0,20(1)\n"
        "mtlr	0\n"
        "lwz	31,12(1)\n"
        "addi	1,1,16\n"
        "blr\n"
    );
    __builtin_unreachable();
}

// 0x800B7BE4 (112 bytes)
// cSoundPlayer::ResumeSFX(void)
__attribute__((noreturn))
void cSoundPlayer::ResumeSFX(void) {
    __asm__ __volatile__(
        "stwu	1,-16(1)\n"
        "mflr	0\n"
        "stw	31,12(1)\n"
        "stw	0,20(1)\n"
        "mr	31,3\n"
        "lwz	0,0(31)\n"
        "cmpwi	0,0\n"
        "beq	.L_800B7C40\n"
        "lwz	0,8(31)\n"
        "cmpwi	0,0\n"
        "beq	.L_800B7C40\n"
        "lwz	3,-24508(13)\n"
        "cmpwi	3,0\n"
        "beq	.L_800B7C38\n"
        "lis	9,-32706\n"
        "li	4,50\n"
        "lfs	1,-25872(9)\n"
        "li	5,0\n"
        "li	6,0\n"
        "li	7,0\n"
        ".long 0x4bff6ed9  /* bl cBoxX::Event(int, int, int, ERSoundEvent *, float) */\n"
        ".L_800B7C38:\n"
        "mr	3,31\n"
        ".long 0x48000221  /* bl cSoundPlayer::NotifyViewChange(void) */\n"
        ".L_800B7C40:\n"
        "lwz	0,20(1)\n"
        "mtlr	0\n"
        "lwz	31,12(1)\n"
        "addi	1,1,16\n"
        "blr\n"
    );
    __builtin_unreachable();
}

// 0x800B7C54 (112 bytes)
// cSoundPlayer::PauseMusic(void)
__attribute__((noreturn))
void cSoundPlayer::PauseMusic(void) {
    __asm__ __volatile__(
        "stwu	1,-16(1)\n"
        "mflr	0\n"
        "stw	31,12(1)\n"
        "stw	0,20(1)\n"
        "mr	31,3\n"
        "lwz	0,0(31)\n"
        "cmpwi	0,0\n"
        "beq	.L_800B7CB0\n"
        "lwz	0,8(31)\n"
        "cmpwi	0,0\n"
        "beq	.L_800B7CB0\n"
        "lwz	3,-24508(13)\n"
        "cmpwi	3,0\n"
        "beq	.L_800B7CA8\n"
        "lis	9,-32706\n"
        "li	4,51\n"
        "lfs	1,-25868(9)\n"
        "li	5,0\n"
        "li	6,0\n"
        "li	7,0\n"
        ".long 0x4bff6e69  /* bl cBoxX::Event(int, int, int, ERSoundEvent *, float) */\n"
        ".L_800B7CA8:\n"
        "mr	3,31\n"
        ".long 0x480001b1  /* bl cSoundPlayer::NotifyViewChange(void) */\n"
        ".L_800B7CB0:\n"
        "lwz	0,20(1)\n"
        "mtlr	0\n"
        "lwz	31,12(1)\n"
        "addi	1,1,16\n"
        "blr\n"
    );
    __builtin_unreachable();
}

// 0x800B7CC4 (112 bytes)
// cSoundPlayer::ResumeMusic(void)
__attribute__((noreturn))
void cSoundPlayer::ResumeMusic(void) {
    __asm__ __volatile__(
        "stwu	1,-16(1)\n"
        "mflr	0\n"
        "stw	31,12(1)\n"
        "stw	0,20(1)\n"
        "mr	31,3\n"
        "lwz	0,0(31)\n"
        "cmpwi	0,0\n"
        "beq	.L_800B7D20\n"
        "lwz	0,8(31)\n"
        "cmpwi	0,0\n"
        "beq	.L_800B7D20\n"
        "lwz	3,-24508(13)\n"
        "cmpwi	3,0\n"
        "beq	.L_800B7D18\n"
        "lis	9,-32706\n"
        "li	4,52\n"
        "lfs	1,-25864(9)\n"
        "li	5,0\n"
        "li	6,0\n"
        "li	7,0\n"
        ".long 0x4bff6df9  /* bl cBoxX::Event(int, int, int, ERSoundEvent *, float) */\n"
        ".L_800B7D18:\n"
        "mr	3,31\n"
        ".long 0x48000141  /* bl cSoundPlayer::NotifyViewChange(void) */\n"
        ".L_800B7D20:\n"
        "lwz	0,20(1)\n"
        "mtlr	0\n"
        "lwz	31,12(1)\n"
        "addi	1,1,16\n"
        "blr\n"
    );
    __builtin_unreachable();
}

// 0x800B7D34 (148 bytes)
// cSoundPlayer::PauseSounds(void)
__attribute__((noreturn))
void cSoundPlayer::PauseSounds(void) {
    __asm__ __volatile__(
        "stwu	1,-16(1)\n"
        "mflr	0\n"
        "stmw	30,8(1)\n"
        "stw	0,20(1)\n"
        "mr	31,3\n"
        "li	0,1\n"
        "lwz	9,0(31)\n"
        "stw	0,12(31)\n"
        "cmpwi	9,0\n"
        "beq	.L_800B7DB4\n"
        "lwz	0,8(31)\n"
        "cmpwi	0,0\n"
        "beq	.L_800B7DB4\n"
        "lwz	3,-24508(13)\n"
        "cmpwi	3,0\n"
        "beq	.L_800B7DAC\n"
        "lis	30,-32706\n"
        "li	4,47\n"
        "lfs	1,-25860(30)\n"
        "li	5,0\n"
        "li	6,0\n"
        "li	7,0\n"
        ".long 0x4bff6d81  /* bl cBoxX::Event(int, int, int, ERSoundEvent *, float) */\n"
        "lfs	1,-25860(30)\n"
        "li	4,21\n"
        "lwz	3,-24508(13)\n"
        "li	5,0\n"
        "li	6,0\n"
        "li	7,0\n"
        ".long 0x4bff6d65  /* bl cBoxX::Event(int, int, int, ERSoundEvent *, float) */\n"
        ".L_800B7DAC:\n"
        "mr	3,31\n"
        ".long 0x480000ad  /* bl cSoundPlayer::NotifyViewChange(void) */\n"
        ".L_800B7DB4:\n"
        "lwz	0,20(1)\n"
        "mtlr	0\n"
        "lmw	30,8(1)\n"
        "addi	1,1,16\n"
        "blr\n"
    );
    __builtin_unreachable();
}

// 0x800B7DC8 (148 bytes)
// cSoundPlayer::ResumeSounds(void)
__attribute__((noreturn))
void cSoundPlayer::ResumeSounds(void) {
    __asm__ __volatile__(
        "stwu	1,-16(1)\n"
        "mflr	0\n"
        "stmw	30,8(1)\n"
        "stw	0,20(1)\n"
        "mr	31,3\n"
        "lwz	0,0(31)\n"
        "cmpwi	0,0\n"
        "beq	.L_800B7E40\n"
        "lwz	0,8(31)\n"
        "cmpwi	0,0\n"
        "beq	.L_800B7E40\n"
        "lwz	3,-24508(13)\n"
        "cmpwi	3,0\n"
        "beq	.L_800B7E38\n"
        "lis	30,-32706\n"
        "li	4,48\n"
        "lfs	1,-25856(30)\n"
        "li	5,0\n"
        "li	6,0\n"
        "li	7,0\n"
        ".long 0x4bff6cf5  /* bl cBoxX::Event(int, int, int, ERSoundEvent *, float) */\n"
        "lfs	1,-25856(30)\n"
        "li	4,22\n"
        "lwz	3,-24508(13)\n"
        "li	5,0\n"
        "li	6,0\n"
        "li	7,0\n"
        ".long 0x4bff6cd9  /* bl cBoxX::Event(int, int, int, ERSoundEvent *, float) */\n"
        ".L_800B7E38:\n"
        "mr	3,31\n"
        ".long 0x48000021  /* bl cSoundPlayer::NotifyViewChange(void) */\n"
        ".L_800B7E40:\n"
        "li	0,0\n"
        "stw	0,12(31)\n"
        "lwz	0,20(1)\n"
        "mtlr	0\n"
        "lmw	30,8(1)\n"
        "addi	1,1,16\n"
        "blr\n"
    );
    __builtin_unreachable();
}

// 0x800B7E5C (84 bytes)
// cSoundPlayer::NotifyViewChange(void)
__attribute__((noreturn))
void cSoundPlayer::NotifyViewChange(void) {
    __asm__ __volatile__(
        "stwu	1,-8(1)\n"
        "mflr	0\n"
        "stw	0,12(1)\n"
        "lwz	0,0(3)\n"
        "cmpwi	0,0\n"
        "beq	.L_800B7EA0\n"
        "lwz	0,8(3)\n"
        "cmpwi	0,0\n"
        "beq	.L_800B7EA0\n"
        "lis	9,-32706\n"
        "lwz	3,-24508(13)\n"
        "lfs	1,-25852(9)\n"
        "li	4,46\n"
        "li	5,0\n"
        "li	6,0\n"
        "li	7,0\n"
        ".long 0x4bff6c71  /* bl cBoxX::Event(int, int, int, ERSoundEvent *, float) */\n"
        ".L_800B7EA0:\n"
        "lwz	0,12(1)\n"
        "mtlr	0\n"
        "addi	1,1,8\n"
        "blr\n"
    );
    __builtin_unreachable();
}

// 0x800B7EB0 (84 bytes)
// cSoundPlayer::NotifyHourChange(void)
__attribute__((noreturn))
void cSoundPlayer::NotifyHourChange(void) {
    __asm__ __volatile__(
        "stwu	1,-8(1)\n"
        "mflr	0\n"
        "stw	0,12(1)\n"
        "lwz	0,0(3)\n"
        "cmpwi	0,0\n"
        "beq	.L_800B7EF4\n"
        "lwz	0,8(3)\n"
        "cmpwi	0,0\n"
        "beq	.L_800B7EF4\n"
        "lis	9,-32706\n"
        "lwz	3,-24508(13)\n"
        "lfs	1,-25848(9)\n"
        "li	4,46\n"
        "li	5,0\n"
        "li	6,0\n"
        "li	7,0\n"
        ".long 0x4bff6c1d  /* bl cBoxX::Event(int, int, int, ERSoundEvent *, float) */\n"
        ".L_800B7EF4:\n"
        "lwz	0,12(1)\n"
        "mtlr	0\n"
        "addi	1,1,8\n"
        "blr\n"
    );
    __builtin_unreachable();
}

// 0x800B7F54 (136 bytes)
// cSoundPlayer::SetOldFXVolume(int)
__attribute__((noreturn))
void cSoundPlayer::SetOldFXVolume(int) {
    __asm__ __volatile__(
        "stwu	1,-16(1)\n"
        "mflr	0\n"
        "stmw	30,8(1)\n"
        "stw	0,20(1)\n"
        "lis	9,-32697\n"
        "mr	31,4\n"
        "lwz	11,24340(9)\n"
        "stb	31,28(11)\n"
        "lwz	0,0(3)\n"
        "cmpwi	0,0\n"
        "beq	.L_800B7FC8\n"
        "lwz	0,8(3)\n"
        "cmpwi	0,0\n"
        "beq	.L_800B7FC8\n"
        "lis	30,-32706\n"
        "lwz	3,-24508(13)\n"
        "lfs	1,-25844(30)\n"
        "li	4,37\n"
        "mr	5,31\n"
        "li	6,0\n"
        "li	7,0\n"
        ".long 0x4bff6b65  /* bl cBoxX::Event(int, int, int, ERSoundEvent *, float) */\n"
        "lfs	1,-25844(30)\n"
        "mr	5,31\n"
        "lwz	3,-24508(13)\n"
        "li	4,39\n"
        "li	6,0\n"
        "li	7,0\n"
        ".long 0x4bff6b49  /* bl cBoxX::Event(int, int, int, ERSoundEvent *, float) */\n"
        ".L_800B7FC8:\n"
        "lwz	0,20(1)\n"
        "mtlr	0\n"
        "lmw	30,8(1)\n"
        "addi	1,1,16\n"
        "blr\n"
    );
    __builtin_unreachable();
}

// 0x800B7FDC (96 bytes)
// cSoundPlayer::SetMusicVolume(int)
__attribute__((noreturn))
void cSoundPlayer::SetMusicVolume(int) {
    __asm__ __volatile__(
        "stwu	1,-8(1)\n"
        "mflr	0\n"
        "stw	0,12(1)\n"
        "lis	9,-32697\n"
        "lwz	11,24340(9)\n"
        "stb	4,29(11)\n"
        "lwz	0,0(3)\n"
        "cmpwi	0,0\n"
        "beq	.L_800B802C\n"
        "lwz	0,8(3)\n"
        "cmpwi	0,0\n"
        "beq	.L_800B802C\n"
        "lis	9,-32706\n"
        "mr	5,4\n"
        "lwz	3,-24508(13)\n"
        "li	4,38\n"
        "lfs	1,-25840(9)\n"
        "li	6,0\n"
        "li	7,0\n"
        ".long 0x4bff6ae5  /* bl cBoxX::Event(int, int, int, ERSoundEvent *, float) */\n"
        ".L_800B802C:\n"
        "lwz	0,12(1)\n"
        "mtlr	0\n"
        "addi	1,1,8\n"
        "blr\n"
    );
    __builtin_unreachable();
}

// 0x800B803C (96 bytes)
// cSoundPlayer::SetSFXVolume(int)
__attribute__((noreturn))
void cSoundPlayer::SetSFXVolume(int) {
    __asm__ __volatile__(
        "stwu	1,-8(1)\n"
        "mflr	0\n"
        "stw	0,12(1)\n"
        "lis	9,-32697\n"
        "lwz	11,24340(9)\n"
        "stb	4,28(11)\n"
        "lwz	0,0(3)\n"
        "cmpwi	0,0\n"
        "beq	.L_800B808C\n"
        "lwz	0,8(3)\n"
        "cmpwi	0,0\n"
        "beq	.L_800B808C\n"
        "lis	9,-32706\n"
        "mr	5,4\n"
        "lwz	3,-24508(13)\n"
        "li	4,43\n"
        "lfs	1,-25836(9)\n"
        "li	6,0\n"
        "li	7,0\n"
        ".long 0x4bff6a85  /* bl cBoxX::Event(int, int, int, ERSoundEvent *, float) */\n"
        ".L_800B808C:\n"
        "lwz	0,12(1)\n"
        "mtlr	0\n"
        "addi	1,1,8\n"
        "blr\n"
    );
    __builtin_unreachable();
}

// 0x800B809C (96 bytes)
// cSoundPlayer::SetVOXVolume(int)
__attribute__((noreturn))
void cSoundPlayer::SetVOXVolume(int) {
    __asm__ __volatile__(
        "stwu	1,-8(1)\n"
        "mflr	0\n"
        "stw	0,12(1)\n"
        "lis	9,-32697\n"
        "lwz	11,24340(9)\n"
        "stb	4,40(11)\n"
        "lwz	0,0(3)\n"
        "cmpwi	0,0\n"
        "beq	.L_800B80EC\n"
        "lwz	0,8(3)\n"
        "cmpwi	0,0\n"
        "beq	.L_800B80EC\n"
        "lis	9,-32706\n"
        "mr	5,4\n"
        "lwz	3,-24508(13)\n"
        "li	4,39\n"
        "lfs	1,-25832(9)\n"
        "li	6,0\n"
        "li	7,0\n"
        ".long 0x4bff6a25  /* bl cBoxX::Event(int, int, int, ERSoundEvent *, float) */\n"
        ".L_800B80EC:\n"
        "lwz	0,12(1)\n"
        "mtlr	0\n"
        "addi	1,1,8\n"
        "blr\n"
    );
    __builtin_unreachable();
}

// 0x800B80FC (96 bytes)
// cSoundPlayer::SetAmbientVolume(int)
__attribute__((noreturn))
void cSoundPlayer::SetAmbientVolume(int) {
    __asm__ __volatile__(
        "stwu	1,-8(1)\n"
        "mflr	0\n"
        "stw	0,12(1)\n"
        "lis	9,-32697\n"
        "lwz	11,24340(9)\n"
        "stb	4,41(11)\n"
        "lwz	0,0(3)\n"
        "cmpwi	0,0\n"
        "beq	.L_800B814C\n"
        "lwz	0,8(3)\n"
        "cmpwi	0,0\n"
        "beq	.L_800B814C\n"
        "lis	9,-32706\n"
        "mr	5,4\n"
        "lwz	3,-24508(13)\n"
        "li	4,44\n"
        "lfs	1,-25828(9)\n"
        "li	6,0\n"
        "li	7,0\n"
        ".long 0x4bff69c5  /* bl cBoxX::Event(int, int, int, ERSoundEvent *, float) */\n"
        ".L_800B814C:\n"
        "lwz	0,12(1)\n"
        "mtlr	0\n"
        "addi	1,1,8\n"
        "blr\n"
    );
    __builtin_unreachable();
}

