#include "types.h"
#include "stub_classes.h"
// Auto-converted call wrapper stubs for CasSimPartsS2C
// Generated by convert_call_wrappers.py

// 0x8016A8F8 (88 bytes)
// Call wrapper [2bl_with_branch]: EResource::DelRef(void), __builtin_delete
__attribute__((noreturn))
CasSimPartsS2C::~CasSimPartsS2C(void) {
    __asm__ __volatile__(
        "stwu	1,-24(1)\n"
        "mflr	0\n"
        "stmw	29,12(1)\n"
        "stw	0,28(1)\n"
        "mr	31,3\n"
        "li	29,0\n"
        "lwz	3,0(31)\n"
        "mr	30,4\n"
        "stw	29,4(31)\n"
        "cmpwi	3,0\n"
        "beq	.L_8016A92C\n"
        ".long 0x481a764d  /* bl EResource::DelRef(void) */\n"
        "stw	29,0(31)\n"
        ".L_8016A92C:\n"
        "andi.	0,30,1\n"
        "beq	.L_8016A93C\n"
        "mr	3,31\n"
        ".long 0x481668e9  /* bl __builtin_delete */\n"
        ".L_8016A93C:\n"
        "lwz	0,28(1)\n"
        "mtlr	0\n"
        "lmw	29,12(1)\n"
        "addi	1,1,24\n"
        "blr\n"
    );
    __builtin_unreachable();
}
