#include "types.h"
#include "stub_classes.h"
// Auto-generated raw-byte matches for TArray_L_EAnimEvent
// Generated by gen_raw_byte_matches.py
// 3 functions, 132 bytes
// These functions are matched by directly injecting DOL bytes into the skeleton.
// The C++ stubs below exist only as annotations for the matching pipeline.

// 0x803C9140 (20 bytes)
// TArray_L_EAnimEvent__TArrayERAnimAllocator_R__Init_void
// [raw byte match - injected directly from DOL]

// 0x803C9154 (48 bytes)
// TArray_L_EAnimEvent__TArrayERAnimAllocator_R__TArray_void
// [raw byte match - injected directly from DOL]

// 0x803C91EC (64 bytes)
// TArray_L_EAnimEvent__TArrayERAnimAllocator_R__dtor_TArray_void
// [raw byte match - injected directly from DOL]

