extern void *_wrap_EffectsSequencerManager__AddRef_char_ptr__EFile_ptr__int();
void *EffectsSequencerManager__AddRef_char_ptr__EFile_ptr__int() { return _wrap_EffectsSequencerManager__AddRef_char_ptr__EFile_ptr__int(); }
