#include "types.h"
#include "stub_classes.h"
// Auto-generated raw-byte matches for ENgcScheduler
// Generated by gen_raw_byte_matches.py
// 7 functions, 296 bytes
// These functions are matched by directly injecting DOL bytes into the skeleton.
// The C++ stubs below exist only as annotations for the matching pipeline.

// 0x8034D918 (40 bytes)
// ENgcScheduler__QueueSetupFrameBuffer_int
// [raw byte match - injected directly from DOL]

// 0x8034D940 (40 bytes)
// ENgcScheduler__QueueDisplayList_EDL_ptr__bool
// [raw byte match - injected directly from DOL]

// 0x8034D968 (40 bytes)
// ENgcScheduler__QueueCompletionEvent_EEvent_ref
// [raw byte match - injected directly from DOL]

// 0x8034D990 (40 bytes)
// ENgcScheduler__QueueSwapBuffer_int__int
// [raw byte match - injected directly from DOL]

// 0x8034D9B8 (40 bytes)
// ENgcScheduler__Flush_void
// [raw byte match - injected directly from DOL]

// 0x8034D9F0 (56 bytes)
// ENgcScheduler__Main_void
// [raw byte match - injected directly from DOL]

// 0x8034DA28 (40 bytes)
// ENgcScheduler__SendCommand_ESchedCommand_ptr
// [raw byte match - injected directly from DOL]

