#include "types.h"
// Auto-generated inline asm decomp stubs for TreeTableQuickData
// Generated by gen_asm_decomp.py
// 10 functions, 1636 bytes
//
// Each function has its original C++ signature with the body as inline PPC asm.
// These can be incrementally replaced with real C++ as decompilation progresses.

class ObjectDataID;

class TreeTableQuickData {
public:
    TreeTableQuickData(void);
    ~TreeTableQuickData(void);
    void LoadFromDataID(ObjectDataID &);
    void Load(unsigned int, short);
    void GetNthEntry(int) const;
    void GetEntryByIndex(int) const;
    void GetEntryByTreeID(short, short) const;
    void GetNthOrderedEntry(int) const;
    void QueryInterface(unsigned int, void **);
    void Release(void);
};

// 0x8015DCB8 (104 bytes)
// TreeTableQuickData::TreeTableQuickData(void)
__attribute__((noreturn))
TreeTableQuickData::TreeTableQuickData(void) {
    __asm__ __volatile__(
        "stwu	1,-32(1)\n"
        "mflr	0\n"
        "stmw	29,20(1)\n"
        "stw	0,36(1)\n"
        "lis	9,-32698\n"
        "mr	30,3\n"
        "li	29,0\n"
        "addi	9,9,23400\n"
        "stw	9,0(30)\n"
        "addi	11,30,8\n"
        "stw	29,4(30)\n"
        "addi	9,11,8\n"
        "stw	29,8(30)\n"
        "addi	3,30,24\n"
        "stw	29,4(11)\n"
        "li	4,0\n"
        "stw	29,4(9)\n"
        "li	5,0\n"
        ".long 0x4bffddf5  /* bl ObjectDataID::ObjectDataID(unsigned int, unsigned short) */\n"
        "stw	29,32(30)\n"
        "mr	3,30\n"
        "lwz	0,36(1)\n"
        "mtlr	0\n"
        "lmw	29,20(1)\n"
        "addi	1,1,32\n"
        "blr\n"
    );
    __builtin_unreachable();
}

// 0x8015DD20 (268 bytes)
// TreeTableQuickData::~TreeTableQuickData(void)
__attribute__((noreturn))
TreeTableQuickData::~TreeTableQuickData(void) {
    __asm__ __volatile__(
        "stwu	1,-40(1)\n"
        "mflr	0\n"
        "stmw	25,12(1)\n"
        "stw	0,44(1)\n"
        "lis	9,-32698\n"
        "mr	29,3\n"
        "addi	9,9,23400\n"
        "li	0,0\n"
        "lwz	28,8(29)\n"
        "addi	26,29,8\n"
        "stw	9,0(29)\n"
        "mr	25,4\n"
        "stw	0,4(29)\n"
        "lwz	30,4(26)\n"
        "mr	31,28\n"
        "addi	27,29,8\n"
        "cmpw	28,30\n"
        "beq	.L_8015DD98\n"
        ".L_8015DD68:\n"
        "lwz	11,0(31)\n"
        "cmpwi	11,0\n"
        "beq	.L_8015DD8C\n"
        "lwz	9,0(11)\n"
        "lha	3,24(9)\n"
        "lwz	0,28(9)\n"
        "add	3,11,3\n"
        "mtlr	0\n"
        "blrl\n"
        ".L_8015DD8C:\n"
        "addi	31,31,4\n"
        "cmpw	31,30\n"
        "bne	.L_8015DD68\n"
        ".L_8015DD98:\n"
        "stw	28,4(26)\n"
        "lwz	30,4(27)\n"
        "lwz	31,8(29)\n"
        "cmpw	31,30\n"
        "beq	.L_8015DDDC\n"
        ".L_8015DDAC:\n"
        "lwz	11,0(31)\n"
        "cmpwi	11,0\n"
        "beq	.L_8015DDD0\n"
        "lwz	9,0(11)\n"
        "lha	3,24(9)\n"
        "lwz	0,28(9)\n"
        "add	3,11,3\n"
        "mtlr	0\n"
        "blrl\n"
        ".L_8015DDD0:\n"
        "addi	31,31,4\n"
        "cmpw	31,30\n"
        "bne	.L_8015DDAC\n"
        ".L_8015DDDC:\n"
        "lwz	3,0(27)\n"
        "cmpwi	3,0\n"
        "beq	.L_8015DE08\n"
        "lwz	0,12(27)\n"
        "subf	0,3,0\n"
        "clrrwi	4,0,2\n"
        "cmplwi	4,128\n"
        "ble	.L_8015DE04\n"
        ".long 0x48173425  /* bl __builtin_delete */\n"
        "b	.L_8015DE08\n"
        ".L_8015DE04:\n"
        ".long 0x4823e05d  /* bl __node_alloc<false, 0>::_M_deallocate(void *, unsigned int) */\n"
        ".L_8015DE08:\n"
        "andi.	0,25,1\n"
        "beq	.L_8015DE18\n"
        "mr	3,29\n"
        ".long 0x4817340d  /* bl __builtin_delete */\n"
        ".L_8015DE18:\n"
        "lwz	0,44(1)\n"
        "mtlr	0\n"
        "lmw	25,12(1)\n"
        "addi	1,1,40\n"
        "blr\n"
    );
    __builtin_unreachable();
}

// 0x8015DE60 (440 bytes)
// TreeTableQuickData::LoadFromDataID(ObjectDataID &)
__attribute__((noreturn))
void TreeTableQuickData::LoadFromDataID(ObjectDataID &) {
    __asm__ __volatile__(
        "stwu	1,-56(1)\n"
        "mflr	0\n"
        "stmw	22,16(1)\n"
        "stw	0,60(1)\n"
        "lwz	9,-21508(13)\n"
        "mr	27,3\n"
        "mr	24,4\n"
        "lwz	11,0(9)\n"
        "lwz	4,0(24)\n"
        "lha	3,56(11)\n"
        "lwz	0,60(11)\n"
        "add	3,9,3\n"
        "mtlr	0\n"
        "blrl\n"
        "mr.	3,3\n"
        "beq	.L_8015DEAC\n"
        "lwz	3,8(3)\n"
        "cmpwi	3,0\n"
        "bne	.L_8015DEB4\n"
        ".L_8015DEAC:\n"
        "li	3,0\n"
        "b	.L_8015E004\n"
        ".L_8015DEB4:\n"
        "lwz	3,36(3)\n"
        "li	4,0\n"
        "cmpwi	3,0\n"
        "beq	.L_8015DEC8\n"
        "lwz	4,-4(3)\n"
        ".L_8015DEC8:\n"
        "mulli	4,4,12\n"
        "lhz	5,4(24)\n"
        "add	4,3,4\n"
        ".long 0x48251361  /* bl TreeTable * FindRes<TreeTable>(TreeTable *, TreeTable *, int) */\n"
        "mr.	25,3\n"
        "beq	.L_8015DEAC\n"
        "addi	28,27,8\n"
        "stw	25,4(27)\n"
        "lwz	29,8(27)\n"
        "mr	26,28\n"
        "addi	23,1,8\n"
        "addi	22,27,24\n"
        "lwz	30,4(28)\n"
        "mr	31,29\n"
        "cmpw	29,30\n"
        "beq	.L_8015DF38\n"
        ".L_8015DF08:\n"
        "lwz	11,0(31)\n"
        "cmpwi	11,0\n"
        "beq	.L_8015DF2C\n"
        "lwz	9,0(11)\n"
        "lha	3,24(9)\n"
        "lwz	0,28(9)\n"
        "add	3,11,3\n"
        "mtlr	0\n"
        "blrl\n"
        ".L_8015DF2C:\n"
        "addi	31,31,4\n"
        "cmpw	31,30\n"
        "bne	.L_8015DF08\n"
        ".L_8015DF38:\n"
        "stw	29,4(28)\n"
        "li	5,0\n"
        "lwz	3,0(25)\n"
        "cmpwi	3,0\n"
        "beq	.L_8015DF50\n"
        "lwz	5,-4(3)\n"
        ".L_8015DF50:\n"
        "lwz	3,8(27)\n"
        "li	9,0\n"
        "lwz	4,4(26)\n"
        "stw	9,8(1)\n"
        "subf	0,3,4\n"
        "srawi	0,0,2\n"
        "cmplw	5,0\n"
        "bge	.L_8015DFC0\n"
        "slwi	0,5,2\n"
        "add	29,0,3\n"
        "lwz	30,4(26)\n"
        "mr	31,29\n"
        "cmpw	29,30\n"
        "beq	.L_8015DFB8\n"
        ".L_8015DF88:\n"
        "lwz	11,0(31)\n"
        "cmpwi	11,0\n"
        "beq	.L_8015DFAC\n"
        "lwz	9,0(11)\n"
        "lha	3,24(9)\n"
        "lwz	0,28(9)\n"
        "add	3,11,3\n"
        "mtlr	0\n"
        "blrl\n"
        ".L_8015DFAC:\n"
        "addi	31,31,4\n"
        "cmpw	31,30\n"
        "bne	.L_8015DF88\n"
        ".L_8015DFB8:\n"
        "stw	29,4(26)\n"
        "b	.L_8015DFD0\n"
        ".L_8015DFC0:\n"
        "subf	5,0,5\n"
        "mr	3,26\n"
        "mr	6,23\n"
        ".long 0x482512d9  /* bl vector<ConsoleAutoRefCount<TreeTableEntryQuickData>, allocator<ConsoleAutoRefCount<TreeTableEntryQuickData> > >::_M_fill_insert(ConsoleAutoRefCount<TreeTableEntryQuickData> *, unsigned int, ConsoleAutoRefCount<TreeTableEntryQuickData> &) */\n"
        ".L_8015DFD0:\n"
        "lwz	11,8(1)\n"
        "cmpwi	11,0\n"
        "beq	.L_8015DFF4\n"
        "lwz	9,0(11)\n"
        "lha	3,24(9)\n"
        "lwz	0,28(9)\n"
        "add	3,11,3\n"
        "mtlr	0\n"
        "blrl\n"
        ".L_8015DFF4:\n"
        "mr	3,22\n"
        "mr	4,24\n"
        ".long 0x4bffdb21  /* bl ObjectDataID::operator=(ObjectDataID &) */\n"
        "li	3,1\n"
        ".L_8015E004:\n"
        "lwz	0,60(1)\n"
        "mtlr	0\n"
        "lmw	22,16(1)\n"
        "addi	1,1,56\n"
        "blr\n"
    );
    __builtin_unreachable();
}

// 0x8015E028 (96 bytes)
// TreeTableQuickData::Load(unsigned int, short)
__attribute__((noreturn))
void TreeTableQuickData::Load(unsigned int, short) {
    __asm__ __volatile__(
        "stwu	1,-24(1)\n"
        "mflr	0\n"
        "stmw	30,16(1)\n"
        "stw	0,28(1)\n"
        "mr	30,3\n"
        "clrlwi	5,5,16\n"
        "addi	3,1,8\n"
        ".long 0x4bffdab1  /* bl ObjectDataID::ObjectDataID(unsigned int, unsigned short) */\n"
        "lwz	9,0(30)\n"
        "addi	4,1,8\n"
        "lha	3,40(9)\n"
        "lwz	0,44(9)\n"
        "add	3,30,3\n"
        "mtlr	0\n"
        "blrl\n"
        "cmpwi	3,0\n"
        "li	3,-50\n"
        "beq	.L_8015E074\n"
        "li	3,0\n"
        ".L_8015E074:\n"
        "lwz	0,28(1)\n"
        "mtlr	0\n"
        "lmw	30,16(1)\n"
        "addi	1,1,24\n"
        "blr\n"
    );
    __builtin_unreachable();
}

// 0x8015E088 (244 bytes)
// TreeTableQuickData::GetNthEntry(int) const
__attribute__((noreturn))
void TreeTableQuickData::GetNthEntry(int) const {
    __asm__ __volatile__(
        "stwu	1,-24(1)\n"
        "mflr	0\n"
        "stmw	29,12(1)\n"
        "stw	0,28(1)\n"
        "mr	30,3\n"
        "lwz	11,4(30)\n"
        "cmpwi	11,0\n"
        "beq	.L_8015E0C8\n"
        "cmpwi	4,0\n"
        "blt	.L_8015E0C8\n"
        "lwz	0,12(30)\n"
        "lwz	9,8(30)\n"
        "subf	0,9,0\n"
        "srawi	0,0,2\n"
        "cmpw	4,0\n"
        "blt	.L_8015E0D0\n"
        ".L_8015E0C8:\n"
        "li	3,0\n"
        "b	.L_8015E168\n"
        ".L_8015E0D0:\n"
        "slwi	29,4,2\n"
        "lwzx	0,9,29\n"
        "mr	3,0\n"
        "cmpwi	0,0\n"
        "bne	.L_8015E168\n"
        "mr	3,11\n"
        ".long 0x4bfeb2c9  /* bl TreeTable::GetNthEntry(int) const */\n"
        "mr.	31,3\n"
        "li	3,0\n"
        "beq	.L_8015E168\n"
        "li	3,28\n"
        ".long 0x481730b5  /* bl __builtin_new */\n"
        "mr	4,31\n"
        ".long 0x4bfff7f5  /* bl TreeTableEntryQuickData::TreeTableEntryQuickData(TreeTableEntry *) */\n"
        "lwz	30,8(30)\n"
        "mr	31,3\n"
        "lwzx	0,30,29\n"
        "cmpw	31,0\n"
        "beq	.L_8015E164\n"
        "cmpwi	31,0\n"
        "beq	.L_8015E13C\n"
        "lwz	9,0(31)\n"
        "lha	3,16(9)\n"
        "lwz	0,20(9)\n"
        "add	3,31,3\n"
        "mtlr	0\n"
        "blrl\n"
        ".L_8015E13C:\n"
        "lwzx	11,30,29\n"
        "cmpwi	11,0\n"
        "beq	.L_8015E160\n"
        "lwz	9,0(11)\n"
        "lha	3,24(9)\n"
        "lwz	0,28(9)\n"
        "add	3,11,3\n"
        "mtlr	0\n"
        "blrl\n"
        ".L_8015E160:\n"
        "stwx	31,30,29\n"
        ".L_8015E164:\n"
        "mr	3,31\n"
        ".L_8015E168:\n"
        "lwz	0,28(1)\n"
        "mtlr	0\n"
        "lmw	29,12(1)\n"
        "addi	1,1,24\n"
        "blr\n"
    );
    __builtin_unreachable();
}

// 0x8015E17C (96 bytes)
// TreeTableQuickData::GetEntryByIndex(int) const
__attribute__((noreturn))
void TreeTableQuickData::GetEntryByIndex(int) const {
    __asm__ __volatile__(
        "stwu	1,-16(1)\n"
        "mflr	0\n"
        "stw	31,12(1)\n"
        "stw	0,20(1)\n"
        "mr	31,3\n"
        "lwz	3,4(31)\n"
        "cmpwi	3,0\n"
        "beq	.L_8015E1C4\n"
        "extsh	4,4\n"
        ".long 0x4bfeb711  /* bl TreeTable::GetIndexOfResource(short) const */\n"
        "lwz	9,0(31)\n"
        "mr	4,3\n"
        "lha	3,120(9)\n"
        "lwz	0,124(9)\n"
        "add	3,31,3\n"
        "mtlr	0\n"
        "blrl\n"
        "b	.L_8015E1C8\n"
        ".L_8015E1C4:\n"
        "li	3,0\n"
        ".L_8015E1C8:\n"
        "lwz	0,20(1)\n"
        "mtlr	0\n"
        "lwz	31,12(1)\n"
        "addi	1,1,16\n"
        "blr\n"
    );
    __builtin_unreachable();
}

// 0x8015E1DC (92 bytes)
// TreeTableQuickData::GetEntryByTreeID(short, short) const
__attribute__((noreturn))
void TreeTableQuickData::GetEntryByTreeID(short, short) const {
    __asm__ __volatile__(
        "stwu	1,-16(1)\n"
        "mflr	0\n"
        "stw	31,12(1)\n"
        "stw	0,20(1)\n"
        "mr	31,3\n"
        "lwz	3,4(31)\n"
        "cmpwi	3,0\n"
        "beq	.L_8015E220\n"
        ".long 0x4bfeb729  /* bl TreeTable::GetIndexByTreeID(short, short) const */\n"
        "lwz	9,0(31)\n"
        "mr	4,3\n"
        "lha	3,120(9)\n"
        "lwz	0,124(9)\n"
        "add	3,31,3\n"
        "mtlr	0\n"
        "blrl\n"
        "b	.L_8015E224\n"
        ".L_8015E220:\n"
        "li	3,0\n"
        ".L_8015E224:\n"
        "lwz	0,20(1)\n"
        "mtlr	0\n"
        "lwz	31,12(1)\n"
        "addi	1,1,16\n"
        "blr\n"
    );
    __builtin_unreachable();
}

// 0x8015E238 (92 bytes)
// TreeTableQuickData::GetNthOrderedEntry(int) const
__attribute__((noreturn))
void TreeTableQuickData::GetNthOrderedEntry(int) const {
    __asm__ __volatile__(
        "stwu	1,-16(1)\n"
        "mflr	0\n"
        "stw	31,12(1)\n"
        "stw	0,20(1)\n"
        "mr	31,3\n"
        "lwz	3,4(31)\n"
        "cmpwi	3,0\n"
        "beq	.L_8015E27C\n"
        ".long 0x4bfeb729  /* bl TreeTable::GetIndexOfNthOrderedEntry(int) const */\n"
        "lwz	9,0(31)\n"
        "mr	4,3\n"
        "lha	3,120(9)\n"
        "lwz	0,124(9)\n"
        "add	3,31,3\n"
        "mtlr	0\n"
        "blrl\n"
        "b	.L_8015E280\n"
        ".L_8015E27C:\n"
        "li	3,0\n"
        ".L_8015E280:\n"
        "lwz	0,20(1)\n"
        "mtlr	0\n"
        "lwz	31,12(1)\n"
        "addi	1,1,16\n"
        "blr\n"
    );
    __builtin_unreachable();
}

// 0x8015E47C (112 bytes)
// TreeTableQuickData::QueryInterface(unsigned int, void **)
__attribute__((noreturn))
void TreeTableQuickData::QueryInterface(unsigned int, void **) {
    __asm__ __volatile__(
        "stwu	1,-16(1)\n"
        "mflr	0\n"
        "stmw	30,8(1)\n"
        "stw	0,20(1)\n"
        "mr	31,3\n"
        "mr.	30,5\n"
        "beq	.L_8015E4D4\n"
        "cmpwi	4,1\n"
        "beq	.L_8015E4B0\n"
        "lis	0,27635\n"
        "ori	0,0,8752\n"
        "cmpw	4,0\n"
        "bne	.L_8015E4D4\n"
        ".L_8015E4B0:\n"
        "lwz	9,0(31)\n"
        "lha	3,16(9)\n"
        "lwz	0,20(9)\n"
        "add	3,31,3\n"
        "mtlr	0\n"
        "blrl\n"
        "stw	31,0(30)\n"
        "li	3,1\n"
        "b	.L_8015E4D8\n"
        ".L_8015E4D4:\n"
        "li	3,0\n"
        ".L_8015E4D8:\n"
        "lwz	0,20(1)\n"
        "mtlr	0\n"
        "lmw	30,8(1)\n"
        "addi	1,1,16\n"
        "blr\n"
    );
    __builtin_unreachable();
}

// 0x8015E500 (92 bytes)
// TreeTableQuickData::Release(void)
__attribute__((noreturn))
void TreeTableQuickData::Release(void) {
    __asm__ __volatile__(
        "stwu	1,-8(1)\n"
        "mflr	0\n"
        "stw	0,12(1)\n"
        "mr	11,3\n"
        "lwz	9,32(11)\n"
        "addi	3,9,-1\n"
        "stw	3,32(11)\n"
        "cmpwi	3,0\n"
        "bne	.L_8015E54C\n"
        "cmpwi	11,0\n"
        "beq	.L_8015E548\n"
        "lwz	9,0(11)\n"
        "li	4,3\n"
        "lha	3,264(9)\n"
        "lwz	0,268(9)\n"
        "add	3,11,3\n"
        "mtlr	0\n"
        "blrl\n"
        ".L_8015E548:\n"
        "li	3,0\n"
        ".L_8015E54C:\n"
        "lwz	0,12(1)\n"
        "mtlr	0\n"
        "addi	1,1,8\n"
        "blr\n"
    );
    __builtin_unreachable();
}

