#include "types.h"
#include "stub_classes.h"
// Auto-converted call wrapper stubs for Emitter
// Generated by convert_call_wrappers.py

// 0x802384B0 (92 bytes)
// Call wrapper [2bl_with_branch]: PEmitterReg, ERLevel::InsertInstance(EInstance *, EInstance *)
__attribute__((noreturn))
void Emitter::Reg(psystem *, bool) {
    __asm__ __volatile__(
        "stwu	1,-16(1)\n"
        "mflr	0\n"
        "stmw	30,8(1)\n"
        "stw	0,20(1)\n"
        "mr	30,3\n"
        "mr	31,5\n"
        "mr	3,4\n"
        "lwz	4,124(30)\n"
        "cmpwi	4,0\n"
        "beq	.L_802384F8\n"
        ".long 0x480cb0fd  /* bl PEmitterReg */\n"
        "cmpwi	31,0\n"
        "beq	.L_802384F8\n"
        "lwz	9,-26512(13)\n"
        "mr	4,30\n"
        "li	5,0\n"
        "lwz	3,48(9)\n"
        ".long 0x4bffacc9  /* bl ERLevel::InsertInstance(EInstance *, EInstance *) */\n"
        ".L_802384F8:\n"
        "lwz	0,20(1)\n"
        "mtlr	0\n"
        "lmw	30,8(1)\n"
        "addi	1,1,16\n"
        "blr\n"
    );
    __builtin_unreachable();
}

// 0x8023850C (100 bytes)
// Call wrapper [2bl_with_branch]: PEmitterUnReg, ERLevel::RemoveInstance(EInstance *)
__attribute__((noreturn))
void Emitter::UnReg(psystem *, bool) {
    __asm__ __volatile__(
        "stwu	1,-16(1)\n"
        "mflr	0\n"
        "stmw	30,8(1)\n"
        "stw	0,20(1)\n"
        "mr	31,3\n"
        "mr	30,5\n"
        "mr	3,4\n"
        "lwz	4,124(31)\n"
        "cmpwi	4,0\n"
        "beq	.L_8023855C\n"
        ".long 0x480cb0ed  /* bl PEmitterUnReg */\n"
        "cmpwi	30,0\n"
        "beq	.L_8023855C\n"
        "lwz	9,-26512(13)\n"
        "lwz	0,4(31)\n"
        "lwz	3,48(9)\n"
        "cmpwi	0,0\n"
        "beq	.L_8023855C\n"
        "mr	4,31\n"
        ".long 0x4bffb9b9  /* bl ERLevel::RemoveInstance(EInstance *) */\n"
        ".L_8023855C:\n"
        "lwz	0,20(1)\n"
        "mtlr	0\n"
        "lmw	30,8(1)\n"
        "addi	1,1,16\n"
        "blr\n"
    );
    __builtin_unreachable();
}

// 0x80238608 (116 bytes)
// Call wrapper [1bl_with_branch]: ERLevel::RemoveInstance(EInstance *)
__attribute__((noreturn))
void Emitter::SetState(int, int) {
    __asm__ __volatile__(
        "stwu	1,-8(1)\n"
        "mflr	0\n"
        "stw	0,12(1)\n"
        "mr	11,3\n"
        "lwz	9,124(11)\n"
        "cmpwi	9,0\n"
        "beq	.L_8023866C\n"
        "cmpwi	cr7,5,0\n"
        "beq	.L_80238638\n"
        "lwz	0,80(9)\n"
        "or	0,0,4\n"
        "b	.L_80238640\n"
        ".L_80238638:\n"
        "lwz	0,80(9)\n"
        "andc	0,0,4\n"
        ".L_80238640:\n"
        "stw	0,80(9)\n"
        "andi.	0,4,16384\n"
        "beq	.L_8023866C\n"
        "beq	.L_8023866C\n"
        "lwz	9,-26512(13)\n"
        "lwz	0,4(11)\n"
        "lwz	3,48(9)\n"
        "cmpwi	0,0\n"
        "beq	.L_8023866C\n"
        "mr	4,11\n"
        ".long 0x4bffb8a9  /* bl ERLevel::RemoveInstance(EInstance *) */\n"
        ".L_8023866C:\n"
        "lwz	0,12(1)\n"
        "mtlr	0\n"
        "addi	1,1,8\n"
        "blr\n"
    );
    __builtin_unreachable();
}

// 0x8023872C (96 bytes)
// Call wrapper [2bl_with_branch]: Emitter::Destroy(void), EInstance::~EInstance(void)
__attribute__((noreturn))
Emitter::~Emitter(void) {
    __asm__ __volatile__(
        "stwu	1,-16(1)\n"
        "mflr	0\n"
        "stmw	30,8(1)\n"
        "stw	0,20(1)\n"
        "mr	31,3\n"
        "lis	9,-32697\n"
        "lwz	11,124(31)\n"
        "addi	9,9,-25824\n"
        "mr	30,4\n"
        "stw	9,0(31)\n"
        "cmpwi	11,0\n"
        "beq	.L_8023876C\n"
        "lwz	0,80(11)\n"
        "andi.	9,0,16384\n"
        "bne	.L_8023876C\n"
        ".long 0x4bfffd19  /* bl Emitter::Destroy(void) */\n"
        ".L_8023876C:\n"
        "mr	3,31\n"
        "mr	4,30\n"
        ".long 0x4bfefbfd  /* bl EInstance::~EInstance(void) */\n"
        "lwz	0,20(1)\n"
        "mtlr	0\n"
        "lmw	30,8(1)\n"
        "addi	1,1,16\n"
        "blr\n"
    );
    __builtin_unreachable();
}

// 0x8023884C (104 bytes)
// Call wrapper [1bl_with_branch]: Emitter::SetCallbacks(void (*)(particle *, PVector4 *, float, float, PVector4 *, void *), void (*)(void *), void (*)(void *), void (*)(pemitter *, PVector4 *, PVector4 *), void *, void (*)(void *), void *, void (*)(void *), void *)
__attribute__((noreturn))
void Emitter::EmitterSetPostDestroyCallback(void (*)(void *), void *) {
    __asm__ __volatile__(
        "stwu	1,-16(1)\n"
        "mflr	0\n"
        "stw	0,20(1)\n"
        "lwz	0,124(3)\n"
        "mr	9,4\n"
        "mr	10,5\n"
        "cmpwi	0,0\n"
        "beq	.L_802388A4\n"
        "li	0,0\n"
        "li	4,0\n"
        "li	5,0\n"
        "li	6,0\n"
        "li	7,0\n"
        "li	8,0\n"
        "stw	0,12(1)\n"
        "ori	4,4,65535\n"
        "stw	0,8(1)\n"
        "ori	5,5,65535\n"
        "ori	6,6,65535\n"
        "ori	7,7,65535\n"
        "ori	8,8,65535\n"
        ".long 0x4bfffeed  /* bl Emitter::SetCallbacks(void (*)(particle *, PVector4 *, float, float, PVector4 *, void *), void (*)(void *), void (*)(void *), void (*)(pemitter *, PVector4 *, PVector4 *), void *, void (*)(void *), void *, void (*)(void *), void *) */\n"
        ".L_802388A4:\n"
        "lwz	0,20(1)\n"
        "mtlr	0\n"
        "addi	1,1,16\n"
        "blr\n"
    );
    __builtin_unreachable();
}

// 0x802388B4 (116 bytes)
// Call wrapper [1bl_with_branch]: Emitter::SetCallbacks(void (*)(particle *, PVector4 *, float, float, PVector4 *, void *), void (*)(void *), void (*)(void *), void (*)(pemitter *, PVector4 *, PVector4 *), void *, void (*)(void *), void *, void (*)(void *), void *)
__attribute__((noreturn))
void Emitter::EmitterSetIntervalCallback(void (*)(void *), void *) {
    __asm__ __volatile__(
        "stwu	1,-16(1)\n"
        "mflr	0\n"
        "stw	0,20(1)\n"
        "lwz	0,124(3)\n"
        "mr	12,4\n"
        "mr	11,5\n"
        "cmpwi	0,0\n"
        "beq	.L_80238918\n"
        "li	4,0\n"
        "li	5,0\n"
        "li	6,0\n"
        "li	7,0\n"
        "li	8,0\n"
        "li	9,0\n"
        "li	10,0\n"
        "stw	12,8(1)\n"
        "stw	11,12(1)\n"
        "ori	4,4,65535\n"
        "ori	5,5,65535\n"
        "ori	6,6,65535\n"
        "ori	7,7,65535\n"
        "ori	8,8,65535\n"
        "ori	9,9,65535\n"
        "ori	10,10,65535\n"
        ".long 0x4bfffe79  /* bl Emitter::SetCallbacks(void (*)(particle *, PVector4 *, float, float, PVector4 *, void *), void (*)(void *), void (*)(void *), void (*)(pemitter *, PVector4 *, PVector4 *), void *, void (*)(void *), void *, void (*)(void *), void *) */\n"
        ".L_80238918:\n"
        "lwz	0,20(1)\n"
        "mtlr	0\n"
        "addi	1,1,16\n"
        "blr\n"
    );
    __builtin_unreachable();
}
