#include "types.h"
// Auto-generated inline asm decomp stubs for LoadingScreenFadeOutState
// Generated by gen_asm_decomp.py
// 4 functions, 680 bytes
//
// Each function has its original C++ signature with the body as inline PPC asm.
// These can be incrementally replaced with real C++ as decompilation progresses.

class ERC;

class LoadingScreenFadeOutState {
public:
    void Update(float);
    void DrawTopmost(ERC *);
    void FaderUpdate(float);
    void FaderGetFadeOpacity(void);
};

// 0x8009060C (248 bytes)
// LoadingScreenFadeOutState::Update(float)
__attribute__((noreturn))
void LoadingScreenFadeOutState::Update(float) {
    __asm__ __volatile__(
        "stwu	1,-24(1)\n"
        "mflr	0\n"
        "stfd	31,16(1)\n"
        "stw	31,12(1)\n"
        "stw	0,28(1)\n"
        "mr	31,3\n"
        "fmr	31,1\n"
        "lwz	9,8(31)\n"
        "lfs	12,-22736(13)\n"
        "addi	11,9,168\n"
        "lwz	0,12(11)\n"
        "andi.	9,0,16\n"
        "beq	.L_80090694\n"
        "lis	9,-32706\n"
        "lfs	0,8(11)\n"
        "lfs	13,-32660(9)\n"
        "fcmpu	cr0,0,13\n"
        "beq	.L_80090694\n"
        "fsubs	0,0,12\n"
        "fcmpu	cr0,0,13\n"
        "stfs	0,8(11)\n"
        "cror	so,eq,lt\n"
        "bns	.L_80090694\n"
        "stfs	13,8(11)\n"
        "andi.	9,0,1\n"
        "beq	.L_80090680\n"
        "clrrwi	0,0,1\n"
        "ori	0,0,4\n"
        "b	.L_80090690\n"
        ".L_80090680:\n"
        "andi.	9,0,2\n"
        "beq	.L_80090694\n"
        "rlwinm	0,0,0,31,29\n"
        "ori	0,0,8\n"
        ".L_80090690:\n"
        "stw	0,12(11)\n"
        ".L_80090694:\n"
        "lwz	3,-32160(13)\n"
        "lwz	0,180(3)\n"
        "andi.	9,0,8\n"
        "beq	.L_800906D4\n"
        ".long 0x480004b9  /* bl LoadingScreenStateMachine::DeleteLoadingScreen(void) */\n"
        "lwz	10,-26392(13)\n"
        "li	0,1\n"
        "lwz	8,-32160(13)\n"
        "lis	9,-32706\n"
        "stw	0,800(10)\n"
        "li	11,0\n"
        "lfs	1,-32660(9)\n"
        "mr	3,31\n"
        "stw	11,180(8)\n"
        "li	4,0\n"
        ".long 0x480053d5  /* bl StateMachineState::OwnerSetNextState(int, float) */\n"
        ".L_800906D4:\n"
        "lwz	9,-32160(13)\n"
        "lwz	3,152(9)\n"
        "cmpwi	3,0\n"
        "beq	.L_800906EC\n"
        "fmr	1,31\n"
        ".long 0x4bfc66cd  /* bl CLoadingScreen::Update(float) */\n"
        ".L_800906EC:\n"
        "lwz	0,28(1)\n"
        "mtlr	0\n"
        "lwz	31,12(1)\n"
        "lfd	31,16(1)\n"
        "addi	1,1,24\n"
        "blr\n"
    );
    __builtin_unreachable();
}

// 0x80090704 (200 bytes)
// LoadingScreenFadeOutState::DrawTopmost(ERC *)
__attribute__((noreturn))
void LoadingScreenFadeOutState::DrawTopmost(ERC *) {
    __asm__ __volatile__(
        "stwu	1,-24(1)\n"
        "mflr	0\n"
        "stfd	31,16(1)\n"
        "stmw	30,8(1)\n"
        "stw	0,28(1)\n"
        "lwz	9,-32160(13)\n"
        "mr	30,4\n"
        "lwz	31,152(9)\n"
        "cmpwi	31,0\n"
        "beq	.L_800907B4\n"
        "lwz	3,8(3)\n"
        "addi	9,3,168\n"
        "lwz	0,12(9)\n"
        "andi.	11,0,1\n"
        "beq	.L_80090758\n"
        "lfs	0,168(3)\n"
        "lfs	13,8(9)\n"
        "lfs	12,4(9)\n"
        "fsubs	0,0,13\n"
        "fmuls	31,0,12\n"
        "b	.L_80090790\n"
        ".L_80090758:\n"
        "andi.	11,0,2\n"
        "beq	.L_80090770\n"
        "lfs	13,4(9)\n"
        "lfs	0,8(9)\n"
        "fmuls	31,0,13\n"
        "b	.L_80090790\n"
        ".L_80090770:\n"
        "andi.	9,0,4\n"
        "beq	.L_80090784\n"
        "lis	9,-32706\n"
        "lfs	31,-32612(9)\n"
        "b	.L_80090790\n"
        ".L_80090784:\n"
        "andi.	11,0,8\n"
        "lis	9,-32706\n"
        "lfs	31,-32608(9)\n"
        ".L_80090790:\n"
        "lis	3,-32706\n"
        "fmr	1,31\n"
        "addi	3,3,-32656\n"
        "crset	4*cr1+eq\n"
        ".long 0x4831056d  /* bl LssDummyPrintf(char *,...) */\n"
        "mr	3,31\n"
        "mr	4,30\n"
        "fmr	1,31\n"
        ".long 0x4bfc66e5  /* bl CLoadingScreen::DrawTopmost(ERC *, float) */\n"
        ".L_800907B4:\n"
        "lwz	0,28(1)\n"
        "mtlr	0\n"
        "lmw	30,8(1)\n"
        "lfd	31,16(1)\n"
        "addi	1,1,24\n"
        "blr\n"
    );
    __builtin_unreachable();
}

// 0x80091348 (112 bytes)
// LoadingScreenFadeOutState::FaderUpdate(float)
__attribute__((noreturn))
void LoadingScreenFadeOutState::FaderUpdate(float) {
    __asm__ __volatile__(
        "lwz	9,8(3)\n"
        "addi	11,9,168\n"
        "lwz	0,12(11)\n"
        "andi.	9,0,16\n"
        "beqlr\n"
        "lis	9,-32706\n"
        "lfs	0,8(11)\n"
        "lfs	13,-32496(9)\n"
        "fcmpu	cr0,0,13\n"
        "beqlr\n"
        "fsubs	0,0,1\n"
        "fcmpu	cr0,0,13\n"
        "stfs	0,8(11)\n"
        "cror	so,eq,lt\n"
        "bnslr\n"
        "stfs	13,8(11)\n"
        "andi.	9,0,1\n"
        "beq	.L_800913A0\n"
        "clrrwi	0,0,1\n"
        "ori	0,0,4\n"
        "stw	0,12(11)\n"
        "blr\n"
        ".L_800913A0:\n"
        "andi.	9,0,2\n"
        "beqlr\n"
        "rlwinm	0,0,0,31,29\n"
        "ori	0,0,8\n"
        "stw	0,12(11)\n"
        "blr\n"
    );
    __builtin_unreachable();
}

// 0x800913B8 (120 bytes)
// LoadingScreenFadeOutState::FaderGetFadeOpacity(void)
__attribute__((noreturn))
void LoadingScreenFadeOutState::FaderGetFadeOpacity(void) {
    __asm__ __volatile__(
        "lwz	11,8(3)\n"
        "addi	9,11,168\n"
        "lwz	0,12(9)\n"
        "andi.	10,0,1\n"
        "beq	.L_800913E4\n"
        "lfs	0,168(11)\n"
        "lfs	13,8(9)\n"
        "lfs	12,4(9)\n"
        "fsubs	0,0,13\n"
        "fmuls	1,0,12\n"
        "blr\n"
        ".L_800913E4:\n"
        "andi.	11,0,2\n"
        "beq	.L_800913FC\n"
        "lfs	13,4(9)\n"
        "lfs	0,8(9)\n"
        "fmuls	1,0,13\n"
        "blr\n"
        ".L_800913FC:\n"
        "andi.	9,0,4\n"
        "beq	.L_80091410\n"
        "lis	9,-32706\n"
        "lfs	1,-32492(9)\n"
        "blr\n"
        ".L_80091410:\n"
        "andi.	10,0,8\n"
        "beq	.L_80091424\n"
        "lis	9,-32706\n"
        "lfs	1,-32488(9)\n"
        "blr\n"
        ".L_80091424:\n"
        "lis	9,-32706\n"
        "lfs	1,-32488(9)\n"
        "blr\n"
    );
    __builtin_unreachable();
}

