#include "types.h"
#include "stub_classes.h"
// Auto-generated matching stubs for ENgcTextureCMPR
// Generated by auto_match.py
// 2 functions, 12 bytes

// 0x80351534 (4 bytes)
void ENgcTextureCMPR::SwizzleImage(unsigned char *, int, int, unsigned char *) { }
#if 0

// 0x80351568 (8 bytes)
void* ENgcTextureCMPR::operator new(unsigned int, void *) { return (void*)0; }  // mr r3,r4
#endif

