#include "types.h"
#include "stub_classes.h"
// Auto-generated raw-byte matches for SpacePartition
// Generated by gen_raw_byte_matches.py
// 2 functions, 84 bytes
// These functions are matched by directly injecting DOL bytes into the skeleton.
// The C++ stubs below exist only as annotations for the matching pipeline.

// 0x80138E30 (64 bytes)
// SpacePartition__GetNode_int
// [raw byte match - injected directly from DOL]

// 0x80138F1C (20 bytes)
// SpacePartition__IsSpatialNode_int
// [raw byte match - injected directly from DOL]

