#include "types.h"
#include "stub_classes.h"
// Auto-generated raw-byte matches for TArray_L_EILight_ptr
// Generated by gen_raw_byte_matches.py
// 4 functions, 172 bytes
// These functions are matched by directly injecting DOL bytes into the skeleton.
// The C++ stubs below exist only as annotations for the matching pipeline.

// 0x8039F614 (20 bytes)
// TArray_L_EILight_ptr__TArrayDefaultAllocator_R__Init_void
// [raw byte match - injected directly from DOL]

// 0x8039F628 (48 bytes)
// TArray_L_EILight_ptr__TArrayDefaultAllocator_R__TArray_void
// [raw byte match - injected directly from DOL]

// 0x8039F6C0 (64 bytes)
// TArray_L_EILight_ptr__TArrayDefaultAllocator_R__dtor_TArray_void
// [raw byte match - injected directly from DOL]

// 0x8039F9F4 (40 bytes)
// TArray_L_EILight_ptr__TArrayDefaultAllocator_R__Add_EILight_ptrr
// [raw byte match - injected directly from DOL]

