#include "types.h"
#include "stub_classes.h"
// Auto-generated matching stubs for Interaction (branching leaf functions)
// Generated by auto_match_branch.py
// 13 functions, 408 bytes

// 0x800C1D8C (24 bytes)
bool Interaction::HasID() const { return *(int*)((char*)this + 0x38) != 0; }

// 0x800C1DEC (32 bytes)
void Interaction::SetContinuation(bool val) { register int __r0 __asm__("r0") = *(int*)((char*)this + 0x3C); __asm__ __volatile__("" : "+r"(__r0)); __r0 &= 0xFFFFFFFD; *(int*)((char*)this + 0x3C) = __r0; if (val) { __r0 |= 0x2; *(int*)((char*)this + 0x3C) = __r0; } }

// 0x800C1E18 (32 bytes)
void Interaction::SetChecked(bool val) { register int __r0 __asm__("r0") = *(int*)((char*)this + 0x3C); __asm__ __volatile__("" : "+r"(__r0)); __r0 &= 0xFFFFFFFB; *(int*)((char*)this + 0x3C) = __r0; if (val) { __r0 |= 0x4; *(int*)((char*)this + 0x3C) = __r0; } }

// 0x800C1E44 (32 bytes)
void Interaction::SetAvailable(bool val) { register int __r0 __asm__("r0") = *(int*)((char*)this + 0x3C); __asm__ __volatile__("" : "+r"(__r0)); __r0 &= 0xFFFFFFF7; *(int*)((char*)this + 0x3C) = __r0; if (val) { __r0 |= 0x8; *(int*)((char*)this + 0x3C) = __r0; } }

// 0x800C1E70 (32 bytes)
void Interaction::SetHidden(bool val) { register int __r0 __asm__("r0") = *(int*)((char*)this + 0x3C); __asm__ __volatile__("" : "+r"(__r0)); __r0 &= 0xFFFFFFEF; *(int*)((char*)this + 0x3C) = __r0; if (val) { __r0 |= 0x10; *(int*)((char*)this + 0x3C) = __r0; } }

// 0x800C1E9C (32 bytes)
void Interaction::SetPushToHead(bool val) { register int __r0 __asm__("r0") = *(int*)((char*)this + 0x3C); __asm__ __volatile__("" : "+r"(__r0)); __r0 &= 0xFFFFFFDF; *(int*)((char*)this + 0x3C) = __r0; if (val) { __r0 |= 0x20; *(int*)((char*)this + 0x3C) = __r0; } }

// 0x800C1EC8 (32 bytes)
void Interaction::SetCarryNameOver(bool val) { register int __r0 __asm__("r0") = *(int*)((char*)this + 0x3C); __asm__ __volatile__("" : "+r"(__r0)); __r0 &= 0xFFFFFFBF; *(int*)((char*)this + 0x3C) = __r0; if (val) { __r0 |= 0x40; *(int*)((char*)this + 0x3C) = __r0; } }

// 0x800C1EF4 (32 bytes)
void Interaction::SetNameChanged(bool val) { register int __r0 __asm__("r0") = *(int*)((char*)this + 0x3C); __asm__ __volatile__("" : "+r"(__r0)); __r0 &= 0xFFFFFF7F; *(int*)((char*)this + 0x3C) = __r0; if (val) { __r0 |= 0x80; *(int*)((char*)this + 0x3C) = __r0; } }

// 0x800C1F20 (32 bytes)
void Interaction::SetCancelled(bool val) { register int __r0 __asm__("r0") = *(int*)((char*)this + 0x3C); __asm__ __volatile__("" : "+r"(__r0)); __r0 &= 0xFFFFFEFF; *(int*)((char*)this + 0x3C) = __r0; if (val) { __r0 |= 0x100; *(int*)((char*)this + 0x3C) = __r0; } }

// 0x800C1F4C (32 bytes)
void Interaction::SetDebugOverride(bool val) { register int __r0 __asm__("r0") = *(int*)((char*)this + 0x3C); __asm__ __volatile__("" : "+r"(__r0)); __r0 &= 0xFFFFFDFF; *(int*)((char*)this + 0x3C) = __r0; if (val) { __r0 |= 0x200; *(int*)((char*)this + 0x3C) = __r0; } }

// 0x800C1F78 (32 bytes)
void Interaction::SetMustRun(bool val) { register int __r0 __asm__("r0") = *(int*)((char*)this + 0x3C); __asm__ __volatile__("" : "+r"(__r0)); __r0 &= 0xFFFFFBFF; *(int*)((char*)this + 0x3C) = __r0; if (val) { __r0 |= 0x400; *(int*)((char*)this + 0x3C) = __r0; } }

// 0x800C1FA4 (32 bytes)
void Interaction::SetDisabled(bool val) { register int __r0 __asm__("r0") = *(int*)((char*)this + 0x3C); __asm__ __volatile__("" : "+r"(__r0)); __r0 &= 0xFFFFF7FF; *(int*)((char*)this + 0x3C) = __r0; if (val) { __r0 |= 0x800; *(int*)((char*)this + 0x3C) = __r0; } }

// 0x800C1FD0 (32 bytes)
void Interaction::SetRunAsSub(bool val) { register int __r0 __asm__("r0") = *(int*)((char*)this + 0x3C); __asm__ __volatile__("" : "+r"(__r0)); __r0 &= 0xFFFF7FFF; *(int*)((char*)this + 0x3C) = __r0; if (val) { __r0 |= 0x8000; *(int*)((char*)this + 0x3C) = __r0; } }

