#include "types.h"
#include "stub_classes.h"
// Auto-generated raw-byte matches for UIDrawTable
// Generated by gen_raw_byte_matches.py
// 3 functions, 164 bytes
// These functions are matched by directly injecting DOL bytes into the skeleton.
// The C++ stubs below exist only as annotations for the matching pipeline.

// 0x8017AA1C (52 bytes)
// UIDrawTable__ContainsEntry_CBFunctor1_L_ERC_ptr_R__ref
// [raw byte match - injected directly from DOL]

// 0x8017AB18 (60 bytes)
// UIDrawTable__Instance_void
// [raw byte match - injected directly from DOL]

// 0x803B1424 (52 bytes)
// UIDrawTable__DrawTableRecord__dtor_DrawTableRecord_void
// [raw byte match - injected directly from DOL]

