#include "types.h"
#include "stub_classes.h"
// Auto-generated raw-byte matches for global_constructors_keyed_to_EffectsEmitterManager
// Generated by gen_raw_byte_matches.py
// 1 functions, 44 bytes
// These functions are matched by directly injecting DOL bytes into the skeleton.
// The C++ stubs below exist only as annotations for the matching pipeline.

// 0x80328A58 (44 bytes)
// global_constructors_keyed_to_EffectsEmitterManager__AllocateAndLoadResource_EFile_ptr__unsigned_int__unsigned_int
// [raw byte match - injected directly from DOL]

