// Auto-generated matching stubs for ActionMenu
// Generated by auto_match.py
// 1 functions, 16 bytes
#include "types.h"
#include "stub_classes.h"

// 0x80184008 (16 bytes)
void ActionMenu::CompleteMenu() { *(char*)((char*)this + 0xA0) += -1; }

