#include "types.h"
#include "stub_classes.h"
// Auto-generated matching stubs for AmbientSoundPlayer (branching leaf functions)
// Generated by auto_match_branch.py
// 1 functions, 40 bytes

// 0x800AAA18 (40 bytes)
bool AmbientSoundPlayer::IsValid() { return (*(int*)((char*)this + 0x0) != 0) && (*(int*)((char*)this + 0x4) != 0); }

