#include "types.h"
#include "stub_classes.h"
// Auto-generated raw-byte matches for AnimTableImpl
// Generated by gen_raw_byte_matches.py
// 3 functions, 128 bytes
// These functions are matched by directly injecting DOL bytes into the skeleton.
// The C++ stubs below exist only as annotations for the matching pipeline.

// 0x800AAB08 (52 bytes)
// AnimTableImpl__dtor_AnimTableImpl_void
// [raw byte match - injected directly from DOL]

// 0x800AABC4 (64 bytes)
// AnimTableImpl__GetEntry_int
// [raw byte match - injected directly from DOL]

// 0x800AAC04 (12 bytes)
// AnimTableImpl__GetID_void
// [raw byte match - injected directly from DOL]

