#include "types.h"
#include "stub_classes.h"
// Auto-generated raw-byte matches for AnimTable
// Generated by gen_raw_byte_matches.py
// 3 functions, 156 bytes
// These functions are matched by directly injecting DOL bytes into the skeleton.
// The C++ stubs below exist only as annotations for the matching pipeline.

// 0x800AAA84 (40 bytes)
// AnimTable__CreateInstance_void
// [raw byte match - injected directly from DOL]

// 0x800AAAAC (64 bytes)
// AnimTable__DestroyInstance_AnimTable_ptr
// [raw byte match - injected directly from DOL]

// 0x803A2AAC (52 bytes)
// AnimTable__dtor_AnimTable_void
// [raw byte match - injected directly from DOL]

