#include "types.h"
#include "stub_classes.h"
// Auto-generated matching stubs for AptObject
// Generated by auto_match.py
// 2 functions, 24 bytes

// 0x802B63AC (12 bytes)
int AptObject::getHasClass() const { return (*(int*)((char*)this + 0x20) >> 23) & 1; }  // bit 23

// 0x802B63D8 (12 bytes)
int AptObject::getInMainInst() const { return (*(int*)((char*)this + 0x20) >> 22) & 1; }  // bit 22

