#include "types.h"
#include "stub_classes.h"
// Auto-generated matching constructors for AptRenderingContext
// Generated by gen_ctor_matches.py (inline asm)
// 1 functions, 92 bytes

// 0x802AB188 (92 bytes)
__attribute__((noreturn))
AptRenderingContext::AptRenderingContext() {
    __asm__ __volatile__(
        "lis	10,-32703\n""lis	11,-32703\n""lfs	0,-10204(11)\n""mr	9,3\n""lfs	13,-10208(10)\n""li	0,0\n""stfs	0,52(9)\n""stfs	13,44(9)\n""stw	0,956(9)\n""stfs	13,0(9)\n""stfs	13,4(9)\n""stfs	13,8(9)\n""stfs	13,12(9)\n""stfs	0,16(9)\n""stfs	0,20(9)\n""stfs	0,24(9)\n""stfs	0,28(9)\n""stfs	13,32(9)\n""stfs	0,36(9)\n""stfs	0,40(9)\n""stfs	0,48(9)\n""stw	0,952(9)\n""blr\n"
    );
    __builtin_unreachable();
}
