#include "types.h"
#include "stub_classes.h"
// Auto-converted call wrapper stubs for BitMatrix64
// Generated by convert_call_wrappers.py

// 0x8009BB4C (100 bytes)
// Call wrapper [2bl_with_branch]: BitArray64::~BitArray64(void), __builtin_delete
__attribute__((noreturn))
BitMatrix64::~BitMatrix64(void) {
    __asm__ __volatile__(
        "stwu	1,-24(1)\n"
        "mflr	0\n"
        "stmw	29,12(1)\n"
        "stw	0,28(1)\n"
        "mr	29,4\n"
        "mr.	30,3\n"
        "beq	.L_8009BB8C\n"
        "addi	31,30,512\n"
        "cmpw	30,31\n"
        "beq	.L_8009BB8C\n"
        ".L_8009BB74:\n"
        "addi	31,31,-8\n"
        "li	4,0\n"
        "mr	3,31\n"
        ".long 0x4bfffbc1  /* bl BitArray64::~BitArray64(void) */\n"
        "cmpw	30,31\n"
        "bne	.L_8009BB74\n"
        ".L_8009BB8C:\n"
        "andi.	0,29,1\n"
        "beq	.L_8009BB9C\n"
        "mr	3,30\n"
        ".long 0x48235689  /* bl __builtin_delete */\n"
        ".L_8009BB9C:\n"
        "lwz	0,28(1)\n"
        "mtlr	0\n"
        "lmw	29,12(1)\n"
        "addi	1,1,24\n"
        "blr\n"
    );
    __builtin_unreachable();
}
