#include "types.h"
#include "stub_classes.h"
// Auto-generated raw-byte matches for CameraManager
// Generated by gen_raw_byte_matches.py
// 1 functions, 40 bytes
// These functions are matched by directly injecting DOL bytes into the skeleton.
// The C++ stubs below exist only as annotations for the matching pipeline.

// 0x8001EB50 (40 bytes)
// CameraManager__dtor_CameraManager_void
// [raw byte match - injected directly from DOL]

