#include "types.h"
#include "stub_classes.h"
// Auto-generated matching constructors for CasTweakTool
// Generated by gen_ctor_matches.py (inline asm)
// 1 functions, 40 bytes

// 0x801752A4 (40 bytes)
__attribute__((noreturn))
CasTweakTool::CasTweakTool() {
    __asm__ __volatile__(
        "lis	9,-32698\n""li	0,4\n""addi	9,9,25256\n""mtctr	0\n""stw	9,272(3)\n"".L_801752B8:\n""bdnz	.L_801752B8\n""li	0,4\n""mtctr	0\n"".L_801752C4:\n""bdnz	.L_801752C4\n""blr\n"
    );
    __builtin_unreachable();
}
