#include "types.h"
// Inline asm leaf matches for cFixedWorldImpl
// 4 functions, 360 bytes

#include "types.h"
// Auto-generated inline asm decomp stubs for cFixedWorldImpl
// Generated by gen_asm_decomp.py
// 33 functions, 23420 bytes
//
// Each function has its original C++ signature with the body as inline PPC asm.
// These can be incrementally replaced with real C++ as decompilation progresses.

class CTilePt;
class FTilePt;
class TileWallStorage;
class iResFile;

struct FloorPattern {};
struct TileWalls {};
struct TileWallsSegment {};

class cFixedWorldImpl {
public:
    cFixedWorldImpl(int, int);
    ~cFixedWorldImpl(void);
    void SetSize(int, int, bool);
    void DeleteArrays(void);
    void Save(iResFile *, int);
    void Load(iResFile *, int);
    void GetWall(CTilePt &);
    void SetWall(CTilePt &, TileWalls);
    void ComputeRooms(int);
    void ComputeArchValue(bool *);
    void DoCommand(short, int);
    void OffsetWorld(CTilePt &);
    void OutOfRoutableExtent(CTilePt &) const;
    void OutOfRoutableExtent(FTilePt &) const;
    void OutOfBounds(CTilePt &) const;
    void OutOfBuildingBounds(CTilePt &, bool) const;
    void OutOfGrid(CTilePt &) const;
    void OutOfBounds(FTilePt &) const;
    void OutOfGrid(FTilePt &) const;
    void GetFloor(CTilePt &);
    void IsGrassAt(CTilePt &);
    void SetFloor(CTilePt &, FloorPattern);
    void GetRoom(CTilePt &);
    void SetRoom(CTilePt &, unsigned short);
    void GetFlags(CTilePt &);
    void SetFlags(CTilePt &, unsigned char);
    void IsOutside(CTilePt &);
    void HasWalls(CTilePt &, TileWallsSegment);
    void HasWalls(CTilePt &);
    void GetWallStorage(CTilePt &);
    void SetWallStorage(CTilePt &, TileWallStorage &);
    void MayEditTile(CTilePt &) const;
    void GetRoomIdFromPoint(CTilePt &);
};


// 0x80151984 (80 bytes)
// cFixedWorldImpl::OutOfRoutableExtent(CTilePt &) const
__attribute__((noreturn))
void cFixedWorldImpl::OutOfRoutableExtent(CTilePt &) const {
    __asm__ __volatile__(
        "lbz	9,0(4)\n"
        "li	11,0\n"
        "lwz	0,28(3)\n"
        "extsb	9,9\n"
        "cmpw	9,0\n"
        "blt	.L_801519C8\n"
        "lwz	0,32(3)\n"
        "cmpw	9,0\n"
        "bgt	.L_801519C8\n"
        "lbz	0,1(4)\n"
        "lwz	9,36(3)\n"
        "extsb	4,0\n"
        "cmpw	4,9\n"
        "blt	.L_801519C8\n"
        "lwz	0,40(3)\n"
        "cmpw	4,0\n"
        "ble	.L_801519CC\n"
        ".L_801519C8:\n"
        "li	11,1\n"
        ".L_801519CC:\n"
        "mr	3,11\n"
        "blr\n"
    );
}

// 0x80151A40 (80 bytes)
// cFixedWorldImpl::OutOfBounds(CTilePt &) const
__attribute__((noreturn))
void cFixedWorldImpl::OutOfBounds(CTilePt &) const {
    __asm__ __volatile__(
        "lbz	0,0(4)\n"
        "extsb	0,0\n"
        "cmpwi	0,0\n"
        "ble	.L_80151A80\n"
        "lwz	9,20(3)\n"
        "addi	9,9,-1\n"
        "cmpw	0,9\n"
        "bge	.L_80151A80\n"
        "lbz	0,1(4)\n"
        "extsb	0,0\n"
        "cmpwi	0,0\n"
        "ble	.L_80151A80\n"
        "lwz	9,24(3)\n"
        "addi	9,9,-1\n"
        "cmpw	0,9\n"
        "blt	.L_80151A88\n"
        ".L_80151A80:\n"
        "li	3,1\n"
        "blr\n"
        ".L_80151A88:\n"
        "li	3,0\n"
        "blr\n"
    );
}

// 0x80151A90 (128 bytes)
// cFixedWorldImpl::OutOfBuildingBounds(CTilePt &, bool) const
__attribute__((noreturn))
void cFixedWorldImpl::OutOfBuildingBounds(CTilePt &, bool) const {
    __asm__ __volatile__(
        "mr	10,4\n"
        "cmpwi	5,0\n"
        "beq	.L_80151AB8\n"
        "lwz	11,24(3)\n"
        "li	8,2\n"
        "lwz	9,20(3)\n"
        "li	7,2\n"
        "addi	4,11,-2\n"
        "addi	3,9,-2\n"
        "b	.L_80151AD0\n"
        ".L_80151AB8:\n"
        "lwz	11,24(3)\n"
        "li	8,1\n"
        "lwz	9,20(3)\n"
        "li	7,1\n"
        "addi	4,11,-1\n"
        "addi	3,9,-1\n"
        ".L_80151AD0:\n"
        "lbz	0,0(10)\n"
        "extsb	0,0\n"
        "cmpw	0,8\n"
        "blt	.L_80151B00\n"
        "cmpw	0,3\n"
        "bge	.L_80151B00\n"
        "lbz	0,1(10)\n"
        "extsb	0,0\n"
        "cmpw	0,7\n"
        "blt	.L_80151B00\n"
        "cmpw	0,4\n"
        "blt	.L_80151B08\n"
        ".L_80151B00:\n"
        "li	3,1\n"
        "blr\n"
        ".L_80151B08:\n"
        "li	3,0\n"
        "blr\n"
    );
}

// 0x80151B10 (72 bytes)
// cFixedWorldImpl::OutOfGrid(CTilePt &) const
__attribute__((noreturn))
void cFixedWorldImpl::OutOfGrid(CTilePt &) const {
    __asm__ __volatile__(
        "lbz	0,0(4)\n"
        "extsb	9,0\n"
        "cmpwi	9,0\n"
        "blt	.L_80151B48\n"
        "lwz	0,20(3)\n"
        "cmpw	9,0\n"
        "bge	.L_80151B48\n"
        "lbz	0,1(4)\n"
        "extsb	4,0\n"
        "cmpwi	4,0\n"
        "blt	.L_80151B48\n"
        "lwz	0,24(3)\n"
        "cmpw	4,0\n"
        "blt	.L_80151B50\n"
        ".L_80151B48:\n"
        "li	3,1\n"
        "blr\n"
        ".L_80151B50:\n"
        "li	3,0\n"
        "blr\n"
    );
}

