#include "types.h"
#include "stub_classes.h"
// Auto-converted call wrapper stubs for Commander
// Generated by convert_call_wrappers.py

// 0x800B4250 (100 bytes)
// Call wrapper [1bl_with_branch]: __builtin_delete
__attribute__((noreturn))
Commander::~Commander(void) {
    __asm__ __volatile__(
        "stwu	1,-8(1)\n"
        "mflr	0\n"
        "stw	0,12(1)\n"
        "lis	9,-32698\n"
        "addi	11,13,-32076\n"
        "addi	9,9,-5144\n"
        "stw	9,12(3)\n"
        "b	.L_800B428C\n"
        ".L_800B4270:\n"
        "lwz	0,0(11)\n"
        "cmpw	0,3\n"
        "bne	.L_800B4288\n"
        "lwz	0,0(3)\n"
        "stw	0,0(11)\n"
        "b	.L_800B4298\n"
        ".L_800B4288:\n"
        "mr	11,0\n"
        ".L_800B428C:\n"
        "lwz	0,0(11)\n"
        "cmpwi	0,0\n"
        "bne	.L_800B4270\n"
        ".L_800B4298:\n"
        "andi.	0,4,1\n"
        "beq	.L_800B42A4\n"
        ".long 0x4821cf81  /* bl __builtin_delete */\n"
        ".L_800B42A4:\n"
        "lwz	0,12(1)\n"
        "mtlr	0\n"
        "addi	1,1,8\n"
        "blr\n"
    );
    __builtin_unreachable();
}
