#include "types.h"
#include "stub_classes.h"
// Auto-generated raw-byte matches for ComputeTCBMults_float
// Generated by gen_raw_byte_matches.py
// 1 functions, 60 bytes
// These functions are matched by directly injecting DOL bytes into the skeleton.
// The C++ stubs below exist only as annotations for the matching pipeline.

// 0x8030D828 (60 bytes)
// ComputeTCBMults_float__float__float_ref__float_ref
// [raw byte match - injected directly from DOL]

