#include "types.h"
#include "stub_classes.h"
// Auto-generated matching stubs for DlgWrapper (medium functions)
// Generated by auto_match_medium.py
// 3 functions, 72 bytes

// 0x8007E608 (24 bytes)
bool DlgWrapper::DialogAccepted() { /* compare fields 172(r3) and 52(r9) */ return false; }

// 0x8007E620 (24 bytes)
bool DlgWrapper::DialogDeclined() { /* compare fields 172(r3) and 52(r9) */ return false; }

// 0x8007E638 (24 bytes)
bool DlgWrapper::DialogAlt1() { /* compare fields 172(r3) and 52(r9) */ return false; }

