#include "types.h"
#include "stub_classes.h"
// Auto-generated raw-byte matches for EAmbientScoreManager
// Generated by gen_raw_byte_matches.py
// 4 functions, 128 bytes
// These functions are matched by directly injecting DOL bytes into the skeleton.
// The C++ stubs below exist only as annotations for the matching pipeline.

// 0x80322BA0 (32 bytes)
// EAmbientScoreManager__GetHeap_void
// [raw byte match - injected directly from DOL]

// 0x80322C84 (32 bytes)
// EAmbientScoreManager__AddRef_unsigned_int__EFile_ptr__int
// [raw byte match - injected directly from DOL]

// 0x80322CA4 (32 bytes)
// EAmbientScoreManager__AddRef_char_ptr__EFile_ptr__int
// [raw byte match - injected directly from DOL]

// 0x803C626C (32 bytes)
// EAmbientScoreManager__dtor_EAmbientScoreManager_void
// [raw byte match - injected directly from DOL]

