#include "types.h"
#include "stub_classes.h"
// Auto-generated raw-byte matches for EAudioSampleManager
// Generated by gen_raw_byte_matches.py
// 5 functions, 208 bytes
// These functions are matched by directly injecting DOL bytes into the skeleton.
// The C++ stubs below exist only as annotations for the matching pipeline.

// 0x8032CC80 (64 bytes)
// EAudioSampleManager__EAudioSampleManager_void
// [raw byte match - injected directly from DOL]

// 0x8032CCC0 (48 bytes)
// EAudioSampleManager__dtor_EAudioSampleManager_void
// [raw byte match - injected directly from DOL]

// 0x8032D94C (32 bytes)
// EAudioSampleManager__AddRef_unsigned_int__EFile_ptr__int
// [raw byte match - injected directly from DOL]

// 0x8032D96C (32 bytes)
// EAudioSampleManager__AddRef_char_ptr__EFile_ptr__int
// [raw byte match - injected directly from DOL]

// 0x8036C33C (32 bytes)
// EAudioSampleManager__GetHeap_void
// [raw byte match - injected directly from DOL]

