#include "types.h"
#include "stub_classes.h"
// Auto-converted call wrapper stubs for EFenceWall
// Generated by convert_call_wrappers.py

// 0x8039E42C (68 bytes)
// Call wrapper [2bl_with_branch]: ERoomWall::~ERoomWall(void), ERoomWall::operator delete(void *)
__attribute__((noreturn))
EFenceWall::~EFenceWall(void) {
    __asm__ __volatile__(
        "stwu	1,-16(1)\n"
        "mflr	0\n"
        "stmw	30,8(1)\n"
        "stw	0,20(1)\n"
        "mr	30,4\n"
        "mr	31,3\n"
        "li	4,0\n"
        ".long 0x4bc8e371  /* bl ERoomWall::~ERoomWall(void) */\n"
        "andi.	0,30,1\n"
        "beq	.L_8039E45C\n"
        "mr	3,31\n"
        ".long 0x4bc8e141  /* bl ERoomWall::operator delete(void *) */\n"
        ".L_8039E45C:\n"
        "lwz	0,20(1)\n"
        "mtlr	0\n"
        "lmw	30,8(1)\n"
        "addi	1,1,16\n"
        "blr\n"
    );
    __builtin_unreachable();
}
