#include "types.h"
#include "stub_classes.h"
// Auto-generated raw-byte matches for EFloorShdTblNode
// Generated by gen_raw_byte_matches.py
// 2 functions, 112 bytes
// These functions are matched by directly injecting DOL bytes into the skeleton.
// The C++ stubs below exist only as annotations for the matching pipeline.

// 0x8004571C (64 bytes)
// EFloorShdTblNode__AddLightStrip_EFloorStripInfo
// [raw byte match - injected directly from DOL]

// 0x800477A0 (48 bytes)
// EFloorShdTblNode__RemapFloorAndGrassId_unsigned_int
// [raw byte match - injected directly from DOL]

