#include "types.h"
#include "stub_classes.h"
// Auto-converted call wrapper stubs for EHashTable
// Generated by convert_call_wrappers.py

// 0x802C8AAC (112 bytes)
// Call wrapper [2bl_with_branch]: EHashTable::Find(unsigned int, unsigned int) const, EHashTable::InsertNew(unsigned int, unsigned int, unsigned int)
__attribute__((noreturn))
void EHashTable::SetValue(unsigned int, unsigned int) {
    __asm__ __volatile__(
        "stwu	1,-24(1)\n"
        "mflr	0\n"
        "stmw	28,8(1)\n"
        "stw	0,28(1)\n"
        "mr	30,3\n"
        "mr	31,4\n"
        "lwz	9,12(30)\n"
        "mr	28,5\n"
        "mr	5,31\n"
        "divwu	0,31,9\n"
        "mullw	0,0,9\n"
        "subf	29,0,31\n"
        "mr	4,29\n"
        ".long 0x48000339  /* bl EHashTable::Find(unsigned int, unsigned int) const */\n"
        "mr.	3,3\n"
        "beq	.L_802C8AF4\n"
        "stw	28,16(3)\n"
        "b	.L_802C8B08\n"
        ".L_802C8AF4:\n"
        "mr	3,30\n"
        "mr	4,29\n"
        "mr	5,31\n"
        "mr	6,28\n"
        ".long 0x480000a5  /* bl EHashTable::InsertNew(unsigned int, unsigned int, unsigned int) */\n"
        ".L_802C8B08:\n"
        "lwz	0,28(1)\n"
        "mtlr	0\n"
        "lmw	28,8(1)\n"
        "addi	1,1,24\n"
        "blr\n"
    );
    __builtin_unreachable();
}

// 0x802C8CD8 (160 bytes)
// Call wrapper [1bl_with_branch]: __builtin_delete
__attribute__((noreturn))
void EHashTable::Remove(unsigned int, HTIteratorPtrType *) {
    __asm__ __volatile__(
        "stwu	1,-8(1)\n"
        "mflr	0\n"
        "stw	0,12(1)\n"
        "mr	11,3\n"
        "slwi	4,4,2\n"
        "lwz	9,8(11)\n"
        "lwzx	3,9,4\n"
        "add	9,9,4\n"
        "b	.L_802C8D04\n"
        ".L_802C8CFC:\n"
        "addi	9,3,8\n"
        "lwz	3,8(3)\n"
        ".L_802C8D04:\n"
        "cmpwi	3,0\n"
        "beq	.L_802C8D14\n"
        "cmpw	3,5\n"
        "bne	.L_802C8CFC\n"
        ".L_802C8D14:\n"
        "lwz	0,8(3)\n"
        "stw	0,0(9)\n"
        "lwz	9,0(11)\n"
        "cmpw	9,3\n"
        "bne	.L_802C8D34\n"
        "lwz	0,4(3)\n"
        "stw	0,0(11)\n"
        "b	.L_802C8D40\n"
        ".L_802C8D34:\n"
        "lwz	9,0(3)\n"
        "lwz	0,4(3)\n"
        "stw	0,4(9)\n"
        ".L_802C8D40:\n"
        "lwz	0,4(11)\n"
        "cmpw	0,3\n"
        "bne	.L_802C8D58\n"
        "lwz	0,0(3)\n"
        "stw	0,4(11)\n"
        "b	.L_802C8D64\n"
        ".L_802C8D58:\n"
        "lwz	9,4(3)\n"
        "lwz	0,0(3)\n"
        "stw	0,0(9)\n"
        ".L_802C8D64:\n"
        ".long 0x480084bd  /* bl __builtin_delete */\n"
        "lwz	0,12(1)\n"
        "mtlr	0\n"
        "addi	1,1,8\n"
        "blr\n"
    );
    __builtin_unreachable();
}

// 0x802C8E4C (92 bytes)
// Call wrapper [2bl_with_branch]: __builtin_delete, EHashTable::ClearTable(void)
__attribute__((noreturn))
void EHashTable::RemoveAll(void) {
    __asm__ __volatile__(
        "stwu	1,-16(1)\n"
        "mflr	0\n"
        "stmw	30,8(1)\n"
        "stw	0,20(1)\n"
        "mr	31,3\n"
        "lwz	30,4(31)\n"
        "cmpwi	30,0\n"
        "beq	.L_802C8E80\n"
        ".L_802C8E6C:\n"
        "mr	3,30\n"
        "lwz	30,0(30)\n"
        ".long 0x480083ad  /* bl __builtin_delete */\n"
        "mr.	30,30\n"
        "bne	.L_802C8E6C\n"
        ".L_802C8E80:\n"
        "li	0,0\n"
        "mr	3,31\n"
        "stw	0,0(31)\n"
        "stw	0,4(31)\n"
        ".long 0x4bfffb5d  /* bl EHashTable::ClearTable(void) */\n"
        "lwz	0,20(1)\n"
        "mtlr	0\n"
        "lmw	30,8(1)\n"
        "addi	1,1,16\n"
        "blr\n"
    );
    __builtin_unreachable();
}

// 0x802C8F80 (88 bytes)
// Call wrapper [2bl_with_branch]: EHashTable::GetSize(void) const, EHashTable::SetTableSize(int)
__attribute__((noreturn))
void EHashTable::AutoSizeTable(void) {
    __asm__ __volatile__(
        "stwu	1,-16(1)\n"
        "mflr	0\n"
        "stw	31,12(1)\n"
        "stw	0,20(1)\n"
        "mr	31,3\n"
        ".long 0x4bffff79  /* bl EHashTable::GetSize(void) const */\n"
        "li	4,1\n"
        "cmpw	4,3\n"
        "bge	.L_802C8FB0\n"
        ".L_802C8FA4:\n"
        "add	4,4,4\n"
        "cmpw	4,3\n"
        "blt	.L_802C8FA4\n"
        ".L_802C8FB0:\n"
        "cmpwi	4,1\n"
        "ble	.L_802C8FBC\n"
        "addi	4,4,-1\n"
        ".L_802C8FBC:\n"
        "mr	3,31\n"
        ".long 0x48000019  /* bl EHashTable::SetTableSize(int) */\n"
        "lwz	0,20(1)\n"
        "mtlr	0\n"
        "lwz	31,12(1)\n"
        "addi	1,1,16\n"
        "blr\n"
    );
    __builtin_unreachable();
}
