#include "types.h"
#include "stub_classes.h"
// Auto-generated raw-byte matches for EInstance
// Generated by gen_raw_byte_matches.py
// 23 functions, 604 bytes
// These functions are matched by directly injecting DOL bytes into the skeleton.
// The C++ stubs below exist only as annotations for the matching pipeline.

// 0x802287F4 (36 bytes)
// EInstance__GetBoundSphere_EBoundSphere_ref
// [raw byte match - injected directly from DOL]

// 0x80228818 (48 bytes)
// EInstance__RemoveFromLevel_void
// [raw byte match - injected directly from DOL]

// 0x802291F8 (36 bytes)
// EInstance__InsertInOrderTable_EOrderTableData_ref
// [raw byte match - injected directly from DOL]

// 0x80229270 (20 bytes)
// EInstance__GetInstAlpha_void
// [raw byte match - injected directly from DOL]

// 0x802292F4 (40 bytes)
// EInstance__New_void
// [raw byte match - injected directly from DOL]

// 0x8022931C (32 bytes)
// EInstance__Construct_EInstance_ptr
// [raw byte match - injected directly from DOL]

// 0x8022933C (36 bytes)
// EInstance__Destruct_EInstance_ptr
// [raw byte match - injected directly from DOL]

// 0x80229360 (64 bytes)
// EInstance__SafeDelete_void
// [raw byte match - injected directly from DOL]

// 0x8022943C (32 bytes)
// EInstance__CreateCopy_void__const
// [raw byte match - injected directly from DOL]

// 0x8022948C (20 bytes)
// EInstance__GetInstName_EInstance__InstType_ref
// [raw byte match - injected directly from DOL]

// 0x802295C4 (8 bytes)
// EInstance__SetPortalType_EPortalType
// [raw byte match - injected directly from DOL]

// 0x802295CC (8 bytes)
// EInstance__GetPortalType_void
// [raw byte match - injected directly from DOL]

// 0x802295D4 (12 bytes)
// EInstance__RegisterOtherSideFn_unsigned_int__void__p__unsigned_int__bool__short_ref__short_ref
// [raw byte match - injected directly from DOL]

// 0x802295E8 (8 bytes)
// EInstance__GetThisSideFn_void
// [raw byte match - injected directly from DOL]

// 0x802295F8 (8 bytes)
// EInstance__GetOtherSideFn_void
// [raw byte match - injected directly from DOL]

// 0x80229600 (12 bytes)
// EInstance__RegisterThisSideFn_unsigned_int__void__p__unsigned_int__bool__short_ref__short_ref
// [raw byte match - injected directly from DOL]

// 0x8022960C (12 bytes)
// EInstance__RegisterHiddenFn_unsigned_int__bool__p__unsigned_int
// [raw byte match - injected directly from DOL]

// 0x80229618 (60 bytes)
// EInstance__IsHidden_void
// [raw byte match - injected directly from DOL]

// 0x80229660 (8 bytes)
// EInstance__GetBounds_void__const
// [raw byte match - injected directly from DOL]

// 0x80229690 (24 bytes)
// EInstance__GetVelocity_EVec3_ref
// [raw byte match - injected directly from DOL]

// 0x802296A8 (24 bytes)
// EInstance__GetPos_EVec3_ref
// [raw byte match - injected directly from DOL]

// 0x802296C0 (36 bytes)
// EInstance__GetOrient_EMat4_ref
// [raw byte match - injected directly from DOL]

// 0x8022972C (20 bytes)
// EInstance__ShouldInterestFade_bool
// [raw byte match - injected directly from DOL]

