#include "types.h"
#include "stub_classes.h"
// Auto-generated raw-byte matches for EIPointAmbLight
// Generated by gen_raw_byte_matches.py
// 6 functions, 236 bytes
// These functions are matched by directly injecting DOL bytes into the skeleton.
// The C++ stubs below exist only as annotations for the matching pipeline.

// 0x80229B98 (40 bytes)
// EIPointAmbLight__New_void
// [raw byte match - injected directly from DOL]

// 0x80229BC0 (32 bytes)
// EIPointAmbLight__Construct_EIPointAmbLight_ptr
// [raw byte match - injected directly from DOL]

// 0x80229BE0 (36 bytes)
// EIPointAmbLight__Destruct_EIPointAmbLight_ptr
// [raw byte match - injected directly from DOL]

// 0x80229C04 (64 bytes)
// EIPointAmbLight__SafeDelete_void
// [raw byte match - injected directly from DOL]

// 0x80229CE0 (32 bytes)
// EIPointAmbLight__CreateCopy_void__const
// [raw byte match - injected directly from DOL]

// 0x803C1490 (32 bytes)
// EIPointAmbLight__dtor_EIPointAmbLight_void
// [raw byte match - injected directly from DOL]

