#include "types.h"
#include "stub_classes.h"
// Auto-generated raw-byte matches for EIPortalPointLight
// Generated by gen_raw_byte_matches.py
// 8 functions, 328 bytes
// These functions are matched by directly injecting DOL bytes into the skeleton.
// The C++ stubs below exist only as annotations for the matching pipeline.

// 0x8022A720 (32 bytes)
// EIPortalPointLight__GetLumina_void__const
// [raw byte match - injected directly from DOL]

// 0x8022A7E8 (60 bytes)
// EIPortalPointLight__SetPortal_EInstance_ptr__bool
// [raw byte match - injected directly from DOL]

// 0x8022AF8C (40 bytes)
// EIPortalPointLight__New_void
// [raw byte match - injected directly from DOL]

// 0x8022AFB4 (32 bytes)
// EIPortalPointLight__Construct_EIPortalPointLight_ptr
// [raw byte match - injected directly from DOL]

// 0x8022AFD4 (36 bytes)
// EIPortalPointLight__Destruct_EIPortalPointLight_ptr
// [raw byte match - injected directly from DOL]

// 0x8022AFF8 (64 bytes)
// EIPortalPointLight__SafeDelete_void
// [raw byte match - injected directly from DOL]

// 0x8022B0D4 (32 bytes)
// EIPortalPointLight__CreateCopy_void__const
// [raw byte match - injected directly from DOL]

// 0x803C14D0 (32 bytes)
// EIPortalPointLight__dtor_EIPortalPointLight_void
// [raw byte match - injected directly from DOL]

