#include "types.h"
#include "stub_classes.h"
// Auto-generated matching stubs for ELiveMode (branching leaf functions)
// Generated by auto_match_branch.py
// 1 functions, 24 bytes

// 0x80090070 (24 bytes)
bool ELiveMode::IsRunningIntroCamera() { return *(int*)((char*)this + 0xC) != 0; }

