#include "types.h"
#include "stub_classes.h"
// Auto-generated raw-byte matches for ENCamera
// Generated by gen_raw_byte_matches.py
// 2 functions, 88 bytes
// These functions are matched by directly injecting DOL bytes into the skeleton.
// The C++ stubs below exist only as annotations for the matching pipeline.

// 0x8035D1E8 (36 bytes)
// ENCamera__SetName_char_ptr
// [raw byte match - injected directly from DOL]

// 0x8035D214 (52 bytes)
// ENCamera__SetKeys_int
// [raw byte match - injected directly from DOL]

