#include "types.h"
// Inline asm leaf matches for ENgcTextureBase
// 1 functions, 200 bytes

#include "types.h"
// Auto-generated inline asm decomp stubs for ENgcTextureBase
// Generated by gen_asm_decomp.py
// 9 functions, 2252 bytes
//
// Each function has its original C++ signature with the body as inline PPC asm.
// These can be incrementally replaced with real C++ as decompilation progresses.

class ETextureDef;

class ENgcTextureBase {
public:
    ENgcTextureBase(unsigned int, int, int);
    ~ENgcTextureBase(void);
    void FlushImageMemoryRange(bool);
    void Create(ETextureDef &);
    void Select(int, int);
    void UpdateMipLevel(int, int &, int &);
    void UpdateEnd(void);
    void ComputeMipLevelOffset(int, int &, int &);
    void ClearSwizzleFlag(void);
};


// 0x803503A8 (200 bytes)
// ENgcTextureBase::ComputeMipLevelOffset(int, int &, int &)
__attribute__((noreturn))
void ENgcTextureBase::ComputeMipLevelOffset(int, int &, int &) {
    __asm__ __volatile__(
        "lhz	8,16(3)\n"
        "li	12,0\n"
        "lbz	11,124(3)\n"
        "addi	0,8,-1\n"
        "lhz	10,18(3)\n"
        "add	0,0,11\n"
        "neg	11,11\n"
        "addi	9,10,-1\n"
        "and	0,0,11\n"
        "stw	0,0(5)\n"
        "lbz	0,125(3)\n"
        "add	9,9,0\n"
        "neg	0,0\n"
        "and	9,9,0\n"
        "stw	9,0(6)\n"
        "lbz	7,26(3)\n"
        "cmpwi	7,24\n"
        "bne	.L_803503F4\n"
        "li	7,32\n"
        ".L_803503F4:\n"
        "cmpw	12,4\n"
        "bge	.L_80350468\n"
        "mtctr	4\n"
        ".L_80350400:\n"
        "lwz	9,0(6)\n"
        "lwz	0,0(5)\n"
        "mullw	0,0,9\n"
        "mullw	9,0,7\n"
        "addic.	11,9,7\n"
        "bge	.L_8035041C\n"
        "addi	11,9,14\n"
        ".L_8035041C:\n"
        "lbz	9,124(3)\n"
        "srawi	8,8,1\n"
        "addi	0,8,-1\n"
        "srawi	10,10,1\n"
        "add	0,0,9\n"
        "srawi	11,11,3\n"
        "neg	9,9\n"
        "addi	11,11,31\n"
        "and	0,0,9\n"
        "clrrwi	11,11,5\n"
        "stw	0,0(5)\n"
        "addi	9,10,-1\n"
        "add	12,12,11\n"
        "lbz	0,125(3)\n"
        "add	9,9,0\n"
        "neg	0,0\n"
        "and	9,9,0\n"
        "stw	9,0(6)\n"
        "bdnz	.L_80350400\n"
        ".L_80350468:\n"
        "mr	3,12\n"
        "blr\n"
    );
}

