#include "types.h"
#include "stub_classes.h"
// Auto-generated raw-byte matches for ENgcShader
// Generated by gen_raw_byte_matches.py
// 5 functions, 192 bytes
// These functions are matched by directly injecting DOL bytes into the skeleton.
// The C++ stubs below exist only as annotations for the matching pipeline.

// 0x8034DC04 (60 bytes)
// ENgcShader__ENgcShader_void
// [raw byte match - injected directly from DOL]

// 0x8034DF80 (32 bytes)
// ENgcShader__ChangeMaterial_EMaterial_ref
// [raw byte match - injected directly from DOL]

// 0x8034DFA0 (48 bytes)
// ENgcShader__op_new_unsigned_int
// [raw byte match - injected directly from DOL]

// 0x8034DFD0 (8 bytes)
// ENgcShader__op_new_unsigned_int__void_ptr
// [raw byte match - injected directly from DOL]

// 0x8034DFD8 (44 bytes)
// ENgcShader__op_delete_void_ptr
// [raw byte match - injected directly from DOL]

