#include "types.h"
// Inline asm leaf matches for ENgcAudioSampleManager
// 2 functions, 416 bytes

#include "types.h"
// Auto-generated inline asm decomp stubs for ENgcAudioSampleManager
// Generated by gen_asm_decomp.py
// 9 functions, 2568 bytes
//
// Each function has its original C++ signature with the body as inline PPC asm.
// These can be incrementally replaced with real C++ as decompilation progresses.

class ARAMBlock;
class EFile;
class ERSampledata;

class ENgcAudioSampleManager {
public:
    ENgcAudioSampleManager(void);
    void AllocateAndLoadResource(EFile *, unsigned int, unsigned int);
    void OnDelRef(ERSampledata *);
    void heapInit(void);
    void heapAlloc(unsigned int);
    void heapResortSmaller(ARAMBlock *);
    void heapResortLarger(ARAMBlock *);
    void heapFree(unsigned int);
    void heapWalk(bool) const;
};


// 0x8032D42C (200 bytes)
// ENgcAudioSampleManager::heapResortSmaller(ARAMBlock *)
__attribute__((noreturn))
void ENgcAudioSampleManager::heapResortSmaller(ARAMBlock *) {
    __asm__ __volatile__(
        "lwz	9,4(4)\n"
        "lwz	11,16(4)\n"
        "lwz	0,16(9)\n"
        "lwz	10,8(4)\n"
        "subf	8,11,0\n"
        "cmpwi	10,0\n"
        "beqlr\n"
        ".L_8032D448:\n"
        "lwz	9,4(10)\n"
        "lwz	11,16(10)\n"
        "lwz	0,16(9)\n"
        "subf	0,11,0\n"
        "cmplw	0,8\n"
        "bgt	.L_8032D4A4\n"
        "lwz	9,8(4)\n"
        "cmpw	10,9\n"
        "beqlr\n"
        "lwz	0,12(4)\n"
        "stw	0,12(9)\n"
        "cmpwi	0,0\n"
        "beq	.L_8032D488\n"
        "lwz	9,12(4)\n"
        "lwz	0,8(4)\n"
        "stw	0,8(9)\n"
        ".L_8032D488:\n"
        "stw	10,8(4)\n"
        "lwz	0,12(10)\n"
        "stw	0,12(4)\n"
        "stw	4,12(10)\n"
        "lwz	9,12(4)\n"
        "stw	4,8(9)\n"
        "blr\n"
        ".L_8032D4A4:\n"
        "lwz	10,8(10)\n"
        "cmpwi	10,0\n"
        "bne	.L_8032D448\n"
        "lwz	0,12(4)\n"
        "lwz	9,8(4)\n"
        "cmpwi	0,0\n"
        "stw	0,12(9)\n"
        "beq	.L_8032D4D0\n"
        "lwz	9,12(4)\n"
        "lwz	0,8(4)\n"
        "stw	0,8(9)\n"
        ".L_8032D4D0:\n"
        "stw	10,8(4)\n"
        "lwz	0,3364(3)\n"
        "cmpwi	0,0\n"
        "stw	0,12(4)\n"
        "beq	.L_8032D4EC\n"
        "lwz	9,3364(3)\n"
        "stw	4,8(9)\n"
        ".L_8032D4EC:\n"
        "stw	4,3364(3)\n"
        "blr\n"
    );
}

// 0x8032D4F4 (216 bytes)
// ENgcAudioSampleManager::heapResortLarger(ARAMBlock *)
__attribute__((noreturn))
void ENgcAudioSampleManager::heapResortLarger(ARAMBlock *) {
    __asm__ __volatile__(
        "lwz	9,4(4)\n"
        "lwz	11,16(4)\n"
        "lwz	0,16(9)\n"
        "lwz	10,12(4)\n"
        "subf	7,11,0\n"
        "cmpwi	10,0\n"
        "beqlr\n"
        ".L_8032D510:\n"
        "lwz	9,4(10)\n"
        "lwz	11,16(10)\n"
        "lwz	0,16(9)\n"
        "subf	0,11,0\n"
        "cmplw	0,7\n"
        "blt	.L_8032D57C\n"
        "lwz	0,12(4)\n"
        "cmpw	10,0\n"
        "beqlr\n"
        "lwz	9,8(4)\n"
        "cmpwi	9,0\n"
        "beq	.L_8032D548\n"
        "stw	0,12(9)\n"
        "b	.L_8032D54C\n"
        ".L_8032D548:\n"
        "stw	0,3364(3)\n"
        ".L_8032D54C:\n"
        "lwz	9,12(4)\n"
        "cmpwi	9,0\n"
        "beq	.L_8032D560\n"
        "lwz	0,8(4)\n"
        "stw	0,8(9)\n"
        ".L_8032D560:\n"
        "stw	10,12(4)\n"
        "lwz	0,8(10)\n"
        "stw	0,8(4)\n"
        "stw	4,8(10)\n"
        "lwz	9,8(4)\n"
        "stw	4,12(9)\n"
        "blr\n"
        ".L_8032D57C:\n"
        "mr	8,10\n"
        "lwz	10,12(8)\n"
        "cmpwi	10,0\n"
        "bne	.L_8032D510\n"
        "lwz	9,8(4)\n"
        "cmpwi	9,0\n"
        "beq	.L_8032D5A4\n"
        "lwz	0,12(4)\n"
        "stw	0,12(9)\n"
        "b	.L_8032D5AC\n"
        ".L_8032D5A4:\n"
        "lwz	0,12(4)\n"
        "stw	0,3364(3)\n"
        ".L_8032D5AC:\n"
        "lwz	9,12(4)\n"
        "li	11,0\n"
        "lwz	0,8(4)\n"
        "stw	0,8(9)\n"
        "stw	4,12(8)\n"
        "stw	8,8(4)\n"
        "stw	11,12(4)\n"
        "blr\n"
    );
}

