#include "types.h"
#include "stub_classes.h"
// Auto-generated raw-byte matches for ENgcController
// Generated by gen_raw_byte_matches.py
// 3 functions, 96 bytes
// These functions are matched by directly injecting DOL bytes into the skeleton.
// The C++ stubs below exist only as annotations for the matching pipeline.

// 0x803C70FC (32 bytes)
// ENgcController__dtor_ENgcController_void
// [raw byte match - injected directly from DOL]

// 0x803C7234 (32 bytes)
// ENgcController__IsMotorOneActive_void__const
// [raw byte match - injected directly from DOL]

// 0x803C7254 (32 bytes)
// ENgcController__IsMotorTwoActive_void__const
// [raw byte match - injected directly from DOL]

