#include "types.h"
#include "stub_classes.h"
// Auto-generated raw-byte matches for ENgcControllerManager
// Generated by gen_raw_byte_matches.py
// 2 functions, 116 bytes
// These functions are matched by directly injecting DOL bytes into the skeleton.
// The C++ stubs below exist only as annotations for the matching pipeline.

// 0x8032DC10 (64 bytes)
// ENgcControllerManager__ENgcControllerManager_void
// [raw byte match - injected directly from DOL]

// 0x8032DC50 (52 bytes)
// ENgcControllerManager__dtor_ENgcControllerManager_void
// [raw byte match - injected directly from DOL]

