#include "types.h"
#include "stub_classes.h"
// Auto-generated raw-byte matches for EQuickdataManager
// Generated by gen_raw_byte_matches.py
// 5 functions, 180 bytes
// These functions are matched by directly injecting DOL bytes into the skeleton.
// The C++ stubs below exist only as annotations for the matching pipeline.

// 0x8032526C (32 bytes)
// EQuickdataManager__GetHeap_void
// [raw byte match - injected directly from DOL]

// 0x803254F8 (32 bytes)
// EQuickdataManager__AddRef_unsigned_int__EFile_ptr__int
// [raw byte match - injected directly from DOL]

// 0x80325518 (32 bytes)
// EQuickdataManager__AddRef_char_ptr__EFile_ptr__int
// [raw byte match - injected directly from DOL]

// 0x80325590 (52 bytes)
// EQuickdataManager__SetCurrentLanguage_int
// [raw byte match - injected directly from DOL]

// 0x803C6450 (32 bytes)
// EQuickdataManager__dtor_EQuickdataManager_void
// [raw byte match - injected directly from DOL]

