#include "types.h"
#include "stub_classes.h"
// Auto-generated matching constructors for ERAmbientSound
// Generated by gen_ctor_matches.py (inline asm)
// 1 functions, 108 bytes

// 0x80366998 (108 bytes)
__attribute__((noreturn))
ERAmbientSound::ERAmbientSound() {
    __asm__ __volatile__(
        "stwu	1,-16(1)\n""mr	9,3\n""li	0,0\n""lis	11,-32702\n""stw	0,36(9)\n""lfs	0,12772(11)\n""addi	10,9,44\n""stw	0,40(9)\n""stw	0,4(10)\n""stfs	0,20(9)\n""stb	0,33(9)\n""stfs	0,0(9)\n""stfs	0,4(9)\n""stfs	0,8(9)\n""stfs	0,12(9)\n""stfs	0,16(9)\n""stb	0,24(9)\n""stb	0,25(9)\n""stb	0,26(9)\n""stb	0,27(9)\n""stb	0,28(9)\n""stb	0,29(9)\n""stb	0,30(9)\n""stb	0,31(9)\n""stb	0,32(9)\n""addi	1,1,16\n""blr\n"
    );
    __builtin_unreachable();
}
