#include "types.h"
#include "stub_classes.h"
// Auto-generated raw-byte matches for EResourceManager
// Generated by gen_raw_byte_matches.py
// 20 functions, 888 bytes
// These functions are matched by directly injecting DOL bytes into the skeleton.
// The C++ stubs below exist only as annotations for the matching pipeline.

// 0x803267D8 (60 bytes)
// EResourceManager__GetRef_char_ptr
// [raw byte match - injected directly from DOL]

// 0x80326920 (60 bytes)
// EResourceManager__PreloadResource_char_ptr
// [raw byte match - injected directly from DOL]

// 0x80326BE4 (36 bytes)
// EResourceManager__AddResource_EResource_ptr__unsigned_int
// [raw byte match - injected directly from DOL]

// 0x80326CF8 (36 bytes)
// EResourceManager__AddRef_unsigned_int__EFile_ptr__int
// [raw byte match - injected directly from DOL]

// 0x80326DB4 (44 bytes)
// EResourceManager__AddRefAsync_unsigned_int
// [raw byte match - injected directly from DOL]

// 0x80326DE0 (28 bytes)
// EResourceManager__GetIds_unsigned_int_ptrr__int_ref
// [raw byte match - injected directly from DOL]

// 0x80326DFC (36 bytes)
// EResourceManager__RefreshResources_void
// [raw byte match - injected directly from DOL]

// 0x80326F24 (60 bytes)
// EResourceManager__Refresh_char_ptr
// [raw byte match - injected directly from DOL]

// 0x803270D0 (60 bytes)
// EResourceManager__DelRefAsync_char_ptr
// [raw byte match - injected directly from DOL]

// 0x803273D0 (56 bytes)
// EResourceManager__GetPos_unsigned_int
// [raw byte match - injected directly from DOL]

// 0x80327408 (60 bytes)
// EResourceManager__GetSize_unsigned_int
// [raw byte match - injected directly from DOL]

// 0x80327444 (48 bytes)
// EResourceManager__IsValid_unsigned_int
// [raw byte match - injected directly from DOL]

// 0x803274F4 (60 bytes)
// EResourceManager__IsLoaded_char_ptr
// [raw byte match - injected directly from DOL]

// 0x8032758C (32 bytes)
// EResourceManager__GetHeap_void
// [raw byte match - injected directly from DOL]

// 0x803275F4 (60 bytes)
// EResourceManager__FreeUnreferencedResources_void
// [raw byte match - injected directly from DOL]

// 0x80327630 (36 bytes)
// EResourceManager__GetUnreferencedResourceCount_void
// [raw byte match - injected directly from DOL]

// 0x80327ECC (8 bytes)
// EResourceManager__IsInitialized_void
// [raw byte match - injected directly from DOL]

// 0x80327EDC (52 bytes)
// EResourceManager__CanCache_EResource_ptr
// [raw byte match - injected directly from DOL]

// 0x80327F10 (32 bytes)
// EResourceManager__LookupId_EResourceManager_ptr__unsigned_int__unsigned_int_ref__unsigned_int_ref
// [raw byte match - injected directly from DOL]

// 0x803C6F88 (24 bytes)
// EResourceManager__ResourceIndexRecord__CheckPos_EResourceManager__ResourceIndexRecord_ref__EResourceManager__ResourceIndexRecord_ref
// [raw byte match - injected directly from DOL]

