#include "types.h"
#include "stub_classes.h"
// Auto-generated matching constructors for ERTQuantize
// Generated by gen_ctor_matches.py (inline asm)
// 1 functions, 56 bytes

// 0x802CE6E4 (56 bytes)
__attribute__((noreturn))
ERTQuantize::ERTQuantize() {
    __asm__ __volatile__(
        "lis	9,-32697\n""li	0,256\n""mr	11,3\n""addi	9,9,-24072\n""mtctr	0\n""stw	9,0(11)\n"".L_802CE6FC:\n""bdnz	.L_802CE6FC\n""li	9,0\n""li	0,1\n""sth	0,4234(11)\n""mr	3,11\n""stw	9,4236(11)\n""stw	9,4240(11)\n""blr\n"
    );
    __builtin_unreachable();
}
