#include "types.h"
// Inline asm leaf matches for ESimsCam
// 2 functions, 168 bytes

#include "types.h"
// Auto-generated inline asm decomp stubs for ESimsCam
// Generated by gen_asm_decomp.py
// 45 functions, 18212 bytes
//
// Each function has its original C++ signature with the body as inline PPC asm.
// These can be incrementally replaced with real C++ as decompilation progresses.

class E3DWindow;
class ERC;
class cXObject;

struct CameraNoiseSetting {};
struct EVec3 {};

class ESimsCam {
public:
    ESimsCam(int);
    ~ESimsCam(void);
    void GetCurZoomRatio(void);
    void GetNearPlane(void);
    void GetFov(void);
    void ForceFullScreenViewport(void);
    void Reset(void);
    void SetState(int);
    void SetMode(int);
    void FollowPlayerInteractor(int);
    void Update(void);
    void ApplyPan(float);
    void ApplyZoom(float);
    void HandleRotation(void);
    void HandleZoom(void);
    void UpdateWin(void);
    void CalcEyePosition(EVec3 &, int &);
    void ResetPos(float);
    void FollowSimStiff(void);
    void IsInDeadZone(EVec3 &) const;
    void InterpolateActualCameraParamsToTarget(float);
    void CenterOnSelectedSim(void);
    void SetPosAndReset(EVec3 &, EVec3 &, EVec3 &);
    void SetPos(EVec3 &, EVec3 &, EVec3 &);
    void ForcePosition(EVec3 &, EVec3 &, EVec3 &);
    void ForceTarget(EVec3 &);
    void PointOutsideScreenRect(EVec3 &, float, float, float, float);
    void ValidateCursorPosition(int, EVec3 *);
    void CalRoomId(EVec3 &);
    void GetContainingRoomId(EVec3 &);
    void SetWinPos(E3DWindow &);
    void CalcPitch(EVec3 &);
    void CalcZAxisTheta(EVec3 &);
    void GetCursorPos(void);
    void GetObjectPosition(EVec3 *, cXObject *);
    void GetObjectOrientation(EVec3 *, cXObject *);
    void DrawDebug(ERC *);
    void CursorNotActive(void);
    void SetActiveNoiseSetting(CameraNoiseSetting);
    void ApplyNoise(EVec3, EVec3, EVec3);
    void DrawCameraInfo(ERC *);
    void ReadControllerZoom(void);
    void ReadControllerRotation(void);
    ESimsCam(void);
    void* operator new(unsigned int);
};


// 0x80016728 (72 bytes)
// ESimsCam::GetCurZoomRatio(void)
__attribute__((noreturn))
void ESimsCam::GetCurZoomRatio(void) {
    __asm__ __volatile__(
        "lwz	9,0(3)\n"
        "lis	11,-32707\n"
        "lfs	13,1096(3)\n"
        "lfs	12,40(9)\n"
        "lfs	0,44(9)\n"
        "fsubs	13,13,12\n"
        "lfs	1,-7424(11)\n"
        "fsubs	0,0,12\n"
        "fdivs	13,13,0\n"
        "fcmpu	cr0,13,1\n"
        "bltlr\n"
        "lis	9,-32707\n"
        "fmr	1,13\n"
        "lfs	0,-7420(9)\n"
        "fcmpu	cr0,13,0\n"
        "blelr\n"
        "fmr	1,0\n"
        "blr\n"
    );
}

// 0x80016BD4 (96 bytes)
// ESimsCam::SetMode(ESimsCam::CameraMode)
__attribute__((noreturn))
void ESimsCam::SetMode(int) {
    __asm__ __volatile__(
        "lis	9,-32697\n"
        "lwz	0,4(3)\n"
        "addi	9,9,24012\n"
        "addi	9,9,280\n"
        "slwi	0,0,2\n"
        "lwzx	9,9,0\n"
        "cmpwi	9,0\n"
        "beq	.L_80016C18\n"
        "lwz	0,352(9)\n"
        "li	9,0\n"
        "cmpwi	0,0\n"
        "beq	.L_80016C10\n"
        "cmpwi	0,8\n"
        "beq	.L_80016C10\n"
        "li	9,1\n"
        ".L_80016C10:\n"
        "cmpwi	9,0\n"
        "bnelr\n"
        ".L_80016C18:\n"
        "cmpwi	4,2\n"
        "bne	.L_80016C24\n"
        "lwz	4,976(3)\n"
        ".L_80016C24:\n"
        "lwz	0,972(3)\n"
        "stw	4,972(3)\n"
        "stw	0,976(3)\n"
        "blr\n"
    );
}

