#include "types.h"
#include "stub_classes.h"
// Auto-generated matching constructors for ESpriteRender
// Generated by gen_ctor_matches.py (inline asm)
// 1 functions, 208 bytes

// 0x80035460 (208 bytes)
__attribute__((noreturn))
ESpriteRender::ESpriteRender() {
    __asm__ __volatile__(
        "lis	11,-32698\n""li	0,0\n""mr	10,3\n""addi	11,11,-18840\n""stw	11,232(10)\n""addi	9,10,164\n""stw	0,164(10)\n""lis	8,-32707\n""stw	0,4(9)\n""lis	11,-32765\n""stw	0,8(9)\n""addi	11,11,23560\n""stw	0,12(9)\n""stw	0,16(9)\n""stw	0,20(9)\n""stw	0,24(9)\n""stw	0,28(9)\n""stw	0,32(9)\n""stw	0,36(9)\n""stw	0,40(9)\n""lfs	0,5368(8)\n""stw	0,52(9)\n""stfs	0,48(9)\n""stfs	0,44(9)\n""stw	0,0(10)\n""stw	0,4(10)\n""stw	0,8(10)\n""stw	0,16(10)\n""stw	0,52(10)\n""stw	0,24(10)\n""stw	0,32(10)\n""stw	0,164(10)\n""stw	0,4(9)\n""stw	0,8(9)\n""stw	0,12(9)\n""stw	0,16(9)\n""stw	0,20(9)\n""stw	0,24(9)\n""stw	0,28(9)\n""stw	0,32(9)\n""stw	0,36(9)\n""stw	0,52(9)\n""stw	11,184(10)\n""stw	0,48(10)\n""stw	10,188(10)\n""stw	0,12(10)\n""stw	0,20(10)\n""stw	0,28(10)\n""stw	0,36(10)\n""stw	0,40(10)\n""stw	0,44(10)\n""blr\n"
    );
    __builtin_unreachable();
}
