#include "types.h"
#include "stub_classes.h"
// Auto-generated raw-byte matches for ESubModelShader
// Generated by gen_raw_byte_matches.py
// 8 functions, 400 bytes
// These functions are matched by directly injecting DOL bytes into the skeleton.
// The C++ stubs below exist only as annotations for the matching pipeline.

// 0x802FBA2C (56 bytes)
// ESubModelShader__VertexDataAllocation_int__char_ptr__int__char_ptr
// [raw byte match - injected directly from DOL]

// 0x802FBA64 (64 bytes)
// ESubModelShader__VertexDataDeallocation_void_ptr__bool
// [raw byte match - injected directly from DOL]

// 0x802FBAA4 (40 bytes)
// ESubModelShader__MorphDataAllocation_int__int
// [raw byte match - injected directly from DOL]

// 0x802FBACC (40 bytes)
// ESubModelShader__MorphDataDeallocation_void_ptr
// [raw byte match - injected directly from DOL]

// 0x802FBBC8 (64 bytes)
// ESubModelShader__DelRefSubResources_void
// [raw byte match - injected directly from DOL]

// 0x802FD3E8 (20 bytes)
// ESubModelShader__UnRegisterMorphTarget_int
// [raw byte match - injected directly from DOL]

// 0x802FF7D0 (64 bytes)
// ESubModelShader__CanColorBeModified_void
// [raw byte match - injected directly from DOL]

// 0x802FF810 (52 bytes)
// ESubModelShader__GetModifiableColor_unsigned_int
// [raw byte match - injected directly from DOL]

