#include "types.h"
#include "stub_classes.h"
// Auto-generated raw-byte matches for ETexture
// Generated by gen_raw_byte_matches.py
// 9 functions, 248 bytes
// These functions are matched by directly injecting DOL bytes into the skeleton.
// The C++ stubs below exist only as annotations for the matching pipeline.

// 0x8036507C (48 bytes)
// ETexture__op_new_unsigned_int
// [raw byte match - injected directly from DOL]

// 0x803650AC (8 bytes)
// ETexture__op_new_unsigned_int__void_ptr
// [raw byte match - injected directly from DOL]

// 0x803650B4 (44 bytes)
// ETexture__op_delete_void_ptr
// [raw byte match - injected directly from DOL]

// 0x803650F0 (8 bytes)
// ETexture__GetXSize_void
// [raw byte match - injected directly from DOL]

// 0x803650F8 (8 bytes)
// ETexture__GetYSize_void
// [raw byte match - injected directly from DOL]

// 0x80365110 (8 bytes)
// ETexture__GetPaletteSize_void
// [raw byte match - injected directly from DOL]

// 0x80365144 (52 bytes)
// ETexture__UpdatePaletteDeswizzled_void
// [raw byte match - injected directly from DOL]

// 0x803651A8 (44 bytes)
// ETexture__Test1_int__int__int__int
// [raw byte match - injected directly from DOL]

// 0x803651D4 (28 bytes)
// ETexture__IsValid_void
// [raw byte match - injected directly from DOL]

