#include "types.h"
#include "stub_classes.h"
// Auto-generated raw-byte matches for getBytesLoaded_char_ptr
// Generated by gen_raw_byte_matches.py
// 1 functions, 8 bytes
// These functions are matched by directly injecting DOL bytes into the skeleton.
// The C++ stubs below exist only as annotations for the matching pipeline.

// 0x800067E0 (8 bytes)
// getBytesLoaded_char_ptr__AptGetBytesEnum
// [raw byte match - injected directly from DOL]

