#include "types.h"
#include "stub_classes.h"
// Auto-generated raw-byte matches for InteractionHelper
// Generated by gen_raw_byte_matches.py
// 2 functions, 76 bytes
// These functions are matched by directly injecting DOL bytes into the skeleton.
// The C++ stubs below exist only as annotations for the matching pipeline.

// 0x80190DC0 (52 bytes)
// InteractionHelper__GetCount_IHRecord_ptr
// [raw byte match - injected directly from DOL]

// 0x80190DF4 (24 bytes)
// InteractionHelper__GetNext_IHRecord_ptr
// [raw byte match - injected directly from DOL]

