#include "types.h"
#include "stub_classes.h"
// Auto-generated matching constructors for InventoryItems
// Generated by gen_ctor_matches.py (inline asm)
// 1 functions, 32 bytes

// 0x8004A31C (32 bytes)
__attribute__((noreturn))
BBI::InventoryItems::InventoryItems() {
    __asm__ __volatile__(
        "li	11,36\n""li	0,0\n""mtctr	11\n""addi	9,3,140\n"".L_8004A32C:\n""stw	0,0(9)\n""addi	9,9,-4\n""bdnz	.L_8004A32C\n""blr\n"
    );
    __builtin_unreachable();
}
