#include "types.h"
#include "stub_classes.h"
// Auto-generated raw-byte matches for LiveModeInitState
// Generated by gen_raw_byte_matches.py
// 2 functions, 116 bytes
// These functions are matched by directly injecting DOL bytes into the skeleton.
// The C++ stubs below exist only as annotations for the matching pipeline.

// 0x8008CA18 (64 bytes)
// LiveModeInitState__DatasetFinishAddRefAsync_void
// [raw byte match - injected directly from DOL]

// 0x803A09E0 (52 bytes)
// LiveModeInitState__dtor_LiveModeInitState_void
// [raw byte match - injected directly from DOL]

