#include "types.h"
#include "stub_classes.h"
// Auto-generated raw-byte matches for localConvertToWide_unsigned_wchar_t_ptr
// Generated by gen_raw_byte_matches.py
// 2 functions, 88 bytes
// These functions are matched by directly injecting DOL bytes into the skeleton.
// The C++ stubs below exist only as annotations for the matching pipeline.

// 0x800A008C (44 bytes)
// localConvertToWide_unsigned_wchar_t_ptr__char_ptr
// [raw byte match - injected directly from DOL]

// 0x800A6CB8 (44 bytes)
// localConvertToWide_unsigned_wchar_t_ptr__char_ptr_1
// [raw byte match - injected directly from DOL]

