#include "types.h"
// Inline asm leaf matches for MorphUtilities
// 2 functions, 332 bytes

#include "types.h"
// Auto-generated inline asm decomp stubs for MorphUtilities
// Generated by gen_asm_decomp.py
// 8 functions, 2476 bytes
//
// Each function has its original C++ signature with the body as inline PPC asm.
// These can be incrementally replaced with real C++ as decompilation progresses.

class CasSimDescriptionS2C;

class MorphUtilities {
public:
    void ApplyAllMorphs(CasSimDescriptionS2C &);
    void ApplyMorph(int, float);
    void ApplyMorphHead(float);
    void MorphLatticeOnHead(unsigned int, float, unsigned int);
    void MorphLatticeOnBodyPart(unsigned int, float, unsigned int);
    void GetFacialMorphTargetIndexAndValue(float, float &, int &, float &, int &);
    void GetBodyLatticeIndexAndValue(float, float &, int &, float &, int &);
    void GetHeadLatticeIndexAndValue(float, float &, int &, float &, int &);
};


// 0x800583AC (200 bytes)
// MorphUtilities::GetFacialMorphTargetIndexAndValue(float, float &, int &, float &, int &)
__attribute__((noreturn))
void MorphUtilities::GetFacialMorphTargetIndexAndValue(float, float &, int &, float &, int &) {
    __asm__ __volatile__(
        "lis	9,-32707\n"
        "li	0,-1\n"
        "lfs	0,15444(9)\n"
        "stw	0,0(5)\n"
        "stfs	0,0(4)\n"
        "fcmpu	cr0,1,0\n"
        "stw	0,0(7)\n"
        "stfs	0,0(6)\n"
        "cror	so,eq,gt\n"
        "bns	.L_800583F8\n"
        "lis	9,-32707\n"
        "lfs	0,15448(9)\n"
        "fcmpu	cr0,1,0\n"
        "bge	.L_800583F8\n"
        "li	0,0\n"
        "fsubs	0,0,1\n"
        ".L_800583EC:\n"
        "stw	0,0(5)\n"
        "stfs	0,0(4)\n"
        "blr\n"
        ".L_800583F8:\n"
        "lis	9,-32707\n"
        "lfs	13,15448(9)\n"
        "fcmpu	cr0,1,13\n"
        "cror	so,eq,gt\n"
        "bns	.L_80058428\n"
        "lis	9,-32707\n"
        "lfs	0,15452(9)\n"
        "fcmpu	cr0,1,0\n"
        "bge	.L_80058428\n"
        "li	0,1\n"
        "fsubs	0,1,13\n"
        "b	.L_800583EC\n"
        ".L_80058428:\n"
        "lis	9,-32707\n"
        "lfs	0,15452(9)\n"
        "fcmpu	cr0,1,0\n"
        "cror	so,eq,gt\n"
        "bnslr\n"
        "lis	9,-32707\n"
        "lfs	13,15456(9)\n"
        "fcmpu	cr0,1,13\n"
        "cror	so,eq,lt\n"
        "bnslr\n"
        "li	0,1\n"
        "fsubs	13,13,1\n"
        "stw	0,0(5)\n"
        "li	9,2\n"
        "stfs	13,0(4)\n"
        "fsubs	0,1,0\n"
        "stw	9,0(7)\n"
        "stfs	0,0(6)\n"
        "blr\n"
    );
}

// 0x80058474 (132 bytes)
// MorphUtilities::GetBodyLatticeIndexAndValue(float, float &, int &, float &, int &)
__attribute__((noreturn))
void MorphUtilities::GetBodyLatticeIndexAndValue(float, float &, int &, float &, int &) {
    __asm__ __volatile__(
        "li	0,0\n"
        "lis	9,-32707\n"
        "stw	0,0(5)\n"
        "lfs	0,15460(9)\n"
        "li	0,-1\n"
        "stw	0,0(7)\n"
        "stfs	0,0(4)\n"
        "fcmpu	cr0,1,0\n"
        "stfs	0,0(6)\n"
        "cror	so,eq,gt\n"
        "bns	.L_800584C4\n"
        "lis	9,-32707\n"
        "lfs	0,15464(9)\n"
        "fcmpu	cr0,1,0\n"
        "bge	.L_800584C4\n"
        "li	0,1\n"
        "fsubs	0,0,1\n"
        ".L_800584B8:\n"
        "stw	0,0(5)\n"
        "stfs	0,0(4)\n"
        "blr\n"
        ".L_800584C4:\n"
        "lis	9,-32707\n"
        "lfs	13,15464(9)\n"
        "fcmpu	cr0,1,13\n"
        "cror	so,eq,gt\n"
        "bnslr\n"
        "lis	9,-32707\n"
        "lfs	0,15468(9)\n"
        "fcmpu	cr0,1,0\n"
        "cror	so,eq,lt\n"
        "bnslr\n"
        "li	0,0\n"
        "fsubs	0,1,13\n"
        "b	.L_800584B8\n"
    );
}

