#include "types.h"
#include "stub_classes.h"
// Auto-generated raw-byte matches for MUStatesTransitionAutoSaveExisting
// Generated by gen_raw_byte_matches.py
// 1 functions, 52 bytes
// These functions are matched by directly injecting DOL bytes into the skeleton.
// The C++ stubs below exist only as annotations for the matching pipeline.

// 0x800940D4 (52 bytes)
// MUStatesTransitionAutoSaveExisting__dtor_MUStatesTransitionAutoSaveExisting_void
// [raw byte match - injected directly from DOL]

