#include "types.h"
// Inline asm leaf matches for Neighbor
// 3 functions, 416 bytes

#include "types.h"
// Auto-generated inline asm decomp stubs for Neighbor
// Generated by gen_asm_decomp.py
// 39 functions, 13740 bytes
//
// Each function has its original C++ signature with the body as inline PPC asm.
// These can be incrementally replaced with real C++ as decompilation progresses.

class ENeighborhoodCustomChar;
class ObjSelector;
class ReconBuffer;

struct tRelationshipType {};

class Neighbor {
public:
    Neighbor(void);
    ~Neighbor(void);
    Neighbor(short, ObjSelector *);
    Neighbor(Neighbor &);
    void operator=(Neighbor &);
    void GetNumPersistentDataFields(void);
    void DoStream(ReconBuffer *, int);
    void GetFamily(void);
    void IsCharacter(void);
    void RecalculateRelationshipData(void);
    void RelCountsAsRel(tRelationshipType, tRelationshipType);
    void CalculateRelationshipLevel(int, int);
    void CalculateRelationshipLevel(Neighbor *);
    void CountRelationshipsOfType(tRelationshipType);
    void IsMarriedTo(Neighbor *) const;
    void GetRelationshipById(int, int *);
    void AdjustRelationship(Neighbor *, int);
    void CopyRelationships(Neighbor *);
    void LoadFromCharacter(ENeighborhoodCustomChar &);
    void SaveToCharacter(ENeighborhoodCustomChar &);
    void InitDefaultValues(void);
    void InitWantsFears(void);
    void InitWantFearIcons(void);
    void SpawnWantFearDialog(unsigned int) const;
    void Notify(int &, bool);
    void FindDuplicateBookmark(int &) const;
    void ForceNewTree(unsigned short);
    void FindActiveSlotIndex(int &) const;
    void AdvanceBookmark(unsigned int);
    void FindBookmarkToReplace(unsigned int, unsigned int);
    void CalculateBookmarkAd(int &);
    void CalcAdMultiplier(float, float, float);
    void CalculateWantFearAd(int &, short);
    void MakeNewActiveBookmark(unsigned int);
    void SelectInactiveBookmark(bool, bool);
    void StartNewTree(unsigned int);
    void UpdateUIifNeeded(unsigned int, int);
    void ResetAllWantsAndFears(void);
    void ShuffleWantFear(int);
};


// 0x800C9E30 (224 bytes)
// Neighbor::RelCountsAsRel(tRelationshipType, tRelationshipType)
__attribute__((noreturn))
void Neighbor::RelCountsAsRel(tRelationshipType, tRelationshipType) {
    __asm__ __volatile__(
        "cmpwi	4,5\n"
        "beq	.L_800C9E88\n"
        "bgt	.L_800C9E68\n"
        "cmpwi	4,2\n"
        "beq	.L_800C9E90\n"
        "bgt	.L_800C9E54\n"
        "cmpwi	4,1\n"
        "beq	.L_800C9E88\n"
        "b	.L_800C9F08\n"
        ".L_800C9E54:\n"
        "cmpwi	4,3\n"
        "beq	.L_800C9EA0\n"
        "cmpwi	4,4\n"
        "beq	.L_800C9EB4\n"
        "b	.L_800C9F08\n"
        ".L_800C9E68:\n"
        "cmpwi	4,7\n"
        "beq	.L_800C9ED8\n"
        "blt	.L_800C9EC4\n"
        "cmpwi	4,8\n"
        "beq	.L_800C9EE8\n"
        "cmpwi	4,9\n"
        "beq	.L_800C9EF8\n"
        "b	.L_800C9F08\n"
        ".L_800C9E88:\n"
        "li	3,0\n"
        "blr\n"
        ".L_800C9E90:\n"
        "xori	3,3,2\n"
        "subfic	0,3,0\n"
        "adde	3,0,3\n"
        "blr\n"
        ".L_800C9EA0:\n"
        "addi	3,3,-2\n"
        "subfic	3,3,1\n"
        "li	3,0\n"
        "adde	3,3,3\n"
        "blr\n"
        ".L_800C9EB4:\n"
        "xori	3,3,4\n"
        "subfic	0,3,0\n"
        "adde	3,0,3\n"
        "blr\n"
        ".L_800C9EC4:\n"
        "addi	3,3,-6\n"
        "subfic	3,3,3\n"
        "li	3,0\n"
        "adde	3,3,3\n"
        "blr\n"
        ".L_800C9ED8:\n"
        "xori	3,3,7\n"
        "subfic	0,3,0\n"
        "adde	3,0,3\n"
        "blr\n"
        ".L_800C9EE8:\n"
        "xori	3,3,8\n"
        "subfic	0,3,0\n"
        "adde	3,0,3\n"
        "blr\n"
        ".L_800C9EF8:\n"
        "xori	3,3,9\n"
        "subfic	0,3,0\n"
        "adde	3,0,3\n"
        "blr\n"
        ".L_800C9F08:\n"
        "li	3,0\n"
        "blr\n"
    );
}

// 0x800CB2D0 (92 bytes)
// Neighbor::FindActiveSlotIndex(WantFear::Bookmark &) const
__attribute__((noreturn))
void Neighbor::FindActiveSlotIndex(int &) const {
    __asm__ __volatile__(
        "lwz	0,4(4)\n"
        "li	9,1\n"
        "cmpwi	0,0\n"
        "bne	.L_800CB2E4\n"
        "li	9,0\n"
        ".L_800CB2E4:\n"
        "cmpwi	9,0\n"
        "bne	.L_800CB2FC\n"
        "lha	3,-21222(13)\n"
        "blr\n"
        ".L_800CB2F4:\n"
        "mr	3,9\n"
        "blr\n"
        ".L_800CB2FC:\n"
        "li	0,7\n"
        "addi	3,3,408\n"
        "mtctr	0\n"
        "li	9,0\n"
        ".L_800CB30C:\n"
        "lwz	0,0(3)\n"
        "addi	3,3,4\n"
        "cmpw	0,4\n"
        "beq	.L_800CB2F4\n"
        "addi	9,9,1\n"
        "bdnz	.L_800CB30C\n"
        "lha	3,-21222(13)\n"
        "blr\n"
    );
}

// 0x800CB644 (100 bytes)
// Neighbor::CalcAdMultiplier(float, float, float)
__attribute__((noreturn))
void Neighbor::CalcAdMultiplier(float, float, float) {
    __asm__ __volatile__(
        "lis	9,-32706\n"
        "fmr	0,2\n"
        "lfs	13,-22816(9)\n"
        "li	0,0\n"
        "fcmpu	cr0,2,3\n"
        "ble	.L_800CB668\n"
        "fmr	2,3\n"
        "li	0,1\n"
        "fmr	3,0\n"
        ".L_800CB668:\n"
        "fcmpu	cr0,1,2\n"
        "ble	.L_800CB68C\n"
        "lis	9,-32706\n"
        "fcmpu	cr0,1,3\n"
        "lfs	13,-22812(9)\n"
        "bge	.L_800CB68C\n"
        "fsubs	13,3,2\n"
        "fsubs	0,1,2\n"
        "fdivs	13,0,13\n"
        ".L_800CB68C:\n"
        "cmpwi	0,0\n"
        "beq	.L_800CB6A0\n"
        "lis	9,-32706\n"
        "lfs	0,-22812(9)\n"
        "fsubs	13,0,13\n"
        ".L_800CB6A0:\n"
        "fmr	1,13\n"
        "blr\n"
    );
}

