#include "types.h"
#include "stub_classes.h"
// Auto-generated matching stubs for O2TTarget
// Generated by auto_match.py
// 2 functions, 32 bytes

// 0x801CEA60 (20 bytes)
void O2TTarget::SaveGame(char *, char *) { register int __r0 __asm__("r0") = 0; __asm__ __volatile__("" : "+r"(__r0)); register int __r9 __asm__("r9") = 1; __asm__ __volatile__("" : "+r"(__r9)); *(int*)((char*)this + 0x250) = __r0; *(int*)((char*)this + 0x90) = __r9; }

// 0x801CFA60 (12 bytes)
void O2TTarget::OnCancelDialog() { register int __r0 __asm__("r0") = 0; __asm__ __volatile__("" : "+r"(__r0)); *(int*)((char*)this + 0x250) = __r0; }
