#include "types.h"
#include "stub_classes.h"
// Auto-generated raw-byte matches for op_gt_BString2_ref
// Generated by gen_raw_byte_matches.py
// 2 functions, 88 bytes
// These functions are matched by directly injecting DOL bytes into the skeleton.
// The C++ stubs below exist only as annotations for the matching pipeline.

// 0x800A05AC (44 bytes)
// op_gt_BString2_ref__unsigned_wchar_t_ptr
// [raw byte match - injected directly from DOL]

// 0x800A05D8 (44 bytes)
// op_gt_BString2_ref__wchar_t
// [raw byte match - injected directly from DOL]

