#include "types.h"
#include "stub_classes.h"
// Auto-generated matching constructors for PAZBase
// Generated by gen_ctor_matches.py (inline asm)
// 1 functions, 168 bytes

// 0x801D00E8 (168 bytes)
__attribute__((noreturn))
PAZBase::PAZBase() {
    __asm__ __volatile__(
        "lis	11,-32698\n""mr	9,3\n""li	0,0\n""addi	11,11,-12328\n""stw	11,128(9)\n""addi	8,9,40\n""stw	0,0(9)\n""addi	7,9,56\n""stw	0,4(9)\n""addi	6,9,72\n""stw	0,8(9)\n""addi	5,9,88\n""stw	0,12(9)\n""addi	4,9,104\n""stw	0,16(9)\n""lis	11,-32698\n""stw	0,20(9)\n""li	10,1\n""stw	0,24(9)\n""addi	11,11,29304\n""stw	0,8(8)\n""stw	0,40(9)\n""stw	0,8(7)\n""stw	0,56(9)\n""stw	0,8(6)\n""stw	0,72(9)\n""stw	0,8(5)\n""stw	0,88(9)\n""stw	0,8(4)\n""stw	11,128(9)\n""stw	10,160(9)\n""stw	0,180(9)\n""stw	0,104(9)\n""stw	0,120(9)\n""stw	0,132(9)\n""stw	10,136(9)\n""stw	0,140(9)\n""stw	0,144(9)\n""stw	0,148(9)\n""stw	0,152(9)\n""stw	0,184(9)\n""blr\n"
    );
    __builtin_unreachable();
}
