#include "types.h"
// Inline asm leaf matches for PiecewiseFn
// 1 functions, 312 bytes

#include "types.h"
// Auto-generated inline asm decomp stubs for PiecewiseFn
// Generated by gen_asm_decomp.py
// 4 functions, 856 bytes
//
// Each function has its original C++ signature with the body as inline PPC asm.
// These can be incrementally replaced with real C++ as decompilation progresses.

class PiecewisePt;

class PiecewiseFn {
public:
    ~PiecewiseFn(void);
    void SetMaxPoints(int);
    void AddPoint(PiecewisePt &);
    void AddPointsFromText(char *);
};


// 0x8012CCE4 (312 bytes)
// PiecewiseFn::AddPoint(PiecewisePt &)
__attribute__((noreturn))
void PiecewiseFn::AddPoint(PiecewisePt &) {
    __asm__ __volatile__(
        "lwz	9,8(3)\n"
        "lwz	0,12(3)\n"
        "cmpw	9,0\n"
        "beqlr\n"
        "li	11,0\n"
        "li	8,0\n"
        "cmpw	11,9\n"
        "bge	.L_8012CD58\n"
        "lwz	10,0(3)\n"
        "lfs	0,0(4)\n"
        "lfs	13,0(10)\n"
        "fmr	12,0\n"
        "fcmpu	cr0,13,0\n"
        "beqlr\n"
        "fcmpu	cr0,12,13\n"
        "blt	.L_8012CD58\n"
        "mr	0,9\n"
        "fmr	13,12\n"
        "li	9,0\n"
        ".L_8012CD30:\n"
        "addi	11,8,1\n"
        "addi	9,9,8\n"
        "mr	8,11\n"
        "cmpw	11,0\n"
        "bge	.L_8012CD58\n"
        "lfsx	0,9,10\n"
        "fcmpu	cr0,0,13\n"
        "beqlr\n"
        "fcmpu	cr0,12,0\n"
        "bge	.L_8012CD30\n"
        ".L_8012CD58:\n"
        "lwz	9,8(3)\n"
        "addi	0,11,1\n"
        "slwi	6,11,3\n"
        "mr	8,9\n"
        "addi	9,9,1\n"
        "cmpw	8,0\n"
        "stw	9,8(3)\n"
        "blt	.L_8012CDA4\n"
        "slwi	7,8,3\n"
        ".L_8012CD7C:\n"
        "lwz	11,0(3)\n"
        "addi	8,8,-1\n"
        "cmpw	8,0\n"
        "add	11,7,11\n"
        "lwz	9,-8(11)\n"
        "lwz	10,-4(11)\n"
        "addi	7,7,-8\n"
        "stw	9,0(11)\n"
        "stw	10,4(11)\n"
        "bge	.L_8012CD7C\n"
        ".L_8012CDA4:\n"
        "lwz	9,0(3)\n"
        "li	7,0\n"
        "lwz	11,0(4)\n"
        "lwz	12,4(4)\n"
        "add	9,6,9\n"
        "stw	11,0(9)\n"
        "stw	12,4(9)\n"
        "lwz	0,8(3)\n"
        "addic.	9,0,-1\n"
        "blelr\n"
        "lis	9,-32706\n"
        "li	8,0\n"
        "lfs	12,-12696(9)\n"
        "li	6,0\n"
        ".L_8012CDDC:\n"
        "lwz	11,0(3)\n"
        "addi	7,7,1\n"
        "lwz	10,4(3)\n"
        "add	9,8,11\n"
        "lfsx	13,8,11\n"
        "lfs	0,8(9)\n"
        "addi	8,8,8\n"
        "fsubs	0,0,13\n"
        "fdivs	0,12,0\n"
        "stfsx	0,6,10\n"
        "addi	6,6,4\n"
        "lwz	9,8(3)\n"
        "addi	9,9,-1\n"
        "cmpw	7,9\n"
        "blt	.L_8012CDDC\n"
        "blr\n"
    );
}

