#include "types.h"
#include "stub_classes.h"
// Auto-generated matching stubs for PlumbBob (branching leaf functions)
// Generated by auto_match_branch.py
// 1 functions, 24 bytes

// 0x8005A468 (24 bytes)
void PlumbBob::ForceMorphToPlumbbob() { if (*(int*)((char*)this + 0x160) != 0) { *(int*)((char*)this + 0x160) = 0; } }

