#include "types.h"
#include "stub_classes.h"
// Auto-converted call wrapper stubs for PZ1Target
// Generated by convert_call_wrappers.py

// 0x801D1994 (116 bytes)
// Call wrapper [1bl_with_branch]: PAZBase::~PAZBase(void)
__attribute__((noreturn))
PZ1Target::~PZ1Target(void) {
    __asm__ __volatile__(
        "stwu	1,-8(1)\n"
        "mflr	0\n"
        "stw	0,12(1)\n"
        "lis	9,-32698\n"
        "lwz	0,188(3)\n"
        "addi	9,9,29160\n"
        "stw	9,128(3)\n"
        "cmpwi	0,30\n"
        "beq	.L_801D19E0\n"
        "bgt	.L_801D19C8\n"
        "cmpwi	0,26\n"
        "beq	.L_801D19D4\n"
        "b	.L_801D19F4\n"
        ".L_801D19C8:\n"
        "cmpwi	0,39\n"
        "beq	.L_801D19EC\n"
        "b	.L_801D19F4\n"
        ".L_801D19D4:\n"
        "lwz	0,140(3)\n"
        "stw	0,-29712(13)\n"
        "b	.L_801D19F4\n"
        ".L_801D19E0:\n"
        "lwz	0,140(3)\n"
        "stw	0,-29708(13)\n"
        "b	.L_801D19F4\n"
        ".L_801D19EC:\n"
        "lwz	0,140(3)\n"
        "stw	0,-29704(13)\n"
        ".L_801D19F4:\n"
        ".long 0x4bffe79d  /* bl PAZBase::~PAZBase(void) */\n"
        "lwz	0,12(1)\n"
        "mtlr	0\n"
        "addi	1,1,8\n"
        "blr\n"
    );
    __builtin_unreachable();
}
