#include "types.h"
// Inline asm leaf matches for RoomManager
// 3 functions, 484 bytes

#include "types.h"
// Auto-generated inline asm decomp stubs for RoomManager
// Generated by gen_asm_decomp.py
// 22 functions, 5908 bytes
//
// Each function has its original C++ signature with the body as inline PPC asm.
// These can be incrementally replaced with real C++ as decompilation progresses.

class CTilePt;
class Room;

class RoomManager {
public:
    RoomManager(void);
    ~RoomManager(void);
    void RoomScoreChanged(int);
    void RoomLightingChanged(int);
    void AllRoomsLightingChanged(void);
    void AllRoomsScoreChanged(void);
    void ComputeRooms(void);
    void PrintStats(void);
    void GetRoom(unsigned short);
    void GetNewRoom(unsigned short);
    void UpdateRooms(void);
    void OffsetWorld(CTilePt &);
    void ProcessDegenerateTile(CTilePt &, unsigned short, int);
    void ResolveDiagonal(CTilePt &, Room **, Room **, int *, int *);
    void ResolveDiagonal(CTilePt &, unsigned short *, unsigned short *, int *, int *);
    void ResetRooms(void);
    void GetOutsideAmbientLevel(void);
    void ClearRoomPartitions(void);
    void ResetRoomManager(void);
    void SetRoomIntensityScale(int, bool, float);
    void SetRoomIntensityColorScale(int, bool, int, float);
    void ChangeLightingGroup(unsigned short, unsigned short);
};


// 0x80136014 (156 bytes)
// RoomManager::RoomScoreChanged(int)
__attribute__((noreturn))
void RoomManager::RoomScoreChanged(int) {
    __asm__ __volatile__(
        "stwu	1,-32(1)\n"
        "sth	4,16(1)\n"
        "lwz	11,4(3)\n"
        "lwz	9,4(11)\n"
        "cmpwi	9,0\n"
        "beq	.L_80136054\n"
        "clrlwi	4,4,16\n"
        ".L_80136030:\n"
        "lhz	0,16(9)\n"
        "cmplw	0,4\n"
        "blt	.L_80136048\n"
        "mr	11,9\n"
        "lwz	9,8(11)\n"
        "b	.L_8013604C\n"
        ".L_80136048:\n"
        "lwz	9,12(9)\n"
        ".L_8013604C:\n"
        "cmpwi	9,0\n"
        "bne	.L_80136030\n"
        ".L_80136054:\n"
        "lwz	10,4(3)\n"
        "cmpw	11,10\n"
        "beq	.L_80136070\n"
        "lhz	9,16(1)\n"
        "lhz	0,16(11)\n"
        "cmplw	9,0\n"
        "bge	.L_80136074\n"
        ".L_80136070:\n"
        "mr	11,10\n"
        ".L_80136074:\n"
        "lwz	0,4(3)\n"
        "li	9,1\n"
        "stw	11,8(1)\n"
        "cmpw	11,0\n"
        "stw	0,24(1)\n"
        "bne	.L_80136090\n"
        "li	9,0\n"
        ".L_80136090:\n"
        "cmpwi	9,0\n"
        "beq	.L_801360A8\n"
        "lwz	9,20(11)\n"
        "li	0,1\n"
        "stw	0,132(9)\n"
        "stw	0,32(3)\n"
        ".L_801360A8:\n"
        "addi	1,1,32\n"
        "blr\n"
    );
}

// 0x801360B0 (156 bytes)
// RoomManager::RoomLightingChanged(int)
__attribute__((noreturn))
void RoomManager::RoomLightingChanged(int) {
    __asm__ __volatile__(
        "stwu	1,-32(1)\n"
        "sth	4,16(1)\n"
        "lwz	11,4(3)\n"
        "lwz	9,4(11)\n"
        "cmpwi	9,0\n"
        "beq	.L_801360F0\n"
        "clrlwi	4,4,16\n"
        ".L_801360CC:\n"
        "lhz	0,16(9)\n"
        "cmplw	0,4\n"
        "blt	.L_801360E4\n"
        "mr	11,9\n"
        "lwz	9,8(11)\n"
        "b	.L_801360E8\n"
        ".L_801360E4:\n"
        "lwz	9,12(9)\n"
        ".L_801360E8:\n"
        "cmpwi	9,0\n"
        "bne	.L_801360CC\n"
        ".L_801360F0:\n"
        "lwz	10,4(3)\n"
        "cmpw	11,10\n"
        "beq	.L_8013610C\n"
        "lhz	9,16(1)\n"
        "lhz	0,16(11)\n"
        "cmplw	9,0\n"
        "bge	.L_80136110\n"
        ".L_8013610C:\n"
        "mr	11,10\n"
        ".L_80136110:\n"
        "lwz	0,4(3)\n"
        "li	9,1\n"
        "stw	11,8(1)\n"
        "cmpw	11,0\n"
        "stw	0,24(1)\n"
        "bne	.L_8013612C\n"
        "li	9,0\n"
        ".L_8013612C:\n"
        "cmpwi	9,0\n"
        "beq	.L_80136144\n"
        "lwz	9,20(11)\n"
        "li	0,1\n"
        "stw	0,132(9)\n"
        "stw	0,32(3)\n"
        ".L_80136144:\n"
        "addi	1,1,32\n"
        "blr\n"
    );
}

// 0x80136644 (172 bytes)
// RoomManager::GetRoom(unsigned short)
__attribute__((noreturn))
void RoomManager::GetRoom(unsigned short) {
    __asm__ __volatile__(
        "stwu	1,-32(1)\n"
        "li	9,0\n"
        "mr	0,4\n"
        "ori	9,9,65530\n"
        "sth	4,8(1)\n"
        "cmplw	0,9\n"
        "bgt	.L_801366E4\n"
        "lwz	11,4(3)\n"
        "addi	8,1,8\n"
        "lwz	9,4(11)\n"
        "mr	10,11\n"
        "cmpwi	9,0\n"
        "beq	.L_8013669C\n"
        ".L_80136678:\n"
        "lhz	0,16(9)\n"
        "cmplw	0,4\n"
        "blt	.L_80136690\n"
        "mr	11,9\n"
        "lwz	9,8(11)\n"
        "b	.L_80136694\n"
        ".L_80136690:\n"
        "lwz	9,12(9)\n"
        ".L_80136694:\n"
        "cmpwi	9,0\n"
        "bne	.L_80136678\n"
        ".L_8013669C:\n"
        "cmpw	11,10\n"
        "beq	.L_801366B4\n"
        "lhz	9,0(8)\n"
        "lhz	0,16(11)\n"
        "cmplw	9,0\n"
        "bge	.L_801366B8\n"
        ".L_801366B4:\n"
        "mr	11,10\n"
        ".L_801366B8:\n"
        "lwz	0,4(3)\n"
        "li	9,1\n"
        "stw	11,16(1)\n"
        "cmpw	11,0\n"
        "stw	0,24(1)\n"
        "bne	.L_801366D4\n"
        "li	9,0\n"
        ".L_801366D4:\n"
        "cmpwi	9,0\n"
        "beq	.L_801366E4\n"
        "lwz	3,20(11)\n"
        "b	.L_801366E8\n"
        ".L_801366E4:\n"
        "li	3,0\n"
        ".L_801366E8:\n"
        "addi	1,1,32\n"
        "blr\n"
    );
}

