#include "types.h"
#include "stub_classes.h"
// Auto-generated matching stubs for SKLTarget
// Generated by auto_match.py
// 4 functions, 44 bytes

// 0x801E1628 (12 bytes)
void SKLTarget::ShowSkills() { register int __r0 __asm__("r0") = 1; __asm__ __volatile__("" : "+r"(__r0)); *(int*)((char*)this + 0x90) = __r0; }

// 0x801E1634 (16 bytes)
void SKLTarget::HideSkills() { register int __r0 __asm__("r0") = 0; __asm__ __volatile__("" : "+r"(__r0)); *(int*)((char*)this + 0x9C) = __r0; *(int*)((char*)this + 0x90) = __r0; }

// 0x801E19BC (8 bytes)
int SKLTarget::IsSkillsActive() { return *(int*)((char*)this + 0x88); }  // offset 0x88

// 0x801E19C4 (8 bytes)
void SKLTarget::SetTextButtonPressed(bool val) { *(int*)((char*)this + 0x9C) = val; }  // offset 0x9C

