#include "types.h"
#include "stub_classes.h"
// Auto-generated raw-byte matches for StateMachineState
// Generated by gen_raw_byte_matches.py
// 6 functions, 184 bytes
// These functions are matched by directly injecting DOL bytes into the skeleton.
// The C++ stubs below exist only as annotations for the matching pipeline.

// 0x80095AA4 (36 bytes)
// StateMachineState__OwnerSetNextState_int__float
// [raw byte match - injected directly from DOL]

// 0x80095AC8 (36 bytes)
// StateMachineState__OwnerCallState_int
// [raw byte match - injected directly from DOL]

// 0x80095AEC (36 bytes)
// StateMachineState__OwnerReturnFromState_int
// [raw byte match - injected directly from DOL]

// 0x8039CFFC (20 bytes)
// StateMachineState__SetFlag_unsigned_int
// [raw byte match - injected directly from DOL]

// 0x803A0288 (52 bytes)
// StateMachineState__dtor_StateMachineState_void
// [raw byte match - injected directly from DOL]

// 0x803A02C0 (4 bytes)
// StateMachineState__Reset_void
// [raw byte match - injected directly from DOL]

