#include "types.h"
#include "stub_classes.h"
// Auto-generated raw-byte matches for TArray_L_EAnimNodeDataPos
// Generated by gen_raw_byte_matches.py
// 4 functions, 184 bytes
// These functions are matched by directly injecting DOL bytes into the skeleton.
// The C++ stubs below exist only as annotations for the matching pipeline.

// 0x803C8F20 (20 bytes)
// TArray_L_EAnimNodeDataPos__TArrayERAnimAllocator_R__Init_void
// [raw byte match - injected directly from DOL]

// 0x803C8F34 (48 bytes)
// TArray_L_EAnimNodeDataPos__TArrayERAnimAllocator_R__TArray_void
// [raw byte match - injected directly from DOL]

// 0x803C9014 (64 bytes)
// TArray_L_EAnimNodeDataPos__TArrayERAnimAllocator_R__dtor_TArray_void
// [raw byte match - injected directly from DOL]

// 0x803C922C (52 bytes)
// TArray_L_EAnimNodeDataPos__TArrayERAnimAllocator_R__Construct_EAnimNodeDataPos_ptr__int
// [raw byte match - injected directly from DOL]

