#include "types.h"
#include "stub_classes.h"
// Auto-generated raw-byte matches for TrackDataReader
// Generated by gen_raw_byte_matches.py
// 5 functions, 140 bytes
// These functions are matched by directly injecting DOL bytes into the skeleton.
// The C++ stubs below exist only as annotations for the matching pipeline.

// 0x801162F4 (48 bytes)
// TrackDataReader__dtor_TrackDataReader_void
// [raw byte match - injected directly from DOL]

// 0x8011633C (20 bytes)
// TrackDataReader__op_assign_ERSoundTrackData_ptr
// [raw byte match - injected directly from DOL]

// 0x80116350 (20 bytes)
// TrackDataReader__op_sub_minus__void
// [raw byte match - injected directly from DOL]

// 0x80116364 (20 bytes)
// TrackDataReader__op_add_eq_int
// [raw byte match - injected directly from DOL]

// 0x8011643C (32 bytes)
// TrackDataReader__JumpToEnd_void
// [raw byte match - injected directly from DOL]

