#include "types.h"
#include "stub_classes.h"
// Auto-generated raw-byte matches for TreeTableAdScratch
// Generated by gen_raw_byte_matches.py
// 6 functions, 108 bytes
// These functions are matched by directly injecting DOL bytes into the skeleton.
// The C++ stubs below exist only as annotations for the matching pipeline.

// 0x801499E8 (52 bytes)
// TreeTableAdScratch__dtor_TreeTableAdScratch_void
// [raw byte match - injected directly from DOL]

// 0x80149B00 (8 bytes)
// TreeTableAdScratch__GetPersonalityAd_void__const
// [raw byte match - injected directly from DOL]

// 0x80149B10 (8 bytes)
// TreeTableAdScratch__GetMin_void__const
// [raw byte match - injected directly from DOL]

// 0x80149B20 (16 bytes)
// TreeTableAdScratch__GetMax_void__const
// [raw byte match - injected directly from DOL]

// 0x80149B30 (16 bytes)
// TreeTableAdScratch__SetMax_int
// [raw byte match - injected directly from DOL]

// 0x80149B40 (8 bytes)
// TreeTableAdScratch__GetRange_void__const
// [raw byte match - injected directly from DOL]

