#include "types.h"
#include "stub_classes.h"
// Auto-generated raw-byte matches for UIReflow
// Generated by gen_raw_byte_matches.py
// 12 functions, 384 bytes
// These functions are matched by directly injecting DOL bytes into the skeleton.
// The C++ stubs below exist only as annotations for the matching pipeline.

// 0x8017EAB0 (32 bytes)
// UIReflow__Reflow_X_int
// [raw byte match - injected directly from DOL]

// 0x8017EAD0 (32 bytes)
// UIReflow__Reflow_Y_int
// [raw byte match - injected directly from DOL]

// 0x8017EAF0 (32 bytes)
// UIReflow__Reflow_Z_unsigned_int
// [raw byte match - injected directly from DOL]

// 0x8017EB10 (32 bytes)
// UIReflow__Reflow_H_unsigned_int
// [raw byte match - injected directly from DOL]

// 0x8017EB30 (32 bytes)
// UIReflow__Reflow_W_unsigned_int
// [raw byte match - injected directly from DOL]

// 0x8017EB50 (32 bytes)
// UIReflow__Reflow_XScale_float
// [raw byte match - injected directly from DOL]

// 0x8017EB70 (32 bytes)
// UIReflow__Reflow_YScale_float
// [raw byte match - injected directly from DOL]

// 0x8017EB90 (32 bytes)
// UIReflow__Reflow_Rotation_float
// [raw byte match - injected directly from DOL]

// 0x8017EC28 (32 bytes)
// UIReflow__Reflow_Alpha_unsigned_int
// [raw byte match - injected directly from DOL]

// 0x8017EC9C (32 bytes)
// UIReflow__Reflow_ColorOverride_unsigned_int
// [raw byte match - injected directly from DOL]

// 0x8017ECBC (32 bytes)
// UIReflow__Reflow_ColorOnlyOverride_unsigned_int
// [raw byte match - injected directly from DOL]

// 0x8017ECDC (32 bytes)
// UIReflow__Reflow_FontSizeOverride_unsigned_int
// [raw byte match - injected directly from DOL]

