#include "types.h"
#include "stub_classes.h"
// Auto-converted call wrapper stubs for UIReflow
// Generated by convert_call_wrappers.py

// 0x8017D2B0 (112 bytes)
// Call wrapper [2bl_with_branch]: UIScreenManager::GetScreenFlashName(char *, UIScreenID), AptViewer::NewCallFunction(char *, char *, char *, int,...)
__attribute__((noreturn))
void UIReflow::SetFocus(UIScreenID) {
    __asm__ __volatile__(
        "stwu	1,-136(1)\n"
        "mflr	0\n"
        "stw	0,140(1)\n"
        "lwz	0,4(3)\n"
        "cmpwi	0,0\n"
        "bne	.L_8017D310\n"
        "lis	9,-32697\n"
        "mr	5,4\n"
        "lwz	3,24336(9)\n"
        "addi	4,1,8\n"
        ".long 0x48002c6d  /* bl UIScreenManager::GetScreenFlashName(char *, UIScreenID) */\n"
        "cmpwi	3,0\n"
        "beq	.L_8017D310\n"
        "lis	4,-32706\n"
        "lis	8,-32706\n"
        "lwz	3,-25136(13)\n"
        "addi	4,4,14152\n"
        "addi	8,8,14160\n"
        "li	5,0\n"
        "li	6,0\n"
        "li	7,2\n"
        "addi	9,1,8\n"
        "crclr	4*cr1+eq\n"
        ".long 0x4be93089  /* bl AptViewer::NewCallFunction(char *, char *, char *, int,...) */\n"
        ".L_8017D310:\n"
        "lwz	0,140(1)\n"
        "mtlr	0\n"
        "addi	1,1,136\n"
        "blr\n"
    );
    __builtin_unreachable();
}
