#include "types.h"
// Inline asm leaf matches for UIUserDrawCBTable
// 1 functions, 104 bytes

#include "types.h"
// Auto-generated inline asm decomp stubs for UIUserDrawCBTable
// Generated by gen_asm_decomp.py
// 10 functions, 1276 bytes
//
// Each function has its original C++ signature with the body as inline PPC asm.
// These can be incrementally replaced with real C++ as decompilation progresses.

template <typename T0, typename T1> class CBFunctor2;

class ERC;
class structDrawCBparams;

class UIUserDrawCBTable {
public:
    UIUserDrawCBTable(void);
    ~UIUserDrawCBTable(void);
    void AddRecord(char *, CBFunctor2<ERC *, structDrawCBparams *> *, char *);
    void RemoveRecord(int *);
    void InstallEntry(char *, CBFunctor2<ERC *, structDrawCBparams *> *, char *);
    void UnInstallEntry(char *);
    void UnInstallAllName(char *);
    void FindEntry(char *);
    void ExecuteCallback(ERC *, char *);
    void Shutdown(void);
};


// 0x80181F18 (104 bytes)
// UIUserDrawCBTable::AddRecord(char *, CBFunctor2<ERC *, structDrawCBparams *> *, char *)
__attribute__((noreturn))
void UIUserDrawCBTable::AddRecord(char *, CBFunctor2<ERC *, structDrawCBparams *> *, char *) {
    __asm__ __volatile__(
        "lwz	10,8(3)\n"
        "lwz	9,4(10)\n"
        "stw	9,8(3)\n"
        "cmpwi	9,0\n"
        "beq	.L_80181F34\n"
        "li	0,0\n"
        "stw	0,0(9)\n"
        ".L_80181F34:\n"
        "stw	4,8(10)\n"
        "stw	5,12(10)\n"
        "stw	6,16(10)\n"
        "lwz	0,0(3)\n"
        "cmpwi	0,0\n"
        "bne	.L_80181F60\n"
        "stw	10,0(3)\n"
        "stw	0,0(10)\n"
        "stw	10,4(3)\n"
        "stw	0,4(10)\n"
        "blr\n"
        ".L_80181F60:\n"
        "lwz	9,4(3)\n"
        "li	11,0\n"
        "stw	10,4(9)\n"
        "lwz	0,4(3)\n"
        "stw	0,0(10)\n"
        "stw	10,4(3)\n"
        "stw	11,4(10)\n"
        "blr\n"
    );
}

