#include "types.h"
#include "stub_classes.h"
// Auto-generated matching stubs for WXFTarget
// Generated by auto_match.py
// 1 functions, 4 bytes

// 0x801E62E8 (4 bytes)
void WXFTarget::Update() { }

