#include "types.h"
#include "stub_classes.h"
// Auto-converted call wrapper stubs for WXFTarget
// Generated by convert_call_wrappers.py

// 0x801E6E30 (144 bytes)
// Call wrapper [2bl_with_branch]: HelpDialog::SpawnHelpDialog(int, char *, char *, HelpDialogCallback *, bool, char *), HelpDialog::SpawnHelpDialog(int, char *, char *, HelpDialogCallback *, bool, char *)
__attribute__((noreturn))
void WXFTarget::ShowHelp(void) {
    __asm__ __volatile__(
        "stwu	1,-8(1)\n"
        "mflr	0\n"
        "stw	0,12(1)\n"
        "lwz	0,304(3)\n"
        "cmplwi	0,1\n"
        "bgt	.L_801E6E80\n"
        "lis	9,-32704\n"
        "slwi	0,0,2\n"
        "addi	9,9,-32504\n"
        "lis	5,-32705\n"
        "lwzx	6,9,0\n"
        "addi	7,3,132\n"
        "lis	9,-32705\n"
        "lwz	4,148(3)\n"
        "addi	5,5,27124\n"
        "addi	9,9,-1988\n"
        "addi	3,3,160\n"
        "li	8,0\n"
        ".long 0x4bf8ecc9  /* bl HelpDialog::SpawnHelpDialog(int, char *, char *, HelpDialogCallback *, bool, char *) */\n"
        "b	.L_801E6EB0\n"
        ".L_801E6E80:\n"
        "lis	9,-32704\n"
        "slwi	0,0,2\n"
        "addi	9,9,-32504\n"
        "lis	5,-32705\n"
        "lwzx	6,9,0\n"
        "addi	7,3,132\n"
        "lwz	4,148(3)\n"
        "addi	5,5,27124\n"
        "addi	3,3,160\n"
        "li	8,0\n"
        "li	9,0\n"
        ".long 0x4bf8ec95  /* bl HelpDialog::SpawnHelpDialog(int, char *, char *, HelpDialogCallback *, bool, char *) */\n"
        ".L_801E6EB0:\n"
        "lwz	0,12(1)\n"
        "mtlr	0\n"
        "addi	1,1,8\n"
        "blr\n"
    );
    __builtin_unreachable();
}
