#include "types.h"
#include "stub_classes.h"
// Auto-converted call wrapper stubs for BehPrintParams
// Generated by convert_call_wrappers.py

// 0x800ABC48 (72 bytes)
// Call wrapper [2bl_with_branch]: strlen, strcpy
__attribute__((noreturn))
void BehPrintParams::SetFilename(char *) {
    __asm__ __volatile__(
        "stwu	1,-16(1)\n"
        "mflr	0\n"
        "stmw	30,8(1)\n"
        "stw	0,20(1)\n"
        "mr	31,4\n"
        "mr	30,3\n"
        "mr	3,31\n"
        ".long 0x48197d01  /* bl strlen */\n"
        "cmplwi	3,512\n"
        "bgt	.L_800ABC7C\n"
        "mr	3,30\n"
        "mr	4,31\n"
        ".long 0x48197c69  /* bl strcpy */\n"
        ".L_800ABC7C:\n"
        "lwz	0,20(1)\n"
        "mtlr	0\n"
        "lmw	30,8(1)\n"
        "addi	1,1,16\n"
        "blr\n"
    );
    __builtin_unreachable();
}
