#include "types.h"
// Auto-generated inline asm decomp stubs for TreeTable
// Generated by gen_asm_decomp.py
// 2 functions, 208 bytes
//
// Each function has its original C++ signature with the body as inline PPC asm.
// These can be incrementally replaced with real C++ as decompilation progresses.

class TreeTable {
public:
    void GetIndexOfResource(short) const;
    void GetIndexByTreeID(short, short) const;
};

// 0x801498B0 (116 bytes)
// TreeTable::GetIndexOfResource(short) const
__attribute__((noreturn))
void TreeTable::GetIndexOfResource(short) const {
    __asm__ __volatile__(
        "stwu	1,-16(1)\n"
        "mflr	0\n"
        "stw	31,12(1)\n"
        "stw	0,20(1)\n"
        "mr	31,3\n"
        "mr	5,4\n"
        "lwz	3,0(31)\n"
        "li	4,0\n"
        "cmpwi	3,0\n"
        "beq	.L_801498DC\n"
        "lwz	4,-4(3)\n"
        ".L_801498DC:\n"
        "mulli	4,4,36\n"
        "add	4,3,4\n"
        ".long 0x4826490d  /* bl TreeTableEntry * FindRes<TreeTableEntry>(TreeTableEntry *, TreeTableEntry *, int) */\n"
        "mr.	3,3\n"
        "beq	.L_8014990C\n"
        "lwz	9,0(31)\n"
        "lis	0,14563\n"
        "ori	0,0,36409\n"
        "subf	9,9,3\n"
        "mullw	9,9,0\n"
        "srawi	3,9,2\n"
        "b	.L_80149910\n"
        ".L_8014990C:\n"
        "li	3,-1\n"
        ".L_80149910:\n"
        "lwz	0,20(1)\n"
        "mtlr	0\n"
        "lwz	31,12(1)\n"
        "addi	1,1,16\n"
        "blr\n"
    );
    __builtin_unreachable();
}

// 0x80149924 (92 bytes)
// TreeTable::GetIndexByTreeID(short, short) const
__attribute__((noreturn))
void TreeTable::GetIndexByTreeID(short, short) const {
    __asm__ __volatile__(
        "lwz	9,0(3)\n"
        "li	8,0\n"
        "cmpwi	9,0\n"
        "beq	.L_80149938\n"
        "lwz	8,-4(9)\n"
        ".L_80149938:\n"
        "li	3,0\n"
        "cmpw	3,8\n"
        "bge	.L_80149978\n"
        "mr	10,9\n"
        ".L_80149948:\n"
        "mulli	9,3,36\n"
        "lhax	0,10,9\n"
        "add	11,10,9\n"
        "cmpw	0,4\n"
        "bne	.L_80149968\n"
        "lha	0,2(11)\n"
        "cmpw	0,5\n"
        "beqlr\n"
        ".L_80149968:\n"
        "addi	0,3,1\n"
        "extsh	3,0\n"
        "cmpw	3,8\n"
        "blt	.L_80149948\n"
        ".L_80149978:\n"
        "li	3,-1\n"
        "blr\n"
    );
    __builtin_unreachable();
}

