#include "types.h"
#include "stub_classes.h"
// Auto-generated raw-byte matches for ETextureManager
// Generated by gen_raw_byte_matches.py
// 4 functions, 128 bytes
// These functions are matched by directly injecting DOL bytes into the skeleton.
// The C++ stubs below exist only as annotations for the matching pipeline.

// 0x80328658 (32 bytes)
// ETextureManager__GetHeap_void
// [raw byte match - injected directly from DOL]

// 0x80328750 (32 bytes)
// ETextureManager__AddRef_unsigned_int__EFile_ptr__int
// [raw byte match - injected directly from DOL]

// 0x80328770 (32 bytes)
// ETextureManager__AddRef_char_ptr__EFile_ptr__int
// [raw byte match - injected directly from DOL]

// 0x803C7000 (32 bytes)
// ETextureManager__dtor_ETextureManager_void
// [raw byte match - injected directly from DOL]

