#include "types.h"
#include "stub_classes.h"
// Auto-converted call wrapper stubs for InLevelStoryState
// Generated by convert_call_wrappers.py

// 0x803A1928 (96 bytes)
// Call wrapper [2bl_with_branch]: UIDialog::~UIDialog(void), __builtin_delete
__attribute__((noreturn))
InLevelStoryState::~InLevelStoryState(void) {
    __asm__ __volatile__(
        "stwu	1,-16(1)\n"
        "mflr	0\n"
        "stmw	30,8(1)\n"
        "stw	0,20(1)\n"
        "lis	9,-32698\n"
        "mr	31,3\n"
        "addi	9,9,-10536\n"
        "mr	30,4\n"
        "stw	9,24(31)\n"
        "addi	3,31,44\n"
        "li	4,2\n"
        ".long 0x4be157ad  /* bl UIDialog::~UIDialog(void) */\n"
        "lis	9,-32698\n"
        "andi.	0,30,1\n"
        "addi	9,9,-13880\n"
        "stw	9,24(31)\n"
        "beq	.L_803A1974\n"
        "mr	3,31\n"
        ".long 0x4bf2f8b1  /* bl __builtin_delete */\n"
        ".L_803A1974:\n"
        "lwz	0,20(1)\n"
        "mtlr	0\n"
        "lmw	30,8(1)\n"
        "addi	1,1,16\n"
        "blr\n"
    );
    __builtin_unreachable();
}
