#include "types.h"
#include "stub_classes.h"
// Auto-generated matching stubs for ResourceBehavior
// Generated by auto_match.py
// 1 functions, 20 bytes

// 0x800ACBB4 (20 bytes)
int ResourceBehavior::AddRef() { *(int*)((char*)this + 0x1C) += 1; }  // refcount increment

