#include "types.h"
// Auto-generated inline asm decomp stubs for SetVar_EYE_saveToSlotStatus
// Generated by gen_asm_decomp.py
// 2 functions, 224 bytes
//
// Each function has its original C++ signature with the body as inline PPC asm.
// These can be incrementally replaced with real C++ as decompilation progresses.

class SetVar_EYE_saveToSlotStatus {
public:
    void Handler(char *);
    SetVar_EYE_saveToSlotStatus(char *);
};

// 0x801E9744 (140 bytes)
// SetVar_EYE_saveToSlotStatus::Handler(char *)
__attribute__((noreturn))
void SetVar_EYE_saveToSlotStatus::Handler(char *) {
    __asm__ __volatile__(
        "stwu	1,-24(1)\n"
        "mflr	0\n"
        "stmw	30,16(1)\n"
        "stw	0,28(1)\n"
        "lbz	0,0(4)\n"
        "cmpwi	0,48\n"
        "bne	.L_801E97BC\n"
        "lwz	9,-28712(13)\n"
        "lwz	0,180(9)\n"
        "cmpwi	0,0\n"
        "beq	.L_801E97BC\n"
        "lwz	3,140(9)\n"
        ".long 0x4be4fa8d  /* bl EyeToyClient::GetRepTexture(int) */\n"
        "mr	30,3\n"
        "addi	5,1,8\n"
        "lwz	9,36(30)\n"
        "mr	6,5\n"
        "li	4,0\n"
        "lwz	0,68(9)\n"
        "lha	3,64(9)\n"
        "mtlr	0\n"
        "add	3,30,3\n"
        "blrl\n"
        "lhz	0,18(30)\n"
        "lhz	5,16(30)\n"
        "lwz	9,-28712(13)\n"
        "mullw	5,5,0\n"
        "lwz	4,180(9)\n"
        "slwi	5,5,1\n"
        ".long 0x48059c9d  /* bl memcpy */\n"
        ".L_801E97BC:\n"
        "lwz	0,28(1)\n"
        "mtlr	0\n"
        "lmw	30,16(1)\n"
        "addi	1,1,24\n"
        "blr\n"
    );
    __builtin_unreachable();
}

// 0x80203928 (84 bytes)
// SetVar_EYE_saveToSlotStatus::SetVar_EYE_saveToSlotStatus(char *)
__attribute__((noreturn))
SetVar_EYE_saveToSlotStatus::SetVar_EYE_saveToSlotStatus(char *) {
    __asm__ __volatile__(
        "stwu	1,-16(1)\n"
        "mflr	0\n"
        "stmw	30,8(1)\n"
        "stw	0,20(1)\n"
        "lis	9,-32698\n"
        "mr	30,3\n"
        "addi	9,9,32728\n"
        "mr	3,4\n"
        "stw	9,8(30)\n"
        "stw	4,0(30)\n"
        ".long 0x4bfe5e81  /* bl AptVar::Hash(char *) */\n"
        "lis	9,-32698\n"
        "stw	3,4(30)\n"
        "addi	9,9,32536\n"
        "mr	3,30\n"
        "stw	9,8(30)\n"
        "lwz	0,20(1)\n"
        "mtlr	0\n"
        "lmw	30,8(1)\n"
        "addi	1,1,16\n"
        "blr\n"
    );
    __builtin_unreachable();
}

