#include "types.h"
// Auto-generated inline asm decomp stubs for EIPortalPointLight
// Generated by gen_asm_decomp.py
// 8 functions, 2036 bytes
//
// Each function has its original C++ signature with the body as inline PPC asm.
// These can be incrementally replaced with real C++ as decompilation progresses.

class EStream;
class EVec3;

struct TypeInfo;

class EIPortalPointLight {
public:
    EIPortalPointLight(void);
    void Write(EStream &);
    void Read(EStream &);
    void LightingParameters(EVec3 &, float &, EVec3 &, EVec3 &);
    void Setup(void);
    void Update(void);
    void IsEnabled(void);
    void RegisterType(unsigned short);
    const TypeInfo* GetTypeInfo() const;
    const char* GetTypeName() const;
    u32 GetTypeKey() const;
    u16 GetTypeVersion() const;
    static const TypeInfo* GetTypeInfoStatic();
    static u16 GetReadVersion();
};

// 0x8022A740 (168 bytes)
// EIPortalPointLight::EIPortalPointLight(void)
__attribute__((noreturn))
EIPortalPointLight::EIPortalPointLight(void) {
    __asm__ __volatile__(
        "stwu	1,-48(1)\n"
        "mflr	0\n"
        "stfd	31,40(1)\n"
        "stmw	29,28(1)\n"
        "stw	0,52(1)\n"
        "mr	30,3\n"
        "li	29,0\n"
        ".long 0x4bfff671  /* bl EIPointLight::EIPointLight(void) */\n"
        "lis	11,-32704\n"
        "lwz	0,92(30)\n"
        "lfs	31,-5104(11)\n"
        "addi	9,1,8\n"
        "lis	11,-32697\n"
        "oris	0,0,8\n"
        "stfs	31,8(9)\n"
        "addi	11,11,-27584\n"
        "stfs	31,4(9)\n"
        "mr	4,9\n"
        "stw	11,0(30)\n"
        "mr	3,30\n"
        "stw	0,92(30)\n"
        "stw	29,212(30)\n"
        "stfs	31,8(1)\n"
        ".long 0x4bfffadd  /* bl EIPointLight::SetPosition(EVec3 &) */\n"
        "stfs	31,196(30)\n"
        "li	0,1\n"
        "mr	3,30\n"
        "lfs	0,-28484(13)\n"
        "stw	0,204(30)\n"
        "stfs	0,200(30)\n"
        "lfs	13,-28460(13)\n"
        "stw	29,208(30)\n"
        "stfs	13,140(30)\n"
        "stw	0,136(30)\n"
        ".long 0x48000379  /* bl EIPortalPointLight::Setup(void) */\n"
        "mr	3,30\n"
        "lwz	0,52(1)\n"
        "mtlr	0\n"
        "lmw	29,28(1)\n"
        "lfd	31,40(1)\n"
        "addi	1,1,48\n"
        "blr\n"
    );
    __builtin_unreachable();
}

// 0x8022A824 (228 bytes)
// EIPortalPointLight::Write(EStream &)
__attribute__((noreturn))
void EIPortalPointLight::Write(EStream &) {
    __asm__ __volatile__(
        "stwu	1,-56(1)\n"
        "mflr	0\n"
        "stmw	29,44(1)\n"
        "stw	0,60(1)\n"
        "mr	30,3\n"
        "mr	29,4\n"
        ".long 0x4bffd1f1  /* bl EILight::Write(EStream &) */\n"
        "lwz	9,0(30)\n"
        "addi	4,1,8\n"
        "lwz	0,372(9)\n"
        "lha	3,368(9)\n"
        "mtlr	0\n"
        "add	3,30,3\n"
        "blrl\n"
        "addi	4,1,8\n"
        "mr	3,29\n"
        ".long 0x480a7ba5  /* bl operator<<(EStream &, EVec3 &) */\n"
        "mr	29,3\n"
        "addi	4,1,32\n"
        "lwz	9,24(29)\n"
        "li	5,4\n"
        "lfs	0,196(30)\n"
        "lwz	0,60(9)\n"
        "lha	3,56(9)\n"
        "mtlr	0\n"
        "stfs	0,32(1)\n"
        "add	3,29,3\n"
        "blrl\n"
        "lwz	9,24(29)\n"
        "addi	4,1,36\n"
        "li	5,4\n"
        "lfs	0,200(30)\n"
        "lwz	0,60(9)\n"
        "lha	3,56(9)\n"
        "mtlr	0\n"
        "stfs	0,36(1)\n"
        "add	3,29,3\n"
        "blrl\n"
        "lwz	0,204(30)\n"
        "li	9,0\n"
        "cmpwi	0,0\n"
        "beq	.L_8022A8D0\n"
        "li	9,1\n"
        ".L_8022A8D0:\n"
        "stb	9,24(1)\n"
        "addi	4,1,24\n"
        "li	5,1\n"
        "lwz	9,24(29)\n"
        "lha	3,56(9)\n"
        "lwz	0,60(9)\n"
        "add	3,29,3\n"
        "mtlr	0\n"
        "blrl\n"
        "lwz	0,60(1)\n"
        "mtlr	0\n"
        "lmw	29,44(1)\n"
        "addi	1,1,56\n"
        "blr\n"
    );
    __builtin_unreachable();
}

// 0x8022A908 (212 bytes)
// EIPortalPointLight::Read(EStream &)
__attribute__((noreturn))
void EIPortalPointLight::Read(EStream &) {
    __asm__ __volatile__(
        "stwu	1,-40(1)\n"
        "mflr	0\n"
        "stmw	30,32(1)\n"
        "stw	0,44(1)\n"
        "mr	31,3\n"
        "mr	30,4\n"
        ".long 0x4bffd221  /* bl EILight::Read(EStream &) */\n"
        "lis	9,-32688\n"
        "lhz	0,-13178(9)\n"
        "cmpwi	0,0\n"
        "bne	.L_8022A9BC\n"
        "addi	4,1,8\n"
        "mr	3,30\n"
        ".long 0x480a7d31  /* bl operator>>(EStream &, EVec3 &) */\n"
        "mr	30,3\n"
        "addi	4,31,196\n"
        "lwz	9,24(30)\n"
        "li	5,4\n"
        "lwz	0,52(9)\n"
        "lha	3,48(9)\n"
        "mtlr	0\n"
        "add	3,30,3\n"
        "blrl\n"
        "lwz	9,24(30)\n"
        "addi	4,31,200\n"
        "li	5,4\n"
        "lwz	0,52(9)\n"
        "lha	3,48(9)\n"
        "mtlr	0\n"
        "add	3,30,3\n"
        "blrl\n"
        "lwz	9,24(30)\n"
        "addi	4,1,24\n"
        "li	5,1\n"
        "lwz	0,52(9)\n"
        "lha	3,48(9)\n"
        "mtlr	0\n"
        "add	3,30,3\n"
        "blrl\n"
        "lbz	0,24(1)\n"
        "li	9,1\n"
        "cmpwi	0,0\n"
        "bne	.L_8022A9B8\n"
        "li	9,0\n"
        ".L_8022A9B8:\n"
        "stw	9,204(31)\n"
        ".L_8022A9BC:\n"
        "mr	3,31\n"
        "addi	4,1,8\n"
        ".long 0x4bfff8b5  /* bl EIPointLight::SetPosition(EVec3 &) */\n"
        "lwz	0,44(1)\n"
        "mtlr	0\n"
        "lmw	30,32(1)\n"
        "addi	1,1,40\n"
        "blr\n"
    );
    __builtin_unreachable();
}

// 0x8022A9DC (356 bytes)
// EIPortalPointLight::LightingParameters(EVec3 &, float &, EVec3 &, EVec3 &)
__attribute__((noreturn))
void EIPortalPointLight::LightingParameters(EVec3 &, float &, EVec3 &, EVec3 &) {
    __asm__ __volatile__(
        "stwu	1,-48(1)\n"
        "mflr	0\n"
        "stmw	28,32(1)\n"
        "stw	0,52(1)\n"
        "mr	31,3\n"
        "lis	9,-32704\n"
        "lfs	13,-5100(9)\n"
        "mr	30,4\n"
        "lfs	0,200(31)\n"
        "mr	4,6\n"
        "mr	29,7\n"
        "fmuls	0,0,13\n"
        "stfs	0,0(5)\n"
        "lwz	9,0(31)\n"
        "lwz	0,372(9)\n"
        "lha	3,368(9)\n"
        "mtlr	0\n"
        "add	3,31,3\n"
        "blrl\n"
        "lis	11,-32704\n"
        "addi	9,1,8\n"
        "lfs	0,-5096(11)\n"
        "addi	5,1,24\n"
        "addi	6,1,26\n"
        "mr	28,9\n"
        "stfs	0,8(9)\n"
        "stfs	0,4(9)\n"
        "stfs	0,8(1)\n"
        "lwz	0,8(9)\n"
        "lwz	11,8(1)\n"
        "lwz	10,4(9)\n"
        "stw	11,0(30)\n"
        "stw	0,8(30)\n"
        "stw	10,4(30)\n"
        "lwz	0,28(31)\n"
        "cmpwi	0,0\n"
        "beq	.L_8022AA84\n"
        "lwz	3,40(31)\n"
        "li	4,0\n"
        "mtlr	0\n"
        "blrl\n"
        "b	.L_8022AA8C\n"
        ".L_8022AA84:\n"
        "sth	0,24(1)\n"
        "sth	0,26(1)\n"
        ".L_8022AA8C:\n"
        "lwz	0,32(31)\n"
        "addi	5,1,28\n"
        "addi	6,1,30\n"
        "cmpwi	0,0\n"
        "beq	.L_8022AAB4\n"
        "lwz	3,36(31)\n"
        "li	4,0\n"
        "mtlr	0\n"
        "blrl\n"
        "b	.L_8022AAC0\n"
        ".L_8022AAB4:\n"
        "li	0,-1\n"
        "sth	0,28(1)\n"
        "sth	0,30(1)\n"
        ".L_8022AAC0:\n"
        "lha	9,26(1)\n"
        "lha	0,30(1)\n"
        "cmpw	9,0\n"
        "beq	.L_8022AB00\n"
        "addi	9,31,144\n"
        "lfs	13,140(31)\n"
        "lfs	0,8(9)\n"
        "lfs	12,4(9)\n"
        "lfs	11,144(31)\n"
        "fmuls	0,0,13\n"
        "fmuls	12,12,13\n"
        "stfs	0,16(1)\n"
        "fmuls	11,11,13\n"
        "stfs	12,12(1)\n"
        "stfs	11,8(1)\n"
        "b	.L_8022AB14\n"
        ".L_8022AB00:\n"
        "lis	9,-32704\n"
        "lfs	0,-5096(9)\n"
        "stfs	0,8(1)\n"
        "stfs	0,8(28)\n"
        "stfs	0,4(28)\n"
        ".L_8022AB14:\n"
        "lwz	0,8(28)\n"
        "lwz	9,8(1)\n"
        "lwz	11,4(28)\n"
        "stw	0,8(29)\n"
        "stw	9,0(29)\n"
        "stw	11,4(29)\n"
        "lwz	0,52(1)\n"
        "mtlr	0\n"
        "lmw	28,32(1)\n"
        "addi	1,1,48\n"
        "blr\n"
    );
    __builtin_unreachable();
}

// 0x8022AB40 (272 bytes)
// EIPortalPointLight::Setup(void)
__attribute__((noreturn))
void EIPortalPointLight::Setup(void) {
    __asm__ __volatile__(
        "stwu	1,-64(1)\n"
        "mflr	0\n"
        "stmw	29,52(1)\n"
        "stw	0,68(1)\n"
        "lis	9,-32704\n"
        "mr	29,3\n"
        "lfs	0,-5092(9)\n"
        "addi	10,1,20\n"
        "lwz	0,204(29)\n"
        "addi	30,1,8\n"
        "stfs	0,32(1)\n"
        "addi	31,1,32\n"
        "stfs	0,40(1)\n"
        "cmpwi	0,0\n"
        "stfs	0,36(1)\n"
        "lwz	0,32(1)\n"
        "lwz	9,36(1)\n"
        "lwz	11,40(1)\n"
        "stw	0,20(1)\n"
        "stw	9,4(10)\n"
        "stw	11,8(10)\n"
        "lwz	0,20(1)\n"
        "stw	0,8(1)\n"
        "stw	9,4(30)\n"
        "stw	11,8(30)\n"
        "beq	.L_8022ABD8\n"
        "lwz	9,0(29)\n"
        "mr	4,31\n"
        "lha	3,368(9)\n"
        "lwz	0,372(9)\n"
        "add	3,29,3\n"
        "mtlr	0\n"
        "blrl\n"
        "lfs	1,200(29)\n"
        "mr	3,30\n"
        "mr	4,31\n"
        ".long 0x4809ad61  /* bl EBound3::Compute(EVec3 &, float) */\n"
        "b	.L_8022AC30\n"
        ".L_8022ABD8:\n"
        "lis	9,-32704\n"
        "lis	11,-32704\n"
        "lfs	0,-5088(9)\n"
        "lfs	13,-5084(11)\n"
        "stfs	0,8(31)\n"
        "stfs	0,4(31)\n"
        "stfs	0,32(1)\n"
        "lwz	9,32(1)\n"
        "lwz	11,4(31)\n"
        "lwz	0,8(31)\n"
        "stw	9,8(1)\n"
        "stw	0,8(30)\n"
        "stw	11,4(30)\n"
        "stfs	13,8(31)\n"
        "stfs	13,4(31)\n"
        "stfs	13,32(1)\n"
        "lwz	0,32(1)\n"
        "lwz	9,8(31)\n"
        "lwz	11,4(31)\n"
        "stw	0,20(1)\n"
        "stw	9,8(10)\n"
        "stw	11,4(10)\n"
        ".L_8022AC30:\n"
        "mr	3,29\n"
        "addi	4,1,8\n"
        ".long 0x4bffdb45  /* bl EInstance::SetBounds(EBound3 &) */\n"
        "lwz	0,68(1)\n"
        "mtlr	0\n"
        "lmw	29,52(1)\n"
        "addi	1,1,64\n"
        "blr\n"
    );
    __builtin_unreachable();
}

// 0x8022AC50 (540 bytes)
// EIPortalPointLight::Update(void)
__attribute__((noreturn))
void EIPortalPointLight::Update(void) {
    __asm__ __volatile__(
        "stwu	1,-120(1)\n"
        "mflr	0\n"
        "stw	31,116(1)\n"
        "stw	0,124(1)\n"
        "mr	31,3\n"
        "lwz	0,208(31)\n"
        "cmpwi	0,0\n"
        "beq	.L_8022AC90\n"
        "lwz	9,212(31)\n"
        "lwz	0,36(9)\n"
        "lwz	11,32(9)\n"
        "stw	0,40(31)\n"
        "stw	11,28(31)\n"
        "lwz	0,28(9)\n"
        "lwz	11,40(9)\n"
        "b	.L_8022ACAC\n"
        ".L_8022AC90:\n"
        "lwz	9,212(31)\n"
        "lwz	0,40(9)\n"
        "lwz	11,28(9)\n"
        "stw	0,40(31)\n"
        "stw	11,28(31)\n"
        "lwz	0,32(9)\n"
        "lwz	11,36(9)\n"
        ".L_8022ACAC:\n"
        "stw	0,32(31)\n"
        "stw	11,36(31)\n"
        "lwz	11,212(31)\n"
        "addi	4,1,8\n"
        "lwz	9,0(11)\n"
        "lwz	0,276(9)\n"
        "lha	3,272(9)\n"
        "mtlr	0\n"
        "add	3,11,3\n"
        "blrl\n"
        "lis	9,-32704\n"
        "lwz	0,208(31)\n"
        "lfs	13,-5080(9)\n"
        "lfs	0,-28444(13)\n"
        "cmpwi	0,0\n"
        "stfs	13,80(1)\n"
        "stfs	0,76(1)\n"
        "stfs	13,72(1)\n"
        "beq	.L_8022AD00\n"
        "fneg	0,0\n"
        "stfs	0,76(1)\n"
        ".L_8022AD00:\n"
        "addi	9,1,8\n"
        "lfs	9,76(1)\n"
        "lfs	13,16(9)\n"
        "addi	5,1,104\n"
        "lfs	7,20(9)\n"
        "addi	6,1,106\n"
        "lfs	0,24(9)\n"
        "fmuls	13,9,13\n"
        "lfs	10,4(9)\n"
        "fmuls	7,9,7\n"
        "lfs	8,72(1)\n"
        "fmuls	9,9,0\n"
        "lfs	11,8(1)\n"
        "lfs	6,8(9)\n"
        "fmadds	10,8,10,7\n"
        "fmadds	11,8,11,13\n"
        "lfs	12,32(9)\n"
        "lfs	0,80(1)\n"
        "fmadds	8,8,6,9\n"
        "lfs	13,36(9)\n"
        "lfs	9,40(9)\n"
        "fmadds	12,0,12,11\n"
        "lfs	7,56(9)\n"
        "fmadds	13,0,13,10\n"
        "lfs	6,48(9)\n"
        "fmadds	0,0,9,8\n"
        "lfs	11,52(9)\n"
        "fadds	0,0,7\n"
        "lwz	0,28(31)\n"
        "fadds	12,12,6\n"
        "fadds	13,13,11\n"
        "stfs	12,88(1)\n"
        "stfs	13,92(1)\n"
        "cmpwi	0,0\n"
        "stfs	0,96(1)\n"
        "beq	.L_8022ADA4\n"
        "lwz	3,40(31)\n"
        "li	4,0\n"
        "mtlr	0\n"
        "blrl\n"
        "b	.L_8022ADAC\n"
        ".L_8022ADA4:\n"
        "sth	0,104(1)\n"
        "sth	0,106(1)\n"
        ".L_8022ADAC:\n"
        "lha	0,106(1)\n"
        "li	11,0\n"
        "cmpwi	0,0\n"
        "beq	.L_8022ADC0\n"
        "li	11,1\n"
        ".L_8022ADC0:\n"
        "lwz	9,212(31)\n"
        "lwz	0,20(9)\n"
        "cmpwi	0,2\n"
        "beq	.L_8022AE08\n"
        "bgt	.L_8022ADE0\n"
        "cmpwi	0,1\n"
        "beq	.L_8022ADEC\n"
        "b	.L_8022AE4C\n"
        ".L_8022ADE0:\n"
        "cmpwi	0,3\n"
        "beq	.L_8022AE24\n"
        "b	.L_8022AE4C\n"
        ".L_8022ADEC:\n"
        "slwi	0,11,2\n"
        "addi	9,13,-28484\n"
        "lfsx	0,9,0\n"
        "lis	11,-32704\n"
        "lfs	13,-5076(11)\n"
        "addi	9,13,-28460\n"
        "b	.L_8022AE3C\n"
        ".L_8022AE08:\n"
        "slwi	0,11,2\n"
        "addi	9,13,-28476\n"
        "lfsx	0,9,0\n"
        "lis	11,-32704\n"
        "lfs	13,-5072(11)\n"
        "addi	9,13,-28452\n"
        "b	.L_8022AE3C\n"
        ".L_8022AE24:\n"
        "slwi	0,11,2\n"
        "addi	9,13,-28492\n"
        "lfsx	0,9,0\n"
        "lis	11,-32704\n"
        "lfs	13,-5068(11)\n"
        "addi	9,13,-28468\n"
        ".L_8022AE3C:\n"
        "stfs	0,200(31)\n"
        "stfs	13,96(1)\n"
        "lfsx	0,9,0\n"
        "stfs	0,140(31)\n"
        ".L_8022AE4C:\n"
        "mr	3,31\n"
        "addi	4,1,88\n"
        ".long 0x4bfff425  /* bl EIPointLight::SetPosition(EVec3 &) */\n"
        "lwz	0,124(1)\n"
        "mtlr	0\n"
        "lwz	31,116(1)\n"
        "addi	1,1,120\n"
        "blr\n"
    );
    __builtin_unreachable();
}

// 0x8022AE6C (176 bytes)
// EIPortalPointLight::IsEnabled(void)
__attribute__((noreturn))
void EIPortalPointLight::IsEnabled(void) {
    __asm__ __volatile__(
        "stwu	1,-24(1)\n"
        "mflr	0\n"
        "stw	31,20(1)\n"
        "stw	0,28(1)\n"
        "mr	31,3\n"
        "addi	5,1,8\n"
        "lwz	0,28(31)\n"
        "addi	6,1,10\n"
        "cmpwi	0,0\n"
        "beq	.L_8022AEA8\n"
        "lwz	3,40(31)\n"
        "li	4,0\n"
        "mtlr	0\n"
        "blrl\n"
        "b	.L_8022AEB0\n"
        ".L_8022AEA8:\n"
        "sth	0,8(1)\n"
        "sth	0,10(1)\n"
        ".L_8022AEB0:\n"
        "lwz	0,32(31)\n"
        "addi	5,1,12\n"
        "addi	6,1,14\n"
        "cmpwi	0,0\n"
        "beq	.L_8022AED8\n"
        "lwz	3,36(31)\n"
        "li	4,0\n"
        "mtlr	0\n"
        "blrl\n"
        "b	.L_8022AEE4\n"
        ".L_8022AED8:\n"
        "li	0,-1\n"
        "sth	0,12(1)\n"
        "sth	0,14(1)\n"
        ".L_8022AEE4:\n"
        "lha	9,14(1)\n"
        "li	3,0\n"
        "lha	0,10(1)\n"
        "cmpw	9,0\n"
        "beq	.L_8022AF08\n"
        "lwz	0,136(31)\n"
        "cmpwi	0,0\n"
        "beq	.L_8022AF08\n"
        "li	3,1\n"
        ".L_8022AF08:\n"
        "lwz	0,28(1)\n"
        "mtlr	0\n"
        "lwz	31,20(1)\n"
        "addi	1,1,24\n"
        "blr\n"
    );
    __builtin_unreachable();
}

// 0x8022B080 (84 bytes)
// EIPortalPointLight::RegisterType(unsigned short)
__attribute__((noreturn))
void EIPortalPointLight::RegisterType(unsigned short) {
    __asm__ __volatile__(
        "stwu	1,-8(1)\n"
        "mflr	0\n"
        "stw	0,12(1)\n"
        "mr	7,3\n"
        "lis	4,-32733\n"
        "lis	3,-32688\n"
        "lis	5,-32733\n"
        "lis	6,-32733\n"
        "lis	8,-32704\n"
        "lis	9,-32688\n"
        "addi	3,3,-13200\n"
        "addi	4,4,-20596\n"
        "addi	5,5,-20556\n"
        "addi	6,6,-20524\n"
        "addi	8,8,-5352\n"
        "addi	9,9,-13440\n"
        ".long 0x480aa80d  /* bl ETypeInfo::Register(EStorable *(*)(void), void (*)(void *), void (*)(void *), unsigned short, char *, ETypeInfo *) */\n"
        "lwz	0,12(1)\n"
        "mtlr	0\n"
        "addi	1,1,8\n"
        "blr\n"
    );
    __builtin_unreachable();
}



// TypeInfo getter implementations

struct TypeInfo;
extern TypeInfo EIPortalPointLight_typeInfo;

// 0x8022B038 (12 bytes)
const TypeInfo* EIPortalPointLight::GetTypeInfo() const {
    return &EIPortalPointLight_typeInfo;
}

// 0x8022B044 (12 bytes)
const char* EIPortalPointLight::GetTypeName() const {
    return *(const char**)((char*)&EIPortalPointLight_typeInfo + 0x0C);
}

// 0x8022B050 (12 bytes)
u32 EIPortalPointLight::GetTypeKey() const {
    return *(u32*)((char*)&EIPortalPointLight_typeInfo + 0x10);
}

// 0x8022B05C (12 bytes)
u16 EIPortalPointLight::GetTypeVersion() const {
    return *(u16*)((char*)&EIPortalPointLight_typeInfo + 0x14);
}

// 0x8022B068 (12 bytes)
const TypeInfo* EIPortalPointLight::GetTypeInfoStatic() {
    return &EIPortalPointLight_typeInfo;
}

// 0x8022B074 (12 bytes)
u16 EIPortalPointLight::GetReadVersion() {
    return *(u16*)((char*)&EIPortalPointLight_typeInfo + 0x16);
}

