#include "types.h"
// Auto-generated inline asm decomp stubs for ERAnim
// Generated by gen_asm_decomp.py
// 5 functions, 2024 bytes
//
// Each function has its original C++ signature with the body as inline PPC asm.
// These can be incrementally replaced with real C++ as decompilation progresses.

class EFile;

struct TypeInfo;

class EAnimNodeDataPos {
public:
    const TypeInfo* GetTypeInfo() const;
    const char* GetTypeName() const;
    u32 GetTypeKey() const;
    u16 GetTypeVersion() const;
    static const TypeInfo* GetTypeInfoStatic();
    static u16 GetReadVersion();
};

struct TypeInfo;

class ERAnim {
public:
    ERAnim(void);
    ~ERAnim(void);
    void Load(EFile *);
    void OldLoad(EFile *);
    void RegisterType(unsigned short);
    const TypeInfo* GetTypeInfo() const;
    const char* GetTypeName() const;
    u32 GetTypeKey() const;
    u16 GetTypeVersion() const;
    static const TypeInfo* GetTypeInfoStatic();
    static u16 GetReadVersion();
};

// 0x803673AC (320 bytes)
// ERAnim::ERAnim(void)
__attribute__((noreturn))
ERAnim::ERAnim(void) {
    __asm__ __volatile__(
        "stwu	1,-48(1)\n"
        "mflr	0\n"
        "stfd	31,40(1)\n"
        "stmw	29,28(1)\n"
        "stw	0,52(1)\n"
        "mr	30,3\n"
        "addi	29,30,80\n"
        ".long 0x4bfaaa01  /* bl EResource::EResource(void) */\n"
        "lis	9,-32697\n"
        "addi	3,30,52\n"
        "addi	9,9,-9144\n"
        "stw	9,0(30)\n"
        ".long 0x48061b59  /* bl TArray<EAnimNodeDataPos, TArrayERAnimAllocator>::TArray(void) */\n"
        "addi	3,30,68\n"
        ".long 0x48061c85  /* bl TArray<float, TArrayERAnimAllocator>::TArray(void) */\n"
        "mr	3,29\n"
        ".long 0x4bf78159  /* bl EBitArray::EBitArray(void) */\n"
        "lis	9,-32697\n"
        "lis	10,-32702\n"
        "addi	9,9,-9000\n"
        "lis	6,-32702\n"
        "stw	9,16(29)\n"
        "addi	11,30,100\n"
        "li	8,251\n"
        "li	7,3\n"
        "lfs	0,12904(10)\n"
        "li	0,0\n"
        "li	9,1\n"
        "lis	10,-32702\n"
        "stfs	0,100(30)\n"
        "lis	5,-32702\n"
        "lis	4,-32702\n"
        "lis	29,-32702\n"
        "lfs	31,12908(6)\n"
        "addi	3,30,136\n"
        "stw	8,8(11)\n"
        "stb	7,12(11)\n"
        "stb	0,13(11)\n"
        "stb	9,14(11)\n"
        "stfs	31,4(11)\n"
        "lfs	13,12912(10)\n"
        "stfs	13,20(11)\n"
        "stfs	13,16(11)\n"
        "lfs	0,12916(5)\n"
        "stfs	0,28(11)\n"
        "lfs	13,12920(4)\n"
        "stfs	13,32(11)\n"
        "lfs	0,12924(29)\n"
        "stfs	0,24(11)\n"
        ".long 0x48036415  /* bl TArray<EAnimNote, TArrayERAnimAllocator>::TArray(void) */\n"
        "addi	3,30,148\n"
        ".long 0x48061cdd  /* bl TArray<EAnimEvent, TArrayERAnimAllocator>::TArray(void) */\n"
        "addi	9,1,8\n"
        "li	11,0\n"
        "stfs	31,8(9)\n"
        "addi	8,30,40\n"
        "stfs	31,4(9)\n"
        "addi	7,30,28\n"
        "stfs	31,8(1)\n"
        "mr	3,30\n"
        "stw	11,24(30)\n"
        "lwz	11,8(9)\n"
        "lwz	0,8(1)\n"
        "lwz	10,4(9)\n"
        "stw	0,40(30)\n"
        "stw	11,8(8)\n"
        "stw	10,4(8)\n"
        "lwz	9,-25836(13)\n"
        "lwz	0,40(30)\n"
        "addi	9,9,1\n"
        "stw	0,28(30)\n"
        "stw	11,8(7)\n"
        "stw	10,4(7)\n"
        "stw	9,-25836(13)\n"
        "lwz	0,52(1)\n"
        "mtlr	0\n"
        "lmw	29,28(1)\n"
        "lfd	31,40(1)\n"
        "addi	1,1,48\n"
        "blr\n"
    );
    __builtin_unreachable();
}

// 0x803674EC (196 bytes)
// ERAnim::~ERAnim(void)
__attribute__((noreturn))
ERAnim::~ERAnim(void) {
    __asm__ __volatile__(
        "stwu	1,-24(1)\n"
        "mflr	0\n"
        "stmw	29,12(1)\n"
        "stw	0,28(1)\n"
        "lwz	11,-25836(13)\n"
        "lis	9,-32697\n"
        "mr	31,3\n"
        "addi	9,9,-9144\n"
        "addi	11,11,-1\n"
        "stw	9,0(31)\n"
        "mr	29,4\n"
        "stw	11,-25836(13)\n"
        "addi	3,31,148\n"
        "li	4,2\n"
        ".long 0x48061cc9  /* bl TArray<EAnimEvent, TArrayERAnimAllocator>::~TArray(void) */\n"
        "addi	30,31,80\n"
        "li	4,2\n"
        "addi	3,31,136\n"
        ".long 0x48036311  /* bl TArray<EAnimNote, TArrayERAnimAllocator>::~TArray(void) */\n"
        "lis	9,-32697\n"
        "mr	3,30\n"
        "addi	9,9,-9000\n"
        "stw	9,16(30)\n"
        ".long 0x4bf781e5  /* bl EBitArray::Deallocate(void) */\n"
        "lis	9,-32697\n"
        "mr	3,30\n"
        "addi	9,9,-23560\n"
        "stw	9,16(30)\n"
        ".long 0x4bf781d1  /* bl EBitArray::Deallocate(void) */\n"
        "addi	3,31,68\n"
        "li	4,2\n"
        ".long 0x48061b99  /* bl TArray<float, TArrayERAnimAllocator>::~TArray(void) */\n"
        "addi	3,31,52\n"
        "li	4,2\n"
        ".long 0x48061aa1  /* bl TArray<EAnimNodeDataPos, TArrayERAnimAllocator>::~TArray(void) */\n"
        "mr	3,31\n"
        "li	4,0\n"
        ".long 0x4bfaa879  /* bl EResource::~EResource(void) */\n"
        "andi.	0,29,1\n"
        "beq	.L_8036759C\n"
        "lis	3,-32693\n"
        "mr	4,31\n"
        "addi	3,3,11064\n"
        ".long 0x4bfc0115  /* bl EResourceManager::Free(void *) */\n"
        ".L_8036759C:\n"
        "lwz	0,28(1)\n"
        "mtlr	0\n"
        "lmw	29,12(1)\n"
        "addi	1,1,24\n"
        "blr\n"
    );
    __builtin_unreachable();
}

// 0x803679AC (752 bytes)
// ERAnim::Load(EFile *)
__attribute__((noreturn))
void ERAnim::Load(EFile *) {
    __asm__ __volatile__(
        "stwu	1,-72(1)\n"
        "mflr	0\n"
        "stmw	26,48(1)\n"
        "stw	0,76(1)\n"
        "mr	31,3\n"
        "mr	27,4\n"
        "addi	3,1,8\n"
        ".long 0x4bff34a9  /* bl EDataHeader::EDataHeader(void) */\n"
        "lis	5,16718\n"
        "addi	3,1,8\n"
        "mr	4,27\n"
        "ori	5,5,18765\n"
        "li	6,17\n"
        "li	7,18\n"
        ".long 0x4bff36b9  /* bl EDataHeader::Read(EFile &, unsigned int, unsigned int, unsigned int) */\n"
        "cmpwi	3,0\n"
        "beq	.L_80367C70\n"
        "addi	3,1,8\n"
        "addi	29,31,80\n"
        ".long 0x4bff3929  /* bl EDataHeader::GetName(void) */\n"
        "addi	28,31,136\n"
        "lwz	9,24(1)\n"
        "lwz	0,16(31)\n"
        "rlwimi	0,9,8,0,23\n"
        "stw	0,16(31)\n"
        ".long 0x4bf684f1  /* bl MainHeap(void) */\n"
        "lwz	4,24(1)\n"
        "li	5,0\n"
        ".long 0x4bf69089  /* bl EAHeap::Malloc(unsigned int, int) */\n"
        "lwz	9,40(27)\n"
        "mr	26,3\n"
        "lwz	5,24(1)\n"
        "mr	4,26\n"
        "lwz	0,28(9)\n"
        "addi	30,26,28\n"
        "lha	3,24(9)\n"
        "mtlr	0\n"
        "add	3,27,3\n"
        "blrl\n"
        "mr	4,26\n"
        "li	5,4\n"
        "addi	3,31,24\n"
        ".long 0x4bedba01  /* bl memcpy */\n"
        "addi	4,26,4\n"
        "li	5,12\n"
        "addi	3,31,28\n"
        ".long 0x4bedb9f1  /* bl memcpy */\n"
        "li	5,12\n"
        "addi	4,26,16\n"
        "addi	3,31,40\n"
        ".long 0x4bedb9e1  /* bl memcpy */\n"
        "mr	4,30\n"
        "addi	3,31,52\n"
        ".long 0x4bfffb5d  /* bl CopyERAnimNodeArray(TArray<EAnimNodeDataPos, TArrayERAnimAllocator> &, char *) */\n"
        "add	30,30,3\n"
        "li	5,4\n"
        "mr	4,30\n"
        "addi	3,31,64\n"
        ".long 0x4bedb9c1  /* bl memcpy */\n"
        "addi	30,30,4\n"
        "mr	4,30\n"
        "addi	3,31,68\n"
        ".long 0x4bfffc95  /* bl CopyERAnimConstantArray(TArray<float, TArrayERAnimAllocator> &, char *) */\n"
        "add	30,30,3\n"
        "li	5,4\n"
        "addi	3,1,32\n"
        "mr	4,30\n"
        ".long 0x4bedb99d  /* bl memcpy */\n"
        "addi	30,30,4\n"
        "mr	3,29\n"
        "li	4,0\n"
        "li	5,0\n"
        ".long 0x4bf77e21  /* bl EBitArray::SetSize(int, int) */\n"
        "lwz	4,32(1)\n"
        "li	5,0\n"
        "mr	3,29\n"
        ".long 0x4bf77e11  /* bl EBitArray::SetSize(int, int) */\n"
        "mr	3,29\n"
        ".long 0x4bf781e1  /* bl EBitArray::GetElementCount(void) const */\n"
        "slwi	0,3,2\n"
        "mr	4,30\n"
        "lwz	3,80(31)\n"
        "add	30,30,0\n"
        "mr	5,0\n"
        ".long 0x4bedb959  /* bl memcpy */\n"
        "mr	4,30\n"
        "li	5,4\n"
        "addi	3,31,100\n"
        "addi	30,30,4\n"
        ".long 0x4bedb945  /* bl memcpy */\n"
        "mr	4,30\n"
        "li	5,4\n"
        "addi	3,31,104\n"
        "addi	30,30,4\n"
        ".long 0x4bedb931  /* bl memcpy */\n"
        "mr	4,30\n"
        "li	5,4\n"
        "addi	3,31,108\n"
        "addi	30,30,4\n"
        ".long 0x4bedb91d  /* bl memcpy */\n"
        "mr	4,30\n"
        "li	5,1\n"
        "addi	3,31,114\n"
        "addi	30,30,1\n"
        ".long 0x4bedb909  /* bl memcpy */\n"
        "mr	4,30\n"
        "li	5,4\n"
        "addi	3,31,116\n"
        "addi	30,30,4\n"
        ".long 0x4bedb8f5  /* bl memcpy */\n"
        "mr	4,30\n"
        "li	5,4\n"
        "addi	3,31,120\n"
        "addi	30,30,4\n"
        ".long 0x4bedb8e1  /* bl memcpy */\n"
        "mr	4,30\n"
        "li	5,4\n"
        "addi	3,31,124\n"
        "addi	30,30,4\n"
        ".long 0x4bedb8cd  /* bl memcpy */\n"
        "mr	4,30\n"
        "li	5,4\n"
        "addi	3,31,128\n"
        "addi	30,30,4\n"
        ".long 0x4bedb8b9  /* bl memcpy */\n"
        "mr	4,30\n"
        "li	5,1\n"
        "addi	3,31,112\n"
        "addi	30,30,1\n"
        ".long 0x4bedb8a5  /* bl memcpy */\n"
        "mr	4,30\n"
        "li	5,1\n"
        "addi	3,31,113\n"
        "addi	30,30,1\n"
        ".long 0x4bedb891  /* bl memcpy */\n"
        "mr	4,30\n"
        "mr	3,28\n"
        ".long 0x4bfffbfd  /* bl CopyERAnimNoteArray(TArray<EAnimNote, TArrayERAnimAllocator> &, char *) */\n"
        "add	30,30,3\n"
        "mr	4,30\n"
        "addi	3,31,148\n"
        ".long 0x4bfffcc9  /* bl CopyERAnimEventArray(TArray<EAnimEvent, TArrayERAnimAllocator> &, char *) */\n"
        "lwz	0,24(31)\n"
        "lis	8,17200\n"
        "lis	9,-32702\n"
        "xoris	0,0,32768\n"
        "lfd	13,12928(9)\n"
        "stw	0,44(1)\n"
        "lis	9,-32702\n"
        "lfs	10,100(31)\n"
        "mr	10,11\n"
        "stw	8,40(1)\n"
        "lfs	11,12936(9)\n"
        "lfd	0,40(1)\n"
        "fsub	0,0,13\n"
        "frsp	0,0\n"
        "fdivs	0,0,10\n"
        "fmuls	0,0,11\n"
        "fmr	13,0\n"
        "fctiwz	12,13\n"
        "stfd	12,40(1)\n"
        "lwz	0,44(1)\n"
        "stw	0,20(31)\n"
        "lwz	9,4(28)\n"
        "cmpwi	9,0\n"
        "beq	.L_80367C60\n"
        "addi	9,9,-1\n"
        "lwz	11,136(31)\n"
        "mulli	9,9,12\n"
        "lwzx	9,11,9\n"
        "cmpw	9,0\n"
        "ble	.L_80367C60\n"
        "stw	9,20(31)\n"
        ".L_80367C60:\n"
        ".long 0x4bf682a1  /* bl MainHeap(void) */\n"
        "mr	4,26\n"
        ".long 0x4bf69111  /* bl EAHeap::Free(void *) */\n"
        "b	.L_80367C7C\n"
        ".L_80367C70:\n"
        "mr	3,31\n"
        "mr	4,27\n"
        ".long 0x48000025  /* bl ERAnim::OldLoad(EFile *) */\n"
        ".L_80367C7C:\n"
        "addi	3,1,8\n"
        "li	4,2\n"
        ".long 0x4bff3225  /* bl EDataHeader::~EDataHeader(void) */\n"
        "lwz	0,76(1)\n"
        "mtlr	0\n"
        "lmw	26,48(1)\n"
        "addi	1,1,72\n"
        "blr\n"
    );
    __builtin_unreachable();
}

// 0x80367C9C (672 bytes)
// ERAnim::OldLoad(EFile *)
__attribute__((noreturn))
void ERAnim::OldLoad(EFile *) {
    __asm__ __volatile__(
        "stwu	1,-80(1)\n"
        "mflr	0\n"
        "stmw	27,60(1)\n"
        "stw	0,84(1)\n"
        "mr	31,3\n"
        "mr	27,4\n"
        "addi	3,1,8\n"
        ".long 0x4bff31b9  /* bl EDataHeader::EDataHeader(void) */\n"
        "lis	5,16718\n"
        "addi	3,1,8\n"
        "mr	4,27\n"
        "ori	5,5,18765\n"
        "li	6,17\n"
        "li	7,17\n"
        ".long 0x4bff33c9  /* bl EDataHeader::Read(EFile &, unsigned int, unsigned int, unsigned int) */\n"
        "cmpwi	3,0\n"
        "beq	.L_80367F1C\n"
        "addi	3,1,8\n"
        "addi	29,31,80\n"
        ".long 0x4bff3639  /* bl EDataHeader::GetName(void) */\n"
        "lwz	9,24(1)\n"
        "lwz	0,16(31)\n"
        "rlwimi	0,9,8,0,23\n"
        "stw	0,16(31)\n"
        ".long 0x4bf68205  /* bl MainHeap(void) */\n"
        "lwz	4,24(1)\n"
        "li	5,0\n"
        ".long 0x4bf68d9d  /* bl EAHeap::Malloc(unsigned int, int) */\n"
        "lwz	9,40(27)\n"
        "mr	28,3\n"
        "lwz	5,24(1)\n"
        "mr	4,28\n"
        "lwz	0,28(9)\n"
        "addi	30,28,28\n"
        "lha	3,24(9)\n"
        "mtlr	0\n"
        "add	3,27,3\n"
        "blrl\n"
        "mr	4,28\n"
        "li	5,4\n"
        "addi	3,31,24\n"
        ".long 0x4bedb715  /* bl memcpy */\n"
        "addi	4,28,4\n"
        "li	5,12\n"
        "addi	3,31,28\n"
        ".long 0x4bedb705  /* bl memcpy */\n"
        "li	5,12\n"
        "addi	4,28,16\n"
        "addi	3,31,40\n"
        ".long 0x4bedb6f5  /* bl memcpy */\n"
        "mr	4,30\n"
        "addi	3,31,52\n"
        ".long 0x4bfff871  /* bl CopyERAnimNodeArray(TArray<EAnimNodeDataPos, TArrayERAnimAllocator> &, char *) */\n"
        "add	30,30,3\n"
        "li	5,4\n"
        "mr	4,30\n"
        "addi	3,31,64\n"
        ".long 0x4bedb6d5  /* bl memcpy */\n"
        "addi	30,30,4\n"
        "mr	4,30\n"
        "addi	3,31,68\n"
        ".long 0x4bfff9a9  /* bl CopyERAnimConstantArray(TArray<float, TArrayERAnimAllocator> &, char *) */\n"
        "add	30,30,3\n"
        "li	5,4\n"
        "addi	3,1,32\n"
        "mr	4,30\n"
        ".long 0x4bedb6b1  /* bl memcpy */\n"
        "addi	30,30,4\n"
        "mr	3,29\n"
        "li	4,0\n"
        "li	5,0\n"
        ".long 0x4bf77b35  /* bl EBitArray::SetSize(int, int) */\n"
        "lwz	4,32(1)\n"
        "li	5,0\n"
        "mr	3,29\n"
        ".long 0x4bf77b25  /* bl EBitArray::SetSize(int, int) */\n"
        "mr	3,29\n"
        ".long 0x4bf77ef5  /* bl EBitArray::GetElementCount(void) const */\n"
        "slwi	0,3,2\n"
        "mr	4,30\n"
        "lwz	3,80(31)\n"
        "add	30,30,0\n"
        "mr	5,0\n"
        ".long 0x4bedb66d  /* bl memcpy */\n"
        "mr	4,30\n"
        "li	5,4\n"
        "addi	3,31,100\n"
        "addi	30,30,4\n"
        ".long 0x4bedb659  /* bl memcpy */\n"
        "mr	4,30\n"
        "li	5,4\n"
        "addi	3,31,104\n"
        "addi	30,30,4\n"
        ".long 0x4bedb645  /* bl memcpy */\n"
        "mr	4,30\n"
        "li	5,4\n"
        "addi	3,31,108\n"
        "addi	30,30,4\n"
        ".long 0x4bedb631  /* bl memcpy */\n"
        "mr	4,30\n"
        "li	5,1\n"
        "addi	3,31,114\n"
        "addi	30,30,1\n"
        ".long 0x4bedb61d  /* bl memcpy */\n"
        "mr	4,30\n"
        "li	5,4\n"
        "addi	3,31,116\n"
        "addi	30,30,4\n"
        ".long 0x4bedb609  /* bl memcpy */\n"
        "mr	4,30\n"
        "li	5,4\n"
        "addi	3,31,120\n"
        "addi	30,30,4\n"
        ".long 0x4bedb5f5  /* bl memcpy */\n"
        "mr	4,30\n"
        "li	5,4\n"
        "addi	3,31,124\n"
        "addi	30,30,4\n"
        ".long 0x4bedb5e1  /* bl memcpy */\n"
        "mr	4,30\n"
        "li	5,4\n"
        "addi	3,31,128\n"
        "addi	30,30,4\n"
        ".long 0x4bedb5cd  /* bl memcpy */\n"
        "mr	4,30\n"
        "li	5,1\n"
        "addi	3,31,112\n"
        "addi	30,30,1\n"
        ".long 0x4bedb5b9  /* bl memcpy */\n"
        "li	5,1\n"
        "mr	4,30\n"
        "addi	3,31,113\n"
        ".long 0x4bedb5a9  /* bl memcpy */\n"
        "addi	4,30,1\n"
        "addi	3,31,148\n"
        ".long 0x4bfff9f1  /* bl CopyERAnimEventArray(TArray<EAnimEvent, TArrayERAnimAllocator> &, char *) */\n"
        "lwz	0,24(31)\n"
        "lis	8,17200\n"
        "lis	9,-32702\n"
        "xoris	0,0,32768\n"
        "lfd	13,12944(9)\n"
        "stw	0,52(1)\n"
        "lis	10,-32702\n"
        "lfs	10,100(31)\n"
        "mr	9,11\n"
        "stw	8,48(1)\n"
        "lfs	11,12952(10)\n"
        "lfd	0,48(1)\n"
        "fsub	0,0,13\n"
        "frsp	0,0\n"
        "fdivs	0,0,10\n"
        "fmuls	0,0,11\n"
        "fmr	13,0\n"
        "fctiwz	12,13\n"
        "stfd	12,48(1)\n"
        "lwz	9,52(1)\n"
        "stw	9,20(31)\n"
        ".long 0x4bf67ff1  /* bl MainHeap(void) */\n"
        "mr	4,28\n"
        ".long 0x4bf68e61  /* bl EAHeap::Free(void *) */\n"
        ".L_80367F1C:\n"
        "addi	3,1,8\n"
        "li	4,2\n"
        ".long 0x4bff2f85  /* bl EDataHeader::~EDataHeader(void) */\n"
        "lwz	0,84(1)\n"
        "mtlr	0\n"
        "lmw	27,60(1)\n"
        "addi	1,1,80\n"
        "blr\n"
    );
    __builtin_unreachable();
}

// 0x803680D4 (84 bytes)
// ERAnim::RegisterType(unsigned short)
__attribute__((noreturn))
void ERAnim::RegisterType(unsigned short) {
    __asm__ __volatile__(
        "stwu	1,-8(1)\n"
        "mflr	0\n"
        "stw	0,12(1)\n"
        "mr	7,3\n"
        "lis	4,-32714\n"
        "lis	3,-32688\n"
        "lis	5,-32714\n"
        "lis	6,-32713\n"
        "lis	8,-32702\n"
        "lis	9,-32688\n"
        "addi	3,3,-10364\n"
        "addi	4,4,32724\n"
        "addi	5,5,32764\n"
        "addi	6,6,-32728\n"
        "addi	8,8,12824\n"
        "addi	9,9,-13000\n"
        ".long 0x4bf6d7b9  /* bl ETypeInfo::Register(EStorable *(*)(void), void (*)(void *), void (*)(void *), unsigned short, char *, ETypeInfo *) */\n"
        "lwz	0,12(1)\n"
        "mtlr	0\n"
        "addi	1,1,8\n"
        "blr\n"
    );
    __builtin_unreachable();
}



// TypeInfo getter implementations

struct TypeInfo;
extern TypeInfo ERAnim_typeInfo;

// 0x8036808C (12 bytes)
const TypeInfo* ERAnim::GetTypeInfo() const {
    return &ERAnim_typeInfo;
}

// 0x80368098 (12 bytes)
const char* ERAnim::GetTypeName() const {
    return *(const char**)((char*)&ERAnim_typeInfo + 0x0C);
}

// 0x803680A4 (12 bytes)
u32 ERAnim::GetTypeKey() const {
    return *(u32*)((char*)&ERAnim_typeInfo + 0x10);
}

// 0x803680B0 (12 bytes)
u16 ERAnim::GetTypeVersion() const {
    return *(u16*)((char*)&ERAnim_typeInfo + 0x14);
}

// 0x803680BC (12 bytes)
const TypeInfo* ERAnim::GetTypeInfoStatic() {
    return &ERAnim_typeInfo;
}

// 0x803680C8 (12 bytes)
u16 ERAnim::GetReadVersion() {
    return *(u16*)((char*)&ERAnim_typeInfo + 0x16);
}


struct TypeInfo;
extern TypeInfo EAnimNodeDataPos_typeInfo;

// 0x803C9800 (12 bytes)
const TypeInfo* EAnimNodeDataPos::GetTypeInfo() const {
    return &EAnimNodeDataPos_typeInfo;
}

// 0x803C980C (12 bytes)
const char* EAnimNodeDataPos::GetTypeName() const {
    return *(const char**)((char*)&EAnimNodeDataPos_typeInfo + 0x0C);
}

// 0x803C9818 (12 bytes)
u32 EAnimNodeDataPos::GetTypeKey() const {
    return *(u32*)((char*)&EAnimNodeDataPos_typeInfo + 0x10);
}

// 0x803C9824 (12 bytes)
u16 EAnimNodeDataPos::GetTypeVersion() const {
    return *(u16*)((char*)&EAnimNodeDataPos_typeInfo + 0x14);
}

