#include "types.h"
// Auto-generated inline asm decomp stubs for cHitControlGroup
// Generated by gen_asm_decomp.py
// 1 functions, 192 bytes
//
// Each function has its original C++ signature with the body as inline PPC asm.
// These can be incrementally replaced with real C++ as decompilation progresses.

class cHitControlGroup {
public:
    void SetVolume(int);
};

// 0x801167C8 (192 bytes)
// cHitControlGroup::SetVolume(int)
__attribute__((noreturn))
void cHitControlGroup::SetVolume(int) {
    __asm__ __volatile__(
        "stwu	1,-48(1)\n"
        "mflr	0\n"
        "stmw	30,40(1)\n"
        "stw	0,52(1)\n"
        "lwz	9,-24136(13)\n"
        "mr	30,3\n"
        "stw	4,4(30)\n"
        "addi	9,9,4\n"
        "lwz	0,4(9)\n"
        "stw	0,16(1)\n"
        "lwz	11,4(9)\n"
        "lwz	0,0(11)\n"
        "stw	0,8(1)\n"
        "stw	0,24(1)\n"
        "b	.L_80116850\n"
        ".L_80116804:\n"
        "lwz	9,-24136(13)\n"
        "lwz	31,8(3)\n"
        "lwz	3,80(9)\n"
        "mr	4,31\n"
        ".long 0x48003535  /* bl cSoundCache::IsInMemory(cTrack *) const */\n"
        "cmpwi	3,0\n"
        "beq	.L_8011683C\n"
        "mr	3,31\n"
        ".long 0x4800261d  /* bl cTrack::GetControlGroup(void) */\n"
        "lwz	0,0(30)\n"
        "cmpw	3,0\n"
        "bne	.L_8011683C\n"
        "mr	3,31\n"
        ".long 0x4800259d  /* bl cTrack::UpdateVolPan(void) */\n"
        ".L_8011683C:\n"
        "lwz	9,8(1)\n"
        "stw	9,32(1)\n"
        "lwz	0,0(9)\n"
        "stw	9,24(1)\n"
        "stw	0,8(1)\n"
        ".L_80116850:\n"
        "lwz	3,8(1)\n"
        "li	9,1\n"
        "lwz	0,16(1)\n"
        "cmpw	3,0\n"
        "bne	.L_80116868\n"
        "li	9,0\n"
        ".L_80116868:\n"
        "cmpwi	9,0\n"
        "bne	.L_80116804\n"
        "li	3,1\n"
        "lwz	0,52(1)\n"
        "mtlr	0\n"
        "lmw	30,40(1)\n"
        "addi	1,1,48\n"
        "blr\n"
    );
    __builtin_unreachable();
}

