#include "types.h"
// Inline asm leaf matches for CASMorphTarget
// 1 functions, 184 bytes

#include "types.h"
// Auto-generated inline asm decomp stubs for CASMorphTarget
// Generated by gen_asm_decomp.py
// 8 functions, 3532 bytes
//
// Each function has its original C++ signature with the body as inline PPC asm.
// These can be incrementally replaced with real C++ as decompilation progresses.

struct UIScreenID {};

class CASMorphTarget {
public:
    CASMorphTarget(void);
    ~CASMorphTarget(void);
    void SetVariable(char *, char *);
    void SetVariableSubnav(UIScreenID, int, int);
    void GetLocalizableSubnav(UIScreenID, int, unsigned short *);
    void GetVariable(char *);
    void EnterMorphScreen(void);
    void ExitMorphScreenPrev(void);
};


// 0x8019CF0C (184 bytes)
// CASMorphTarget::SetVariableSubnav(UIScreenID, int, int)
__attribute__((noreturn))
void CASMorphTarget::SetVariableSubnav(UIScreenID, int, int) {
    __asm__ __volatile__(
        "mr.	6,6\n"
        "bnelr\n"
        "cmpwi	4,6\n"
        "bne	.L_8019CF5C\n"
        "cmpwi	5,1\n"
        "beq	.L_8019CF48\n"
        "bgt	.L_8019CF34\n"
        "cmpwi	5,0\n"
        "beq	.L_8019CF40\n"
        "blr\n"
        ".L_8019CF34:\n"
        "cmpwi	5,2\n"
        "beq	.L_8019CF50\n"
        "blr\n"
        ".L_8019CF40:\n"
        "stw	6,140(3)\n"
        "blr\n"
        ".L_8019CF48:\n"
        "stw	5,140(3)\n"
        "blr\n"
        ".L_8019CF50:\n"
        "li	0,3\n"
        "stw	0,140(3)\n"
        "blr\n"
        ".L_8019CF5C:\n"
        "cmpwi	4,8\n"
        "bnelr\n"
        "cmpwi	5,2\n"
        "beq	.L_8019CFAC\n"
        "bgt	.L_8019CF84\n"
        "cmpwi	5,0\n"
        "beq	.L_8019CF94\n"
        "cmpwi	5,1\n"
        "beq	.L_8019CFA4\n"
        "blr\n"
        ".L_8019CF84:\n"
        "cmpwi	5,4\n"
        "beq	.L_8019CFBC\n"
        "blt	.L_8019CFB4\n"
        "blr\n"
        ".L_8019CF94:\n"
        "li	0,2\n"
        ".L_8019CF98:\n"
        "stw	6,152(3)\n"
        "stw	0,140(3)\n"
        "blr\n"
        ".L_8019CFA4:\n"
        "li	0,4\n"
        "b	.L_8019CF98\n"
        ".L_8019CFAC:\n"
        "li	0,6\n"
        "b	.L_8019CF98\n"
        ".L_8019CFB4:\n"
        "li	0,5\n"
        "b	.L_8019CF98\n"
        ".L_8019CFBC:\n"
        "li	0,7\n"
        "b	.L_8019CF98\n"
    );
}

