#include "types.h"
#include "stub_classes.h"
// Auto-converted call wrapper stubs for WantFearManager
// Generated by convert_call_wrappers.py

// 0x8014BCB8 (76 bytes)
// Call wrapper [2bl_with_branch]: EResource::DelRef(void), __builtin_delete
__attribute__((noreturn))
WantFearManager::~WantFearManager(void) {
    __asm__ __volatile__(
        "stwu	1,-16(1)\n"
        "mflr	0\n"
        "stmw	30,8(1)\n"
        "stw	0,20(1)\n"
        "mr	31,3\n"
        "mr	30,4\n"
        "lwz	3,0(31)\n"
        "cmpwi	3,0\n"
        "beq	.L_8014BCE0\n"
        ".long 0x481c6295  /* bl EResource::DelRef(void) */\n"
        ".L_8014BCE0:\n"
        "andi.	0,30,1\n"
        "beq	.L_8014BCF0\n"
        "mr	3,31\n"
        ".long 0x48185535  /* bl __builtin_delete */\n"
        ".L_8014BCF0:\n"
        "lwz	0,20(1)\n"
        "mtlr	0\n"
        "lmw	30,8(1)\n"
        "addi	1,1,16\n"
        "blr\n"
    );
    __builtin_unreachable();
}
