#include "types.h"
#include "stub_classes.h"
// Auto-generated matching constructors for AwarenessManager
// Generated by gen_ctor_matches.py (inline asm)
// 1 functions, 96 bytes

// 0x80011EEC (96 bytes)
__attribute__((noreturn))
AwarenessManager::AwarenessManager() {
    __asm__ __volatile__(
        "lis	10,-32707\n""lis	11,-32698\n""lfs	0,-9136(10)\n""mr	9,3\n""li	0,0\n""addi	11,11,-21040\n""li	10,-1\n""stw	11,68(9)\n""stw	10,20(9)\n""stfs	0,48(9)\n""stw	0,0(9)\n""stfs	0,12(9)\n""stfs	0,16(9)\n""stw	0,24(9)\n""stw	0,28(9)\n""stfs	0,32(9)\n""stw	0,64(9)\n""stfs	0,60(9)\n""stw	0,36(9)\n""stw	0,40(9)\n""stfs	0,44(9)\n""stw	0,52(9)\n""stw	0,56(9)\n""blr\n"
    );
    __builtin_unreachable();
}
