#include "types.h"
// Auto-generated inline asm decomp stubs for AptCharacterSpriteInstBase
// Generated by gen_asm_decomp.py
// 2 functions, 464 bytes
//
// Each function has its original C++ signature with the body as inline PPC asm.
// These can be incrementally replaced with real C++ as decompilation progresses.

class AptCharacterSpriteInstBase {
public:
    AptCharacterSpriteInstBase(void);
    ~AptCharacterSpriteInstBase(void);
};

// 0x802881B8 (320 bytes)
// AptCharacterSpriteInstBase::AptCharacterSpriteInstBase(void)
__attribute__((noreturn))
AptCharacterSpriteInstBase::AptCharacterSpriteInstBase(void) {
    __asm__ __volatile__(
        "stwu	1,-24(1)\n"
        "mflr	0\n"
        "stmw	29,12(1)\n"
        "stw	0,28(1)\n"
        "mr	31,3\n"
        "li	30,0\n"
        "li	29,-1\n"
        "lis	9,-32704\n"
        "addi	9,9,20176\n"
        "stw	30,16(31)\n"
        "stw	29,0(31)\n"
        "addi	3,31,36\n"
        "stw	30,8(31)\n"
        "stw	30,12(31)\n"
        "stw	9,20(31)\n"
        ".long 0x48012d99  /* bl AptDisplayList::AptDisplayList(void) */\n"
        "lwz	0,28(31)\n"
        "li	4,20\n"
        "stw	30,32(31)\n"
        "rlwinm	0,0,0,25,23\n"
        "stw	30,40(31)\n"
        "ori	0,0,64\n"
        "lwz	3,-23020(13)\n"
        "rlwimi	0,30,4,26,27\n"
        "rlwimi	0,30,8,0,23\n"
        "stw	0,28(31)\n"
        ".long 0x4802d629  /* bl DOGMA_PoolManager::Allocate(unsigned int) */\n"
        "li	4,8\n"
        ".long 0x48021661  /* bl AptNativeHash::AptNativeHash(int) */\n"
        "lwz	9,-26996(13)\n"
        "lis	4,-32694\n"
        "stw	3,12(31)\n"
        "addi	4,4,-11332\n"
        "stw	29,24(31)\n"
        "addi	4,4,376\n"
        "stw	30,44(31)\n"
        "addi	3,9,12\n"
        ".long 0x48021d51  /* bl AptNativeHash::Lookup(EAStringC *) const */\n"
        "lwz	9,8(3)\n"
        "lha	0,32(9)\n"
        "lwz	9,36(9)\n"
        "add	3,3,0\n"
        "mtlr	9\n"
        "blrl\n"
        "lwz	30,12(3)\n"
        "lwz	29,12(31)\n"
        "cmpwi	30,0\n"
        "beq	.L_802882A4\n"
        "lwz	9,8(30)\n"
        "lis	4,-32704\n"
        "lis	5,-32704\n"
        "addi	4,4,16788\n"
        "lha	3,8(9)\n"
        "addi	5,5,16836\n"
        "lwz	0,12(9)\n"
        "li	6,80\n"
        "add	3,30,3\n"
        "mtlr	0\n"
        "blrl\n"
        ".L_802882A4:\n"
        "lwz	11,8(29)\n"
        "cmpwi	11,0\n"
        "beq	.L_802882DC\n"
        "lwz	9,8(11)\n"
        "lis	4,-32704\n"
        "lis	5,-32704\n"
        "addi	4,4,16788\n"
        "lha	3,16(9)\n"
        "addi	5,5,16836\n"
        "lwz	0,20(9)\n"
        "li	6,81\n"
        "add	3,11,3\n"
        "mtlr	0\n"
        "blrl\n"
        ".L_802882DC:\n"
        "stw	30,8(29)\n"
        "mr	3,31\n"
        "lwz	0,28(1)\n"
        "mtlr	0\n"
        "lmw	29,12(1)\n"
        "addi	1,1,24\n"
        "blr\n"
    );
    __builtin_unreachable();
}

// 0x802882F8 (144 bytes)
// AptCharacterSpriteInstBase::~AptCharacterSpriteInstBase(void)
__attribute__((noreturn))
AptCharacterSpriteInstBase::~AptCharacterSpriteInstBase(void) {
    __asm__ __volatile__(
        "stwu	1,-16(1)\n"
        "mflr	0\n"
        "stmw	30,8(1)\n"
        "stw	0,20(1)\n"
        "mr	31,3\n"
        "lis	9,-32704\n"
        "lwz	0,44(31)\n"
        "addi	9,9,20176\n"
        "mr	30,4\n"
        "stw	9,20(31)\n"
        "cmpwi	0,1\n"
        "bne	.L_80288338\n"
        "lwz	3,-23020(13)\n"
        "li	5,64\n"
        "lwz	4,8(31)\n"
        ".long 0x4802d659  /* bl DOGMA_PoolManager::Deallocate(void *, unsigned int) */\n"
        ".L_80288338:\n"
        "addi	3,31,36\n"
        "li	4,2\n"
        ".long 0x48012c8d  /* bl AptDisplayList::~AptDisplayList(void) */\n"
        "lwz	3,12(31)\n"
        "lis	9,-32704\n"
        "addi	9,9,20216\n"
        "stw	9,20(31)\n"
        "cmpwi	3,0\n"
        "beq	.L_80288364\n"
        "li	4,3\n"
        ".long 0x4802156d  /* bl AptNativeHash::~AptNativeHash(void) */\n"
        ".L_80288364:\n"
        "andi.	0,30,1\n"
        "beq	.L_80288374\n"
        "mr	3,31\n"
        ".long 0x48048eb1  /* bl __builtin_delete */\n"
        ".L_80288374:\n"
        "lwz	0,20(1)\n"
        "mtlr	0\n"
        "lmw	30,8(1)\n"
        "addi	1,1,16\n"
        "blr\n"
    );
    __builtin_unreachable();
}

