#include "types.h"
#include "stub_classes.h"
// Auto-generated raw-byte matches for EApp
// Generated by gen_raw_byte_matches.py
// 4 functions, 168 bytes
// These functions are matched by directly injecting DOL bytes into the skeleton.
// The C++ stubs below exist only as annotations for the matching pipeline.

// 0x802E21E0 (52 bytes)
// EApp__dtor_EApp_void
// [raw byte match - injected directly from DOL]

// 0x802E247C (52 bytes)
// EApp__SystemInit_void
// [raw byte match - injected directly from DOL]

// 0x802E26F0 (32 bytes)
// EApp__PlayMovie_unsigned_int__int__int
// [raw byte match - injected directly from DOL]

// 0x802E28F0 (32 bytes)
// EApp__GetMovieHeap_void
// [raw byte match - injected directly from DOL]

