#include "types.h"
#include "stub_classes.h"
// Auto-generated raw-byte matches for Vsprintf_char_ptr
// Generated by gen_raw_byte_matches.py
// 1 functions, 52 bytes
// These functions are matched by directly injecting DOL bytes into the skeleton.
// The C++ stubs below exist only as annotations for the matching pipeline.

// 0x802DE9B4 (52 bytes)
// Vsprintf_char_ptr__char_ptr__va_list_tag_ptr
// [raw byte match - injected directly from DOL]

