#include "types.h"
#include "stub_classes.h"
// Auto-generated raw-byte matches for XOSFontSetXFB_void_ptr
// Generated by gen_raw_byte_matches.py
// 1 functions, 16 bytes
// These functions are matched by directly injecting DOL bytes into the skeleton.
// The C++ stubs below exist only as annotations for the matching pipeline.

// 0x8032ED58 (16 bytes)
// XOSFontSetXFB_void_ptr__int__int
// [raw byte match - injected directly from DOL]

