#include "types.h"
// Auto-generated inline asm decomp stubs for TheSimsEAMovieState
// Generated by gen_asm_decomp.py
// 3 functions, 456 bytes
//
// Each function has its original C++ signature with the body as inline PPC asm.
// These can be incrementally replaced with real C++ as decompilation progresses.

class TheSimsEAMovieState {
public:
    void Startup(void);
    void Update(float);
    void Shutdown(void);
};

// 0x800971C8 (288 bytes)
// TheSimsEAMovieState::Startup(void)
__attribute__((noreturn))
void TheSimsEAMovieState::Startup(void) {
    __asm__ __volatile__(
        "stwu	1,-16(1)\n"
        "mflr	0\n"
        "stw	31,12(1)\n"
        "stw	0,20(1)\n"
        "mr	31,3\n"
        ".long 0x48238c89  /* bl RootHeap(void) */\n"
        ".long 0x48239c49  /* bl EAHeap::Compact(void) */\n"
        ".long 0x48238d1d  /* bl MainHeap(void) */\n"
        ".long 0x48239c41  /* bl EAHeap::Compact(void) */\n"
        ".long 0x48238db5  /* bl ResourceHeap(void) */\n"
        ".long 0x48239c39  /* bl EAHeap::Compact(void) */\n"
        ".long 0x48239029  /* bl AudioHeap(void) */\n"
        ".long 0x48239c31  /* bl EAHeap::Compact(void) */\n"
        ".long 0x48238e45  /* bl VMHeap(void) */\n"
        ".long 0x48239c29  /* bl EAHeap::Compact(void) */\n"
        ".long 0x482390c9  /* bl ShaderHeap(void) */\n"
        ".long 0x48239c21  /* bl EAHeap::Compact(void) */\n"
        ".long 0x48239171  /* bl TextureHeap(void) */\n"
        ".long 0x48239c19  /* bl EAHeap::Compact(void) */\n"
        ".long 0x48239219  /* bl AnimationHeap(void) */\n"
        ".long 0x48239c11  /* bl EAHeap::Compact(void) */\n"
        ".long 0x482392c1  /* bl ModelHeap(void) */\n"
        ".long 0x48239c09  /* bl EAHeap::Compact(void) */\n"
        ".long 0x48239369  /* bl FlashesHeap(void) */\n"
        ".long 0x48239c01  /* bl EAHeap::Compact(void) */\n"
        ".long 0x48239401  /* bl AptHeap(void) */\n"
        ".long 0x48239bf9  /* bl EAHeap::Compact(void) */\n"
        ".long 0x48238ead  /* bl DebugHeap(void) */\n"
        ".long 0x48239bf1  /* bl EAHeap::Compact(void) */\n"
        ".long 0x48238f41  /* bl CUIHeap(void) */\n"
        ".long 0x48239be9  /* bl EAHeap::Compact(void) */\n"
        ".long 0x48239769  /* bl EAHeap::SetNextCheckPoint(void) */\n"
        "lwz	10,-26564(13)\n"
        "lis	9,-32706\n"
        "lwz	11,0(10)\n"
        "lfs	1,-29812(9)\n"
        "lha	3,96(11)\n"
        "lwz	0,100(11)\n"
        "add	3,10,3\n"
        "mtlr	0\n"
        "blrl\n"
        "lis	9,-32697\n"
        "lwz	9,25096(9)\n"
        "cmpwi	9,0\n"
        "beq	.L_80097294\n"
        "lis	9,-32706\n"
        "mr	3,31\n"
        "lfs	1,-29808(9)\n"
        "li	4,3\n"
        ".long 0x4bffe819  /* bl StateMachineState::OwnerSetNextState(int, float) */\n"
        "b	.L_800972C8\n"
        ".L_80097294:\n"
        "stw	9,-28408(13)\n"
        "li	0,1\n"
        "stw	9,-28404(13)\n"
        "lis	3,-32697\n"
        "stw	0,28(31)\n"
        "addi	3,3,23428\n"
        ".long 0x4bfa63f5  /* bl GameData::GetLocalizedEAMovie(void) */\n"
        "mr	4,3\n"
        "li	5,-1\n"
        "lis	3,-32697\n"
        "li	6,-1\n"
        "addi	3,3,-7672\n"
        ".long 0x4824b42d  /* bl EApp::PlayMovie(unsigned int, int, int) */\n"
        ".L_800972C8:\n"
        "lis	3,-32697\n"
        "addi	3,3,23428\n"
        ".long 0x4bfa64f9  /* bl GameData::SetBlackGraphicsBackgroundColor(void) */\n"
        "lwz	0,20(1)\n"
        "mtlr	0\n"
        "lwz	31,12(1)\n"
        "addi	1,1,16\n"
        "blr\n"
    );
    __builtin_unreachable();
}

// 0x800972E8 (96 bytes)
// TheSimsEAMovieState::Update(float)
__attribute__((noreturn))
void TheSimsEAMovieState::Update(float) {
    __asm__ __volatile__(
        "stwu	1,-16(1)\n"
        "mflr	0\n"
        "stmw	30,8(1)\n"
        "stw	0,20(1)\n"
        "mr	30,3\n"
        "lis	31,-32697\n"
        "addi	3,31,-7672\n"
        ".long 0x4824b419  /* bl EApp::IsMovieStarting(void) */\n"
        "cmpwi	3,0\n"
        "bne	.L_80097334\n"
        "addi	3,31,-7672\n"
        ".long 0x4824b421  /* bl EApp::IsMoviePlaying(void) */\n"
        "cmpwi	3,0\n"
        "bne	.L_80097334\n"
        "lis	9,-32706\n"
        "mr	3,30\n"
        "lfs	1,-29804(9)\n"
        "li	4,3\n"
        ".long 0x4bffe775  /* bl StateMachineState::OwnerSetNextState(int, float) */\n"
        ".L_80097334:\n"
        "lwz	0,20(1)\n"
        "mtlr	0\n"
        "lmw	30,8(1)\n"
        "addi	1,1,16\n"
        "blr\n"
    );
    __builtin_unreachable();
}

// 0x80097348 (72 bytes)
// TheSimsEAMovieState::Shutdown(void)
__attribute__((noreturn))
void TheSimsEAMovieState::Shutdown(void) {
    __asm__ __volatile__(
        "stwu	1,-8(1)\n"
        "mflr	0\n"
        "stw	0,12(1)\n"
        "lwz	0,28(3)\n"
        "cmpwi	0,0\n"
        "beq	.L_80097374\n"
        "li	0,1\n"
        "li	9,0\n"
        "stw	0,-28408(13)\n"
        "stw	0,-28404(13)\n"
        "stw	9,28(3)\n"
        ".L_80097374:\n"
        "lis	3,-32697\n"
        "addi	3,3,23428\n"
        ".long 0x4bfa64a9  /* bl GameData::SetUglyGraphicsBackgroundColor(void) */\n"
        "lwz	0,12(1)\n"
        "mtlr	0\n"
        "addi	1,1,8\n"
        "blr\n"
    );
    __builtin_unreachable();
}

