#include "types.h"
// Auto-generated inline asm decomp stubs for EResPrefetch
// Generated by gen_asm_decomp.py
// 19 functions, 2896 bytes
//
// Each function has its original C++ signature with the body as inline PPC asm.
// These can be incrementally replaced with real C++ as decompilation progresses.

class EPrefetchMsg;
class EScratchBuffUser;

class EResPrefetch {
public:
    EResPrefetch(void);
    ~EResPrefetch(void);
    void Init(void);
    void Shutdown(void);
    void ReleasedBuffer(EScratchBuffUser *);
    void DoCancel(EPrefetchMsg *);
    void DoBegin(EPrefetchMsg *);
    void LoadAnotherBlock(void);
    void DoFlush(EPrefetchMsg *);
    void Main(void);
    void Flush(void);
    void Cancel(void);
    void BeginPreFetch(char *, char *);
    void BeginPreFetch(char *, unsigned int);
    void AddRef(char *, char *);
    void AddRef(char *, unsigned int);
    void CanAddRef(void);
    void CanReleaseBuffer(void);
    void ResetState(void);
};

// 0x80312380 (140 bytes)
// EResPrefetch::EResPrefetch(void)
__attribute__((noreturn))
EResPrefetch::EResPrefetch(void) {
    __asm__ __volatile__(
        "stwu	1,-16(1)\n"
        "mflr	0\n"
        "stmw	30,8(1)\n"
        "stw	0,20(1)\n"
        "lis	9,-32697\n"
        "mr	30,3\n"
        "addi	9,9,-19680\n"
        "addi	3,30,8\n"
        "stw	9,0(30)\n"
        ".long 0x4bfc5cfd  /* bl EThread::EThread(void) */\n"
        "lis	9,-32697\n"
        "lis	11,-32697\n"
        "addi	9,9,-19760\n"
        "addi	11,11,-19728\n"
        "stw	9,832(30)\n"
        "addi	3,30,840\n"
        "stw	11,0(30)\n"
        ".long 0x48000bed  /* bl EResPrefetchFile::EResPrefetchFile(void) */\n"
        "addi	3,30,908\n"
        ".long 0x4804a0d9  /* bl EMsgQueue::EMsgQueue(void) */\n"
        "lis	0,-8531\n"
        "mr	3,30\n"
        "ori	0,0,48815\n"
        "stw	0,1024(30)\n"
        "stw	0,1016(30)\n"
        "stw	0,1020(30)\n"
        ".long 0x48000afd  /* bl EResPrefetch::ResetState(void) */\n"
        "li	0,0\n"
        "mr	3,30\n"
        "stw	0,984(30)\n"
        "lwz	0,20(1)\n"
        "mtlr	0\n"
        "lmw	30,8(1)\n"
        "addi	1,1,16\n"
        "blr\n"
    );
    __builtin_unreachable();
}

// 0x8031240C (164 bytes)
// EResPrefetch::~EResPrefetch(void)
__attribute__((noreturn))
EResPrefetch::~EResPrefetch(void) {
    __asm__ __volatile__(
        "stwu	1,-24(1)\n"
        "mflr	0\n"
        "stmw	29,12(1)\n"
        "stw	0,28(1)\n"
        "mr	31,3\n"
        "lis	9,-32697\n"
        "lis	11,-32697\n"
        "lwz	0,984(31)\n"
        "addi	9,9,-19760\n"
        "addi	11,11,-19728\n"
        "mr	29,4\n"
        "stw	9,832(31)\n"
        "stw	11,0(31)\n"
        "cmpwi	0,0\n"
        "beq	.L_80312450\n"
        "addi	3,31,908\n"
        ".long 0x4804a24d  /* bl EMsgQueue::Destroy(void) */\n"
        ".L_80312450:\n"
        "addi	30,31,8\n"
        "mr	3,30\n"
        ".long 0x4bfc5f65  /* bl EThread::Destroy(void) */\n"
        "addi	3,31,908\n"
        "li	4,2\n"
        ".long 0x4804a0e5  /* bl EMsgQueue::~EMsgQueue(void) */\n"
        "addi	3,31,840\n"
        "li	4,2\n"
        ".long 0x48000b99  /* bl EResPrefetchFile::~EResPrefetchFile(void) */\n"
        "mr	3,30\n"
        "li	4,0\n"
        ".long 0x4bfc5cdd  /* bl EThread::~EThread(void) */\n"
        "lis	9,-32697\n"
        "andi.	0,29,1\n"
        "addi	9,9,-19680\n"
        "stw	9,0(31)\n"
        "beq	.L_8031249C\n"
        "mr	3,31\n"
        ".long 0x4bfbed89  /* bl __builtin_delete */\n"
        ".L_8031249C:\n"
        "lwz	0,28(1)\n"
        "mtlr	0\n"
        "lmw	29,12(1)\n"
        "addi	1,1,24\n"
        "blr\n"
    );
    __builtin_unreachable();
}

// 0x803124B0 (204 bytes)
// EResPrefetch::Init(void)
__attribute__((noreturn))
void EResPrefetch::Init(void) {
    __asm__ __volatile__(
        "stwu	1,-16(1)\n"
        "mflr	0\n"
        "stmw	30,8(1)\n"
        "stw	0,20(1)\n"
        "lis	9,-32692\n"
        "mr	30,3\n"
        "lwz	0,-17448(9)\n"
        "lwz	11,-26824(13)\n"
        "stw	0,1020(30)\n"
        "lwz	9,824(11)\n"
        "lha	3,72(9)\n"
        "lwz	0,76(9)\n"
        "add	3,11,3\n"
        "mtlr	0\n"
        "blrl\n"
        "stw	3,1016(30)\n"
        "cmpwi	3,0\n"
        "beq	.L_80312504\n"
        "lwz	0,1020(30)\n"
        "divwu	0,0,3\n"
        "b	.L_80312508\n"
        ".L_80312504:\n"
        "li	0,0\n"
        ".L_80312508:\n"
        "stw	0,1024(30)\n"
        "addi	3,30,908\n"
        "li	4,2048\n"
        ".long 0x4804a099  /* bl EMsgQueue::Create(int) */\n"
        "cmpwi	3,0\n"
        "beq	.L_80312564\n"
        "lis	9,-32702\n"
        "addi	31,30,8\n"
        "addi	9,9,1256\n"
        "mr	3,31\n"
        "stw	9,812(31)\n"
        "li	4,23\n"
        "li	5,8192\n"
        "li	6,0\n"
        ".long 0x4bfc5cd1  /* bl EThread::Create(int, int, void *) */\n"
        "cmpwi	3,0\n"
        "beq	.L_80312564\n"
        "mr	3,31\n"
        ".long 0x4bfc5f15  /* bl EThread::Start(void) */\n"
        "li	0,1\n"
        "li	3,1\n"
        "stw	0,984(30)\n"
        "b	.L_80312568\n"
        ".L_80312564:\n"
        "li	3,0\n"
        ".L_80312568:\n"
        "lwz	0,20(1)\n"
        "mtlr	0\n"
        "lmw	30,8(1)\n"
        "addi	1,1,16\n"
        "blr\n"
    );
    __builtin_unreachable();
}

// 0x8031257C (68 bytes)
// EResPrefetch::Shutdown(void)
__attribute__((noreturn))
void EResPrefetch::Shutdown(void) {
    __asm__ __volatile__(
        "stwu	1,-16(1)\n"
        "mflr	0\n"
        "stmw	30,8(1)\n"
        "stw	0,20(1)\n"
        "mr	30,3\n"
        ".long 0x480004e1  /* bl EResPrefetch::Flush(void) */\n"
        "addi	3,30,8\n"
        ".long 0x4bfc5ef1  /* bl EThread::Stop(void) */\n"
        "addi	3,30,908\n"
        ".long 0x4804a0f9  /* bl EMsgQueue::Destroy(void) */\n"
        "li	0,0\n"
        "stw	0,984(30)\n"
        "lwz	0,20(1)\n"
        "mtlr	0\n"
        "lmw	30,8(1)\n"
        "addi	1,1,16\n"
        "blr\n"
    );
    __builtin_unreachable();
}

// 0x803125D4 (116 bytes)
// EResPrefetch::ReleasedBuffer(EScratchBuffUser *)
__attribute__((noreturn))
void EResPrefetch::ReleasedBuffer(EScratchBuffUser *) {
    __asm__ __volatile__(
        "stwu	1,-8(1)\n"
        "mflr	0\n"
        "stw	0,12(1)\n"
        "mr	4,3\n"
        "li	0,0\n"
        "stw	0,988(4)\n"
        "lis	11,-32702\n"
        "stw	0,992(4)\n"
        "lis	9,-32692\n"
        "stw	0,996(4)\n"
        "addi	3,9,-17464\n"
        "stw	0,1004(4)\n"
        "stw	0,1000(4)\n"
        "stw	0,1008(4)\n"
        "stw	0,1012(4)\n"
        "stw	0,1028(4)\n"
        "stw	0,1032(4)\n"
        "stw	0,1036(4)\n"
        "lfs	0,1276(11)\n"
        "stw	0,1044(4)\n"
        "stfs	0,1040(4)\n"
        "lwz	0,8(3)\n"
        "cmpw	4,0\n"
        "bne	.L_80312638\n"
        ".long 0x48015aa5  /* bl EScratchBuffMan::ReleaseBuffer(EScratchBuffUser *) */\n"
        ".L_80312638:\n"
        "lwz	0,12(1)\n"
        "mtlr	0\n"
        "addi	1,1,8\n"
        "blr\n"
    );
    __builtin_unreachable();
}

// 0x80312648 (140 bytes)
// EResPrefetch::DoCancel(EPrefetchMsg *)
__attribute__((noreturn))
void EResPrefetch::DoCancel(EPrefetchMsg *) {
    __asm__ __volatile__(
        "stwu	1,-16(1)\n"
        "mflr	0\n"
        "stw	31,12(1)\n"
        "stw	0,20(1)\n"
        "mr	10,3\n"
        "li	0,0\n"
        "stw	0,988(10)\n"
        "lis	11,-32702\n"
        "stw	0,992(10)\n"
        "lis	9,-32692\n"
        "stw	0,996(10)\n"
        "addi	3,9,-17464\n"
        "stw	0,1004(10)\n"
        "mr	31,4\n"
        "stw	0,1000(10)\n"
        "stw	0,1008(10)\n"
        "stw	0,1012(10)\n"
        "stw	0,1028(10)\n"
        "stw	0,1032(10)\n"
        "stw	0,1036(10)\n"
        "lfs	0,1280(11)\n"
        "stw	0,1044(10)\n"
        "stfs	0,1040(10)\n"
        "lwz	0,8(3)\n"
        "cmpw	10,0\n"
        "bne	.L_803126B8\n"
        "mr	4,10\n"
        ".long 0x48015a25  /* bl EScratchBuffMan::ReleaseBuffer(EScratchBuffUser *) */\n"
        ".L_803126B8:\n"
        "lwz	3,16(31)\n"
        ".long 0x4bfc5271  /* bl ESemaphore::Release(void) */\n"
        "lwz	0,20(1)\n"
        "mtlr	0\n"
        "lwz	31,12(1)\n"
        "addi	1,1,16\n"
        "blr\n"
    );
    __builtin_unreachable();
}

// 0x803126D4 (188 bytes)
// EResPrefetch::DoBegin(EPrefetchMsg *)
__attribute__((noreturn))
void EResPrefetch::DoBegin(EPrefetchMsg *) {
    __asm__ __volatile__(
        "stwu	1,-16(1)\n"
        "mflr	0\n"
        "stmw	30,8(1)\n"
        "stw	0,20(1)\n"
        "mr	31,3\n"
        "mr	30,4\n"
        "lwz	0,1020(31)\n"
        "cmpwi	0,0\n"
        "beq	.L_80312774\n"
        "lis	3,-32692\n"
        "lis	5,-32702\n"
        "addi	5,5,1284\n"
        "li	6,238\n"
        "addi	3,3,-17464\n"
        "mr	4,31\n"
        ".long 0x48015911  /* bl EScratchBuffMan::TryAcquireBuffer(EScratchBuffUser *, char *, int) */\n"
        "lwz	3,12(30)\n"
        "stw	3,988(31)\n"
        "lwz	0,4(30)\n"
        "mr	4,0\n"
        "stw	0,992(31)\n"
        ".long 0x48014ca9  /* bl EResourceManager::GetPos(unsigned int) */\n"
        "mr	0,3\n"
        "lwz	4,992(31)\n"
        "lwz	3,988(31)\n"
        "stw	0,996(31)\n"
        "stw	0,1004(31)\n"
        ".long 0x48014cc9  /* bl EResourceManager::GetSize(unsigned int) */\n"
        "lwz	0,1016(31)\n"
        "lis	9,-32702\n"
        "lfs	0,1368(9)\n"
        "li	11,1\n"
        "divwu	10,3,0\n"
        "stw	3,1000(31)\n"
        "stw	11,1044(31)\n"
        "stfs	0,1040(31)\n"
        "mullw	0,10,0\n"
        "stw	10,1008(31)\n"
        "subf	3,0,3\n"
        "stw	3,1012(31)\n"
        ".L_80312774:\n"
        "mr	3,30\n"
        ".long 0x4bfbeaa9  /* bl __builtin_delete */\n"
        "lwz	0,20(1)\n"
        "mtlr	0\n"
        "lmw	30,8(1)\n"
        "addi	1,1,16\n"
        "blr\n"
    );
    __builtin_unreachable();
}

// 0x80312790 (500 bytes)
// EResPrefetch::LoadAnotherBlock(void)
__attribute__((noreturn))
void EResPrefetch::LoadAnotherBlock(void) {
    __asm__ __volatile__(
        "stwu	1,-32(1)\n"
        "mflr	0\n"
        "stw	31,28(1)\n"
        "stw	0,36(1)\n"
        "mr	31,3\n"
        "lwz	9,1000(31)\n"
        "lwz	0,1020(31)\n"
        "cmplw	9,0\n"
        "ble	.L_8031286C\n"
        "lwz	9,1028(31)\n"
        "lwz	0,1024(31)\n"
        "cmplw	9,0\n"
        "bge	.L_80312844\n"
        "lwz	3,988(31)\n"
        "lwz	4,1032(31)\n"
        "lwz	5,996(31)\n"
        "lwz	6,1016(31)\n"
        ".long 0x48014041  /* bl EResourceManager::ReadData(void *, unsigned int, unsigned int) */\n"
        "lwz	8,1028(31)\n"
        "lis	0,17200\n"
        "lwz	7,1024(31)\n"
        "addi	8,8,1\n"
        "mr	10,11\n"
        "stw	8,20(1)\n"
        "lis	9,-32702\n"
        "lfd	12,1376(9)\n"
        "stw	0,16(1)\n"
        "lwz	9,1032(31)\n"
        "lfd	13,16(1)\n"
        "stw	7,20(1)\n"
        "fsub	13,13,12\n"
        "lwz	11,1016(31)\n"
        "stw	0,16(1)\n"
        "frsp	13,13\n"
        "lwz	0,996(31)\n"
        "add	9,9,11\n"
        "lfd	0,16(1)\n"
        "add	0,0,11\n"
        "stw	9,1032(31)\n"
        "fsub	0,0,12\n"
        "stw	0,996(31)\n"
        "frsp	0,0\n"
        "stw	8,1028(31)\n"
        "fdivs	13,13,0\n"
        "stfs	13,1040(31)\n"
        ".L_80312844:\n"
        "lwz	9,1028(31)\n"
        "lwz	0,1024(31)\n"
        "cmpw	9,0\n"
        "bne	.L_80312970\n"
        "lis	9,-32702\n"
        "li	0,0\n"
        "lfs	0,1384(9)\n"
        "stw	0,1044(31)\n"
        "stfs	0,1040(31)\n"
        "b	.L_80312970\n"
        ".L_8031286C:\n"
        "lwz	9,1028(31)\n"
        "lwz	0,1008(31)\n"
        "cmplw	9,0\n"
        "bge	.L_80312924\n"
        "lwz	4,1032(31)\n"
        "lwz	5,996(31)\n"
        "lwz	6,1016(31)\n"
        "lwz	3,988(31)\n"
        ".long 0x48013f89  /* bl EResourceManager::ReadData(void *, unsigned int, unsigned int) */\n"
        "lwz	8,1028(31)\n"
        "lis	6,17200\n"
        "lwz	5,1008(31)\n"
        "addi	8,8,1\n"
        "mr	7,10\n"
        "stw	8,20(1)\n"
        "lis	9,-32702\n"
        "lfd	12,1376(9)\n"
        "stw	6,16(1)\n"
        "lwz	11,1032(31)\n"
        "lfd	13,16(1)\n"
        "stw	5,20(1)\n"
        "fsub	13,13,12\n"
        "lwz	9,1016(31)\n"
        "stw	6,16(1)\n"
        "frsp	13,13\n"
        "lwz	0,996(31)\n"
        "add	11,11,9\n"
        "lfd	0,16(1)\n"
        "lwz	4,1012(31)\n"
        "add	0,0,9\n"
        "fsub	0,0,12\n"
        "stw	11,1032(31)\n"
        "frsp	0,0\n"
        "cmpwi	4,0\n"
        "fdivs	13,13,0\n"
        "stw	0,996(31)\n"
        "stw	8,1028(31)\n"
        "stfs	13,1040(31)\n"
        "bne	.L_80312970\n"
        "cmpw	8,5\n"
        "bne	.L_80312970\n"
        "lis	9,-32702\n"
        "stw	4,1044(31)\n"
        "lfs	0,1384(9)\n"
        "stfs	0,1040(31)\n"
        "b	.L_80312970\n"
        ".L_80312924:\n"
        "lwz	6,1012(31)\n"
        "cmpwi	6,0\n"
        "beq	.L_80312970\n"
        "lwz	3,988(31)\n"
        "lwz	4,1032(31)\n"
        "lwz	5,996(31)\n"
        ".long 0x48013ed9  /* bl EResourceManager::ReadData(void *, unsigned int, unsigned int) */\n"
        "lwz	9,1032(31)\n"
        "lis	10,-32702\n"
        "lwz	11,1012(31)\n"
        "li	8,0\n"
        "lwz	0,996(31)\n"
        "lfs	0,1384(10)\n"
        "add	9,9,11\n"
        "add	0,0,11\n"
        "stw	9,1032(31)\n"
        "stfs	0,1040(31)\n"
        "stw	0,996(31)\n"
        "stw	8,1044(31)\n"
        ".L_80312970:\n"
        "lwz	0,36(1)\n"
        "mtlr	0\n"
        "lwz	31,28(1)\n"
        "addi	1,1,32\n"
        "blr\n"
    );
    __builtin_unreachable();
}

// 0x80312984 (84 bytes)
// EResPrefetch::DoFlush(EPrefetchMsg *)
__attribute__((noreturn))
void EResPrefetch::DoFlush(EPrefetchMsg *) {
    __asm__ __volatile__(
        "stwu	1,-16(1)\n"
        "mflr	0\n"
        "stmw	30,8(1)\n"
        "stw	0,20(1)\n"
        "mr	31,3\n"
        "mr	30,4\n"
        "b	.L_803129A8\n"
        ".L_803129A0:\n"
        "mr	3,31\n"
        ".long 0x4bfffded  /* bl EResPrefetch::LoadAnotherBlock(void) */\n"
        ".L_803129A8:\n"
        "lwz	0,1044(31)\n"
        "cmpwi	0,0\n"
        "bne	.L_803129A0\n"
        "lwz	3,16(30)\n"
        "cmpwi	3,0\n"
        "beq	.L_803129C4\n"
        ".long 0x4bfc4f6d  /* bl ESemaphore::Release(void) */\n"
        ".L_803129C4:\n"
        "lwz	0,20(1)\n"
        "mtlr	0\n"
        "lmw	30,8(1)\n"
        "addi	1,1,16\n"
        "blr\n"
    );
    __builtin_unreachable();
}

// 0x803129D8 (152 bytes)
// EResPrefetch::Main(void)
__attribute__((noreturn))
void EResPrefetch::Main(void) {
    __asm__ __volatile__(
        "stwu	1,-24(1)\n"
        "mflr	0\n"
        "stmw	30,16(1)\n"
        "stw	0,28(1)\n"
        "mr	31,3\n"
        "addi	30,1,8\n"
        ".L_803129F0:\n"
        "lwz	5,1044(31)\n"
        "li	4,0\n"
        "stw	4,8(1)\n"
        "addi	3,31,908\n"
        "xori	5,5,1\n"
        "mr	4,30\n"
        ".long 0x48049da9  /* bl EMsgQueue::Receive(unsigned int *, bool) */\n"
        "cmpwi	3,0\n"
        "beq	.L_80312A64\n"
        "lwz	4,8(1)\n"
        "lwz	0,0(4)\n"
        "cmpwi	0,1\n"
        "beq	.L_80312A4C\n"
        "bgt	.L_80312A34\n"
        "cmpwi	0,0\n"
        "beq	.L_80312A40\n"
        "b	.L_803129F0\n"
        ".L_80312A34:\n"
        "cmpwi	0,2\n"
        "beq	.L_80312A58\n"
        "b	.L_803129F0\n"
        ".L_80312A40:\n"
        "mr	3,31\n"
        ".long 0x4bfffc05  /* bl EResPrefetch::DoCancel(EPrefetchMsg *) */\n"
        "b	.L_803129F0\n"
        ".L_80312A4C:\n"
        "mr	3,31\n"
        ".long 0x4bfffc85  /* bl EResPrefetch::DoBegin(EPrefetchMsg *) */\n"
        "b	.L_803129F0\n"
        ".L_80312A58:\n"
        "mr	3,31\n"
        ".long 0x4bffff29  /* bl EResPrefetch::DoFlush(EPrefetchMsg *) */\n"
        "b	.L_803129F0\n"
        ".L_80312A64:\n"
        "mr	3,31\n"
        ".long 0x4bfffd29  /* bl EResPrefetch::LoadAnotherBlock(void) */\n"
        "b	.L_803129F0\n"
    );
    __builtin_unreachable();
}

// 0x80312A70 (160 bytes)
// EResPrefetch::Flush(void)
__attribute__((noreturn))
void EResPrefetch::Flush(void) {
    __asm__ __volatile__(
        "stwu	1,-64(1)\n"
        "mflr	0\n"
        "stmw	30,56(1)\n"
        "stw	0,68(1)\n"
        "mr	31,3\n"
        "lwz	0,1044(31)\n"
        "cmpwi	0,0\n"
        "beq	.L_80312AFC\n"
        "addi	30,1,8\n"
        "mr	3,30\n"
        ".long 0x4bfc4cc1  /* bl ESemaphore::ESemaphore(void) */\n"
        "li	4,1\n"
        "li	5,0\n"
        "mr	3,30\n"
        ".long 0x4bfc4dcd  /* bl ESemaphore::Create(int, int) */\n"
        "li	11,0\n"
        "li	0,2\n"
        "li	9,-1\n"
        "addi	4,1,32\n"
        "stw	0,32(1)\n"
        "li	5,1\n"
        "stw	11,40(1)\n"
        "addi	3,31,908\n"
        "stw	9,36(1)\n"
        "stw	30,48(1)\n"
        "stw	11,44(1)\n"
        ".long 0x48049c19  /* bl EMsgQueue::Send(unsigned int, bool) */\n"
        "li	4,-1\n"
        "mr	3,30\n"
        ".long 0x4bfc4df1  /* bl ESemaphore::Acquire(unsigned int) */\n"
        "mr	3,30\n"
        ".long 0x4bfc4ddd  /* bl ESemaphore::Destroy(void) */\n"
        "mr	3,30\n"
        "li	4,2\n"
        ".long 0x4bfc4d09  /* bl ESemaphore::~ESemaphore(void) */\n"
        ".L_80312AFC:\n"
        "lwz	0,68(1)\n"
        "mtlr	0\n"
        "lmw	30,56(1)\n"
        "addi	1,1,64\n"
        "blr\n"
    );
    __builtin_unreachable();
}

// 0x80312B10 (144 bytes)
// EResPrefetch::Cancel(void)
__attribute__((noreturn))
void EResPrefetch::Cancel(void) {
    __asm__ __volatile__(
        "stwu	1,-72(1)\n"
        "mflr	0\n"
        "stmw	29,60(1)\n"
        "stw	0,76(1)\n"
        "addi	30,1,8\n"
        "mr	29,3\n"
        "mr	3,30\n"
        ".long 0x4bfc4c2d  /* bl ESemaphore::ESemaphore(void) */\n"
        "li	4,1\n"
        "li	5,0\n"
        "mr	3,30\n"
        ".long 0x4bfc4d39  /* bl ESemaphore::Create(int, int) */\n"
        "li	0,0\n"
        "li	9,-1\n"
        "addi	4,1,32\n"
        "stw	0,40(1)\n"
        "stw	9,36(1)\n"
        "li	5,1\n"
        "stw	30,48(1)\n"
        "addi	3,29,908\n"
        "stw	0,32(1)\n"
        "stw	0,44(1)\n"
        ".long 0x48049b89  /* bl EMsgQueue::Send(unsigned int, bool) */\n"
        "li	4,-1\n"
        "mr	3,30\n"
        ".long 0x4bfc4d61  /* bl ESemaphore::Acquire(unsigned int) */\n"
        "mr	3,30\n"
        ".long 0x4bfc4d4d  /* bl ESemaphore::Destroy(void) */\n"
        "mr	3,30\n"
        "li	4,2\n"
        ".long 0x4bfc4c79  /* bl ESemaphore::~ESemaphore(void) */\n"
        "lwz	0,76(1)\n"
        "mtlr	0\n"
        "lmw	29,60(1)\n"
        "addi	1,1,72\n"
        "blr\n"
    );
    __builtin_unreachable();
}

// 0x80312BA0 (72 bytes)
// EResPrefetch::BeginPreFetch(char *, char *)
__attribute__((noreturn))
void EResPrefetch::BeginPreFetch(char *, char *) {
    __asm__ __volatile__(
        "stwu	1,-24(1)\n"
        "mflr	0\n"
        "stmw	29,12(1)\n"
        "stw	0,28(1)\n"
        "mr	29,3\n"
        "mr	30,4\n"
        "mr	3,5\n"
        "li	4,0\n"
        ".long 0x4bfb3321  /* bl EChecksum::ComputeSymbol(char *, unsigned int) */\n"
        "mr	5,3\n"
        "mr	4,30\n"
        "mr	3,29\n"
        ".long 0x48000019  /* bl EResPrefetch::BeginPreFetch(char *, unsigned int) */\n"
        "lwz	0,28(1)\n"
        "mtlr	0\n"
        "lmw	29,12(1)\n"
        "addi	1,1,24\n"
        "blr\n"
    );
    __builtin_unreachable();
}

// 0x80312BE8 (136 bytes)
// EResPrefetch::BeginPreFetch(char *, unsigned int)
__attribute__((noreturn))
void EResPrefetch::BeginPreFetch(char *, unsigned int) {
    __asm__ __volatile__(
        "stwu	1,-32(1)\n"
        "mflr	0\n"
        "stmw	27,12(1)\n"
        "stw	0,36(1)\n"
        "mr	28,3\n"
        "mr	27,5\n"
        "mr	29,4\n"
        ".long 0x4bffff0d  /* bl EResPrefetch::Cancel(void) */\n"
        "li	3,20\n"
        ".long 0x4bfbe5a5  /* bl __builtin_new */\n"
        "lwz	11,-22652(13)\n"
        "mr	30,3\n"
        "mr	4,29\n"
        "lwz	9,0(11)\n"
        "lwz	0,164(9)\n"
        "lha	3,160(9)\n"
        "mtlr	0\n"
        "add	3,11,3\n"
        "blrl\n"
        "stw	3,12(30)\n"
        "li	0,1\n"
        "li	9,0\n"
        "stw	0,0(30)\n"
        "stw	27,4(30)\n"
        "addi	3,28,908\n"
        "stw	9,16(30)\n"
        "mr	4,30\n"
        "li	5,1\n"
        ".long 0x48049a99  /* bl EMsgQueue::Send(unsigned int, bool) */\n"
        "lwz	0,36(1)\n"
        "mtlr	0\n"
        "lmw	27,12(1)\n"
        "addi	1,1,32\n"
        "blr\n"
    );
    __builtin_unreachable();
}

// 0x80312C70 (72 bytes)
// EResPrefetch::AddRef(char *, char *)
__attribute__((noreturn))
void EResPrefetch::AddRef(char *, char *) {
    __asm__ __volatile__(
        "stwu	1,-24(1)\n"
        "mflr	0\n"
        "stmw	29,12(1)\n"
        "stw	0,28(1)\n"
        "mr	29,3\n"
        "mr	30,4\n"
        "mr	3,5\n"
        "li	4,0\n"
        ".long 0x4bfb3251  /* bl EChecksum::ComputeSymbol(char *, unsigned int) */\n"
        "mr	5,3\n"
        "mr	4,30\n"
        "mr	3,29\n"
        ".long 0x48000019  /* bl EResPrefetch::AddRef(char *, unsigned int) */\n"
        "lwz	0,28(1)\n"
        "mtlr	0\n"
        "lmw	29,12(1)\n"
        "addi	1,1,24\n"
        "blr\n"
    );
    __builtin_unreachable();
}

// 0x80312CB8 (248 bytes)
// EResPrefetch::AddRef(char *, unsigned int)
__attribute__((noreturn))
void EResPrefetch::AddRef(char *, unsigned int) {
    __asm__ __volatile__(
        "stwu	1,-32(1)\n"
        "mflr	0\n"
        "stmw	27,12(1)\n"
        "stw	0,36(1)\n"
        "lwz	9,-22652(13)\n"
        "mr	31,3\n"
        "mr	28,5\n"
        "lwz	11,0(9)\n"
        "lha	3,160(11)\n"
        "lwz	0,164(11)\n"
        "add	3,9,3\n"
        "mtlr	0\n"
        "blrl\n"
        "mr	29,3\n"
        "mr	4,28\n"
        ".long 0x48013a29  /* bl EResourceManager::GetRef(unsigned int) */\n"
        "cmpwi	3,0\n"
        "bne	.L_80312D2C\n"
        "lis	9,-32692\n"
        "addi	27,9,-17464\n"
        "lwz	0,8(27)\n"
        "cmpw	31,0\n"
        "bne	.L_80312D2C\n"
        "lwz	0,988(31)\n"
        "cmpw	0,29\n"
        "bne	.L_80312D2C\n"
        "lwz	0,992(31)\n"
        "cmpw	0,28\n"
        "beq	.L_80312D4C\n"
        ".L_80312D2C:\n"
        "mr	3,31\n"
        ".long 0x4bfffde1  /* bl EResPrefetch::Cancel(void) */\n"
        "mr	3,29\n"
        "mr	4,28\n"
        "li	5,0\n"
        "li	6,0\n"
        ".long 0x48013fb5  /* bl EResourceManager::AddRef(unsigned int, EFile *, int) */\n"
        "b	.L_80312D9C\n"
        ".L_80312D4C:\n"
        "mr	3,31\n"
        "addi	30,31,840\n"
        ".long 0x4bfffd1d  /* bl EResPrefetch::Flush(void) */\n"
        "lwz	7,1020(31)\n"
        "mr	3,30\n"
        "lwz	8,1004(31)\n"
        "mr	4,29\n"
        "lwz	6,1036(31)\n"
        "mr	5,28\n"
        ".long 0x48000529  /* bl EResPrefetchFile::SetStreamBuffer(EResourceManager *, unsigned int, void *, unsigned int, unsigned int) */\n"
        "mr	5,30\n"
        "mr	4,28\n"
        "li	6,0\n"
        "mr	3,29\n"
        ".long 0x48013f75  /* bl EResourceManager::AddRef(unsigned int, EFile *, int) */\n"
        "mr	30,3\n"
        "mr	4,31\n"
        "mr	3,27\n"
        ".long 0x48015345  /* bl EScratchBuffMan::ReleaseBuffer(EScratchBuffUser *) */\n"
        "mr	3,30\n"
        ".L_80312D9C:\n"
        "lwz	0,36(1)\n"
        "mtlr	0\n"
        "lmw	27,12(1)\n"
        "addi	1,1,32\n"
        "blr\n"
    );
    __builtin_unreachable();
}

// 0x80312DB0 (100 bytes)
// EResPrefetch::CanAddRef(void)
__attribute__((noreturn))
void EResPrefetch::CanAddRef(void) {
    __asm__ __volatile__(
        "lis	9,-32692\n"
        "lwz	0,-17456(9)\n"
        "li	9,0\n"
        "cmpw	3,0\n"
        "bne	.L_80312DD0\n"
        "lwz	0,1044(3)\n"
        "subfic	11,0,0\n"
        "adde	9,11,0\n"
        ".L_80312DD0:\n"
        "cmpwi	9,0\n"
        "li	10,0\n"
        "beq	.L_80312E0C\n"
        "lwz	11,1008(3)\n"
        "lwz	9,1024(3)\n"
        "cmplw	11,9\n"
        "bge	.L_80312DFC\n"
        "lwz	0,1028(3)\n"
        "cmpw	0,11\n"
        "beq	.L_80312E08\n"
        "b	.L_80312E0C\n"
        ".L_80312DFC:\n"
        "lwz	0,1028(3)\n"
        "cmpw	0,9\n"
        "bne	.L_80312E0C\n"
        ".L_80312E08:\n"
        "li	10,1\n"
        ".L_80312E0C:\n"
        "mr	3,10\n"
        "blr\n"
    );
    __builtin_unreachable();
}

// 0x80312E68 (92 bytes)
// EResPrefetch::CanReleaseBuffer(void)
__attribute__((noreturn))
void EResPrefetch::CanReleaseBuffer(void) {
    __asm__ __volatile__(
        "stwu	1,-16(1)\n"
        "mflr	0\n"
        "stw	31,12(1)\n"
        "stw	0,20(1)\n"
        "lwz	0,1044(3)\n"
        "li	31,0\n"
        "cmpwi	0,0\n"
        "bne	.L_80312EAC\n"
        "addi	3,3,908\n"
        ".long 0x48049ac5  /* bl EMsgQueue::GetCount(void) */\n"
        "cmpwi	3,0\n"
        "li	0,1\n"
        "bne	.L_80312EA0\n"
        "li	0,0\n"
        ".L_80312EA0:\n"
        "cmpwi	0,0\n"
        "beq	.L_80312EAC\n"
        "li	31,1\n"
        ".L_80312EAC:\n"
        "mr	3,31\n"
        "lwz	0,20(1)\n"
        "mtlr	0\n"
        "lwz	31,12(1)\n"
        "addi	1,1,16\n"
        "blr\n"
    );
    __builtin_unreachable();
}

// 0x80312EE4 (116 bytes)
// EResPrefetch::ResetState(void)
__attribute__((noreturn))
void EResPrefetch::ResetState(void) {
    __asm__ __volatile__(
        "stwu	1,-8(1)\n"
        "mflr	0\n"
        "stw	0,12(1)\n"
        "lis	9,-32702\n"
        "mr	4,3\n"
        "lfs	0,1392(9)\n"
        "li	0,0\n"
        "lis	9,-32692\n"
        "stw	0,1044(4)\n"
        "stfs	0,1040(4)\n"
        "addi	3,9,-17464\n"
        "stw	0,988(4)\n"
        "stw	0,992(4)\n"
        "stw	0,996(4)\n"
        "stw	0,1004(4)\n"
        "stw	0,1000(4)\n"
        "stw	0,1008(4)\n"
        "stw	0,1012(4)\n"
        "stw	0,1028(4)\n"
        "stw	0,1032(4)\n"
        "stw	0,1036(4)\n"
        "lwz	9,8(3)\n"
        "cmpw	4,9\n"
        "bne	.L_80312F48\n"
        ".long 0x48015195  /* bl EScratchBuffMan::ReleaseBuffer(EScratchBuffUser *) */\n"
        ".L_80312F48:\n"
        "lwz	0,12(1)\n"
        "mtlr	0\n"
        "addi	1,1,8\n"
        "blr\n"
    );
    __builtin_unreachable();
}

