#include "types.h"
#include "stub_classes.h"
// Auto-generated matching stubs for AnimTableImpl
// Generated by auto_match.py
// 2 functions, 20 bytes

// 0x800AAC04 (12 bytes)
short AnimTableImpl::GetID() { return *(short*)((char*)(*(void**)((char*)this + 0x4)) + 0x4); }  // double deref signed short

// 0x800AAC2C (8 bytes)
int AnimTableImpl::GetEntryName(int) { return 0; }

