// Auto-generated matching stubs for AptDate
// Generated by auto_match.py
// 1 functions, 8 bytes

// 0x80296888 (8 bytes)
int AptDate::sMethod_UTC(AptValue *, int) { return /* SDA global @ r13-22936 */; }  // lwz r3,-22936(r13)

