#if 0 // SKIP
// Auto-generated matching stubs for AptScriptFunction2
// Generated by auto_match.py
// 3 functions, 36 bytes

// 0x802B8F18 (12 bytes)
#include "types.h"
#include "stub_classes.h"
int AptScriptFunction2::GetName() const { return *(int*)((char*)(*(void**)((char*)this + 0x34)) + 0x0); }  // double deref

// 0x802B8F24 (12 bytes)
int AptScriptFunction2::GetNumArguments() { return *(int*)((char*)(*(void**)((char*)this + 0x34)) + 0x4); }  // double deref

// 0x802B8F3C (12 bytes)
int AptScriptFunction2::GetByteCodeSize() { return *(int*)((char*)(*(void**)((char*)this + 0x34)) + 0x10); }  // double deref

#endif
