#if 0
#include "types.h"
#include "stub_classes.h"
// Auto-generated matching stubs for AptValueFactory
// Generated by auto_match.py
// 1 functions, 8 bytes

// 0x802B5124 (8 bytes)
int AptValueFactory::CreateUndefined() { return /* SDA global @ r13-22936 */; }  // lwz r3,-22936(r13)

#endif
