#include "types.h"
#include "stub_classes.h"
// Auto-generated matching stubs for Behavior
// Generated by auto_match.py
// 8 functions, 88 bytes

// 0x800AB300 (20 bytes)
Behavior::Behavior() { *(void**)((char*)this + 0x0) = (void*)0x8046E878; }  // vtable init

// 0x800AB540 (12 bytes)
int Behavior::GetNamespaceID() { return *(int*)((char*)(*(void**)((char*)this + 0x4)) + 0x4); }  // double deref

// 0x800AB54C (12 bytes)
int Behavior::GetSemiGlobalNamespaceID() { return *(int*)((char*)(*(void**)((char*)this + 0x4)) + 0x8); }  // double deref

// 0x800AB558 (8 bytes)
int Behavior::GetGlobNamespaceID() { return 0; }  // lwz r3,-31848(r13)

// 0x800AB8C0 (4 bytes)
void Behavior::GetNodeText(short, BehaviorNode *, StringBuffer &) { }

// 0x800AD118 (8 bytes)
ObjSelector* Behavior::GetOwner() { return *(int*)((char*)this + 0x4); }  // offset 0x4

// 0x800AD120 (8 bytes)
Language* Behavior::GetLanguage() { return *(int*)((char*)this + 0x8); }  // offset 0x8

// 0x800AD1A4 (16 bytes)
void Behavior::SetDefaultParam(BehaviorNodeParam *) { register int __r0 __asm__("r0") = -1; __asm__ __volatile__("" : "+r"(__r0)); *(int*)((char*)this + 0x4) = __r0; *(int*)((char*)this + 0x0) = __r0; }

