#include "types.h"
#include "stub_classes.h"
// Auto-generated matching stubs for CameraMotionSystem
// Generated by auto_match.py
// 3 functions, 36 bytes

// 0x8001606C (20 bytes)
void CameraMotionSystem::CameraMotionSystem(SimsCameraParameters *) { *(int*)((char*)this + 0x0) = 0; *(int*)((char*)this + 0x4) = param4; }

// 0x800160A8 (8 bytes)
void CameraMotionSystem::SetMotionType(CameraMotionType) { *(int*)((char*)this + 0x0) = val; }  // offset 0x0

// 0x800160B0 (8 bytes)
int CameraMotionSystem::GetMotionType() { return *(int*)((char*)this + 0x0); }  // offset 0x0

