// Auto-generated matching stubs for CareersImpl
// Generated by auto_match.py
// 2 functions, 20 bytes

// 0x800B1698 (12 bytes)
#include "types.h"
#include "stub_classes.h"
int CareersImpl::GetNumCareers() { return *(int*)((char*)(*(void**)((char*)this + 0x8)) + 0xC); }  // double deref

// 0x800B1B4C (8 bytes)
int CareersImpl::GetSuit(Job &, bool) { /* lwz r3,104(r4) */ return 0; }

