#include "types.h"
#include "stub_classes.h"
// Auto-generated matching stubs for CASFashionTarget
// Generated by auto_match.py
// 2 functions, 16 bytes

// 0x8019B3F4 (4 bytes)
void CASFashionTarget::RandomizeFashion() { }

// 0x8019B3F8 (12 bytes)
void CASFashionTarget::HandleEventChangeFocus(CasEventChangeFocus &) { /* lwz r0,20(r4); stw r0,140(r3) */ }

