#include "types.h"
#include "stub_classes.h"
// Auto-generated matching stubs for CasSceneGamecube
// Generated by auto_match.py
// 2 functions, 16 bytes

// 0x80175764 (8 bytes)
int CasSceneGamecube::GetSceneName() const { return /* SDA global @ r13-31552 */; }  // lwz r3,-31552(r13)

// 0x80175784 (8 bytes)
int CasSceneGamecube::GetRoomFromCameraAngle(unsigned int) const { return 0; }

