// Auto-generated matching stubs for CasSimRenderer
// Generated by auto_match.py
// 4 functions, 32 bytes

// 0x8016FB54 (8 bytes)
int CasSimRenderer::GetPositionNum() const { return *(int*)((char*)this + 0x214); }  // offset 0x214

// 0x8016FB5C (8 bytes)
void CasSimRenderer::SetPositionNum(unsigned int) { *(int*)((char*)this + 0x214) = val; }  // offset 0x214

// 0x8016FB64 (8 bytes)
void CasSimRenderer::SetSimRotation(float) { *(float*)((char*)this + 0x20C) = val; }  // offset 0x20C

// 0x8016FB6C (8 bytes)
void* CasSimRenderer::GetSimModel() { return (char*)this + 0x8; }  // offset 0x8

