#include "types.h"
#include "stub_classes.h"
// Auto-generated matching stubs for CasSceneGamecube (branching leaf functions)
// Generated by auto_match_branch.py
// 1 functions, 24 bytes

// 0x8017576C (24 bytes)
unsigned int CasSceneGamecube::GetRoomModelId(CasScene::RoomId val) const { if (val == 0) return 0x94A667AF; return 0; }

