#if 0
#include "types.h"
#include "stub_classes.h"
// Auto-generated matching stubs for CasSimRendererDynamic
// Generated by auto_match.py
// 1 functions, 8 bytes

// 0x80172C20 (8 bytes)
void CasSimRendererDynamic::LockSimRotation(bool) { *(int*)((char*)this + 0x21C) = val; }  // offset 0x21C

#endif
