#include "types.h"
#include "stub_classes.h"
// Auto-generated matching stubs for CheatMenuParams
// Generated by auto_match_medium.py

// 0x80303CCC (24 bytes)
CheatMenuParams::CheatMenuParams() { *(int*)((char*)this + 0x8) = 0; *(int*)((char*)this + 0x4) = 0; *(int*)((char*)this + 0x0) = 0; }

