#include "types.h"
#include "stub_classes.h"
// Auto-generated matching constructors for cSoundCacheItem
// Generated by gen_ctor_matches.py (inline asm)
// 1 functions, 8 bytes

// 0x800B8CB8 (8 bytes)
__attribute__((noreturn))
cSoundCacheItem::cSoundCacheItem(unsigned int p2) {
    __asm__ __volatile__(
        "stw	4,0(3)\n""blr\n"
    );
    __builtin_unreachable();
}
