#include "types.h"
#include "stub_classes.h"
// Auto-generated matching stubs for cSoundCacheItem
// Generated by auto_match.py
// 1 functions, 8 bytes

// 0x800B8CB8 (8 bytes)
void cSoundCacheItem::cSoundCacheItem(unsigned int) { *(int*)((char*)this + 0x0) = val; }  // offset 0x0

