// Auto-generated matching stubs for CTGFileManager
// Generated by auto_match.py
// 7 functions, 48 bytes

// 0x8007D350 (4 bytes)
void CTGFileManager::CTGFileManager() { }

// 0x8007D37C (8 bytes)
void CTGFileManager::Init() { return 1; }

// 0x8007D384 (4 bytes)
void CTGFileManager::Shutdown() { }

// 0x8007D4C4 (8 bytes)
int CTGFileManager::CreateFile(char *) { return 1; }

// 0x8007D4CC (8 bytes)
void CTGFileManager::DeleteFile(char *) { return 1; }

// 0x8007D4D4 (8 bytes)
int CTGFileManager::MoveFile(char *, char *) { return 1; }

// 0x8007D4DC (8 bytes)
int CTGFileManager::CopyFile(char *, char *) { return 1; }

