// Auto-generated matching stubs for CTilePt
// Generated by auto_match.py
// 2 functions, 20 bytes

// 0x800B45D0 (12 bytes)
#include "types.h"
#include "stub_classes.h"
void CTilePt::CTilePt() { *(char*)((char*)this + 0x2) = 0; }

// 0x800B4DE8 (8 bytes)
void CTilePt::SetLevel(int) { *(char*)((char*)this + 0x2) = val; }  // offset 0x2

