#include "types.h"
#include "stub_classes.h"
// Auto-generated matching stubs for CUnlockDisplay
// Generated by auto_match.py
// 7 functions, 76 bytes

// 0x80078008 (8 bytes)
void CUnlockDisplay::SetViewZoomFactor(float) { *(float*)((char*)this + 0x498) = val; }  // offset 0x498

// 0x80078010 (16 bytes)
void CUnlockDisplay::ManualCameraPos(float, float, float) { *(float*)((char*)this + 0x4A4) = f3; *(float*)((char*)this + 0x49C) = f1; *(float*)((char*)this + 0x4A0) = f2; }

// 0x80078DAC (12 bytes)
void CUnlockDisplay::RemoveAllDirectLights() { *(int*)((char*)this + 0x440) = 0; }

// 0x80078FDC (8 bytes)
int CUnlockDisplay::IsDone() { return *(int*)((char*)this + 0x45C); }  // offset 0x45C

// 0x80078FE4 (12 bytes)
void CUnlockDisplay::Hide() { *(int*)((char*)this + 0x458) = 1; }

// 0x80078FF0 (12 bytes)
void CUnlockDisplay::UnHide() { *(int*)((char*)this + 0x458) = 0; }

// 0x80078FFC (8 bytes)
int CUnlockDisplay::DonePreloadObject() { return *(int*)((char*)this + 0x450); }  // offset 0x450

