#include "types.h"
#include "stub_classes.h"
// Auto-generated matching constructors for ECheatLookup
// Generated by gen_ctor_matches.py (inline asm)
// 1 functions, 64 bytes

// 0x800210E4 (64 bytes)
__attribute__((noreturn))
ECheatLookup::ECheatLookup() {
    __asm__ __volatile__(
        "lis	11,-32707\n""mr	9,3\n""li	0,0\n""addi	11,11,-6164\n""li	10,-1\n""li	8,0\n""li	7,2\n""stw	10,4(9)\n""stb	8,8(9)\n""stw	7,76(9)\n""stw	0,92(9)\n""stw	11,72(9)\n""stw	0,80(9)\n""stw	0,84(9)\n""stw	0,88(9)\n""blr\n"
    );
    __builtin_unreachable();
}
