// Auto-generated matching stubs for EDL
// Generated by auto_match.py
// 2 functions, 16 bytes

// 0x80363378 (8 bytes)
int EDL::GetStart() { return *(int*)((char*)this + 0x48); }  // offset 0x48

// 0x80363408 (8 bytes)
int EDL::GetVertCount() { return *(int*)((char*)this + 0x54); }  // offset 0x54

