// Auto-generated matching stubs for EffectsPreRenderVisitor
// Generated by auto_match.py
// 2 functions, 16 bytes

// 0x8003E188 (8 bytes)
void EffectsPreRenderVisitor::Visit(Effects::Effect &) { return 1; }

// 0x8003E190 (8 bytes)
void EffectsPreRenderVisitor::Visit(Effects::EffectsSequencer &) { return 1; }

