#include "types.h"
#include "stub_classes.h"
// Auto-generated matching stubs for EffectsManager
// Generated by auto_match.py
// 2 functions, 16 bytes

// 0x803523C8 (8 bytes)
void Effects::EffectsManager::Shutdown() { return 1; }

// 0x80352710 (8 bytes)
int Effects::EffectsManager::CreateEffect(REffectsSequencer &, Effects::Effect::ClientParams *) { return 0; }

