#include "types.h"
#include "stub_classes.h"
// Auto-generated matching constructors for EFloorShdTblNode
// Generated by gen_ctor_matches.py (inline asm)
// 1 functions, 36 bytes

// 0x80045520 (36 bytes)
__attribute__((noreturn))
EFloorShdTblNode::EFloorShdTblNode() {
    __asm__ __volatile__(
        "mr	9,3\n""li	0,0\n""addi	11,9,4\n""li	10,1\n""stw	0,4(11)\n""stw	0,4(9)\n""stw	10,8(11)\n""stw	0,0(9)\n""blr\n"
    );
    __builtin_unreachable();
}
