#include "types.h"
#include "stub_classes.h"
// Auto-generated matching stubs for EGameState
// Generated by auto_match.py
// 4 functions, 32 bytes

// 0x80089E10 (16 bytes)
void EGameState::GetState() { /* lwz+mr+stw */ }

// 0x80089E20 (8 bytes)
int EGameState::InTransportMode() { return 0; }

// 0x80089E28 (4 bytes)
void EGameState::PauseAllSounds() { }

// 0x80089E2C (4 bytes)
void EGameState::ResumeAllSounds() { }

