#include "types.h"
#include "stub_classes.h"
// Auto-converted call wrapper stubs for EIDirLight
// Generated by convert_call_wrappers.py

// 0x80227144 (76 bytes)
// Call wrapper [2bl_with_branch]: EILight::Read(EStream &), operator>>(EStream &, EVec3 &)
__attribute__((noreturn))
void EIDirLight::Read(EStream &) {
    __asm__ __volatile__(
        "stwu	1,-16(1)\n"
        "mflr	0\n"
        "stmw	30,8(1)\n"
        "stw	0,20(1)\n"
        "mr	30,3\n"
        "mr	31,4\n"
        ".long 0x480009e5  /* bl EILight::Read(EStream &) */\n"
        "lis	9,-32688\n"
        "lhz	0,-13378(9)\n"
        "cmpwi	0,0\n"
        "bne	.L_8022717C\n"
        "mr	3,31\n"
        "addi	4,30,172\n"
        ".long 0x480ab4f5  /* bl operator>>(EStream &, EVec3 &) */\n"
        ".L_8022717C:\n"
        "lwz	0,20(1)\n"
        "mtlr	0\n"
        "lmw	30,8(1)\n"
        "addi	1,1,16\n"
        "blr\n"
    );
    __builtin_unreachable();
}

// 0x80227238 (196 bytes)
void EIDirLight::Setup(void) { EInstance::SetBounds((r1 + 8)); }

// 0x80227460 (84 bytes)
void EIDirLight::RegisterType(unsigned short) { ETypeInfo::Register((void*)0x8022736c, (void*)0x80227394, (void*)0x802273b4, this, (void*)0x8040e494, (void*)0x8050cb80)  /* on (void*)0x8050cba8 */; }
