// Auto-generated matching stubs for EIPointAmbLight
// Generated by auto_match.py
// 6 functions, 72 bytes

// 0x80229C44 (12 bytes)
void* EIPointAmbLight::GetTypeInfo() const { return (void*)0x8050CC20; }  // global data pointer

// 0x80229C50 (12 bytes)
int EIPointAmbLight::GetTypeName() const { return *(int*)0x8050CC2C; }  // global variable

// 0x80229C5C (12 bytes)
int EIPointAmbLight::GetTypeKey() const { return *(int*)0x8050CC30; }  // global variable

// 0x80229C68 (12 bytes)
unsigned short EIPointAmbLight::GetTypeVersion() const { return *(unsigned short*)0x8050CC34; }  // global variable

// 0x80229C74 (12 bytes)
void* EIPointAmbLight::GetTypeInfoStatic() { return (void*)0x8050CC20; }  // global data pointer

// 0x80229C80 (12 bytes)
unsigned short EIPointAmbLight::GetReadVersion() { return *(unsigned short*)0x8050CC36; }  // global variable

