#include "types.h"
#include "stub_classes.h"
// Auto-generated matching stubs for EIPortalPointLight
// Generated by auto_match.py
// 10 functions, 104 bytes

// 0x8022B038 (12 bytes)
void* EIPortalPointLight::GetTypeInfo() const { return (void*)0x8050CC70; }  // global data pointer

// 0x8022B044 (12 bytes)
void EIPortalPointLight::GetTypeName() const { return *(int*)0x8050CC7C; }  // global variable

// 0x8022B050 (12 bytes)
void EIPortalPointLight::GetTypeKey() const { return *(int*)0x8050CC80; }  // global variable
#if 0

// 0x8022B05C (12 bytes)
unsigned short EIPortalPointLight::GetTypeVersion() const { return *(unsigned short*)0x8050CC84; }  // global variable
#endif

// 0x8022B068 (12 bytes)
void* EIPortalPointLight::GetTypeInfoStatic() { return (void*)0x8050CC70; }  // global data pointer
#if 0

// 0x8022B074 (12 bytes)
unsigned short EIPortalPointLight::GetReadVersion() { return *(unsigned short*)0x8050CC86; }  // global variable
#endif

// 0x8022B0F4 (8 bytes)
void EIPortalPointLight::GetLightType() { return 4; }

// 0x8022B0FC (8 bytes)
void EIPortalPointLight::GetPortal() { return *(int*)((char*)this + 0xD4); }  // offset 0xD4

// 0x8022B104 (8 bytes)
void EIPortalPointLight::IsPointLight() { return true; }

// 0x8022B10C (8 bytes)
void EIPortalPointLight::GetRoomId() { return *(int*)((char*)this + 0xC0); }  // offset 0xC0

