#include "types.h"
#include "stub_classes.h"
// Auto-generated matching stubs for EIWallPart
// Generated by auto_match.py
// 9 functions, 92 bytes

// 0x80030560 (12 bytes)
void* EIWallPart::GetTypeInfo() const{ void* __p; __asm__ __volatile__("lis %0, -32688\n""addi %0, %0, -19536" : "=r"(__p)); return __p; }

// 0x8003056C (12 bytes)
void EIWallPart::GetTypeName() const{ register int __val __asm__("r3"); __asm__ __volatile__("lis %%r9, -32688\n""lwz %0, -19524(%%r9)" : "=r"(__val) : : "r9"); return __val; }

// 0x80030578 (12 bytes)
void EIWallPart::GetTypeKey() const{ register int __val __asm__("r3"); __asm__ __volatile__("lis %%r9, -32688\n""lwz %0, -19520(%%r9)" : "=r"(__val) : : "r9"); return __val; }

// 0x80030584 (12 bytes)
int EIWallPart::GetTypeVersion() const{ register int __val __asm__("r3"); __asm__ __volatile__("lis %%r9, -32688\n""lhz %0, -19516(%%r9)" : "=r"(__val) : : "r9"); return __val; }
// 0x80030590 (12 bytes)
void* EIWallPart::GetTypeInfoStatic(){ void* __p; __asm__ __volatile__("lis %0, -32688\n""addi %0, %0, -19536" : "=r"(__p)); return __p; }

// 0x8003059C (12 bytes)
int EIWallPart::GetReadVersion(){ register int __val __asm__("r3"); __asm__ __volatile__("lis %%r9, -32688\n""lhz %0, -19514(%%r9)" : "=r"(__val) : : "r9"); return __val; }

// 0x8003061C (8 bytes)
void* EIWallPart::operator new(unsigned int, void *) { return (void*)0; }  // mr r3,r4

// 0x80030654 (8 bytes)
void EIWallPart::SetForceFadeOff(bool val) { *(int*)((char*)this + 0x3B0) = val; }  // offset 0x3B0

// 0x8003065C (4 bytes)
void EIWallPart::RealizeShaderTuning() { }

