#include "types.h"
#include "stub_classes.h"
// Auto-generated matching stubs for EMemoryBufferWriteStream
// Generated by auto_match.py
// 2 functions, 16 bytes

// 0x802E0EE8 (8 bytes)
void EMemoryBufferWriteStream::GetPos() const { return *(int*)((char*)this + 0x20); }  // offset 0x20
#if 0

// 0x802E0EF0 (8 bytes)
int EMemoryBufferWriteStream::Read(void *, int) { return 0; }
#endif
