// Auto-generated matching stubs for ENgcTextureC4
// Generated by auto_match.py
// 1 functions, 8 bytes

// 0x8035071C (8 bytes)
int ENgcTextureC4::operator new(unsigned int, void *) { return first; }  // mr r3,r4

