#if 0 // SKIP
// Auto-generated matching stubs for ENgcEngine
// Generated by auto_match.py
// 2 functions, 12 bytes

// 0x8032E638 (4 bytes)
#include "types.h"
#include "stub_classes.h"
void ENgcEngine::InitializeProfiler() { }

// 0x8032E884 (8 bytes)
int ENgcEngine::IsResetting() { return /* SDA global @ r13-26472 */; }  // lwz r3,-26472(r13)

#endif
