#include "types.h"
#include "stub_classes.h"
// Auto-generated matching stubs for ENgcMovie
// Generated by auto_match.py
// 2 functions, 16 bytes
#if 0

// 0x8033549C (4 bytes)
void ENgcMovie::Reset() { }
#endif

// 0x80336388 (12 bytes)
void ENgcMovie::PlayerGetState() { return *(unsigned char*)0x804D39E4; }  // global byte

