// Auto-generated matching stubs for ENgcTextureBase
// Generated by auto_match.py
// 5 functions, 32 bytes

// 0x8034FE38 (4 bytes)
#include "types.h"
#include "stub_classes.h"
void ENgcTextureBase::Invalidate() { }

// 0x80350238 (8 bytes)
int ENgcTextureBase::UpdatePalette() { return *(int*)((char*)this + 0x90); }  // offset 0x90

// 0x80350470 (8 bytes)
int ENgcTextureBase::GetTEVStageCount() { return 1; }

// 0x80350478 (8 bytes)
int ENgcTextureBase::GetTEXCount() { return 1; }

// 0x80350618 (4 bytes)
void ENgcTextureBase::UnswizzleImage(unsigned char *, int, int, unsigned char *) { }

