#include "types.h"
#include "stub_classes.h"
// Auto-converted call wrapper stubs for ERAnim
// Generated by convert_call_wrappers.py

// 0x803680D4 (84 bytes)
void ERAnim::RegisterType(unsigned short) { ETypeInfo::Register((void*)0x80367fd4, (void*)0x80367ffc, (void*)0x80378028, this, (void*)0x80423218, (void*)0x8050cd38)  /* on (void*)0x8050d784 */; }
