#include "types.h"
#include "stub_classes.h"
// Auto-generated matching constructors for ERedBlackTree
// Generated by gen_ctor_matches.py (inline asm)
// 1 functions, 32 bytes

// 0x802CD9B8 (32 bytes)
__attribute__((noreturn))
ERedBlackTree::ERedBlackTree() {
    __asm__ __volatile__(
        "lis	9,-32700\n""mr	11,3\n""li	0,0\n""addi	9,9,-4812\n""stw	0,0(11)\n""stw	9,8(11)\n""stw	0,4(11)\n""blr\n"
    );
    __builtin_unreachable();
}
