#if 0 // SKIP
// Auto-generated matching stubs for ERenderer
// Generated by auto_match.py
// 1 functions, 8 bytes

// 0x80364DA4 (8 bytes)
#include "types.h"
#include "stub_classes.h"
void ERenderer::GetCurrentTexture(int) { return 0; }

#endif
