#include "types.h"
#include "stub_classes.h"
// Auto-generated matching constructors for ERenderSurface
// Generated by gen_ctor_matches.py (inline asm)
// 1 functions, 120 bytes

// 0x80364DAC (120 bytes)
__attribute__((noreturn))
ERenderSurface::ERenderSurface() {
    __asm__ __volatile__(
        "stwu	1,-24(1)\n""lis	11,-32697\n""mr	9,3\n""li	10,64\n""addi	11,11,-9552\n""li	8,1\n""li	0,3\n""stw	10,0(9)\n""lis	7,-32702\n""stw	10,4(9)\n""addi	6,9,12\n""stw	11,32(9)\n""li	5,-1\n""stw	0,8(9)\n""stw	8,28(9)\n""stw	8,24(9)\n""lfs	0,12548(7)\n""stfs	0,8(1)\n""stfs	0,16(1)\n""stfs	0,12(1)\n""lwz	11,8(1)\n""lwz	10,12(1)\n""lwz	0,16(1)\n""stw	11,12(9)\n""stw	0,8(6)\n""stw	10,4(6)\n""stw	5,0(9)\n""stw	5,4(9)\n""addi	1,1,24\n""blr\n"
    );
    __builtin_unreachable();
}
