#include "types.h"
#include "stub_classes.h"
// Auto-converted call wrapper stubs for ERotDecomp
// Generated by convert_call_wrappers.py

// 0x8035DF44 (108 bytes)
void ERotDecomp::Reset(void) { EBitArray::Get(this->field_0x4, this->field_0x1e)  /* on this->field_0x0 */; ReadAllQs(); }

// 0x8035DFB0 (136 bytes)
void ERotDecomp::ResetEnd(void) { EBitArray::Get((this->field_0x18 + -1), this->field_0x1e)  /* on this->field_0x0 */; ReadAllQs(); }
