#include "types.h"
#include "stub_classes.h"
// Auto-converted call wrapper stubs for ERShader
// Generated by convert_call_wrappers.py

// 0x8031F560 (68 bytes)
void ERShader::UpdateTimeOfDayShader(void) { SetShaderASyncForState((r4 << 2)); }

// 0x80320070 (160 bytes)
// Call wrapper [1bl_with_branch]: ERShader::SetCurrentShaderForState(unsigned char)
__attribute__((noreturn))
void ERShader::SetDayNightShaderToClosestTime(int, int) {
    __asm__ __volatile__(
        "stwu	1,-8(1)\n"
        "mflr	0\n"
        "stw	0,12(1)\n"
        "lis	0,-30584\n"
        "srawi	9,5,31\n"
        "ori	0,0,34953\n"
        "lbz	10,68(3)\n"
        "mulhw	0,5,0\n"
        "slwi	4,4,2\n"
        "li	8,0\n"
        "li	11,0\n"
        "cmpw	8,10\n"
        "add	0,0,5\n"
        "srawi	0,0,3\n"
        "subf	0,9,0\n"
        "add	4,4,0\n"
        "clrlwi	4,4,24\n"
        "bge	.L_803200E8\n"
        "lwz	9,72(3)\n"
        "lbz	0,0(9)\n"
        "cmplw	0,4\n"
        "bgt	.L_803200E8\n"
        ".L_803200C8:\n"
        "addi	11,11,1\n"
        "cmpw	11,10\n"
        "bge	.L_803200E8\n"
        "lbzx	0,9,11\n"
        "cmplw	0,4\n"
        "bgt	.L_803200E8\n"
        "mr	8,11\n"
        "b	.L_803200C8\n"
        ".L_803200E8:\n"
        "lbz	0,68(3)\n"
        "cmpw	11,0\n"
        "beq	.L_80320100\n"
        "lwz	9,72(3)\n"
        "lbzx	4,9,8\n"
        ".long 0x4bffdee5  /* bl ERShader::SetCurrentShaderForState(unsigned char) */\n"
        ".L_80320100:\n"
        "lwz	0,12(1)\n"
        "mtlr	0\n"
        "addi	1,1,8\n"
        "blr\n"
    );
    __builtin_unreachable();
}

// 0x8032057C (84 bytes)
void ERShader::RegisterType(unsigned short) { ETypeInfo::Register((void*)0x8032047c, (void*)0x803204a4, (void*)0x803204d0, this, (void*)0x80420a0c, (void*)0x8050cd38)  /* on (void*)0x8050cf00 */; }
