#include "types.h"
#include "stub_classes.h"
// Auto-converted call wrapper stubs for ERSoundEvent
// Generated by convert_call_wrappers.py

// 0x80369F78 (84 bytes)
void ERSoundEvent::RegisterType(unsigned short) { ETypeInfo::Register((void*)0x80379e78, (void*)0x80379ea0, (void*)0x80379ecc, this, (void*)0x8042336c, (void*)0x8050cd38)  /* on (void*)0x8050d84c */; }
