#include "types.h"
#include "stub_classes.h"
// Auto-generated matching stubs for ERTexture
// Generated by auto_match.py
// 7 functions, 80 bytes

// 0x803212A8 (12 bytes)
void* ERTexture::GetTypeInfo() const{ void* __p; __asm__ __volatile__("lis %0, -32688\n""addi %0, %0, -12504" : "=r"(__p)); return __p; }

// 0x803212B4 (12 bytes)
void ERTexture::GetTypeName() const{ register int __val __asm__("r3"); __asm__ __volatile__("lis %%r9, -32688\n""lwz %0, -12492(%%r9)" : "=r"(__val) : : "r9"); return __val; }

// 0x803212C0 (12 bytes)
void ERTexture::GetTypeKey() const{ register int __val __asm__("r3"); __asm__ __volatile__("lis %%r9, -32688\n""lwz %0, -12488(%%r9)" : "=r"(__val) : : "r9"); return __val; }

// 0x803212CC (12 bytes)
int ERTexture::GetTypeVersion() const{ register int __val __asm__("r3"); __asm__ __volatile__("lis %%r9, -32688\n""lhz %0, -12484(%%r9)" : "=r"(__val) : : "r9"); return __val; }
// 0x803212D8 (12 bytes)
void* ERTexture::GetTypeInfoStatic(){ void* __p; __asm__ __volatile__("lis %0, -32688\n""addi %0, %0, -12504" : "=r"(__p)); return __p; }

// 0x803212E4 (12 bytes)
int ERTexture::GetReadVersion(){ register int __val __asm__("r3"); __asm__ __volatile__("lis %%r9, -32688\n""lhz %0, -12482(%%r9)" : "=r"(__val) : : "r9"); return __val; }

// 0x80321394 (8 bytes)
void* ERTexture::operator new(unsigned int, void *) { return (void*)0; }  // mr r3,r4
#endif

