// Auto-generated matching stubs for ERTQuantize4D
// Generated by auto_match.py
// 1 functions, 8 bytes

// 0x8035FF48 (8 bytes)
int ERTQuantize4D::GetPaletteSize() { return *(int*)((char*)this + 0x1024); }  // offset 0x1024

