#include "types.h"
#include "stub_classes.h"
// Auto-generated matching stubs for EStorable
// Generated by auto_match.py
// 8 functions, 76 bytes

// 0x803C1420 (12 bytes)
void* EStorable::GetTypeInfo() const{ void* __p; __asm__ __volatile__("lis %0, -32688\n""addi %0, %0, -13320" : "=r"(__p)); return __p; }

// 0x803C142C (12 bytes)
void EStorable::GetTypeName() const { return *(int*)0x8050CC04; }  // global variable

// 0x803C1438 (12 bytes)
void EStorable::GetTypeKey() const { return *(int*)0x8050CC08; }  // global variable
#if 0

// 0x803C1444 (12 bytes)
unsigned short EStorable::GetTypeVersion() const { return *(unsigned short*)0x8050CC0C; }  // global variable
#endif
#if 0

// 0x803C1484 (4 bytes)
void EStorable::Read(EStream &) { }
#endif

// 0x803C1488 (4 bytes)
void EStorable::Write(EStream &) { }

// 0x803C148C (4 bytes)
void EStorable::Load(EFile &) { }

// 0x803C247C (16 bytes)
void EStorable::Construct(EStorable *){ register void* __vt __asm__("r9"); __asm__ __volatile__("lis %0, -32697\n""addi %0, %0, -28472" : "=r"(__vt)); *(void**)((char*)this + 0) = __vt; }

