// Auto-generated matching stubs for EString
// Generated by auto_match.py
// 1 functions, 8 bytes

// 0x803B0A6C (8 bytes)
int EString::operator char *() const { return *(int*)((char*)this + 0x0); }  // offset 0x0

