// Auto-generated matching stubs for ESubModel
// Generated by auto_match.py
// 1 functions, 8 bytes

// 0x802FAE20 (8 bytes)
#include "types.h"
#include "stub_classes.h"
int ESubModel::GetCompositeShaderFlags() { return 0; }

