#include "types.h"
#include "stub_classes.h"
// Auto-generated matching stubs for FloatConstantsQuickData
// Generated by auto_match.py
// 7 functions, 68 bytes

// 0x800B70FC (8 bytes)
int FloatConstantsQuickData::SaveDataByID(ObjectDataID &) { return 0; }

// 0x800B7174 (8 bytes)
int FloatConstantsQuickData::GetDataSourceType() const { return 1; }

// 0x800B717C (20 bytes)
void FloatConstantsQuickData::AddRef() { *(int*)((char*)this + 0x10) += 1; }  // refcount increment

// 0x800B71EC (8 bytes)
int FloatConstantsQuickData::LoadFromIndex(unsigned int, int) { return 0; }

// 0x800B71F4 (8 bytes)
int FloatConstantsQuickData::GetResourceName(StringBuffer &) const { return 0; }

// 0x800B71FC (8 bytes)
void FloatConstantsQuickData::SetResourceName(StringBuffer &) { return 0; }

// 0x800B7204 (8 bytes)
bool FloatConstantsQuickData::LoadOnlyNameAndIDFromIndex(unsigned int, int) { return false; }

