#include "types.h"
#include "stub_classes.h"
// Auto-generated matching stubs for G2DTarget
// Generated by auto_match.py
// 3 functions, 24 bytes

// 0x801B5A04 (8 bytes)
int G2DTarget::IsG2DActive() { return *(int*)((char*)this + 0x88); }  // offset 0x88

// 0x801B5A0C (8 bytes)
int G2DTarget::IsG2DSpawned() { return *(int*)((char*)this + 0x84); }  // offset 0x84

// 0x801E7050 (8 bytes)
int G2DTarget::IsInitComplete(){ int __sda; __asm__ __volatile__("lwz %0, -30368(%%r13)" : "=r"(__sda)); return __sda; }

