#include "types.h"
#include "stub_classes.h"
// Auto-generated matching stubs for GameData
// Generated by auto_match.py
// 3 functions, 16 bytes

// 0x8003CE78 (4 bytes)
void GameData::SystemPostUpdate() { }

// 0x8003DC38 (4 bytes)
void GameData::StageOutputActualTimes(char *) { }

// 0x8003DDA0 (8 bytes)
int GameData::GetBuildBuyPlayer() const { return *(int*)((char*)this + 0x128); }  // offset 0x128

