#include "types.h"
#include "stub_classes.h"
// Auto-generated matching stubs for IBaseSimInstance
// Generated by auto_match.py
// 1 functions, 20 bytes

// 0x800567E4 (20 bytes)
void IBaseSimInstance::IBaseSimInstance() { *(void**)((char*)this + 0x0) = (void*)0x8046C8E0; }  // vtable init

