#include "types.h"
#include "stub_classes.h"
// Auto-generated matching stubs for IFFBehaviorConstants
// Generated by auto_match.py
// 2 functions, 28 bytes

// 0x8015A614 (20 bytes)
void IFFBehaviorConstants::AddRef() { *(int*)((char*)this + 0x60) += 1; }  // refcount increment

// 0x8015A8A8 (8 bytes)
void IFFBehaviorConstants::GetDataSourceType() const {  }

