// Auto-generated matching stubs for IFFResMap
// Generated by auto_match_medium.py

// 0x800BD968 (32 bytes)
int IFFResMap::CountTypes() { return *(int*)((char*)this + 0x0) / N; }  // division by constant

