#include "types.h"
#include "stub_classes.h"
// Auto-generated matching stubs for Interactor
// Generated by auto_match.py
// 15 functions, 132 bytes

// 0x802092A4 (8 bytes)
void InteractorModule::Interactor::AttachCamera(ESimsCam *) { *(int*)((char*)this + 0x4) = val; }  // offset 0x4

// 0x802092AC (8 bytes)
int InteractorModule::Interactor::GetAttachedCamera() { return *(int*)((char*)this + 0x4); }  // offset 0x4

// 0x802092D8 (20 bytes)
void InteractorModule::Interactor::SetExtents(EVec2 &) { /* copy two fields: 4(r4)->84(r3), 0(r4)->80(r3) */ }

// 0x802094EC (4 bytes)
void InteractorModule::Interactor::OnCommandPressed(InteractorModule::InteractorInputManager::InteractorCommand, float) { }

// 0x802094F0 (16 bytes)
void InteractorModule::Interactor::AddIdleTime(float) { *(float*)((char*)this + 0x58) += val; }

// 0x80209500 (16 bytes)
void InteractorModule::Interactor::ResetIdleTime() { *(float*)((char*)this + 0x58) = *(float*)0x8040CE60; }  // init float from global

// 0x80209510 (4 bytes)
void InteractorModule::Interactor::UpdateOverlapIntersection(InteractorModule::Interactor::OverlapData *) { }

// 0x80209514 (4 bytes)
void InteractorModule::Interactor::ExecuteObjectActionMenu(cXObject *) { }

// 0x80209518 (4 bytes)
void InteractorModule::Interactor::StopInObjectMenu() { }

// 0x8020951C (8 bytes)
int InteractorModule::Interactor::ChooseAction(Interaction *) { return 0; }

// 0x80209524 (8 bytes)
void* InteractorModule::Interactor::GetPos() { return (char*)this + 0x8; }  // offset 0x8

// 0x8020952C (8 bytes)
void* InteractorModule::Interactor::GetSnappedPos() { return (char*)this + 0x20; }  // offset 0x20

// 0x802095CC (8 bytes)
int InteractorModule::Interactor::GetPlayerId() { return *(int*)((char*)this + 0x0); }  // offset 0x0

// 0x802095D4 (8 bytes)
void InteractorModule::Interactor::SetDrawState(int) { *(int*)((char*)this + 0x4C) = val; }  // offset 0x4C

// 0x802095DC (8 bytes)
int InteractorModule::Interactor::GetDrawState() { return *(int*)((char*)this + 0x4C); }  // offset 0x4C

