#if 0 // SKIP
// Auto-generated matching stubs for InventoryItems
// Generated by auto_match.py
// 1 functions, 8 bytes

// 0x8004AA5C (8 bytes)
#include "types.h"
#include "stub_classes.h"
int BBI::InventoryItems::GetContainerSize() const { return 36; }

#endif
