#include "types.h"
#include "stub_classes.h"
// Auto-generated matching stubs for ISimsWallObjectModel
// Generated by auto_match.py
// 7 functions, 76 bytes

// 0x80051218 (4 bytes)
void ISimsWallObjectModel::CreateShadow() { }

// 0x80053F58 (12 bytes)
const ETypeInfo* ISimsWallObjectModel::GetTypeInfo() const{ void* __p; __asm__ __volatile__("lis %0, -32688\n""addi %0, %0, -18448" : "=r"(__p)); return __p; }

// 0x80053F64 (12 bytes)
const char* ISimsWallObjectModel::GetTypeName() const{ register int __val __asm__("r3"); __asm__ __volatile__("lis %%r9, -32688\n""lwz %0, -18436(%%r9)" : "=r"(__val) : : "r9"); return (const char*)__val; }

// 0x80053F70 (12 bytes)
u32 ISimsWallObjectModel::GetTypeKey() const{ register int __val __asm__("r3"); __asm__ __volatile__("lis %%r9, -32688\n""lwz %0, -18432(%%r9)" : "=r"(__val) : : "r9"); return __val; }

// 0x80053F7C (12 bytes)
unsigned short ISimsWallObjectModel::GetTypeVersion() const{ register int __val __asm__("r3"); __asm__ __volatile__("lis %%r9, -32688\n""lhz %0, -18428(%%r9)" : "=r"(__val) : : "r9"); return __val; }

// 0x80053F88 (12 bytes)
const ETypeInfo* ISimsWallObjectModel::GetTypeInfoStatic() { return (void*)0x8050B7F0; }  // global data pointer

// 0x80053F94 (12 bytes)
unsigned short ISimsWallObjectModel::GetReadVersion() { return *(unsigned short*)0x8050B806; }  // global variable

