#include "types.h"
#include "stub_classes.h"
// Auto-generated matching stubs for ITBTarget
// Generated by auto_match.py
// 4 functions, 40 bytes

// 0x801BD870 (12 bytes)
void ITBTarget::ShowIntroThoughtBalloon() { *(int*)((char*)this + 0x98) = 1; }

// 0x801BD87C (12 bytes)
void ITBTarget::HideIntroThoughtBalloon() { *(int*)((char*)this + 0x98) = 0; }

// 0x801BD8F4 (8 bytes)
int ITBTarget::IsIntroThoughtBalloonActive() { return *(int*)((char*)this + 0x88); }  // offset 0x88

// 0x801BDA50 (8 bytes)
float ITBTarget::GetUserReadTime() { return *(float*)((char*)this + 0x9C); }  // offset 0x9C

