#include "types.h"
#include "stub_classes.h"
// Auto-generated matching stubs for LiveModeInitState
// Generated by auto_match.py
// 2 functions, 8 bytes

// 0x8008BC24 (4 bytes)
void LiveModeInitState::Shutdown() { }

// 0x8008C9BC (4 bytes)
void LiveModeInitState::Draw(ERC *) { }

