#include "types.h"
#include "stub_classes.h"
// Auto-converted call wrapper stubs for MMUTarget
// Generated by convert_call_wrappers.py

// 0x801C6644 (72 bytes)
// Call wrapper [2bl_with_branch]: MMUTarget::GetNGHListItemName(char *), MMUTarget::GetLotListItemName(char *)
__attribute__((noreturn))
void MMUTarget::GetListItemName(char *) {
    __asm__ __volatile__(
        "stwu	1,-8(1)\n"
        "mflr	0\n"
        "stw	0,12(1)\n"
        "mr	9,3\n"
        "lwz	0,140(9)\n"
        "cmpwi	0,1\n"
        "bne	.L_801C6668\n"
        ".long 0x480003ad  /* bl MMUTarget::GetNGHListItemName(char *) */\n"
        "b	.L_801C667C\n"
        ".L_801C6668:\n"
        "cmpwi	0,2\n"
        "li	3,0\n"
        "bne	.L_801C667C\n"
        "mr	3,9\n"
        ".long 0x480004dd  /* bl MMUTarget::GetLotListItemName(char *) */\n"
        ".L_801C667C:\n"
        "lwz	0,12(1)\n"
        "mtlr	0\n"
        "addi	1,1,8\n"
        "blr\n"
    );
    __builtin_unreachable();
}

// 0x801C6758 (68 bytes)
// Call wrapper [2bl_with_branch]: MMUTarget::UpdateNGHListItems(void), MMUTarget::UpdateLotListItems(void)
__attribute__((noreturn))
void MMUTarget::UpdateListItems(void) {
    __asm__ __volatile__(
        "stwu	1,-8(1)\n"
        "mflr	0\n"
        "stw	0,12(1)\n"
        "lwz	0,140(3)\n"
        "cmpwi	0,0\n"
        "beq	.L_801C6778\n"
        "cmpwi	0,1\n"
        "bne	.L_801C6780\n"
        ".L_801C6778:\n"
        ".long 0x48000025  /* bl MMUTarget::UpdateNGHListItems(void) */\n"
        "b	.L_801C678C\n"
        ".L_801C6780:\n"
        "cmpwi	0,2\n"
        "bne	.L_801C678C\n"
        ".long 0x48000161  /* bl MMUTarget::UpdateLotListItems(void) */\n"
        ".L_801C678C:\n"
        "lwz	0,12(1)\n"
        "mtlr	0\n"
        "addi	1,1,8\n"
        "blr\n"
    );
    __builtin_unreachable();
}

// 0x801C781C (80 bytes)
// Call wrapper [2bl_with_branch]: MMUTarget::ChangeScreenMode(void), MMUTarget::UpdateText(void)
__attribute__((noreturn))
void MMUTarget::OnCircleKeyPressed(char *, char *) {
    __asm__ __volatile__(
        "stwu	1,-16(1)\n"
        "mflr	0\n"
        "stw	31,12(1)\n"
        "stw	0,20(1)\n"
        "mr	31,3\n"
        "lwz	0,140(31)\n"
        "cmpwi	0,0\n"
        "bne	.L_801C7858\n"
        "lis	9,-32697\n"
        "lwz	0,25040(9)\n"
        "cmpwi	0,0\n"
        "beq	.L_801C7858\n"
        ".long 0x4bffee41  /* bl MMUTarget::ChangeScreenMode(void) */\n"
        "mr	3,31\n"
        ".long 0x48000145  /* bl MMUTarget::UpdateText(void) */\n"
        ".L_801C7858:\n"
        "lwz	0,20(1)\n"
        "mtlr	0\n"
        "lwz	31,12(1)\n"
        "addi	1,1,16\n"
        "blr\n"
    );
    __builtin_unreachable();
}

// 0x801C786C (68 bytes)
void MMUTarget::UpdateTopLevelChoice(char *, char *) { AtoI(p1); OnTopLevelChoiceChange(); }

// 0x801C78B0 (68 bytes)
void MMUTarget::UpdateGameplayChoice(char *, char *) { AtoI(p1); OnGameplayLevelChoiceChange(); }

// 0x801C78F4 (68 bytes)
void MMUTarget::UpdateNumberOfPlayersChoice(char *, char *) { AtoI(p1); OnNumberOfPlayersChoiceChange(); }

// 0x801C85D0 (76 bytes)
// Call wrapper [2bl_with_branch]: AtoI(char *), MMUTarget::ChangeScreenMode(MMUTarget::MMU_MODE)
__attribute__((noreturn))
void MMUTarget::UpdateDevMenuState(char *, char *) {
    __asm__ __volatile__(
        "stwu	1,-16(1)\n"
        "mflr	0\n"
        "stw	31,12(1)\n"
        "stw	0,20(1)\n"
        "lis	9,-32697\n"
        "mr	31,3\n"
        "lwz	0,25040(9)\n"
        "mr	3,5\n"
        "cmpwi	0,0\n"
        "beq	.L_801C8608\n"
        ".long 0x48116659  /* bl AtoI(char *) */\n"
        "mr	4,3\n"
        "mr	3,31\n"
        ".long 0x480000b1  /* bl MMUTarget::ChangeScreenMode(MMUTarget::MMU_MODE) */\n"
        ".L_801C8608:\n"
        "lwz	0,20(1)\n"
        "mtlr	0\n"
        "lwz	31,12(1)\n"
        "addi	1,1,16\n"
        "blr\n"
    );
    __builtin_unreachable();
}

// 0x801C86C4 (92 bytes)
// Call wrapper [2bl_with_branch]: MMUTarget::GetNumberOfControllers(void), UIObjectBase::AptViewer_CallFunction(char *, char *, char *, int, char **)
__attribute__((noreturn))
void MMUTarget::PollControllersForNumOfPlayersState(void) {
    __asm__ __volatile__(
        "stwu	1,-16(1)\n"
        "mflr	0\n"
        "stw	31,12(1)\n"
        "stw	0,20(1)\n"
        "mr	31,3\n"
        ".long 0x4bfff9ed  /* bl MMUTarget::GetNumberOfControllers(void) */\n"
        "lwz	0,256(31)\n"
        "mr	9,3\n"
        "cmpw	0,9\n"
        "beq	.L_801C870C\n"
        "lis	3,-32705\n"
        "stw	9,256(31)\n"
        "addi	3,3,11792\n"
        "li	4,0\n"
        "li	5,0\n"
        "li	6,0\n"
        "li	7,0\n"
        ".long 0x4bfaf64d  /* bl UIObjectBase::AptViewer_CallFunction(char *, char *, char *, int, char **) */\n"
        ".L_801C870C:\n"
        "lwz	0,20(1)\n"
        "mtlr	0\n"
        "lwz	31,12(1)\n"
        "addi	1,1,16\n"
        "blr\n"
    );
    __builtin_unreachable();
}

// 0x801C8720 (104 bytes)
// Call wrapper [2bl_with_branch]: SetupCAS(void), MMUTarget::OnStartGameComplete(bool)
__attribute__((noreturn))
void MMUTarget::OnDialogClose(int) {
    __asm__ __volatile__(
        "stwu	1,-24(1)\n"
        "mflr	0\n"
        "stmw	29,12(1)\n"
        "stw	0,28(1)\n"
        "mr	31,4\n"
        "mr	29,3\n"
        "cmpwi	31,1\n"
        "bne	.L_801C8774\n"
        "lis	9,-32697\n"
        "li	30,0\n"
        "addi	9,9,23428\n"
        "stw	31,132(9)\n"
        "stw	30,240(9)\n"
        ".long 0x4bffe871  /* bl SetupCAS(void) */\n"
        "lis	9,-32697\n"
        "mr	3,29\n"
        "addi	9,9,24012\n"
        "li	4,1\n"
        "stw	30,1100(9)\n"
        "stw	31,1096(9)\n"
        ".long 0x4bfffde1  /* bl MMUTarget::OnStartGameComplete(bool) */\n"
        ".L_801C8774:\n"
        "lwz	0,28(1)\n"
        "mtlr	0\n"
        "lmw	29,12(1)\n"
        "addi	1,1,24\n"
        "blr\n"
    );
    __builtin_unreachable();
}
