// Auto-generated matching stubs for MUStatesLoadGame
// Generated by auto_match.py
// 3 functions, 28 bytes

// 0x80091B78 (12 bytes)
#include "types.h"
#include "stub_classes.h"
void MUStatesLoadGame::Reset() { *(int*)((char*)this + 0x1C) = 0; }

// 0x80091B84 (4 bytes)
void MUStatesLoadGame::Draw(ERC *) { }

// 0x80093E28 (12 bytes)
int MUStatesLoadGame::GetWrapper() { return *(int*)((char*)(*(void**)((char*)this + 0x8)) + 0x98); }  // double deref

