#include "types.h"
#include "stub_classes.h"
// Auto-generated matching stubs for MUStatesDisplay
// Generated by auto_match.py
// 2 functions, 16 bytes

// 0x800931B0 (4 bytes)
void MUStatesDisplay::Startup() { }

// 0x80094270 (12 bytes)
int MUStatesDisplay::GetWrapper() { return *(int*)((char*)(*(void**)((char*)this + 0x8)) + 0x98); }  // double deref

