#if 0 // SKIP
// Auto-generated matching stubs for MUWrapper
// Generated by auto_match.py
// 3 functions, 24 bytes

// 0x80083954 (8 bytes)
#include "types.h"
#include "stub_classes.h"
void MUWrapper::SetScreenConfiguration(int) { *(int*)((char*)this + 0xAC) = val; }  // offset 0xAC

// 0x8008395C (8 bytes)
void MUWrapper::SetBackgroundDrawEnable(bool) { *(int*)((char*)this + 0xC8) = val; }  // offset 0xC8

// 0x80083964 (8 bytes)
int MUWrapper::GetFont() { return *(int*)((char*)this + 0xA4); }  // offset 0xA4

#endif
