// Auto-generated matching stubs for NghResFile
// Generated by auto_match.py
// 26 functions, 168 bytes

// 0x800D3BB8 (8 bytes)
#include "types.h"
#include "stub_classes.h"
void NghResFile::Delete(StringBuffer &) { return 0; }

// 0x800D3BC0 (8 bytes)
int NghResFile::Open(StringBuffer &) { return 0; }

// 0x800D3BC8 (8 bytes)
int NghResFile::CloseForReopen() { return 0; }

// 0x800D3BD0 (8 bytes)
int NghResFile::Reopen() { return 0; }

// 0x800D3BD8 (8 bytes)
int NghResFile::Close() { return 0; }

// 0x800D3BE0 (4 bytes)
void NghResFile::Update() { }

// 0x800D3BE4 (8 bytes)
int NghResFile::Writable() { return 0; }

// 0x800D3C18 (8 bytes)
int NghResFile::ValidFile() { return 1; }

// 0x800D3C20 (8 bytes)
int NghResFile::CountTypes() { return 0; }

// 0x800D3C28 (8 bytes)
int NghResFile::GetIndType(short) { return 0; }

// 0x800D3CC8 (8 bytes)
int NghResFile::GetByName(int, StringBuffer &, void (*)(void *, int)) { return 0; }

// 0x800D3D3C (4 bytes)
void NghResFile::GetName(int *, StringBuffer &) { }

// 0x800D3D40 (8 bytes)
int NghResFile::GetResType(int *) { return 0; }

// 0x800D3D58 (4 bytes)
void NghResFile::GetIndex(int *, short *) { }

// 0x800D3D5C (4 bytes)
void NghResFile::FindUniqueName(int, StringBuffer &) { }

// 0x800D3D60 (8 bytes)
int NghResFile::FindUniqueID(int) { return 0; }

// 0x800D3D68 (4 bytes)
void NghResFile::Detach(int *) { }

// 0x800D3D6C (4 bytes)
void NghResFile::Load(int *) { }

// 0x800D3D70 (8 bytes)
bool NghResFile::IsLittleEndian(int *) { return true; }

// 0x800D3D78 (4 bytes)
void NghResFile::SetID(int *, short) { }

// 0x800D3F6C (4 bytes)
void NghResFile::Write(int *) { }

// 0x800D3F70 (4 bytes)
void NghResFile::Remove(int *) { }

// 0x800D3F74 (4 bytes)
void NghResFile::SetInfo(int *, short, StringBuffer &, char) { }

// 0x800D8EE0 (8 bytes)
void NghResFile::SetStoreChecksum(bool) { *(int*)((char*)this + 0x18C) = val; }  // offset 0x18C

// 0x800D8EE8 (8 bytes)
int NghResFile::GetStoreChecksum() { return *(int*)((char*)this + 0x18C); }  // offset 0x18C

// 0x800D93CC (8 bytes)
int NghResFile::GetSourceType() const { return *(int*)((char*)this + 0x20); }  // offset 0x20

