#include "types.h"
#include "stub_classes.h"
// Auto-converted call wrapper stubs for node_alloc_L_false_0_R
// Generated by convert_call_wrappers.py

// 0x8039C304 (80 bytes)
// Call wrapper [1bl_with_branch]: __node_alloc<false, 0>::_S_refill(unsigned int)
__attribute__((noreturn))
void __node_alloc<false, 0>::_M_allocate(unsigned int) {
    __asm__ __volatile__(
        "stwu	1,-16(1)\n"
        "mflr	0\n"
        "stw	0,20(1)\n"
        "mr	10,3\n"
        "lis	9,-32698\n"
        "addi	0,10,-1\n"
        "addi	9,9,-22352\n"
        "rlwinm	11,0,31,1,29\n"
        "lwzx	3,11,9\n"
        "cmpwi	3,0\n"
        "beq	.L_8039C33C\n"
        "lwz	0,0(3)\n"
        "stwx	0,11,9\n"
        "b	.L_8039C344\n"
        ".L_8039C33C:\n"
        "mr	3,10\n"
        ".long 0x4bffff19  /* bl __node_alloc<false, 0>::_S_refill(unsigned int) */\n"
        ".L_8039C344:\n"
        "lwz	0,20(1)\n"
        "mtlr	0\n"
        "addi	1,1,16\n"
        "blr\n"
    );
    __builtin_unreachable();
}
