#include "types.h"
#include "stub_classes.h"
// Auto-generated matching stubs for O2TTarget
// Generated by auto_match.py
// 2 functions, 32 bytes

// 0x801CEA60 (20 bytes)
void O2TTarget::SaveGame(char *, char *) { *(int*)((char*)this + 0x250) = 0; *(int*)((char*)this + 0x90) = 1; }

// 0x801CFA60 (12 bytes)
void O2TTarget::OnCancelDialog() { *(int*)((char*)this + 0x250) = 0; }

