#include "types.h"
#include "stub_classes.h"
// Auto-generated matching stubs for ObjectDataID
// Generated by auto_match.py
// 3 functions, 32 bytes

// 0x8015BAF4 (16 bytes)
void ObjectDataID::ObjectDataID(unsigned int, unsigned short) { *(int*)((char*)this + 0x0) = param4; *(short*)((char*)this + 0x4) = param5; }

// 0x8015BBE8 (8 bytes)
void ObjectDataID::SetNamespaceID(unsigned int) { *(int*)((char*)this + 0x0) = val; }  // offset 0x0

// 0x8015BBF0 (8 bytes)
void ObjectDataID::SetResourceID(unsigned short) { *(short*)((char*)this + 0x4) = val; }  // offset 0x4

