// Auto-generated matching stubs for ObjSelector
// Generated by auto_match.py
// 4 functions, 28 bytes

// 0x801108DC (12 bytes)
#include "types.h"
#include "stub_classes.h"
int ObjSelector::GetGUID() const { return *(int*)((char*)(*(void**)((char*)this + 0x38)) + 0x1C); }  // double deref

// 0x801108E8 (4 bytes)
void ObjSelector::SetObjectName(char *) { }

// 0x801108EC (4 bytes)
void ObjSelector::ChangedDef() { }

// 0x803A5208 (8 bytes)
int ObjSelector::GetSimDescription() const { return *(int*)((char*)this + 0x8C); }  // offset 0x8C

