// Auto-generated matching stubs for OptionsRecon
// Generated by auto_match.py
// 2 functions, 16 bytes

// 0x80058D24 (8 bytes)
int OptionsRecon::WriteToMemoryCard(char *, unsigned char) { return 0; }

// 0x80058E54 (8 bytes)
int OptionsRecon::ReadFromMemoryCard(char *, unsigned char) { return 0; }

