// Auto-generated matching stubs for PlacementObject
// Generated by auto_match_medium.py

// 0x8021AAB8 (56 bytes)
void InteractorModule::PlacementObject::PlacementObject() { *(int*)((char*)this + 0x0) = 0; *(int*)((char*)this + 0x4) = 0; *(int*)((char*)this + 0x14) = 0; *(int*)((char*)this + 0x18) = 0; *(int*)((char*)this + 0x20) = 0; *(char*)((char*)this + 0x24) = 0; *(int*)((char*)this + 0x28) = 0; }

