#include "types.h"
#include "stub_classes.h"
// Auto-generated matching stubs for PlumbBob
// Generated by auto_match.py
// 1 functions, 12 bytes

// 0x8005A45C (12 bytes)
void PlumbBob::BecomeTransitionIndicator() { *(int*)((char*)this + 0x160) = 1; }

