#include "types.h"
#include "stub_classes.h"
// Auto-generated matching stubs for PreGameFreeplayState
// Generated by auto_match_medium.py

// 0x80095408 (60 bytes)
void PreGameFreeplayState::PreGameFreeplayState(int) { *(int*)((char*)this + 0x0) = p2; *(int*)((char*)this + 0xC) = -1; *(int*)((char*)this + 0x14) = 1; *(void**)((char*)this + 0x18) = (void*)0x8046DEC0; *(int*)((char*)this + 0x1C) = 0; *(int*)((char*)this + 0x4) = -1; *(int*)((char*)this + 0x8) = 0; *(int*)((char*)this + 0x10) = 0; }

