#include "types.h"
#include "stub_classes.h"
// Auto-generated matching stubs for PropTableImpl
// Generated by auto_match.py
// 2 functions, 20 bytes

// 0x80132984 (12 bytes)
short PropTableImpl::GetID() { return *(short*)((char*)(*(void**)((char*)this + 0x4)) + 0x4); }  // double deref signed short

// 0x801329AC (8 bytes)
int PropTableImpl::GetEntryName(int) { return 0; }

