#include "types.h"
#include "stub_classes.h"
// Auto-converted call wrapper stubs for ProtectedAllocPool
// Generated by convert_call_wrappers.py

// 0x802D71D0 (80 bytes)
ProtectedAllocPool::~ProtectedAllocPool(void) { EMutex::~EMutex()  /* on (this + 0x18) */; FastAllocPool::~FastAllocPool(); }
