#if 0
#include "types.h"
#include "stub_classes.h"
// Auto-generated matching stubs for QuickDataBehaviorConstants
// Generated by auto_match.py
// 5 functions, 48 bytes

// 0x8015A06C (4 bytes)
void QuickDataBehaviorConstants::SetValueCount(int) { }

// 0x8015A0E0 (20 bytes)
void QuickDataBehaviorConstants::AddRef() { *(int*)((char*)this + 0x1C) += 1; }  // refcount increment

// 0x8015A7F0 (8 bytes)
int QuickDataBehaviorConstants::SaveDataByID(ObjectDataID &) { return 0; }

// 0x8015A7F8 (8 bytes)
int QuickDataBehaviorConstants::GetDataSourceType() const { return 1; }

// 0x8015A800 (8 bytes)
bool QuickDataBehaviorConstants::LoadOnlyNameAndIDFromIndex(unsigned int, int) { return false; }

#endif
