// Auto-generated matching stubs for ReconObject
// Generated by auto_match.py
// 2 functions, 16 bytes

// 0x80134768 (4 bytes)
#include "types.h"
#include "stub_classes.h"
void ReconObject::DoStream(ReconBuffer *, int) { }

// 0x8013476C (12 bytes)
unsigned int ReconObject::GetType() { return 0x52636F6E; }

