#include "types.h"
#include "stub_classes.h"
// Auto-converted call wrapper stubs for REffectsSequencer
// Generated by convert_call_wrappers.py

// 0x8036B1A8 (84 bytes)
void REffectsSequencer::RegisterType(unsigned short) { ETypeInfo::Register((void*)0x8037b0ac, (void*)0x8037b0dc, (void*)0x8037b0fc, this, (void*)0x80423448, (void*)0x8050cd38)  /* on (void*)0x8050d8c4 */; }
