#include "types.h"
#include "stub_classes.h"
// Auto-converted call wrapper stubs for RParticle
// Generated by convert_call_wrappers.py

// 0x8036C230 (84 bytes)
void RParticle::RegisterType(unsigned short) { ETypeInfo::Register((void*)0x8037c130, (void*)0x8037c158, (void*)0x8037c184, this, (void*)0x80423478, (void*)0x8050cd38)  /* on (void*)0x8050d8ec */; }
