#include "types.h"
#include "stub_classes.h"
// Auto-converted call wrapper stubs for ScalarDecomp
// Generated by convert_call_wrappers.py

// 0x803629E0 (108 bytes)
void ScalarDecomp::Reset(void) { EBitArray::Get(this->field_0x4, this->field_0x1e)  /* on this->field_0x0 */; ReadAllVs(); }

// 0x80362A4C (136 bytes)
void ScalarDecomp::ResetEnd(void) { EBitArray::Get((this->field_0x18 + -1), this->field_0x1e)  /* on this->field_0x0 */; ReadAllVs(); }
