#include "types.h"
#include "stub_classes.h"
// Auto-generated matching stubs for SimImageMaker
// Generated by auto_match.py
// 3 functions, 32 bytes

// 0x8006EBCC (8 bytes)
void SimImageMaker::SetGender(bool) { *(int*)((char*)this + 0x88) = val; }  // offset 0x88

// 0x8006EBD4 (8 bytes)
void SimImageMaker::SetSkinShader(EShader *) { *(int*)((char*)this + 0x8C) = val; }  // offset 0x8C

// 0x8006ECAC (16 bytes)
void SimImageMaker::OverrideImageSize(unsigned int, unsigned int, unsigned int) { *(int*)((char*)this + 0x8) = param6; *(int*)((char*)this + 0x0) = param4; *(int*)((char*)this + 0x4) = param5; }

