// Auto-generated matching stubs for SimpleReconObject<ObjectSaveTypeTable2>
// Generated by auto_match.py
// 1 functions, 8 bytes

// 0x8039E330 (8 bytes)
int SimpleReconObject<ObjectSaveTypeTable2>::GetType() { return *(int*)((char*)this + 0x8); }  // offset 0x8

