// Auto-generated matching stubs for SimpleReconObject<HouseImpl>
// Generated by auto_match.py
// 1 functions, 8 bytes

// 0x803A386C (8 bytes)
int SimpleReconObject<HouseImpl>::GetType() { return *(int*)((char*)this + 0x8); }  // offset 0x8

