// Auto-generated matching stubs for StateMachineState
// Generated by auto_match.py
// 8 functions, 40 bytes

// 0x80095B10 (12 bytes)
#include "types.h"
#include "stub_classes.h"
int StateMachineState::OwnerGetReturnVal() { return *(int*)((char*)(*(void**)((char*)this + 0x8)) + 0x90); }  // double deref

// 0x80095B2C (4 bytes)
void StateMachineState::ValidateHeap(bool) { }

// 0x803A024C (4 bytes)
void StateMachineState::Startup() { }

// 0x803A0250 (4 bytes)
void StateMachineState::DrawTopmost(ERC *) { }

// 0x803A02BC (4 bytes)
void StateMachineState::Shutdown() { }

// 0x803A02C0 (4 bytes)
void StateMachineState::Reset() { }

// 0x803A02C4 (4 bytes)
void StateMachineState::Update(float) { }

// 0x803A02C8 (4 bytes)
void StateMachineState::Draw(ERC *) { }

