#include "types.h"
#include "stub_classes.h"
// Auto-generated matching stubs for StateMachine
// Generated by auto_match.py
// 18 functions, 176 bytes

// 0x80095DFC (16 bytes)
void StateMachine::ReturnFromState(int p4) { *(int*)((char*)this + 0x8C) = p4; *(int*)((char*)this + 0x88) = 1; }

// 0x80095E28 (12 bytes)
int StateMachine::GetCurStateStage() const { return *(int*)((char*)(*(void**)((char*)this + 0x3C)) + 0xC); }  // double deref

// 0x80095EA8 (12 bytes)
int StateMachine::GetLastStateId() const { return *(int*)((char*)(*(void**)((char*)this + 0x44)) + 0x0); }  // double deref

// 0x80095EB4 (12 bytes)
int StateMachine::GetCallingStateId() const { return *(int*)((char*)(*(void**)((char*)this + 0x48)) + 0x0); }  // double deref

// 0x800961B4 (8 bytes)
float StateMachine::GetTimeInState() const { return *(float*)((char*)this + 0x50); }  // offset 0x50

// 0x80096AF8 (4 bytes)
void StateMachine::Startup() { }

// 0x80096B20 (4 bytes)
void StateMachine::Reset() { }

// 0x80096B24 (8 bytes)
int StateMachine::GetMachineId() const { return *(int*)((char*)this + 0x1C); }  // offset 0x1C

// 0x80096B2C (8 bytes)
StateMachineManager* StateMachine::GetManager() const { return *(int*)((char*)this + 0x20); }  // offset 0x20

// 0x80096B34 (8 bytes)
float StateMachine::GetFrameDeltaTime() const { return *(float*)((char*)this + 0x28); }  // offset 0x28

// 0x80096B3C (8 bytes)
int StateMachine::GetReturnVal() const { return *(int*)((char*)this + 0x90); }  // offset 0x90

// 0x80096B44 (12 bytes)
void StateMachine::ResetReturnVal() { register int __r0 __asm__("r0") = 0; __asm__ __volatile__("" : "+r"(__r0)); *(int*)((char*)this + 0x90) = __r0; }

// 0x80096B50 (12 bytes)
void StateMachine::Enable() { register int __r0 __asm__("r0") = 1; __asm__ __volatile__("" : "+r"(__r0)); *(int*)((char*)this + 0x94) = __r0; }

// 0x80096B5C (12 bytes)
void StateMachine::Disable() { register int __r0 __asm__("r0") = 0; __asm__ __volatile__("" : "+r"(__r0)); *(int*)((char*)this + 0x94) = __r0; }

// 0x80096B68 (12 bytes)
void StateMachine::PauseUpdate() { register int __r0 __asm__("r0") = 1; __asm__ __volatile__("" : "+r"(__r0)); *(int*)((char*)this + 0x24) = __r0; }

// 0x80096B74 (12 bytes)
void StateMachine::UnpauseUpdate() { register int __r0 __asm__("r0") = 0; __asm__ __volatile__("" : "+r"(__r0)); *(int*)((char*)this + 0x24) = __r0; }

// 0x80096B80 (8 bytes)
int StateMachine::IsEnabled() { return *(int*)((char*)this + 0x94); }  // offset 0x94

// 0x80096B88 (8 bytes)
int StateMachine::IsPausedUpdate() { return *(int*)((char*)this + 0x24); }  // offset 0x24

