#include "types.h"
#include "stub_classes.h"
// Auto-generated matching stubs for TArray<ENDummyPoint, TArrayDefaultAllocator> (branching leaf functions)
// Generated by auto_match_branch.py
// 2 functions, 56 bytes

// 0x8039CB54 (28 bytes)
void TArray<ENDummyPoint, TArrayDefaultAllocator>::Destruct(ENDummyPoint *, int) { }

// 0x8039CB84 (28 bytes)
void TArray<ENDummyPoint, TArrayDefaultAllocator>::Construct(ENDummyPoint *, int) { }

