#include "types.h"
#include "stub_classes.h"
// Auto-generated matching stubs for TArray<unsigned int, TArrayDefaultAllocator>
// Generated by auto_match.py
// 1 functions, 20 bytes

// 0x803C3D90 (20 bytes)
void TArray<unsigned int, TArrayDefaultAllocator>::Init() { *(int*)((char*)this + 0x4) = 0; *(int*)((char*)this + 0x0) = 0; *(int*)((char*)this + 0x8) = 0; }

