#include "types.h"
#include "stub_classes.h"
// Auto-generated matching stubs for TArray<SimsLightInfo, TArrayERModelAllocator> (branching leaf functions)
// Generated by auto_match_branch.py
// 2 functions, 56 bytes

// 0x803C4340 (28 bytes)
void TArray<SimsLightInfo, TArrayERModelAllocator>::Destruct(SimsLightInfo *, int) { }

// 0x803C517C (28 bytes)
void TArray<SimsLightInfo, TArrayERModelAllocator>::Construct(SimsLightInfo *, int) { }

