#if 0 // SKIP
// Auto-generated matching stubs for TreeTableEntryQuickData
// Generated by auto_match.py
// 28 functions, 132 bytes

// 0x8015E6FC (8 bytes)
#include "types.h"
#include "stub_classes.h"
int TreeTableEntryQuickData::CountAds() const { return 16; }

// 0x8015E7C8 (12 bytes)
int TreeTableEntryQuickData::GetFlags() const { return *(int*)((char*)(*(void**)((char*)this + 0x4)) + 0x10); }  // double deref

// 0x8015E83C (4 bytes)
void TreeTableEntryQuickData::SetOrderIndex(int) { }

// 0x8015E840 (4 bytes)
void TreeTableEntryQuickData::SetAvailableToVisitors(bool) { }

// 0x8015E844 (4 bytes)
void TreeTableEntryQuickData::SetCanJoin(bool) { }

// 0x8015E848 (4 bytes)
void TreeTableEntryQuickData::SetImmediate(bool) { }

// 0x8015E84C (4 bytes)
void TreeTableEntryQuickData::SetAllowConsecutive(bool) { }

// 0x8015E850 (4 bytes)
void TreeTableEntryQuickData::SetAvailableToGhosts(bool) { }

// 0x8015E854 (4 bytes)
void TreeTableEntryQuickData::SetAvailableToAdults(bool) { }

// 0x8015E858 (4 bytes)
void TreeTableEntryQuickData::SetAvailableToChildrenDemo(bool) { }

// 0x8015E85C (4 bytes)
void TreeTableEntryQuickData::SetJoinIndex(int) { }

// 0x8015E860 (4 bytes)
void TreeTableEntryQuickData::SetDebugOnly(bool) { }

// 0x8015E864 (4 bytes)
void TreeTableEntryQuickData::SetAutoFirstSelect(bool) { }

// 0x8015E868 (4 bytes)
void TreeTableEntryQuickData::SetAvailableToVisitingPlayers(bool) { }

// 0x8015E86C (4 bytes)
void TreeTableEntryQuickData::SetIgnorePrefixTree(bool) { }

// 0x8015E870 (4 bytes)
void TreeTableEntryQuickData::SetMustRun(bool) { }

// 0x8015E874 (8 bytes)
int TreeTableEntryQuickData::GetAd(int) { return 0; }

// 0x8015E87C (4 bytes)
void TreeTableEntryQuickData::SetAd(int, ITreeTableAd &) { }

// 0x8015E880 (4 bytes)
void TreeTableEntryQuickData::SetActionTreeID(short) { }

// 0x8015E884 (4 bytes)
void TreeTableEntryQuickData::SetCheckTreeID(short) { }

// 0x8015E888 (4 bytes)
void TreeTableEntryQuickData::SetAttenuation(int) { }

// 0x8015E88C (4 bytes)
void TreeTableEntryQuickData::SetCustomAttenuation(float) { }

// 0x8015E890 (4 bytes)
void TreeTableEntryQuickData::SetAutonomyThreshold(short) { }

// 0x8015E894 (4 bytes)
void TreeTableEntryQuickData::SetName(BString2 &) { }

// 0x8015E898 (4 bytes)
void TreeTableEntryQuickData::SetUseCustomActivation(bool) { }

// 0x8015E89C (4 bytes)
void TreeTableEntryQuickData::SetActivationSubtile(unsigned char, unsigned char) { }

// 0x8015E8A0 (4 bytes)
void TreeTableEntryQuickData::SetActivationExtents(unsigned char, unsigned char, unsigned char, unsigned char) { }

// 0x8015E8A4 (8 bytes)
int TreeTableEntryQuickData::GetImplementation() const { return *(int*)((char*)this + 0x4); }  // offset 0x4

#endif
