// Auto-generated matching stubs for TTabScratchEntry
// Generated by auto_match.py
// 17 functions, 108 bytes

// 0x80149C98 (8 bytes)
#include "types.h"
#include "stub_classes.h"
void TTabScratchEntry::SetJoinIndex(int) { *(short*)((char*)this + 0x116) = val; }  // offset 0x116

// 0x80149D90 (8 bytes)
int TTabScratchEntry::CountAds() const { return 16; }

// 0x80149E80 (8 bytes)
void TTabScratchEntry::SetActionTreeID(short) { *(short*)((char*)this + 0x6) = val; }  // offset 0x6

// 0x80149E90 (8 bytes)
void TTabScratchEntry::SetCheckTreeID(short) { *(short*)((char*)this + 0x4) = val; }  // offset 0x4

// 0x80149E98 (8 bytes)
int TTabScratchEntry::GetAttenuation() const { return *(int*)((char*)this + 0x108); }  // offset 0x108

// 0x80149EA0 (8 bytes)
void TTabScratchEntry::SetAttenuation(int) { *(int*)((char*)this + 0x108) = val; }  // offset 0x108

// 0x80149EA8 (8 bytes)
float TTabScratchEntry::GetCustomAttenuationValue() const { return *(float*)((char*)this + 0x10C); }  // offset 0x10C

// 0x80149EC8 (8 bytes)
void TTabScratchEntry::SetAutonomyThreshold(short) { *(short*)((char*)this + 0x114) = val; }  // offset 0x114

// 0x80149F1C (4 bytes)
void TTabScratchEntry::SetName(BString2 &) { }

// 0x80149F28 (8 bytes)
int TTabScratchEntry::GetOrderIndex() const { return 0; }

// 0x80149F30 (4 bytes)
void TTabScratchEntry::SetOrderIndex(int) { }

// 0x80149F34 (8 bytes)
int TTabScratchEntry::GetUseCustomActivation() const { return 0; }

// 0x80149F3C (4 bytes)
void TTabScratchEntry::SetUseCustomActivation(bool) { }

// 0x80149F40 (4 bytes)
void TTabScratchEntry::GetActivationSubtile(unsigned char &, unsigned char &) const { }

// 0x80149F44 (4 bytes)
void TTabScratchEntry::SetActivationSubtile(unsigned char, unsigned char) { }

// 0x80149F48 (4 bytes)
void TTabScratchEntry::GetActivationExtents(unsigned char &, unsigned char &, unsigned char &, unsigned char &) const { }

// 0x80149F4C (4 bytes)
void TTabScratchEntry::SetActivationExtents(unsigned char, unsigned char, unsigned char, unsigned char) { }

