#include "types.h"
#include "stub_classes.h"
// Auto-generated matching stubs for UrbzCreditsState
// Generated by auto_match.py
// 1 functions, 4 bytes

// 0x80098D2C (4 bytes)
void UrbzCreditsState::Reset() { }

