// Auto-generated matching stubs for WAFTarget
// Generated by auto_match.py
// 4 functions, 40 bytes

// 0x801E3574 (12 bytes)
#include "types.h"
#include "stub_classes.h"
void WAFTarget::ShowWantsAndFears() { *(int*)((char*)this + 0x90) = 1; }

// 0x801E38F8 (8 bytes)
int WAFTarget::IsWantsAndFearsActive() { return *(int*)((char*)this + 0x88); }  // offset 0x88

// 0x801E4A00 (12 bytes)
void WAFTarget::OnGlowEffectComplete() { *(int*)((char*)this + 0x270) = 0; }

// 0x801E4F24 (8 bytes)
void WAFTarget::SetTextButtonPressed(bool) { *(int*)((char*)this + 0x9C) = val; }  // offset 0x9C

