#if 0
#include "types.h"
#include "stub_classes.h"
// Auto-generated matching stubs for WantFearManager
// Generated by auto_match.py
// 3 functions, 36 bytes

// 0x8014BD04 (4 bytes)
void WantFearManager::CaptureLog(bool) { }

// 0x8014BF20 (16 bytes)
void* WantFearManager::GetEventByIndex(int) const { return (char*)(*(void**)((char*)this + 0x8)) + index * 36; }  // struct array, stride=36

// 0x8014BFBC (16 bytes)
int WantFearManager::GetTreeByIndex(int) const { return ((int*)(*(void**)((char*)this + 0xC)))[index]; }  // ptr->array[index], elem_size=4

#endif
