// Auto-generated matching stubs for Wrapper
// Generated by auto_match.py
// 6 functions, 28 bytes

// 0x80086840 (8 bytes)
#include "types.h"
#include "stub_classes.h"
void Wrapper::WrapperStartup(UIObjectBase *) { *(int*)((char*)this + 0x88) = val; }  // offset 0x88

// 0x80086984 (4 bytes)
void Wrapper::WrapperRestoreMessageHandler() { }

// 0x80086988 (4 bytes)
void Wrapper::WrapperRemoveMessageHandler() { }

// 0x8008698C (4 bytes)
void Wrapper::WrapperReset() { }

// 0x80086990 (4 bytes)
void Wrapper::WrapperUpdate() { }

// 0x80086AE8 (4 bytes)
void Wrapper::WrapperCallFunction(char *) { }

