#if 0
#include "types.h"
#include "stub_classes.h"
// Auto-generated matching stubs for XObjLang
// Generated by auto_match.py
// 8 functions, 52 bytes

// 0x8015236C (4 bytes)
void XObjLang::GetTreeTypeName(int, StringBuffer &) { }

// 0x80152370 (4 bytes)
void XObjLang::GetNodeText(Behavior *, short, BehaviorNode *, StringBuffer &) { }

// 0x80152374 (4 bytes)
void XObjLang::GetPrimName(short, StringBuffer &) { }

// 0x80152378 (8 bytes)
bool XObjLang::IsSingleExit(BehaviorNode *) { return false; }

// 0x80152380 (8 bytes)
int XObjLang::CountPrimitives() { return 0; }

// 0x80152388 (8 bytes)
int XObjLang::GetSwizzler() { return 0; }

// 0x801523A4 (8 bytes)
int XObjLang::GetMaxConstants() { return 128; }

// 0x80152824 (8 bytes)
int XObjLang::GetSelector() { return *(int*)((char*)this + 0x4); }  // offset 0x4

#endif
