#include "types.h"
// Auto-generated inline asm decomp stubs for GameEffectsManager
// Generated by gen_asm_decomp.py
// 2 functions, 164 bytes
//
// Each function has its original C++ signature with the body as inline PPC asm.
// These can be incrementally replaced with real C++ as decompilation progresses.

class ELevelDrawData;
class EOrderTableData;

class GameEffectsManager {
public:
    void PreRender(void);
    void RenderCB(ELevelDrawData &, EOrderTableData *);
};

// 0x8003E048 (76 bytes)
// GameEffectsManager::PreRender(void)
__attribute__((noreturn))
void GameEffectsManager::PreRender(void) {
    __asm__ __volatile__(
        "stwu	1,-32(1)\n"
        "mflr	0\n"
        "stmw	29,20(1)\n"
        "stw	0,36(1)\n"
        "lis	9,-32698\n"
        "lis	29,-32698\n"
        "addi	9,9,-18784\n"
        "addi	30,1,8\n"
        "addi	29,29,-18736\n"
        "stw	9,8(1)\n"
        ".long 0x483142f5  /* bl Effects::EffectsManager::GetSingleton(void) */\n"
        "mr	4,30\n"
        ".long 0x483148d9  /* bl Effects::EffectsManager::ForEachActiveEffect(Effects::EffectsVisitor &) */\n"
        "stw	29,8(1)\n"
        "lwz	0,36(1)\n"
        "mtlr	0\n"
        "lmw	29,20(1)\n"
        "addi	1,1,32\n"
        "blr\n"
    );
    __builtin_unreachable();
}

// 0x8003E094 (88 bytes)
// GameEffectsManager::RenderCB(ELevelDrawData &, EOrderTableData *)
__attribute__((noreturn))
void GameEffectsManager::RenderCB(ELevelDrawData &, EOrderTableData *) {
    __asm__ __volatile__(
        "stwu	1,-16(1)\n"
        "mflr	0\n"
        "stw	31,12(1)\n"
        "stw	0,20(1)\n"
        "lwz	11,24(4)\n"
        "mr	31,3\n"
        "cmpwi	11,0\n"
        "beq	.L_8003E0D8\n"
        "lwz	9,324(11)\n"
        "lwz	4,152(31)\n"
        "lwz	0,28(9)\n"
        "lha	3,24(9)\n"
        "mtlr	0\n"
        "add	3,11,3\n"
        "blrl\n"
        "li	0,0\n"
        "stw	0,168(31)\n"
        ".L_8003E0D8:\n"
        "lwz	0,20(1)\n"
        "mtlr	0\n"
        "lwz	31,12(1)\n"
        "addi	1,1,16\n"
        "blr\n"
    );
    __builtin_unreachable();
}

