#include "types.h"
#include "stub_classes.h"
// Auto-generated raw-byte matches for CasEventResetSimDraw
// Generated by gen_raw_byte_matches.py
// 2 functions, 112 bytes
// These functions are matched by directly injecting DOL bytes into the skeleton.
// The C++ stubs below exist only as annotations for the matching pipeline.

// 0x803B0EBC (48 bytes)
// CasEventResetSimDraw__dtor_CasEventResetSimDraw_void
// [raw byte match - injected directly from DOL]

// 0x803B0EEC (64 bytes)
// CasEventResetSimDraw__Log_void__const
// [raw byte match - injected directly from DOL]

