#include "types.h"
#include "stub_classes.h"
// Auto-converted call wrapper stubs for ETexture
// Generated by convert_call_wrappers.py

// 0x80364FC4 (80 bytes)
// Call wrapper [1bl_with_branch]: EResourceManager::Free(void *)
__attribute__((noreturn))
ETexture::~ETexture(void) {
    __asm__ __volatile__(
        "stwu	1,-8(1)\n"
        "mflr	0\n"
        "stw	0,12(1)\n"
        "lis	0,-8531\n"
        "mr	11,3\n"
        "ori	0,0,48879\n"
        "lis	9,-32697\n"
        "addi	9,9,-9440\n"
        "stw	0,32(11)\n"
        "stw	9,36(11)\n"
        "andi.	0,4,1\n"
        "beq	.L_80365004\n"
        "lis	3,-32692\n"
        "mr	4,11\n"
        "addi	3,3,-7364\n"
        ".long 0x4bfc26ad  /* bl EResourceManager::Free(void *) */\n"
        ".L_80365004:\n"
        "lwz	0,12(1)\n"
        "mtlr	0\n"
        "addi	1,1,8\n"
        "blr\n"
    );
    __builtin_unreachable();
}
