#include "types.h"
// Auto-generated inline asm decomp stubs for TArray_L_ENLatticePoints_TArrayDefaultAllocator_R
// Generated by gen_asm_decomp.py
// 4 functions, 536 bytes
//
// Each function has its original C++ signature with the body as inline PPC asm.
// These can be incrementally replaced with real C++ as decompilation progresses.

class ENLatticePoints;

template <typename T0, typename T1> class TArray;
template <> class TArray<ENLatticePoints, TArrayDefaultAllocator> {
public:
    void Destruct(ENLatticePoints *, int);
    void Construct(ENLatticePoints *, int);
    void Copy(ENLatticePoints *, ENLatticePoints *, int);
    void SetSize(int, int);
};

// 0x8039C6F0 (80 bytes)
// TArray<ENLatticePoints, TArrayDefaultAllocator>::Destruct(ENLatticePoints *, int)
__attribute__((noreturn))
void TArray<ENLatticePoints, TArrayDefaultAllocator>::Destruct(ENLatticePoints *, int) {
    __asm__ __volatile__(
        "stwu	1,-16(1)\n"
        "mflr	0\n"
        "stmw	30,8(1)\n"
        "stw	0,20(1)\n"
        "mr	30,3\n"
        "addi	31,4,-1\n"
        "cmpwi	4,0\n"
        "beq	.L_8039C72C\n"
        ".L_8039C710:\n"
        "mr	3,30\n"
        "li	4,2\n"
        ".long 0x4bffff99  /* bl TArray<EVec3, TArrayDefaultAllocator>::~TArray(void) */\n"
        "addi	30,30,12\n"
        "cmpwi	31,0\n"
        "addi	31,31,-1\n"
        "bne	.L_8039C710\n"
        ".L_8039C72C:\n"
        "lwz	0,20(1)\n"
        "mtlr	0\n"
        "lmw	30,8(1)\n"
        "addi	1,1,16\n"
        "blr\n"
    );
    __builtin_unreachable();
}

// 0x8039C784 (76 bytes)
// TArray<ENLatticePoints, TArrayDefaultAllocator>::Construct(ENLatticePoints *, int)
__attribute__((noreturn))
void TArray<ENLatticePoints, TArrayDefaultAllocator>::Construct(ENLatticePoints *, int) {
    __asm__ __volatile__(
        "stwu	1,-16(1)\n"
        "mflr	0\n"
        "stmw	30,8(1)\n"
        "stw	0,20(1)\n"
        "mr	30,3\n"
        "addi	31,4,-1\n"
        "cmpwi	4,0\n"
        "beq	.L_8039C7BC\n"
        ".L_8039C7A4:\n"
        "mr	3,30\n"
        ".long 0x4bffffad  /* bl TArray<EVec3, TArrayDefaultAllocator>::TArray(void) */\n"
        "addi	30,30,12\n"
        "cmpwi	31,0\n"
        "addi	31,31,-1\n"
        "bne	.L_8039C7A4\n"
        ".L_8039C7BC:\n"
        "lwz	0,20(1)\n"
        "mtlr	0\n"
        "lmw	30,8(1)\n"
        "addi	1,1,16\n"
        "blr\n"
    );
    __builtin_unreachable();
}

// 0x8039C998 (88 bytes)
// TArray<ENLatticePoints, TArrayDefaultAllocator>::Copy(ENLatticePoints *, ENLatticePoints *, int)
__attribute__((noreturn))
void TArray<ENLatticePoints, TArrayDefaultAllocator>::Copy(ENLatticePoints *, ENLatticePoints *, int) {
    __asm__ __volatile__(
        "stwu	1,-24(1)\n"
        "mflr	0\n"
        "stmw	29,12(1)\n"
        "stw	0,28(1)\n"
        "mr	29,3\n"
        "mr	30,4\n"
        "addi	31,5,-1\n"
        "cmpwi	5,0\n"
        "beq	.L_8039C9DC\n"
        ".L_8039C9BC:\n"
        "mr	3,29\n"
        "mr	4,30\n"
        ".long 0x4bffff89  /* bl TArray<EVec3, TArrayDefaultAllocator>::operator=(TArray<EVec3, TArrayDefaultAllocator> &) */\n"
        "addi	30,30,12\n"
        "cmpwi	31,0\n"
        "addi	29,29,12\n"
        "addi	31,31,-1\n"
        "bne	.L_8039C9BC\n"
        ".L_8039C9DC:\n"
        "lwz	0,28(1)\n"
        "mtlr	0\n"
        "lmw	29,12(1)\n"
        "addi	1,1,24\n"
        "blr\n"
    );
    __builtin_unreachable();
}

// 0x8039C9F0 (292 bytes)
// TArray<ENLatticePoints, TArrayDefaultAllocator>::SetSize(int, int)
__attribute__((noreturn))
void TArray<ENLatticePoints, TArrayDefaultAllocator>::SetSize(int, int) {
    __asm__ __volatile__(
        "stwu	1,-32(1)\n"
        "mflr	0\n"
        "stmw	26,8(1)\n"
        "stw	0,36(1)\n"
        "mr	31,3\n"
        "mr	29,4\n"
        "mr.	27,5\n"
        "bne	.L_8039CA14\n"
        "mr	27,29\n"
        ".L_8039CA14:\n"
        "lwz	26,4(31)\n"
        "cmpw	29,26\n"
        "bge	.L_8039CA34\n"
        "mulli	0,29,12\n"
        "lwz	3,0(31)\n"
        "subf	4,29,26\n"
        "add	3,3,0\n"
        ".long 0x4bfffcc1  /* bl TArray<ENLatticePoints, TArrayDefaultAllocator>::Destruct(ENLatticePoints *, int) */\n"
        ".L_8039CA34:\n"
        "cmpwi	27,0\n"
        "bne	.L_8039CA58\n"
        "lwz	30,0(31)\n"
        ".long 0x4bf334c1  /* bl MainHeap(void) */\n"
        "mr	4,30\n"
        ".long 0x4bf34331  /* bl EAHeap::Free(void *) */\n"
        "mr	3,31\n"
        ".long 0x4bfffcf1  /* bl TArray<ENLatticePoints, TArrayDefaultAllocator>::Init(void) */\n"
        "b	.L_8039CAE4\n"
        ".L_8039CA58:\n"
        "lwz	0,8(31)\n"
        "cmpw	0,27\n"
        "beq	.L_8039CAE0\n"
        "mulli	30,27,12\n"
        ".long 0x4bf33499  /* bl MainHeap(void) */\n"
        "li	5,0\n"
        "mr	4,30\n"
        ".long 0x4bf34031  /* bl EAHeap::Malloc(unsigned int, int) */\n"
        "mr.	28,3\n"
        "beq	.L_8039CAE4\n"
        "lwz	0,0(31)\n"
        "cmpwi	0,0\n"
        "beq	.L_8039CAD8\n"
        "lwz	0,4(31)\n"
        "mr	30,29\n"
        "cmpw	29,0\n"
        "ble	.L_8039CAA0\n"
        "mr	30,0\n"
        ".L_8039CAA0:\n"
        "mr	4,30\n"
        "mr	3,28\n"
        ".long 0x4bfffcdd  /* bl TArray<ENLatticePoints, TArrayDefaultAllocator>::Construct(ENLatticePoints *, int) */\n"
        "lwz	4,0(31)\n"
        "mr	5,30\n"
        "mr	3,28\n"
        ".long 0x4bfffee1  /* bl TArray<ENLatticePoints, TArrayDefaultAllocator>::Copy(ENLatticePoints *, ENLatticePoints *, int) */\n"
        "lwz	4,4(31)\n"
        "lwz	3,0(31)\n"
        ".long 0x4bfffc2d  /* bl TArray<ENLatticePoints, TArrayDefaultAllocator>::Destruct(ENLatticePoints *, int) */\n"
        "lwz	30,0(31)\n"
        ".long 0x4bf33435  /* bl MainHeap(void) */\n"
        "mr	4,30\n"
        ".long 0x4bf342a5  /* bl EAHeap::Free(void *) */\n"
        ".L_8039CAD8:\n"
        "stw	28,0(31)\n"
        "stw	27,8(31)\n"
        ".L_8039CAE0:\n"
        "stw	29,4(31)\n"
        ".L_8039CAE4:\n"
        "cmpw	29,26\n"
        "ble	.L_8039CB00\n"
        "mulli	0,26,12\n"
        "lwz	3,0(31)\n"
        "subf	4,26,29\n"
        "add	3,3,0\n"
        ".long 0x4bfffc89  /* bl TArray<ENLatticePoints, TArrayDefaultAllocator>::Construct(ENLatticePoints *, int) */\n"
        ".L_8039CB00:\n"
        "lwz	0,36(1)\n"
        "mtlr	0\n"
        "lmw	26,8(1)\n"
        "addi	1,1,32\n"
        "blr\n"
    );
    __builtin_unreachable();
}

