#include "types.h"
#include "stub_classes.h"
// Auto-converted call wrapper stubs for cXPortalImpl
// Generated by convert_call_wrappers.py

// 0x80132224 (72 bytes)
// Call wrapper [2bl_with_branch]: cXMTObjectImpl::PostLoad(int, bool), cXPortalImpl::ApplyWallStyle(bool)
__attribute__((noreturn))
void cXPortalImpl::PostLoad(int, bool) {
    __asm__ __volatile__(
        "stwu	1,-16(1)\n"
        "mflr	0\n"
        "stmw	30,8(1)\n"
        "stw	0,20(1)\n"
        "mr	31,3\n"
        "mr	30,4\n"
        "lwz	3,0(31)\n"
        ".long 0x4bf94b6d  /* bl cXMTObjectImpl::PostLoad(int, bool) */\n"
        "cmpwi	30,51\n"
        "bgt	.L_80132258\n"
        "mr	3,31\n"
        "li	4,1\n"
        ".long 0x4bffdbc9  /* bl cXPortalImpl::ApplyWallStyle(bool) */\n"
        ".L_80132258:\n"
        "lwz	0,20(1)\n"
        "mtlr	0\n"
        "lmw	30,8(1)\n"
        "addi	1,1,16\n"
        "blr\n"
    );
    __builtin_unreachable();
}
