#include "types.h"
#include "stub_classes.h"
// Auto-generated raw-byte matches for HUDTarget
// Generated by gen_raw_byte_matches.py
// 16 functions, 672 bytes
// These functions are matched by directly injecting DOL bytes into the skeleton.
// The C++ stubs below exist only as annotations for the matching pipeline.

// 0x80186DD4 (48 bytes)
// HUDTarget__IncPause_bool
// [raw byte match - injected directly from DOL]

// 0x80186E04 (48 bytes)
// HUDTarget__ReleasePause_bool
// [raw byte match - injected directly from DOL]

// 0x80187F24 (48 bytes)
// HUDTarget__OnPlayerHUDShow_int
// [raw byte match - injected directly from DOL]

// 0x80187F54 (44 bytes)
// HUDTarget__OnPlayerHUDHide_int
// [raw byte match - injected directly from DOL]

// 0x80188D3C (64 bytes)
// HUDTarget__CompleteMenu_int
// [raw byte match - injected directly from DOL]

// 0x80188D7C (64 bytes)
// HUDTarget__ShowMenu_int
// [raw byte match - injected directly from DOL]

// 0x80188E34 (44 bytes)
// HUDTarget__CloseMenu_int
// [raw byte match - injected directly from DOL]

// 0x801892A8 (44 bytes)
// HUDTarget__AddHUDControl_short__short__short_ref
// [raw byte match - injected directly from DOL]

// 0x801892D4 (40 bytes)
// HUDTarget__RemoveHUDControl_short__short
// [raw byte match - injected directly from DOL]

// 0x80189408 (60 bytes)
// HUDTarget__SetJobBarInputRange_int__int__int
// [raw byte match - injected directly from DOL]

// 0x801899E8 (48 bytes)
// HUDTarget__GotoMainMenu_void
// [raw byte match - injected directly from DOL]

// 0x80189A18 (28 bytes)
// HUDTarget__RequestQuitGame_bool
// [raw byte match - injected directly from DOL]

// 0x80189A34 (28 bytes)
// HUDTarget__GetJobBarCount_void
// [raw byte match - injected directly from DOL]

// 0x80189A88 (20 bytes)
// HUDTarget__HideInProgress_void__const
// [raw byte match - injected directly from DOL]

// 0x80189A9C (20 bytes)
// HUDTarget__IsHUDVisible_void__const
// [raw byte match - injected directly from DOL]

// 0x80189AB0 (24 bytes)
// HUDTarget__IsPlayerHUDVisible_int__const
// [raw byte match - injected directly from DOL]

