#include "types.h"
// Auto-generated inline asm decomp stubs for ENgcPerf
// Generated by gen_asm_decomp.py
// 2 functions, 236 bytes
//
// Each function has its original C++ signature with the body as inline PPC asm.
// These can be incrementally replaced with real C++ as decompilation progresses.

class ENgcPerf {
public:
    void ReadMetrics(void);
    void ClearMetrics(void);
};

// 0x80338028 (132 bytes)
// ENgcPerf::ReadMetrics(void)
__attribute__((noreturn))
void ENgcPerf::ReadMetrics(void) {
    __asm__ __volatile__(
        "stwu	1,-24(1)\n"
        "mflr	0\n"
        "stmw	29,12(1)\n"
        "stw	0,28(1)\n"
        "lwz	0,-26336(13)\n"
        "cmpwi	0,0\n"
        "beq	.L_80338098\n"
        ".long 0x48053065  /* bl GXDrawDone */\n"
        ".long 0x480599e9  /* bl GXReadGP0Metric */\n"
        "mr	31,3\n"
        ".long 0x480599e1  /* bl GXReadGP0Metric */\n"
        "mr	30,3\n"
        ".long 0x48059a05  /* bl GXReadGP1Metric */\n"
        "mr	29,3\n"
        ".long 0x480599fd  /* bl GXReadGP1Metric */\n"
        "lwz	0,-26332(13)\n"
        "lis	9,-32700\n"
        "addi	9,9,10240\n"
        "cmplw	30,31\n"
        "slwi	0,0,6\n"
        "ble	.L_80338080\n"
        "mr	30,31\n"
        ".L_80338080:\n"
        "stwx	30,9,0\n"
        "cmplw	3,29\n"
        "addi	9,9,4\n"
        "ble	.L_80338094\n"
        "mr	3,29\n"
        ".L_80338094:\n"
        "stwx	3,9,0\n"
        ".L_80338098:\n"
        "lwz	0,28(1)\n"
        "mtlr	0\n"
        "lmw	29,12(1)\n"
        "addi	1,1,24\n"
        "blr\n"
    );
    __builtin_unreachable();
}

// 0x803380AC (104 bytes)
// ENgcPerf::ClearMetrics(void)
__attribute__((noreturn))
void ENgcPerf::ClearMetrics(void) {
    __asm__ __volatile__(
        "stwu	1,-8(1)\n"
        "mflr	0\n"
        "stw	0,12(1)\n"
        "lwz	0,-26336(13)\n"
        "cmpwi	0,0\n"
        "beq	.L_80338104\n"
        ".long 0x48052fe5  /* bl GXDrawDone */\n"
        "lwz	9,-26332(13)\n"
        "lis	11,-32700\n"
        "lwz	10,-26328(13)\n"
        "addi	11,11,10240\n"
        "addi	9,9,1\n"
        "addi	11,11,8\n"
        "divw	0,9,10\n"
        "li	4,21\n"
        "mullw	0,0,10\n"
        "subf	9,0,9\n"
        "slwi	10,9,6\n"
        "stw	9,-26332(13)\n"
        "lwzx	3,11,10\n"
        ".long 0x48058f35  /* bl GXSetGPMetric */\n"
        ".long 0x48059921  /* bl GXClearGPMetric */\n"
        ".L_80338104:\n"
        "lwz	0,12(1)\n"
        "mtlr	0\n"
        "addi	1,1,8\n"
        "blr\n"
    );
    __builtin_unreachable();
}

