#include "types.h"
#include "stub_classes.h"
// Auto-generated matching stubs for GameData (branching leaf functions)
// Generated by auto_match_branch.py
// 1 functions, 24 bytes

// 0x8003CE7C (24 bytes)
bool GameData::IsDrawCtrlMessageDisabled() { return *(int*)((char*)this + 0x124) != 0; }

